### ISSUE TITLE
Issue when destroying datatable

### ISSUE THREAD

**Issue by rrikesh** [vedmack/yadcf#102]
I'm using DataTable's `fnDestroy()` on a datatable to reset it to its original state. However, the filters added by YADCF aren't destroyed in the process. Could you show me in the right way please?

JSFiddle: http://jsfiddle.net/rrikesh/86yarkqx/
SO Question: http://stackoverflow.com/q/26735050/1370034

Thanks.

**Comment by DerKlink** [comment]
Currently testing the yadcf plugin. Great work so far but I also experiencing the problem that calling `destroy()` on the datatable is not resulting in removing the filters.

Also tried the mentioned solutions from the jsfiddle example but it is still resulting in yadcaf errors
    `table.DataTable().destroy();`
    `table.off();`
    `$('[id^=yadcf]').hide();`

Are there any news I missed? 

Thank you.

**Comment by vedmack** [comment]
Please provide a link to you sample / jsbin so I can see what wrong (make sure you are using the llatest version of yadcf)

**Comment by DerKlink** [comment]
So preparing the jsFiddle showed me that the issue must be caused by something in my project. The jsFiddle is working like charme. So sorry for the false report.

**Comment by vedmack** [comment]
Np :)
