### ISSUE TITLE
If html5 data- attributes set (data-filter etc) on td's, yadcf returns 'undefined'

### ISSUE THREAD

**Issue by FriendlyWP** [vedmack/yadcf#106]
If I set data-filter or data-sort attributes in order to control sorting per this article, YADCF stops working and returns 'undefined' when using 'select' dropdowns: http://www.datatables.net/examples/advanced_init/html5-data-attributes.html

I'm trying to sort a firstname-lastname column by last name, by inserting data-filter in the <td>'s. I tried all four (data-filter, data-search, data-order, data-sort) and they all give the same result.

Any way yacdf could support these? Thanks so much!

**Comment by Organizer** [comment]
Not sure it's related yet but I currently get a "It seems you have forgot to define html5_data attribute" error message when any field/row in my serverside setup and ajax/JSON contains "null" as value.
