### ISSUE TITLE
Using exResetAllFilters and then exFilterColumn causes two requests

### ISSUE THREAD

**Issue by PaulVanSchayck** [vedmack/yadcf#122]
In a DataTables loaded with serverSide data. I'm using `exResetAllFilters` to reset all my filters, and then `exFilterColumn` to set a new filter. This will right now use two AJAX requests.

I'm also not entirely sure what the argument `ajaxSource` for both functions will do.

**Comment by vedmack** [comment]
Added to the 0.8.8.beta.12, read [docs for more info](https://github.com/vedmack/yadcf/blob/master/beta/jquery.dataTables.yadcf.js#L208)

took me a while :)
