### ISSUE TITLE
Some Filters Stop working with ColReorder

### ISSUE THREAD

**Issue by Kussie** [vedmack/yadcf#123]
I am coming across a strange issue with this, when using the ColOrder Plugin and the latest version of Datatables (1.10.4 - New API) and yadcf.  The Date and Text filters become unclickable so i can't actually use those fields.  However i have no issues with the select drop down.

http://pastebin.com/SJtNz6Su

**Comment by lochehong** [comment]
I have the same problem using 1.10.4 and yadcf 0.8.6
dom: 'RTC<"clear">lfrtip',

when i add this line, my yadcf Text boxes becomes not clickiable.

clicking doens't activate the select box either.

**Comment by lochehong** [comment]
http://jsfiddle.net/e4685cug/

try this. the columns can't be clicked. i'm using chrome by the way.

**Comment by lochehong** [comment]
Right click works but not left click

**Comment by vedmack** [comment]
Indeed... this one looks interesting... gonna take a look at it...

**Comment by vedmack** [comment]
fixed in 0.8.7.beta.10 - now all filters are clickable, but know that only text and select filters are really working after the columns reordering see http://jsfiddle.net/e4685cug/16/
