### ISSUE TITLE
ignore_char does not ignore more than one chars

### ISSUE THREAD

**Issue by nekkon** [vedmack/yadcf#125]
Hello, I would like ignore_char to ignore more than 1 char, but a string of chars if possible. What I mean is when adding ignore_char:".-&" to a filter, during range comparison the characters ".", "-", "&" are removed and not taken account in the comparison.

**Comment by toomanyjoes** [comment]
What if I want to ignore all non-numeric chars, like [A-Za-z] for a range_number filter? That doesn't seem to work...

**Comment by vedmack** [comment]
@toomanyjoes post a jsfiddle test page and I will try to add support for it, better open a new issue so it won't get lost
