### ISSUE TITLE
More than once the same filter?

### ISSUE THREAD

**Issue by nekkon** [vedmack/yadcf#127]
Hi, is there an easy way to have two external filters for the same column? Atm from what I understood with filter_container_id you can only have 1..

**Comment by nekkon** [comment]
Thanks for your reply. I followed a different solution. I just move around the filter by changing the div's css as a temporary solution.. Does the job so I am happy atm..

**Comment by vedmack** [comment]
Actually,  you can give a try to the initMultipleColumns, you can use it for a single colum too, just provide different containers ids and cross your fingers. But you should know that is no state saving support for those filters. Read docs for usage sample

 https://github.com/vedmack/yadcf/blob/master/lab/jquery.dataTables.yadcf.js#L255
