### ISSUE TITLE
filter options "undefined" with 0.8.6 version

### ISSUE THREAD

**Issue by Muhahe** [vedmack/yadcf#130]
Hi again,

i just updated to 0.8.6 yadcf version for option to filter multiple tables with one selectbox, and got stucked on "undefined" in selectboxes which should filter. On version 0.8.4.beta.3 everything was okay, and i cant find why. (im using datatables 1.10.4 and external data source) 

this is my filter initialization

```javascript
yadcf.init(projectsTable,[           
    {
        column_number :1,            
        filter_type: "multi_select",
        select_type: 'chosen'
       // use_dataTable_render: 'true'
    },
    {
        column_number :2,
        filter_type: "multi_select",
        select_type: 'chosen'/*,
        use_dataTable_render: 'true'*/
    },
    {
        column_number :3,
        filter_type: "multi_select",
        select_type: 'chosen',
        use_dataTable_render: 'true'
    },
```

and if i debug yadcf.js on line 1271 and below
```javascript
for (columnObjKey in args) {
			if (args.hasOwnProperty(columnObjKey)) {
				columnObj = args[columnObjKey];

				data = columnObj.data;
```

my "args" objects dont have attribute "data" so data is undefined. Can you take a quick look please?

**Comment by vedmack** [comment]
Does it still happens with 0.8.7beta.7? If so, what line number

**Comment by vedmack** [comment]
No sure what the issue here, but if its still happens in latest beta version of yadcf please provide the relevant info (as much as accurate as possible) and reopen this issue
