### ISSUE TITLE
initFilterMultipleTables filter type select/chosen + multiple selectboxes

### ISSUE THREAD

**Issue by Muhahe** [vedmack/yadcf#132]
Hi, 

is there posibility to have multiple selectboxes for initFilterMultipleTables? My idea is to have multiple tables, with same number and type of columns, but to have single filter to filter them. (one filter for one column in each table)

**Comment by vedmack** [comment]
You want multi select input for multiple tables? Asking because you mentioned it in issue title but havent done so in your posted code sample. ..

**Comment by Muhahe** [comment]
yes, that is correct :)

**Comment by vedmack** [comment]
Massive enhancement to the initMultipleTables , now it also read the columns data automatically and place it into select element options still need to add multi select for this one, please test it and see how it behaves for you

**Comment by Muhahe** [comment]
thank you very much, im trying it right now, but one question. Will it create filter for each column, or one filter for all columns? (as filter i now think option element)

**Comment by Muhahe** [comment]
i made a bit tests and woooow it seems like it works. thank you very much, +5 internets for you :)
only one problem i found, but manage to solve it.

when i try to initialize it like this

```javascript
    yadcf.initMultipleTables(subTablesList,[{column_number: [1], filter_container_id:'multiFilterContainer_1', filter_type: 'select', column_data_type: 'rendered_html'},
                                            {column_number: [2], filter_container_id:'multiFilterContainer_2', filter_type: 'select', column_data_type: 'rendered_html'},
                                            {column_number: [3], filter_container_id:'multiFilterContainer_3', filter_type: 'select', column_data_type: 'rendered_html'},
                                            {column_number: [4], filter_container_id:'multiFilterContainer_4', filter_type: 'select', column_data_type: 'rendered_html'},
                                            {column_number: [5], filter_container_id:'multiFilterContainer_5', filter_type: 'select', column_data_type: 'rendered_html'},
                                            {column_number: [6], filter_container_id:'multiFilterContainer_6', filter_type: 'select', column_data_type: 'rendered_html'},
                                            {column_number: [7], filter_container_id:'multiFilterContainer_7', filter_type: 'select', column_data_type: 'rendered_html'},
                            ])

```

there is issue with tablesSelector variable, which isnt empty for next filter processing on line 2660
(so i added line tablesSelectors = '' before loop)
```javascript
tablesSelectors = ''
			for (i = 0; i < tablesArray.length; i++) {
				//tablesSelectors += tablesArray[i].settings()[0].oInstance.selector + ',';
                                tablesSelectors += '#' + tablesArray[i][0].id + ',';
			}

```

and also there is minor problem, that my datatables dont have .oInstance.selector, but it may be only my issue

**Comment by Muhahe** [comment]
another question, is there implemented saveState for multiple filters multiple columns?

**Comment by vedmack** [comment]
Will take a closer look at  the bugs you found and the tweeks you did for your scenario in a few days (hopefully) regarding state saving - since its not a standard filtering and nut supported directly by datatables probably I will  have to write some additional code for that... open a nee issue for that. But know that I don't know when I will have the time for that since there are other open issues

**Comment by Muhahe** [comment]
about filtering i was just asking. im now trying to make that running. And about datatables, they remember state, only filters stay empty.

**Comment by vedmack** [comment]
Please grab the new 0.8.7.beta.8 version and update me on what am I still missing in my implementation, latest version don't rely on table selector and the filtering was also improved

Also added a showcase page http://yadcf-showcase.appspot.com/dom_multi_columns_tables_1.10.html

**Comment by Muhahe** [comment]
HI vedmack, sorry for my delay, but im totaly bussy with exams now. But will reply test and reply ASAP

**Comment by Muhahe** [comment]
Im looking for 0.8.7.beta.8 but found only 0.8.7. Is it still availible?

**Comment by vedmack** [comment]
Its not a beta anymore... 0.8.7 is the final form of that version... (0.8.7
> 0.8.7.beta.XXX) :)

**Comment by Muhahe** [comment]
okay sorry :) i will test it now

**Comment by Muhahe** [comment]
So i test it and i miss suport for chosen multiselect and for save state. Or am i missing some initialization?

**Comment by vedmack** [comment]
Only the fact that this issue is still open and the other issue https://github.com/vedmack/yadcf/issues/143 is still open too :) I still haven't finish those two, my last commits on this feature were 1) don't rely on table selector 2) improve filtering mechanism

**Comment by Muhahe** [comment]
okay thanks :) my bad. this seems it works fine to me (just made a some minor changes because of my issue somewhere)

**Comment by vedmack** [comment]
Done in 0.8.8.beta.10, see in action and scroll down to see code snippet
