### ISSUE TITLE
Error with text filter in server side table with 0.8.7.beta.6

### ISSUE THREAD

**Issue by PaulVanSchayck** [vedmack/yadcf#136]
I get the following error when typing in a text filter using a server side data source and the delay option.

```
Uncaught TypeError: Cannot read property 'target' of undefined  jquery.dataTables.yadcf.js:2212 
keyUp   jquery.dataTables.yadcf.js:2231 
(anonymous function) jquery.dataTables.yadcf.js:374 
```
I guess this is related to commit 5538dd4 as it does not happen before that commit.

**Comment by vedmack** [comment]
Thanks, will fix it, currently the beta version is under quite a big re write...

**Comment by vedmack** [comment]
See showcase http://yadcf-showcase.appspot.com/server_side_source.html (second column)
