### ISSUE TITLE
Programmatic access using exFilterColumn 

### ISSUE THREAD

**Issue by Jrizzi1** [vedmack/yadcf#137]
What I am trying to accomplish is a on click event that will use exFilterColumn to programmatically change the filter

i manage to accomplish this fine on a page load using a url variable like this

```javascript
yadcf.exFilterColumn(table, [[3, 'myvalue' ]]);
```

But when i attempt to wrap this in an on click event on the same page, nothing happens, no log error 
```javascript
$('#worklist').on('click', function(){
			yadcf.exFilterColumn(table, [[3, 'myvalue']]);

			return false;
		});
```

**Comment by vedmack** [comment]
My guess is that your using ajax source in your datatable, in that case when calling the `exFilterColumn` after the table finished loading (like in your `on('click'` scenario you will have to add third parameter `true` (boolean) to your call, so your command will look like this: 

`yadcf.exFilterColumn(table, [[3, 'myvalue']], true);`

Hopefully I will update the docs this time :)

**Comment by Jrizzi1** [comment]
Yes, that was it exactly, thanks much for the heads up!
