### ISSUE TITLE
Adding support for ColReorder to remaining filter_types

### ISSUE THREAD

**Issue by luivis07** [vedmack/yadcf#138]
This is related to this issue: https://github.com/vedmack/yadcf/issues/107. 
Would like to add the 'multi_select' filter type and the 'range_number_slider' to have the same fix as the 'select' and 'text' filters.

**Comment by luivis07** [comment]
It seems like these filter types already support ColReorder since they have the column number as one of their parameters in the function.

**Comment by vedmack** [comment]
they do have the original column number, but when doing the col re order yadcf needs to find the new column number (the index after re order) and that is implemented only for select/text atm

**Comment by luivis07** [comment]
ok I'll leave this one open then.

**Comment by luivis07** [comment]
Daniel, I've noticed a bug with ColReorder & StateSave and the filter being drawn/added. If you look at this fiddle: http://jsfiddle.net/e4685cug/15/ and move header 3 to header1 position, so original order: [0,1,2,3,4,5,6,7], new order/ColReorder variable in StaveSave: [2,0,1,3,4,5,6,7]

**Comment by vedmack** [comment]
Added to all the remaining filter types,grab the latest beta [0.8.8.beta.8](https://github.com/vedmack/yadcf/blob/master/beta/jquery.dataTables.yadcf.js)
