### ISSUE TITLE
filter-reset - input / button

### ISSUE THREAD

**Issue by pinin** [vedmack/yadcf#139]
Hello, thank you for the great plugin.
I should comment:

I think that the filter-reset-button should be `<button>` not use `<input>`.
on the input element is not possible to add css `:after :before`.
You can not insert html `<i></ i>`. This rather limits the possibilities of adapting this button.
Can be applied only to the class as `.btn`.

Thank you, consider the possibility of confusion - `<input>` to `<button>`

**Comment by vedmack** [comment]
Hi,
You are welcome, you are right about that *input limitation*, but even now you can add the [pseudo elements](https://developer.mozilla.org/en-US/docs/Web/CSS/::after) to the `.yadcf-filter-reset-button` class which present on each reset button

**Comment by pinin** [comment]
Thank you for the quick response.
Unfortunately pseudo-element can not be applied to the `<input>`, that's the problem. For this element of the pseudo-element is not working. The `<button>` is ok. Here it is possible to apply `button:after button:before`.

Probably would also be good to better distribute structure within .yadcf-filter-wrapper
[as here](http://getbootstrap.com/components/#input-groups-buttons)

```
<div class="yadcf-filter-wrapper input-group">
    <input class="yadcf-filter form-control">
    <span class="yadcf-filter-reset-button-wrapper input-group-btn">
        <button class="yadcf-filter-reset-button btn btn-default">&#10005;</button>
    </span>
</div>
```

yet I used jquery `.addClass ()` and `.wrap ()`, but there is a problem if you use 
`filter_type: "range_number_slider"`. 
In this case the reset button is not working because

`function rangeNumberSliderClear...` uses `.parent().find()` and `.prev().find()`

Maybe you advise me how to do this layout
Thanks

**Comment by pinin** [comment]
this is my interim solution

I used this script to use my version
```
function yadcfAddBootstrapStyle() {
        var filterWrapper = $('.yadcf-filter-wrapper'),
            filterInput = $('input.yadcf-filter, input.yadcf-filter-range, input.yadcf-filter-date'),
            filterReset = $('input.yadcf-filter-reset-button');

        if ($('.table-filter').hasClass('js-table-filter-group')) {
            filterWrapper.addClass('input-group');
            filterInput.addClass('form-control');
            filterReset.addClass('btn btn-default').wrap("<span class='input-group-btn'></span>");
        } else {
            filterInput.addClass('form-control');
            filterReset.addClass('btn btn-default').wrap("<span></span>");
        }
    }
```

1. Only `.btn` and `form.control`. [sample](http://www.imgup.cz/images/2015/01/09/yadcf-bs-1.jpg)
2. Using as `.input-group`.  [sample](http://www.imgup.cz/images/2015/01/09/yadcf-bs-2.jpg)

a little css for .yadcf-filter-

Unfortunately, in both cases it is necessary to adjust the function, because it is necessary to add the wrapper on the reset button.

`function rangeClear(...)`.
`rangeNumberSliderClear(...)`
In this style
`+$($(event.target).parent().parent().find()`,
`$(event.target).parent().prev().find()`.

**Comment by vedmack** [comment]
so changing to input element of reset into button would good enough? or its more than just that replacement ?

**Comment by pinin** [comment]
Yes, Change `<input>` element of reset into `<button>` and wrap to the `<span>` element would be sufficient for the possibility of styling. With that, it is necessary to modify the `rangeClear` and `rangeNumberSliderClear` function.

general: input element does not support the use of pseudo-element.

this result:
```
<span class="yadcf-filter-reset-button-wrapper">
    <button  type="button" class="yadcf-filter-reset-button">&#10005;</button>
</span>
```
for "x" I used this html entity "&#10005;"

**Comment by vedmack** [comment]
While I see the point of changing the `input` into the `button` element, I'm not sure about how mandatory is the wrapping with span and I prefer to avoid breaking the current position of the element.

**Comment by pinin** [comment]
wrap is not required

**Comment by vedmack** [comment]
fixed in 0.8.7.beta.10, showcase updated

**Comment by MrCsabaToth** [comment]
pinin: I managed to get a fused input reset button if I applied "input-group" class to the wrapper and "input-group-addon" to the button directly. So I didn't use an extra wrapper span, as books advise. Hopefully it'll keep working.

**Comment by MrCsabaToth** [comment]
Since I don't have space for clear buttons in some header cells, my code:

    headerCallback: function (thead, data, start, end, display) {
        $(thead).find("th").each(function (thindex, thelement) {
            var clearBtn = $(thelement).find(".yadcf-filter-reset-button");
            if (clearBtn !== null && clearBtn.length > 0) {
                var filterWrapper = $(thelement).find(".yadcf-filter-wrapper");
                if (filterWrapper !== null && !$(filterWrapper).hasClass("input-group"))
                    $(filterWrapper).addClass("input-group");
                if (!$(clearBtn).hasClass("input-group-addon"))
                    $(clearBtn).addClass("input-group-addon");
            }
        });
    }

Plus some extra padding modification is required for the button, IE, Chrome and FF shows them differently.

**Comment by MrCsabaToth** [comment]
input-group-addon has a width: 1% CSS for example, not meant to be applied directly to the button.

**Comment by vedmack** [comment]
@MrCsabaToth , couldn't you use the headerCallback for finding and wrapping the `yadcf-filter-reset-button` with a span element (for example by using http://api.jquery.com/wrap/ )

**Comment by pinin** [comment]
This is nice, but the wrap on the reset button destroy the reset function when the filter type range.
Therefore it is not possible to wrap reset button.

**Comment by MrCsabaToth** [comment]
pinin: you are right, the reset button won't function if it is wrapped.

**Comment by pinin** [comment]
Here is my solution is not ideal, but it works as I need

HTML
```
<thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Position</th>
        <th>Office</th>
        <th>Extn <small><em>slider</em></small></th>
        <th>Start date</th>
        <th>Status</th>
        <th>Salary</th>
    </tr>
    <tr class="table-filter">
        <th id="tableFilter_0" class="yadcf-no-reset"></th>
        <th id="tableFilter_1"></th>
        <th id="tableFilter_2"></th>
        <th id="tableFilter_3"></th>
        <th id="tableFilter_4"></th>
        <th id="tableFilter_5"></th>
        <th id="tableFilter_6" class="yadcf-no-reset"></th>
        <th id="tableFilter_7" class="yadcf-no-reset"></th>
    </tr>
</thead>
```

JS
```
// Add bootstrap style 
    function yadcfAddBootstrapClass() {
        var filterInput = $('.yadcf-filter, .yadcf-filter-range, .yadcf-filter-date'),
              filterReset = $('.yadcf-filter-reset-button');

        filterInput.addClass('form-control');
        filterReset.addClass('btn btn-default').html('&#10005;');
    };

    yadcfAddBootstrapClass();
```

CSS
```
/* if you do not use the reset button to add the cell this class */
.yadcf-no-reset .yadcf-filter-wrapper {
    padding-right: 0;
}
.yadcf-no-reset .yadcf-filter-reset-button {
    display: none;
}

/* Style no input-group
 * ------------------------------ */
.yadcf-filter-wrapper {
    display: block;

    padding-right: 36px;

    white-space: nowrap;
}
.yadcf-filter-wrapper .form-control,
.yadcf-filter-wrapper .select2-container,
.yadcf-filter-wrapper .select2-container.form-control,
.yadcf-filter-wrapper .yadcf-number-slider-filter-wrapper-inner {
    display: inline-block;

    width: 100%;
}
.yadcf-filter-wrapper .yadcf-filter-range-date {
    width: 100px;
}
.yadcf-filter-wrapper .yadcf-filter-range-number {
    width: 60px;
}

/* Range wrapper */
.yadcf-filter-wrapper-inner {
    display: inline-block;

    vertical-align: middle;
}

/* Range input */
.yadcf-filter-range {
    display: inline-block;

    vertical-align: middle;
}

/* Range separator */
.yadcf-filter-range-date-seperator,
.yadcf-filter-range-number-seperator {
    display: inline-block;

    margin-left: 1px;

    vertical-align: middle;
}

/* Reset button */
.yadcf-filter-reset-button {
    display: inline-block;

    margin-right: -36px;
    margin-left: 1px;

    vertical-align: top;
}
.yadcf-filter-reset-button.btn {
    font-size: 11px;
    line-height: 20px;

    color: #d9d9d9;
}
.yadcf-filter-reset-button.btn:hover {
    color: #333;
}


/* If set stack range 
 * ------------------------------ */
/* Range wrapper */
.yadcf-range-stack .yadcf-filter-wrapper-inner {
    display: inline-block;

    vertical-align: top;
}

/* Range input */
.yadcf-range-stack .yadcf-filter-range {
    display: block;
}

/* Range separator */
.yadcf-range-stack .yadcf-filter-range-date-seperator,
.yadcf-range-stack .yadcf-filter-range-number-seperator {
    display: none;
}

```
Is there a little more style. Hopefully it helps someone
