### ISSUE TITLE
exResetAllFilters - select2

### ISSUE THREAD

**Issue by pinin** [vedmack/yadcf#140]
health, I found this bug for exResetAllFilters

`exResetAllFilters()` does not restore value to Select2
data in the column are reset, but remains in the filter value

**Comment by vedmack** [comment]
does work for me, atleast with the latest version (try the 0.8.7.beta.7)
http://yadcf-showcase.appspot.com/DOM_source_select2.html
if still does no work for you show your complete code / provide jsbin sample

**Comment by pinin** [comment]
Great, it works ok. I used version 0.8.6. In version 0.8.7.beta.6 is ok. 

Thanks
