### ISSUE TITLE
initMultipleTables and stateSave

### ISSUE THREAD

**Issue by Muhahe** [vedmack/yadcf#143]
Implementation of stateSave for initMultipleTables. Currently datatables linked to filter remember state, but filter doesnt. (after refresh page, there are no hightlighted selected options in option element and others)

**Comment by vedmack** [comment]
fixed in [0.8.9.beta.11](https://github.com/vedmack/yadcf/blob/d8932d5109398c3a7a05178a17e4a0b027a9da2a/jquery.dataTables.yadcf.js)
