### ISSUE TITLE
auto_complete source by ajax

### ISSUE THREAD

**Issue by zxishere** [vedmack/yadcf#144]
Is there way to set filter_type: "auto_complete" data  source  by ajax?

But i just soloved the problem by change some code:

				if (columnObj.filter_type === "auto_complete") {
					$("#yadcf-filter-" + table_selector_jq_friendly + "-" + column_number).autocomplete({
						//source: $(document).data("yadcf-filter-" + table_selector_jq_friendly + "-" + column_number),
						source: auto_complete_source,
						select: autocompleteSelect
					});

insert some  "auto_complete_source" span  just like  "text_data_delimiter" near

			text_data_delimiter,
			auto_complete_source,

			text_data_delimiter = columnObj.text_data_delimiter;
			auto_complete_source = columnObj.auto_complete_source;

Useage:
					{column_number: 0,filter_type: "auto_complete", auto_complete_source:"{{ URL::to('admin/sites/auto-complete') }}"},

Excause for my poor english, Thank you all the same Daniel Reznick :+1:

**Comment by vedmack** [comment]
Hi,
Try using the [filter_plugin_options](https://github.com/vedmack/yadcf/blob/master/lab/jquery.dataTables.yadcf.js#L164) , something like 
`filter_plugin_options: { source: "somePage.php" }` or some more complex code like in http://jqueryui.com/autocomplete/#remote-jsonp example.

I haven't tried it myself so in case that it wont work please post a link to your page so I can debug it.

**Comment by zxishere** [comment]
Great ,it work!!!
