### ISSUE TITLE
Generate more correct HTML for the filter clear button

### ISSUE THREAD

**Issue by MrCsabaToth** [vedmack/yadcf#145]
There's a missing space between the end of the added filter clear class (column_number + "-reset\"") and the following onclick handler. The resulting HTML:

'" yadcf-filter--reporttable-6-reset"onclick="yadcf.stopPropagation(event);yadcf.textKeyUP('-reportTable', event, 'clear'); return false;" value="NaN id=">x</button>'

Notice the missing space before the onclick. Maybe it doesn't cause a trouble, but it's better off having a space there IMHO.

**Comment by MrCsabaToth** [comment]
It's actually in three places in the source, I'll create a pull request soon.

**Comment by MrCsabaToth** [comment]
Seems like it cause the click handler not to work on FF, but there are other problems in my case too (some modifications related to bootstrap)

**Comment by vedmack** [comment]
Fixed in https://github.com/vedmack/yadcf/pull/147 :+1:
