### ISSUE TITLE
Being able to use smart filtering in case of contains filter_match_mode

### ISSUE THREAD

**Issue by MrCsabaToth** [vedmack/yadcf#148]
I'm in the situation when the users have the global search box and yadcf text filters per column too. They expect the same kind of functionality from both: if they type fraction of keywords after each other separated by space, the search engine would basically split the whole term to multiple terms separated by space and evaluate each. That's what smart search (bSmart) does under the hood.

https://stackoverflow.com/questions/27997189/yadcf-smart-filtering-with-contains-filter

So far I made a modification in yadcfMatchFilter:
```
if (filter_match_mode === "contains") {
		    oTable.fnFilter(selected_value, column_number, false, true, true, case_insensitive);
```
Notice that the parameters are not false *false* true, but false *true* true, the second parameters is the bSmart for fnFilter.

**Comment by MrCsabaToth** [comment]
I think this could be some kind of configuration option

**Comment by vedmack** [comment]
Will check this one later on, but I actually think that for contains it would be better set the `bSmart` into `true` (permanently)

**Comment by vedmack** [comment]
bSmart is set to true in contains (0.8.7.beta.12)
