### ISSUE TITLE
add yadcf_data_columnName support to server side response

### ISSUE THREAD

**Issue by johndegey** [vedmack/yadcf#154]
Hello,

It would be great to add/change the way of setting the filter's option in the xhr response when working with server side process.

Now the answer is like `"yadcf_data_1":[{"value":"field2_val","label":"field2_label"}]`
It could be like `"yadcf_data_field2":[{"value":"field2_val","label":"field2_label"}]`

Regarding a question i ask on the DT forum, working with column'name (or the data parameter) seems to be the way DT is going now.

http://datatables.net/forums/discussion/25952/how-to-get-dt-api-in-ajax-data-function-with-server-side#latest

Thx

John

**Comment by vedmack** [comment]
If you will provide a link to a page with a serverside setup with column names which will be linked to my [local version of yadcf (dropbox)](https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/resources/js/jquery.dataTables.yadcf.js) it will surely sped up this feature...

**Comment by johndegey** [comment]
Hello Daniel,

Here is the test case
http://yadcf.johndegey.org/listing11.php

**Comment by louking** [comment]
For anyone looking for this, the feature is provided in b2d9b1e9096a1909ed95dca41f9ac8a6181ea0e4 by using `column_selector : '<colname>:name'`; however I don't see the `column_selector` option (which can be used instead of `column_number`) in the api description (opening comments)
