### ISSUE TITLE
server side : resetting a filter should not send the xhr request when not necessary

### ISSUE THREAD

**Issue by johndegey** [vedmack/yadcf#156]
Hello Daniel,

Clicking on the cross always send an xhr request, even when there is nothing to reset in the filter.
http://yadcf.johndegey.org/listing.php

John

**Comment by mash180** [comment]
Hello Daniel really great job on this plugin; this is a real problem on Server Side datatables with large dataset, another thing, filter_delay is working on reset button.


John, I already resolve the xhr request on filter_type = Text adding after the function textKeyUp the following lines:


if(clear==='clear' && $("#yadcf-filter-" + table_selector_jq_friendly + "-" + column_number).val() === ''){
	return;
}


And to avoid filter delay on reset find 

if (options.filter_delay === undefined) {

and replace with

if (options.filter_delay === undefined || clear==='clear') {


For filter_type = range_date

Find function rangClear and add after:

event = eventTargetFixUp(event);

this line:
if($(event.target).closest('div').find("input.inuse").length===0){
	return;
}

I can´t tell the exactly lines, cause already modify a lot the html structure to use with bootstrap 3.

Hope this help.

Manuel

**Comment by vedmack** [comment]
b.t.w this is almost fixed for all the filters types in the latest beta

**Comment by vedmack** [comment]
hopefully covered them all now

**Comment by johndegey** [comment]
Thanks for your work Daniel

John
