### ISSUE TITLE
integrate yadcf and fixedHeader

### ISSUE THREAD

**Issue by johndegey** [vedmack/yadcf#157]
Hello Daniel,

I've made some more test case for the integration between your plugin and the fixingHeader plugin.
Can you take a look.

http://yadcf.johndegey.org/listing4.php

listing 3 and 4 : fixedHeader is initialized before yadcf
listing 5 and 6 : yadcf is initialized before fixedHeader
listing 7 and 8 : yadcf is initialized before fixedHeader, but i've forced a redraw of fixedHeader
(see this post http://datatables.net/forums/discussion/19124/simple-solution-for-fixedheader-column-headers-not-changing-on-window-resize#latest)

i've put 2 test cases without yadcf (so you can compare)
listing 9 : fixedHeader without forcing a redraw
listing 10 : fixedHeader with forcing a redraw

Don't really now if the integration problem can be fixed on your side.
There is just one post on the DT forum
http://datatables.net/forums/discussion/20805/has-anyone-used-fixed-headers-with-yadcf-yet-another-datatables-column-filter#latest
that relates the same problem with columnFilter (that i've used before)

Greatly appreciate your help...

Thanks

John

**Comment by vedmack** [comment]
> [As of v3, FixedHeader doesn't display a clone but rather the original element](https://github.com/DataTables/FixedHeader/issues/47#issuecomment-181425851)
So yadcf works with fixedheadrs out of the box, [see showcase (first table)](http://yadcf-showcase.appspot.com/DOM_Ajax_Multiple_1.10.html)
