### ISSUE TITLE
filter_type: "range_number_slider" not working in case we provide "data-sort" or "data-order" in <td>

### ISSUE THREAD

**Issue by gauravjhs** [vedmack/yadcf#158]
We have a formatted number in a "td". To sort it properly we are using "data-sort" with latest version of datatables. First we got an error that 'Looks like you have forgot to define the html5_data attribute for the ...'. Even after specifying html5_data it's not working. 

Please check this http://jsbin.com/xukaxocife/1/edit
Try filter on first column or sorting it.

**Comment by vedmack** [comment]
Fixed in [0.8.8.beta.4](https://github.com/vedmack/yadcf/blob/master/beta/jquery.dataTables.yadcf.beta.js) see working [jsbin](http://jsbin.com/kahoziquko/1/edit?html,output)
