### ISSUE TITLE
Search by "Not Equal To"

### ISSUE THREAD

**Issue by GMEHTA1981** [vedmack/yadcf#161]
Hello Daniel,

Your plugin is awesome and very helpful ! 
Recently, while using your plugin.. I have come across a request whereby the filter should search records that are "not equal to" search string.

"Filtering - All text filter add a check on top or below the filter that says 'Exclude'."
If exclude is checked, do NOT show any records on the grid that equal one of the selected values for the filter.

Usually in the case where we have massive records, it is easier to filter records sometimes based on "not equal to". For eg: Show me records of all used cars except brand "volvo" 

It seems YADCF does not have this feature as yet. 
Could you please guide me .. how this is possible?

Much thanks !

**Comment by vedmack** [comment]
In what filter types you want to use it?

**Comment by GMEHTA1981** [comment]
Mostly text.

**Comment by GMEHTA1981** [comment]
Daniel any update, please ?

**Comment by vedmack** [comment]
Not yet, but hopefully will add it to very soon

**Comment by vedmack** [comment]
Added to the beta v.18 , see [showcase example](http://yadcf-showcase.appspot.com/DOM_source_select2.html) fourth column and read docs about [exclude and exclude_label](https://github.com/vedmack/yadcf/blob/master/beta/jquery.dataTables.yadcf.js#L158)

**Comment by GMEHTA1981** [comment]
Hi Daniel,

Thank you for address our issue.

I do have two concerns
1) When we click on the "EXCLUDE" checkbox. The event is getting fired. It
should fire event only based on keyup event of the textbox.

2) The query produced in SQL.. looked like Where ShipAlpha =
'^((?!MyShip).)*$' and ...
It seems that sql does not understand ^((?!
Also, there is an error when column has datatype integer (with text filter)

On Sun, Apr 5, 2015 at 4:49 PM, Daniel <notifications@github.com> wrote:

> Added to the beta v.18 , see showcase example
> <http://yadcf-showcase.appspot.com/DOM_source_select2.html> fourth column
> and read docs about exclude and exclude_label
> <https://github.com/vedmack/yadcf/blob/master/beta/jquery.dataTables.yadcf.js#L158>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vedmack/yadcf/issues/161#issuecomment-89848805>.
>



-- 
Regards
Gayatri Mehta

**Comment by GMEHTA1981** [comment]
Daniel,

One more crazy thing.. it brings back ((?!MyShip).)*$ in the textbox..
because bStateSave is true.
It should only bring the string back.

On Mon, Apr 6, 2015 at 1:50 PM, Gayatri mehta <gmehta1981@gmail.com> wrote:

> Hi Daniel,
>
> Thank you for address our issue.
>
> I do have two concerns
> 1) When we click on the "EXCLUDE" checkbox. The event is getting fired. It
> should fire event only based on keyup event of the textbox.
>
> 2) The query produced in SQL.. looked like Where ShipAlpha =
> '^((?!MyShip).)*$' and ...
> It seems that sql does not understand ^((?!
> Also, there is an error when column has datatype integer (with text filter)
>
> On Sun, Apr 5, 2015 at 4:49 PM, Daniel <notifications@github.com> wrote:
>
>> Added to the beta v.18 , see showcase example
>> <http://yadcf-showcase.appspot.com/DOM_source_select2.html> fourth
>> column and read docs about exclude and exclude_label
>> <https://github.com/vedmack/yadcf/blob/master/beta/jquery.dataTables.yadcf.js#L158>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/vedmack/yadcf/issues/161#issuecomment-89848805>.
>>
>
>
>
> --
> Regards
> Gayatri Mehta
>



-- 
Regards
Gayatri Mehta

**Comment by vedmack** [comment]
It should fire even on exclude click if the text filter is not empty (if its empty it should not fire anything indeed) , imagine having a text int the filter and then user clicks on the exclude, your user will expect that checkbox click to have some effect of the filtering.
Since you do you logic on the server I guess you should strip the `^((?!` prefix and the `).)*$` suffix and cast some sql query (yadcf/datatables are only the *messanger* when it come to server side filtering.
As to the `bStateSave` *brings back* that string <-- will fix it

**Comment by GMEHTA1981** [comment]
Hello Daniel,

Your change seems wonderful, so far. However, there may need a change in
approach.
Let me explain you.

This is a screenshot from your own site. Using exclude checkbox I enter
"a_value" in search. Then refreshed the screen.
You will notice how the prefix and suffix value appears.

[image: Inline image 1]

This is happening because of StateSave.
Based, on your advice, from our previous email....

I use sever side (web service) to get data. I used replace to get rid of
prefix and suffix after search is built into the query.
I am able to bring back appropriate data.

However, what happens now, is.. if you leave this page and come back on it.
The search textbox will have search string eg "a_value" but checkbox will
not be checked.
Thus results will vary. To best of my understanding on how you have coded
this..Since it did not find the prefix and suffix value in the search
string, the checkbox did not get checked.

I would suggest and alternative approach of passing additional value to
statesave that recognize the checkbox checked value.

Please provide me your thoughts.

However, the

On Tue, Apr 7, 2015 at 5:31 PM, Daniel <notifications@github.com> wrote:

> It should fire even on exclude click if the text filter is not empty (if
> its empty it should not fire anything indeed) , imagine having a text int
> the filter and then user clicks on the exclude, your user will expect that
> checkbox click to have some effect of the filtering.
> Since you do you logic on the server I guess you should strip the ^((?!
> prefix and the ).)*$ suffix and cast some sql query (yadcf/datatables are
> only the *messanger* when it come to server side filtering.
> As to the bStateSave *brings back* that string <-- will fix it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vedmack/yadcf/issues/161#issuecomment-90738092>.
>



-- 
Regards
Gayatri Mehta

**Comment by vedmack** [comment]
Your screenshots got lost , so either you email them to me or post them again, I couldn't understand the following: "You will notice how the prefix and suffix value appears." , as to the checkbox state getting lost I will fix it and will test it with client side , you will have to see how it works with server side setup

**Comment by vedmack** [comment]
grab the latest beta .20 version and see in action in [showcase](http://yadcf-showcase.appspot.com/DOM_source_select2.html) , I haven't tested it with server side, but know **that in case** that you are sending any data regarding the column filter (search term) back to the client you will have to add the prefix/suffix of the regex expression because of the exclude option
