### ISSUE TITLE
Reset single filter

### ISSUE THREAD

**Issue by dovydasvenckus** [vedmack/yadcf#162]
Hi. First I would like to thank you for great plugin. It's saving my ass. Few days ago my boss asked for advanced filtering on existing datatables. 

Could you add function exResetColumn(table, column_no). That would let reset filter for just one selected column? 

That would help me alot, because I'm doing hideble sort fields, and I would like to reset hidden field filters.

**Comment by vedmack** [comment]
Why reset one if you can reset one or more :)

I added [exResetFilters](https://github.com/vedmack/yadcf/blob/master/beta/jquery.dataTables.yadcf.js#L213) in the latest beta (0.8.8.beta.9) , use it to reset one or more filters , read docs

**Comment by dovydasvenckus** [comment]
Thanks alot :)
