### ISSUE TITLE
Ability to add custom classes to select / other column filter elements.

### ISSUE THREAD

**Issue by ask1987** [vedmack/yadcf#163]
I am using yadcf datatable plugin and its select css style looks like basic CSS style and not the boostrap one.

I am using datatables bootstrap features for css styling but for some reason yadcf still uses basic css style. Check the image attached, it does not look like bootstrap css styling for select elemtn. 

I know you won't be easily able to figure out the problem, without a code link which I don't have.

If you have any pointers, I can get look into them. I can also provide additional information

![yadcf](https://cloud.githubusercontent.com/assets/6270682/6588675/edf2febc-c7ba-11e4-8eb3-8ca23d1d88bf.png)

Before logging this issue, I also added a SO question. 

http://stackoverflow.com/questions/28976996/yadcf-select-css-style

**Comment by ask1987** [comment]
Just an additional information, it is happening only with Firefox and not Chrome.

**Comment by ask1987** [comment]
It seems it is not an issue, it is rather how browser renders HTMl elements. 

Updating, issue header to request a feature for passing custom CSS styles for select / other column filter element. 

Thanks for explanation.

**Comment by vedmack** [comment]
Added new property for filter, style_class - allows adding additional class/classes to filter - available for the following filters: select / multi_select / text / custom_func / multi_select_custom_func

available in yadcf 0.8.8.beta.22

**Comment by ask1987** [comment]
Thanks
