### ISSUE TITLE
do tags into clickable tags filters for datatable - yadcf 

### ISSUE THREAD

**Issue by elixir1349** [vedmack/yadcf#164]
I post here my question http://stackoverflow.com/questions/29005929/do-tags-into-clickable-tags-filters-for-jquery-table-yadcf

I refer to this example:

http://yadcf-showcase.appspot.com/DOM_source_select2.html

I would like add for every tag in column 4 a clickable filtering feature so I can display rows that contains tag1 or tag2 only.

Just another thing
I see that the number of values remains 8 for the Country column and does not change if the number of rows contains perhaps only 2 states. Is possible to fix this because I have a several number of countries or cities?

Thanks

**Comment by vedmack** [comment]
Answered on SO, next time please post questions only on [stackoverflow](http://stackoverflow.com)

for the "other thing" the number remains 8 all the time because select filter should display all the available options for the column and not the one currently filtered...
