### ISSUE TITLE
Multiple filter_types for a column

### ISSUE THREAD

**Issue by gane5h** [vedmack/yadcf#165]
Is it possible to have multiple filter_types (eg: multi_select as well as date_range) for the same column? I want users to be able to filter a date column either with relative date ranges such as "last 3 months" or a specific date range (Jan-1-2014 to Mar-1-2014).

Any pointers will be appreciated! Thanks.

**Comment by vedmack** [comment]
Right now its impossibe, The closest thing that I can think of is adding an ability to yadcf to replace filter type for a specific column and you will have to add some button / trigger to your web app that will call that new yadcf function telling it to replace some filter with a new one

**Comment by RRaylion** [comment]
If you implement could you include the new exclude feature

**Comment by vedmack** [comment]
despite the fact that it could be a nice addition to yadcf it wont be implemented (luck of interest from the community / no time)
