### ISSUE TITLE
date and range_date do not hide datepicker on lost focus.

### ISSUE THREAD

**Issue by gane5h** [vedmack/yadcf#166]
The wrapper for the date and date_range filters only listen for KeyUp event. The usual way to use the datepicker is via a mouse and therefore the picker doesn't hide when losing focus, or the filter is not triggered when the date changes. What's the best way to accomplish this?

**Comment by vedmack** [comment]
Please provide a better explanation, because I can't understand your current question, the calendars are being closed when mouse is clicked outside and that's ok, see the [following date range example](http://jqueryui.com/datepicker/#date-range) a and notice that its behavior is similar to yadcf
