### ISSUE TITLE
load data and implement onclick event for server side

### ISSUE THREAD

**Issue by elixir1349** [vedmack/yadcf#167]
I don't like have data on a single html because my data list could end up with 500.000 entries and so I want load data from mysql or other source (xml..) but i don't know how can I make it because i want preserve onclick event filters, autocomplete feature, and different font styles for each td etc

In this example I create 3 types of onclick events: http://jsfiddle.net/dhirajbodicherla/chcLmmps/4/

You can help me adapt my demo with code for server side sharing adapted demo with slq file so I can understand better, please?

I see your tutorial http://yadcf-showcase.appspot.com/server_side_source.html but I'm a very bad programmer so don't understand well technical aspects yet.

**Comment by vedmack** [comment]
Sorry but I'm not sure I understand your correctly,
In case that you are asking for help in setup a server side processing with yadcf integration, then I'll give you an answer to a similar request to someone that asked for help in PHP integration (on my showcase you can find some help with JAVA integration...

>
First you must figure out how to make work the global filter of datatables (text input in the upper right corner) , then do the same for the yadcf search inputs , I'm not a php user, but I guess that if the global search can be retrieved using $_GET['search'] , then I guess that if you want to get data of the fifth column you use $_GET['columns[4][search][value]']  , then loop over your list of rows and check if the corresponding string contains / equal to the parameter from $_GET['columns[4][search][value]'] , and so on... 

>
and again, I think github can help ya, for example do the following query https://github.com/search?utf8=%E2%9C%93&q=yadcf+serverside&type=Code&ref=searchresults , than go over projects and see who uses php (you can see it in the repository page (click the colored bar) then do another query in that repository for example columns[4][search][value] and so on till you bump on the php file with some relevant code... maybe this will help ? https://github.com/PaulVanSchayck/alberto/blob/8d3f875ebe6f36394f662599f055a5ba3a999eeb/models/GeneRequest.php

In general yadcf doesn't do anything special, it triggers datatbles api to communicate with the server... so you might get some help on datatbles forum

Can't help more than this,

Daniel.
