### ISSUE TITLE
How to search for exact word when it is substring of another word?

### ISSUE THREAD

**Issue by gnranjith** [vedmack/yadcf#169]
I have a field named marital status(It has two values either married or unmarried) in my database and while married is searched i want to display only the rows which match 'married'. But even the rows with the value unmarried are getting fetched. Please help me with how to go forward with this problem.

**Comment by vedmack** [comment]
you should use the [filter_match_mode](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L142) for your filter.

next time use [stackoverflow](http://stackoverflow.com/questions/tagged/yadcf) to ask questions, github is for bug reports and features request only

**Comment by gnranjith** [comment]
I have also tried using the filter_match_mode as [exact](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L146) but then it doesn't select or matches any row because the data tables plugin queries the database with WHERE condition LIKE '%^Married$%' and hence i thought it must be a new feature to be added and hence posted it [here](https://github.com/vedmack/yadcf/issues/169). Please give me some information regarding it. I am sorry if i am wrong. Thanks !

**Comment by vedmack** [comment]
If you are using datatables server setup there is no need to use the `filter_match_mode` property , just write a proper logic in your sql select to math the exact string, something like `SELECT ... WHERE Column_A = '$string';` (try using `=` instead of `like`)
