### ISSUE TITLE
Enhancement for the selection (filter match mode "contains" or "exact)

### ISSUE THREAD

**Issue by gbalme** [vedmack/yadcf#17]
Hi again !

I think I found a bug in the selection. let's tell that I have 2 similar data in a column : 
- test1
- test0-test1

and I've a dropdown list from what I select the data i want to filter.

If I filter my dropdown list to shows items having in this column the data "test1", it shows also items having in this column the data "test0-test1", probably because it contains also "test1". But the contrary is not true if select "test0-test1" in the list, it's ok and select the good items.

So I think it's a bug.

I've a working example to show you if it's not clear

**Comment by sakethsaxena** [comment]
is there a filter_match_mode option for multi select ?

**Comment by vedmack** [comment]
@sakethsaxena - yes, if it does not work for you open a new issue with jsffiddle/etc test case

**Comment by sakethsaxena** [comment]
Hey,
I'm not sure if this is something pertinent enough to create a new issue and I haven't really worked with jsfiddle before so i'll take sometime to come up with it but i've gone through the yadcf documentation and it doesn't say that it is supported for filter_type: "multi_select", 
* filter_match_mode
                Required:           false
                Type:               String
                Default value:      contains
                Possible values:    contains / exact / startsWith / regex
                Description:        Allows to control the matching mode of the filter (supported in select / auto_complete / text filters)


I'm using yadcf with server side and giving a list of values to the filter. 

The initialisation of the filter I'm trying to work with is like this : 

{ column_number : 4,  filter_type: "multi_select", select_type:"select2",  sort_as:"none", filter_match_mode:"exact" },


and the kind of behaviour i'm looking for can be found here : https://select2.github.io/examples.html#matcher

**Comment by vedmack** [comment]
@sakethsaxena , you have mixed lots of unrelated stuff, please post a question on stackoverflow (tag with yadcf) and I will try to help you there, github is used for bug reports / new features request only
