### ISSUE TITLE
AlphaSortable function in javascript

### ISSUE THREAD

**Issue by elixir1349** [vedmack/yadcf#170]
I wish integrate an alphasortable function like this for my table.

![alphasort](https://cloud.githubusercontent.com/assets/3471861/6708474/ed8aec9e-cd70-11e4-99cb-8c47b32cad12.png)

If you click on A or # you filter all names for letter A or # (# filter by number) and so for the other letters / numbers.

This is a live example for another jquery table. 
http://sanderkorvemaker.nl/test/flexigrid/

This is my table http://jsfiddle.net/dhirajbodicherla/chcLmmps/4/

**Comment by vedmack** [comment]
Question should be asked on [stackoverflow.com](http://stackoverflow.com/questions/29122614/alphasortable-function-in-javascript) and I see you already asked
