### ISSUE TITLE
Problem with filter reset and select2 (4.0.0)

### ISSUE THREAD

**Issue by pibou** [vedmack/yadcf#171]
Hi

first of all, thanks for your contribution.
I m having some problem with the same line of code present in the doFilter and exResetAllFilters functions : 

$("#yadcf-filter-" + table_selector_jq_friendly + "-" + column_number).select2("destroy").select2(optionsObj.select_type_options);

When using them with buttons, I have this javascript error "TypeError: $(...).select2(...) is undefined" and the widget loses its select2 aspect.

Any idea ?

**Comment by vedmack** [comment]
You are welcome,

Did you include the select2 js file? if not than include the js and css if you already included, then try grabbing the [js/css from the showcase (view source and grab from there](http://yadcf-showcase.appspot.com/DOM_source_select2.html) and see if it work for you and tell me what version you tried to include of select2 and it didn't work

**Comment by pibou** [comment]
The wrong library was indeed included : I was trying to make it work with  Version 4.0.0-rc.2

**Comment by vedmack** [comment]
fixed in 0.8.8.beta.26
