### ISSUE TITLE
range date filter not working Version:0.8.8.beta.10

### ISSUE THREAD

**Issue by siemar14** [vedmack/yadcf#172]
i am having an issue where my range date filter is not working correctly. When I add the range date filter with the rest of the column filters, the rest of the filters are removed

![other_filters_removed](https://cloud.githubusercontent.com/assets/9990262/6737446/aa5442a8-ce39-11e4-882a-948f5511b380.PNG)

The format of my date column is YYYY-MM-DD. Could this be an issue? I wantt to have all of the filters displayed.

![filters_without_range_date](https://cloud.githubusercontent.com/assets/9990262/6737456/b86b7b9a-ce39-11e4-83ce-ff9933c86cbd.PNG)
```
oTable = $('#requestTable').DataTable({
    });
     
 
    yadcf.init(oTable, [{
    column_number: 0, filter_type:'text', filter_container_id: 'request_id', filter_default_label: 'Request ID', filter_match_mode:"exact"
    },
    {
    column_number: 1, filter_type: 'select', filter_container_id: 'request_name', 
    filter_default_label: 'Requestor Name'
    }, 

    {
    column_number: 2, filter_type: 'range_date', filter_container_id: 'requestedDate', date_format:'mm/dd/yy'
    },

    {
    column_number: 7, filter_type:'text', filter_container_id: 'irb', filter_default_label: 'IRB #',filter_match_mode:"exact"
    },
    {
    column_number: 8, filter_type: 'select', filter_reset_button_text:'Clear Selection', filter_container_id: 'direct_name', 
        filter_default_label: 'Director Name'
    }

    ],

    {   
        externally_triggered: true
    });

```

**Comment by vedmack** [comment]
It works just fine in the [showcase page](http://yadcf-showcase.appspot.com/dom_source_externally_triggered.html)

According to your posted code the format of your date is  `mm/dd/yy` which an invalid format - [see docs](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L130) , but its not the reason for your error.

Can it be that its your css is the problem ? maybe the width of the filters container is too narrow? try to see in the dev tools of your browser if your missing filters are actually there - just no visible.

Inspect dev tools for possible errors.
