### ISSUE TITLE
onclick event freezing after setting multiple_filter

### ISSUE THREAD

**Issue by elixir1349** [vedmack/yadcf#174]
I read docs but seems that onclick event functions don't work anymore if I set for column 5

filter_type: "multi_select":
select_type: 'select2'

Onclick Event freezing when I set filter_type: "multi_select". 
I can using multifilter but onclick event are disabled. Why?
Demo: http://jsfiddle.net/chcLmmps/16/

Look last column, please. 

![onclick no work](https://cloud.githubusercontent.com/assets/3471861/6758380/fb2a309e-cf37-11e4-899c-b337ac1e4560.png)

I try to change 
yadcf.exFilterColumn(oTable, [[5, $(this).text()]]);

into
yadcf.exFilterColumn(oTable, [[5, ['click','label.lightblue']]]);

but doesn't work.

Please help me, please, please.

**Comment by vedmack** [comment]
Hi,

Github issues are to be used for bug and new features only, question should be asked on [stackoverflow](http://stackoverflow.com/questions/29169327/onclick-event-not-work-with-multi-select-filter-javascript).

Closing this
