### ISSUE TITLE
ambiguously multi_select filtering - issue

### ISSUE THREAD

**Issue by elixir1349** [vedmack/yadcf#175]
Sorry Daniel,
I find a issue for multi_select filtering. AND and OR condition are used ambiguously if you set text delimiter for text.
you need a function that allows you to choose whether to use the AND condition or OR condition, or even both. I suppose problem is caused by select_type: 'select2'

Correct me if I wrong
Here a better explanation

http://stackoverflow.com/questions/29175813/ambiguous-multi-select-filter-and-and-or-condition-javascript

Regards

**Comment by vedmack** [comment]
Questions to be asked on stackoverflow, if I decide its an issue I will ask you to open it here, till then post you thoughts on stackoverflow only.
