### ISSUE TITLE
multi different filters for same column

### ISSUE THREAD

**Issue by elixir1349** [vedmack/yadcf#176]
Your yadcf supports 2 or more filters for same column? 
Maybe auto_complete + auto_complete or auto_complete + multiple_select

![multi filters for same column](https://cloud.githubusercontent.com/assets/3471861/6764936/a6beb0e8-cfc8-11e4-9583-ed54f9e46510.png)

**Comment by vedmack** [comment]
Duplicate of https://github.com/vedmack/yadcf/issues/165
