### ISSUE TITLE
exResetAllFilters should clear dataTables Global Search Textbox

### ISSUE THREAD

**Issue by GMEHTA1981** [vedmack/yadcf#177]
Reset all filters clears every column filter present. However does not clear the dataTables main search box. I understand it is not a part of yadcf. However, what happens is on a 'RESET' button, I have script to call exResetAllFilters and then I have to call fnFilterClear.

This leads to two webcalls (service side). When the Data Volume is as high as 700,000 records. It cause double refresh on screen and creates waiting time. 
Is there a way you can add clear global search filter to you exResetAllFilters ? 

 if ($('.yadcf_ResetFilter').exists()) {
        $(".yadcf_ResetFilter").click(function () {
            yadcf.exResetAllFilters(oTable);
            oTable.fnFilterClear();
        });

**Comment by GMEHTA1981** [comment]
Hello Daniel, 

Any update on this ?

**Comment by vedmack** [comment]
added in [beta .20](https://github.com/vedmack/yadcf/blob/master/beta/jquery.dataTables.yadcf.js)
