### ISSUE TITLE
Filter in column A based on data in column B

### ISSUE THREAD

**Issue by bdunsmuir** [vedmack/yadcf#179]
I'd like to be able to filter by a value in column A, but only if the value in column B matches a specific value. 

Example.
 Column A   Column B
     Hold             1

I want to filter for "Hold" but only if Column B has a value of 1

**Comment by vedmack** [comment]
It will be possible only for `custom_func` or `multi_select_custom_func` filter types, any objections? it will be sent as argument to the `custom_func` function.

**Comment by bdunsmuir** [comment]
Sounds great to me, I will be using it with ```multi_select_custom_func```

**Comment by vedmack** [comment]
You can use the third parameter that yadcf will pass to your custom function, read the updated docs of [custom_func](https://github.com/vedmack/yadcf/blob/master/beta/jquery.dataTables.yadcf.js#L40)
