### ISSUE TITLE
Option to have no default filter <option> (multi select only?)

### ISSUE THREAD

**Issue by dankirberger** [vedmack/yadcf#181]
We have found a need for our multi select filters to *not* have any default <option> at all, users instead use the "x" filter reset buttons to clear their filter. We just modified the option list creation directly to not create one for the filter_default_label record.

Would that be worth integrating as a formal option? Perhaps a a value of null for filter_default_label to signify this? I imagine it would only make sense for multi select filters.

**Comment by vedmack** [comment]
If you are using `select_type` property for the column select2/chosen then there wont be any `default label at all`

see code :

```
else if (columnObj.filter_type === "multi_select" || columnObj.filter_type === 'multi_select_custom_func') {
	if (columnObj.select_type === undefined) {
		options_tmp = "<option data-placeholder=\"true\" value=\"" + "-1" + "\">" + filter_default_label + "</option>";
	} else {
		options_tmp = "";
	}
}
```

In case you are not using select2/chosen, then you can try placing `select_type: 'dummy'` and still it should be enough for not placing any default value.

**Comment by dankirberger** [comment]
Perfect, thanks.
