### ISSUE TITLE
Clearing an external filter collapses the filter container

### ISSUE THREAD

**Issue by bdunsmuir** [vedmack/yadcf#183]
When I remove all selections from an external filter, the container collapses and does not expand when clicked on again. I may just be doing something wrong. Here is a JS bin with the issue

http://jsbin.com/licema/1/edit?html,css,js,output

**Comment by bdunsmuir** [comment]
Any idea when you might have time to look at this?

**Comment by vedmack** [comment]
Hopefully in the following days

**Comment by vedmack** [comment]
Spent way too much time on something that I thought would be a minor issue... but still no solution. will see how it can be fixed...

**Comment by vedmack** [comment]
fixed in yadcf 0.8.8.beta.22
