### ISSUE TITLE
More options for sort_as and sort_order

### ISSUE THREAD

**Issue by EosEtIris** [vedmack/yadcf#185]
First off, this plugin is awesome. Thank you for making it.

In the multi_select filter I am using I have both alpha and numerical data to filter cells with. 
At the moment I use sort_as: alpha and sort_order asc and this gives me something like this in the filter drop-down. 16353, 34252, 82742, FncAlpha, FncBeta, branches, tags
What I would like is for them to be displayed like this
branches, tags, FncAlpha, FncBeta, 16353, 34252, 82742
The reason for this is that the likelihood that someone will want to filter by one of the numbers is a lot lower than that they will want to filter by "branches".

The other feature request I have is that when I use sort_as: num and sort_order: asc in a different filter it gives me the following.
100, 83.333, 90.8929, 92.4242
I assume that its being sorted by Text and that's why the 100 is first.
Is there a way you can change it so that it orders it by value?

**Comment by vedmack** [comment]
Please provide jsbin / jsfiddle link to you use cases so I can debug them...

**Comment by EosEtIris** [comment]
This is an example for the first issue I have. The affected columns are the last three.
https://jsfiddle.net/8kxL5hj6/
Here is the example for second issue. The last column is the one affected.
https://jsfiddle.net/yupnfw9s/
I don't quite know why, but you may need to filter the table once before being able to scroll to the last three columns on the first example. Not sure where this bug comes from, if it is a bug, or if its just my browser.
Thanks again.

**Comment by vedmack** [comment]
So you are asking for a alphanumeric sort option? so that first there will be words and then numbers? 

and as to the *other feature* please provide a jsfiddle with an example in which when you use `sort_as: num, sort_order: asc` it does not work as expected I haven't seen it in your jsfiddles

**Comment by EosEtIris** [comment]
If possible I would like to be able to choose what comes first. As in the First example the words are more relevant than the numbers, so I would like them to be displayed first. However in the second example the numbers are more relevant than the words, in which case I would like the numbers to be displayed last. In both cases I would like them to be listed in ascending order.

With regards to the other feature. My apologies, I forgot to change the example back after playing around with the sorting.
https://jsfiddle.net/yupnfw9s/1/
The order is now completely different from the alpha sort. I assume that the % symbol is messing with the sort order.

**Comment by vedmack** [comment]
Added `alphaNum` and `custom` to the `sort_as` and added `sort_as_custom_func` property (read docs) alpha num will order numbers first and then words/letters , in addition I added you the ability to provide your own custom sorting function

**Comment by EosEtIris** [comment]
Was finally able to test the function, and its exactly what I needed. Thank you so much.
