### ISSUE TITLE
Filtering using ColReorder

### ISSUE THREAD

**Issue by dotpmrcunha** [vedmack/yadcf#186]
Hi yadcf,

it seems when I use the ColReorder and then filter there is a problem. In this example  http://jsfiddle.net/e4685cug/ when I move the first column to the second and then I write "Safari" in the text field, the results are filtered by the initial second column and not the one that are suppose to be. In my implementation the same problems occur. Do I need to add anything?

Thanks for your support and keep the good work ;)

**Comment by vedmack** [comment]
I did some tuning in the code but It might be that there is an issue with datatables/colreorder itself , so I  opened an issue over there https://github.com/DataTables/ColReorder/issues/36

**Comment by vedmack** [comment]
My bad, there was no issue on datatables side at all... added the needed code on my side , your jsfiddle works (using the yadcf beta.21)
