### ISSUE TITLE
Radio Button Filter

### ISSUE THREAD

**Issue by siemar14** [vedmack/yadcf#187]
I have a user request for a radio button for yes and no values. Will this be a filter type option available in the future?

**Comment by vedmack** [comment]
Since there is a decent amount of open issues right now I don't think that this one will be added soon, but you are welcome to send a pull request for it :) But hey who knows it can happen sooner...

**Comment by GMEHTA1981** [comment]
Any update on this ?

**Comment by vedmack** [comment]
this **might** be helpful https://github.com/vedmack/yadcf/issues/289#issuecomment-185948373

**Comment by vedmack** [comment]
Despite the fact that it could be a nice addition to yadcf it wont be implemented (luck of interest from the community / no time)
