### ISSUE TITLE
Yadcf + Ghost Reset button in IE

### ISSUE THREAD

**Issue by Raug** [vedmack/yadcf#188]
Hi everyone, i've been using yadcf for a long time now without any issues. It's a great plugin and i've never had an issue with it.

However, one of my coworker told me that the reset button in IE doesn't work.
The fact is i've disabled them on the website so i was very surprised to see them appear on his browser.

There seems to be a ghost reset button that only appears in IE as you can see by opening this example :  http://yadcf-showcase.appspot.com/server_side_source.html

If you open it on chrome or FF there's only the gray cross at the far right of every filter but if you open it in IE there's also an another cross that appears at the right of the search filed and that just clears the text without redraw.

I've browsed the web quite a long itme without finding anything at all on the subject.

I'm currently looking for a way to either disable or hide this ghost button in IE or keep it (i don't really mind) but in that case i'd like it to trigger a redraw when clicked.

Is there a way to do it ?
Is it a problem of IE version ?
Do i need to come back at night, uninstall IE from every computer, install chrome and replace chrome icon with IE's on the desktop ?

Thanks in advance,

Raug

**Comment by Raug** [comment]
Solved.

In case anyone faces the same problem : 

This problem is not really a yadcf problem, in fact this ghost cross appears in every IE input.
I chose to supress it altogether by adding these few lines of css code at the end of my personal css file as seen in this thread : http://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs

<code>
.someinput::-ms-clear {
  width : 0;
  height: 0;
}
</code>

**Comment by vedmack** [comment]
You can also use the following
```
.someinput::-ms-clear {
    display: none;
}
```
