### ISSUE TITLE
Select filter type issue

### ISSUE THREAD

**Issue by KirillRyzhkov** [vedmack/yadcf#189]
I initialized select filter type for a colum using this code
{
column_number: 3,
filter_type: 'select',
column_data_type: "html",
html_data_type: "text",
filter_default_label: "Select status",
}

It is working fine. But problem is that I have to select option Active and Inactive. So if I select Inactive it shows all Inactive records fine but if I select Active it will show Inactive as well because inactive has active part in it. How can I filter only Active records when Active is selected?

**Comment by KirillRyzhkov** [comment]
Ok, found a solution. filter_match_mode: "exact" 
Thanks for the great plugin

**Comment by vedmack** [comment]
You are welcome, next time please use stackoverflow (yadcf tag) for asking a question,  use github for bugs / feature requests only.
