### ISSUE TITLE
Usage with FixedColumn plugin breaks functionality

### ISSUE THREAD

**Issue by Jrizzi1** [vedmack/yadcf#190]
So I am using datatables 1.10.6 with the most recent version of his fixedcolumn plugin on the site

but implementing fixedcolumn broke my yadcf

it seems that when fixedcolumn is called , it is creating a clone table for the frozen rows, which makes the yadcf for the frozen rows to not function at all

[here is the jsfiddle of the issue](http://live.datatables.net/laxinabe/2/edit?html,js,output)

**Comment by RRaylion** [comment]
its the scrollX:100% that is killing the table -- disable and works fine

**Comment by Jrizzi1** [comment]
@RRaylion the whole purpose of the fixedcolumn is to fix columns to the left, without the scrollX:100% , no columns stay fixed

[here is the same example with double the columns](http://live.datatables.net/laxinabe/18/edit)
by commenting out the scrollX:100% you will see what I mean

I appreciate you trying though!

**Comment by 1nickt** [comment]
@Jrizzi1 Did you fix this?

I am dealing with the same issue and am using the `filter_container_id` attribute for column in `yadcf.init` to display the filter for the fixed column elsewhere than the original column, which is hidden underneath the cloned column.

It's working OK, but I would like to put it simply in the header of the cloned column. Unfortunately the cloned table is not given an ID by DataTables, and `yadcf` wants an ID.

Any suggestions welcome, thank you.

**Comment by vedmack** [comment]
Thats not perfect, but I had some progress with the fixed header, see jsbin sample (click the run with JS) http://live.datatables.net/laxinabe/38/edit

**Comment by Jrizzi1** [comment]
It almost working great but i have two frozen columns, and you can see from your example, the first input spans those two columns, rather than giving two inputs in each of the two columns

![image](https://cloud.githubusercontent.com/assets/622313/13847423/881fff98-ec23-11e5-821e-10f6d817c426.png)

**Comment by vedmack** [comment]
Since FixedColumn does not provide an api to work with I wont be able to support it right now.
Maybe in the future FixedColumn  will be re implemented just like FixedHeader and yacf will support it out of the box (just like with FixedHeader)
