### ISSUE TITLE
Range_number_slider doesn't work when data source is JSON

### ISSUE THREAD

**Issue by shrewdlogarithm** [vedmack/yadcf#191]
The code for setting-up the range slider assumes that rowdata (moved into adata) will be indexed by column numbers - but if your datasource is JSON it's indexed by column NAMES - so it just plain doesn't work (any attempt to filter or reset the filter simply blocks all values)

Obviously there are many, many things going-on but certainly a check for it being an array (not an object) would solve the JSON thing

**Comment by vedmack** [comment]
please provide a jsbin/etc to reproduce the problem

**Comment by shrewdlogarithm** [comment]
I'm not about to create an entire example to demonstrate a feature of datatables - sorry, but I spend more time creating examples of bugs than I do coding anything else these days...

The bug is pretty obvious - Datatable's "aaData" parameter supports arrays AND objects (used mostly with JSON data) - objects are indexed by keys not column numbers of course. 

(This is line 879 onwards in the current .js file) (addRangeNumberSliderFilterCapability) 

````
if (rowData !== undefined) {
    aData = rowData;
}
val = aData[col_num] <<<< that's not gonna work here!!
````

A lot of these sorts of problems with datatables come down to the dog's breakfast which is the way Datatables API and functionality has evolved - so many ways of doing stuff that it's hard to keep-up with them all.

range_number works AOK tho, so I'm sure range_number_slider can be kicked-into doing so (I wonder why it has a different filter function when it's effectively filtering the same thing???)

**Comment by vedmack** [comment]
what version are you using?

**Comment by shrewdlogarithm** [comment]
I've actually removed it - but the issues I had were in the latest version
on GitHub at the time of posting (downloaded that day)...

**Comment by vedmack** [comment]
fixed
