### ISSUE TITLE
range date filter with bootstrap date picker.

### ISSUE THREAD

**Issue by nsandy433** [vedmack/yadcf#192]
I want to use bootstrap date picker for yacdf range date filter instead of jquery UI datepicker as we are using bootstrap date picker in our entire application. Is it possible to do that? If so, Can you please tell how can we do that?

**Comment by vedmack** [comment]
additional code is needed to be add to yadcf for that, you can do it yourself and send a PR and I will merge it, or you can leave this issue and wait until I will add the support myself... b.t.w you mean this [bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker)?

**Comment by nsandy433** [comment]
Thank you so much for the quick reply Vedmack. Sorry, actually we are using http://freqdec.github.io/datePicker/demo/   
 - DEMO #1   datepicker.  Can you please tell what code needs to be added to use this datepicker for range date filter?

**Comment by vedmack** [comment]
Hi, is this still relevant? Because yadcf 0.8.9.beta.5 is now support [Eonasdan/bootstrap-datetimepicker](https://eonasdan.github.io/bootstrap-datetimepicker/) , see more details [in here](https://github.com/vedmack/yadcf/issues/211#issuecomment-123026777)
