### ISSUE TITLE
filter_match_mode "regex"

### ISSUE THREAD

**Issue by xmikew** [vedmack/yadcf#193]
Am I missing something? Looking at the code I don't see a way to allow typing in regexes in column filters. 

"contains" turns on smart matching
"starts with" turns on regex, but adds "^"
"exact" does ^$.

Is there a way to allow the user to specify a regex? If there is I'm not seeing it. I'll add a filter_match_mode 'regex' if you think that is the way to go.

Thanks,

\- Mike

**Comment by vedmack** [comment]
currently there is no regex filter_match_mode, feel free to send a PR for this feature :+1:, but please make sure your code will be linted and add the support in all the places in which the filter_match_mode is used

**Comment by vedmack** [comment]
just saying that working with dropbox (public folder) is much much comfortable then with rawgit, go to public folder -> right click on file  -> copy public link...

**Comment by xmikew** [comment]
Thanks, just saw the note about beta. I'll add it there as well

**Comment by vedmack** [comment]
cool, the PR should modify only the beta file and keep the stable version intact
