### ISSUE TITLE
Filters not displayed when using DataTable language option

### ISSUE THREAD

**Issue by ip512** [vedmack/yadcf#195]
When using language option, no filter is displayed. If the option is removed, all configured filters appear.

**Comment by ip512** [comment]
I figured out that it's not the language option itself but the fact that language string were loaded with an ajax request.
I used the init event of datatable to force the intialisation of yadcf to wait for datable init to be complete :

    table.on( 'init.dt', function () {
                yadcf.init(table, [{...}]);
    });

Works fine now

**Comment by vedmack** [comment]
if you'll provide a test case I can take a look at it... because the way you init yadcf look a bit *weird*

**Comment by ip512** [comment]
sure, on this fiddle : http://jsfiddle.net/ip512/10stus57/ you'll see that if you remove language option, filters will appear
