### ISSUE TITLE
Cumulative filters / disabling fitlers 

### ISSUE THREAD

**Issue by jcolls** [vedmack/yadcf#196]
At the moment if you apply a filter on one column and then apply a filter on a different column it is easy to get a "no results" message. This is because the selected filters work in collaboration.  Which is useful in its own right.

It would be good to have the option though to be able to set the filters to work individually of one another.  

It would also be a nice feature on either method to have the ability to style the filter results differently based on if they will return results or not (in the displayed column after the first filter).  This could then give the opportunity to give the appearance of being disabled so that the user is aware.

**Comment by vedmack** [comment]
Please give an small example/scenario in with that kind of a filter

**Comment by RRaylion** [comment]
I think you would need a check box like the exclude to make this work 

filters are by default and --example: I want teachers with this name AND live in this state
but using the datatables api it is a lot harder to implement even with the regex filters --
--example: I want teachers with this name OR live in this state

I would love to see the code that gets this to work and doesn't blow up large data sets

**Comment by jcolls** [comment]
Hi there, 

As an example, if you take a look at another datatables filter widget
http://cyberhobo.github.io/column-filter-widgets-examples/extras/ColumnFilterWidgets/index.html

You'll see that if you filter by the first column (Rendering Engine) and choose for example 'Trident' the other filters are updated to only include the applicable filters from the remaining table data. Further to this if you narrow the results so that there is a single row then the other filters are disabled.  This I think reduces the chances of users ending up with no results because of conflicting filters.

I was suggesting an option for YADCF to work a similar way to the above. But with an additional option that would return the full data in the columns but give the results a class, allowing styling, dependent if they are in the filtered table or in the original dataset.  This would show the users the full filters possible but highlight the ones that would return results.

I would imagine that this feature would be best at table level rather than individual filter level as it would confuse users if it was random so I do not think a checkbox like the exclude option would help much.

**Comment by RRaylion** [comment]
Wow I was totally thinking in the wrong direction...

**Comment by vedmack** [comment]
Take a look at the [cumulative_filtering.html](https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/cumulative_filtering.html)

**Comment by jcolls** [comment]
That is great Daniel. Appears to work perfectly from what I can see.  Thank
you.

**Comment by vedmack** [comment]
Added in [0.8.9.beta.13](https://github.com/vedmack/yadcf/blob/34059cf53ad2a9bf4215d89b9d4a6731ee54246e/jquery.dataTables.yadcf.js), read [updated docs](https://github.com/vedmack/yadcf/blob/34059cf53ad2a9bf4215d89b9d4a6731ee54246e/jquery.dataTables.yadcf.js#L237) / see [new showacse page](http://yadcf-showcase.appspot.com/cumulative_filtering.html)
