### ISSUE TITLE
column_data_type support for range_date

### ISSUE THREAD

**Issue by chimos** [vedmack/yadcf#200]
Hi, 
I am trying to use such a filter:

```javascript
{column_number : 11, filter_type: 'range_date', date_format: 'dd.mm.yyyy', filter_default_label: ['von', 'bis'], filter_container_id: 'extFil-6'},
```

The problem is that the date cell contains hidden data for sorting/formatting purposes and the date filter 'from-to' doesn't work.
```html
<td><span class="hidden">20150505</span>05.05.2015</td>
```

I tried with `column_data_type: 'html'` without success. Is it possible to ignore hidden (`display: none`) html within data?

Thanks

**Comment by vedmack** [comment]
Please try latest [beta.33](https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/resources/js/jquery.dataTables.yadcf.js) and let me know how it works for you , you should use
```
{column_data_type: 'html'`,
 html_data_type: 'selector'`,
 html_data_selector: 'span:eq(1)'
}
```

and change your `td` content into the following structure `'<td><span class="hidden">20150505</span><span>05.05.2015</span></td>'`

**Comment by chimos** [comment]
Thanks for your help. I updated from 0.8.6 to the link you provided, 0.8.8 beta, and changed the HTML structure as you suggested. But the filter widget is not working properly (the datepicker popup doesn't close after date selection) and none of the filters are working at all (I can select values but they don't filter). 

In the console appears this error two times:

>Uncaught TypeError: Cannot read property 'column_number_data' of undefined
>jquery.dataTables.yadcf.js:1045
`if (columnObj.column_number_data !== undefined) {`

**Comment by vedmack** [comment]
Check out [beta 34](https://github.com/vedmack/yadcf/blob/master/beta/jquery.dataTables.yadcf.js)   , see [jsbin sample](http://jsbin.com/zowadenisu/1/edit?html,js,output) ,
note that the td content should have the following content (added `span` wrapper) 
`<td><span><span class="hidden">20150505</span><span>05.05.2015</span></span></td>`

**Comment by chimos** [comment]
The date filter is not working yet. The rest of filters are working now. Without errors in the console.
FYI:
I updated the beta CSS as well.
Added the extra `span` wrapper.
I'm using DataTables 1.10.4

The jsbin sample you provided is working properly but I still can't understand the problem in my code. I will look at it later, when I have more time and maybe try to provide here a demo reproducing my problem, if necessary. 

Thanks for your help!

**Comment by vedmack** [comment]
Without a live sample that will reproduce your issue I wont be able to help much

**Comment by chimos** [comment]
It took me a while to simplify the code and build a demo:
https://jsfiddle.net/chimos/yzd3vfws/2/
You'll see that the 'from-to' date filter doesn't work. You can select values but no results are returned.

**Comment by vedmack** [comment]
Your code will work perfectly if you will use the right index for the column , see [working sample](https://jsfiddle.net/yzd3vfws/5/)

Your date column index should be **8** instead of **11**

:)

**Comment by chimos** [comment]
Yes, it was wrong, it's working now ^^'
Thanks for solving this issue.

I'm using YADCF in multiple sections of a production site. As it is beta, is it safe to use this version? Or should I wait for the next stable release?

**Comment by vedmack** [comment]
you can always find a bug in a stable and in a beta version, I'd say that you can use a beta and in case of a bug just report it.

**Comment by chimos** [comment]
Thank you!
