### ISSUE TITLE
date_format:  dd/mm/yyyy no longer works on 0.8.8.beta.26

### ISSUE THREAD

**Issue by 2bitcoder** [vedmack/yadcf#201]
Filtering by dates with dd/mm/yyyy worked fine on 0.8.8.beta.22,  no longer works 0.8.8.beta.26

does work if I use mm/dd/yyyy

{
           column_number: 16,
           filter_type: "range_date",
           filter_container_id: "external_filter_container",
           date_format: "dd/mm/yyyy"
       },

**Comment by vedmack** [comment]
works fine in beta 35, see [jsbin sample](http://jsbin.com/jagoqahozo/1/edit?js,output)

**Comment by 2bitcoder** [comment]
Thank you - and thank you for such a fantastic datatables plugin
