### ISSUE TITLE
Cancel button is showing up below filter boxes. 

### ISSUE THREAD

**Issue by pricejt** [vedmack/yadcf#202]
I am having trouble trying to figure out why the "x" button is showing up under these filter boxes.

![image](https://cloud.githubusercontent.com/assets/2791439/7851431/be554bfc-04bd-11e5-9bfc-6c073900e7fe.png)

There is an inner wrapper 
![image](https://cloud.githubusercontent.com/assets/2791439/7851443/eb3798c8-04bd-11e5-8752-11d6fcabea18.png)

Then there is a wrapper that is around both lines. 
![image](https://cloud.githubusercontent.com/assets/2791439/7851453/0def3100-04be-11e5-9558-781f616cf8cf.png)

This is my call to the columns

![image](https://cloud.githubusercontent.com/assets/2791439/7851469/4657bdd2-04be-11e5-8aed-18c2e0557c2d.png)

And this is the result. 
![image](https://cloud.githubusercontent.com/assets/2791439/7851472/582d91da-04be-11e5-8368-c00caedaa452.png)

Any help would be appreciated. 
Thanks, Justin

**Comment by vedmack** [comment]
Looks like you forgot to include yadcf css file
