### ISSUE TITLE
scrollY still breaking tables - at least mine 

### ISSUE THREAD

**Issue by RRaylion** [vedmack/yadcf#203]
I updated my tables to newest version,  And I admit I am doing some fairly complex stuff with datatables  and scrollY still hides the filter list behind the table for chosen and select.

`
var oTable = $('#PropertyTable').dataTable({
            "processing": true,
            "ajax": {
                "url": "../api/vw_ppty_scrape",
                "dataSrc": "",

            },
            "bJQueryUI": true,
            "dom": 'Tflrtip',
            "tableTools": {
                "sSwfPath": "../../../Content/swf/copy_csv_xls_pdf.swf",
                "aButtons": [
                    {
                        sExtends: "xls",
                        "oSelectorOpts": {
                            page: 'all',
                            filter: 'applied'
                        },
                        "mColumns": "visible"
                    },
                    {
                        "sExtends": "pdf",
                        "sPdfOrientation": "landscape",
                        "oSelectorOpts": {
                            page: 'all',
                            filter: 'applied'
                        },
                        "mColumns": "visible",
                        "sPdfSize": "legal"
                    },
                    "print"
                ]
            },
            
            //"scrollY": 600,
            "pagingType": "full_numbers",
            "columns": [
                {
                    "className": 'details-control',
                    "orderable": false,
                    "data": null,
                    "defaultContent": '<img src="https://i.imgur.com/SD7Dz.png">',
                    "bSortable": false, "aTargets": [0]
                },
                { "data": "str_owner_nm", "targets": [1], "visible": true, "searchable": true, "width": "175px" },
                { "data": "str_ppty_name", "targets": [2], "visible": true, "searchable": true },
                { "data": "int_ppty_id_match", "targets": [3], "visible": true, "searchable": true, "width": "175px" },
                { "data": "char_priority", "targets": [4], "visible": true, "searchable": true, "width": "200px" },
                { "data":  "char_ignore"},// "defaultContent": "<button class='iP'>Set Ignore</button>", "targets": [5], "visible": true, "searchable": true },
                { "data": "dts_first_scraped", "targets": [7] , "width": "200px" },
                { "data": "int_ppty_scrape_id", "targets": [8] }
            ],

            "aaSorting": [[1, 'asc']],
            "rowCallback": function (row, data) {
                var tableRow = $('td', row).parent();
                var sId = $(tableRow).find('td')[7].innerHTML;
                //if ($(tableRow).find('td')[3].innerHTML != 0 || $(tableRow).find('td')[3].innerHTML != "0") {
                //    $(tableRow).find('.cP')[0].style.display = 'none';
                //    //$(tableRow).find('td')[3].innerHTML = "<button class='cP'>Create / Match Property</button>";
                //}
                if ($(tableRow).find('td')[3].innerHTML == 0 || $(tableRow).find('td')[3].innerHTML == "0") {
                    //$(tableRow).find('.cP')[0].style.display = 'none';
                    $(tableRow).find('td')[3].innerHTML = "<button class='cP'>Create / Match Property</button>";
                }

                if ($(tableRow).find('td')[5].innerHTML == "") {
                    $(tableRow).find('td')[5].innerHTML = "<p data-toggle='tooltip' data-placement='right' align='center'>\
                                                                <input id='changeIgnore' type='checkbox' data-on-text='Yes' data-off-text='No'\
                                                                    data-indeterminate='true' data-label-text='Not Set' class='iP bsSwitch indetermine' data-id='"
                                                                    + $(tableRow).find('td')[7].innerHTML + "' " + "name='switch" + $(tableRow).find('td')[7].innerHTML + "'" + " \\>\
                                                          </p>";
                }
                if ($(tableRow).find('td')[5].innerHTML == "Y") {
                    $(tableRow).find('td')[5].innerHTML = "<p  data-toggle='tooltip' data-placement='right' align='center'>\
                                                                <input id='changeIgnore' type='checkbox' checked='true' data-on-text='Yes' \
                                                                 data-off-text='No' data-indeterminate='false' data-text-label='Click To Toggle' \
                                                                 class='iP bsSwitch determine' data-id='"
                                                                 + $(tableRow).find('td')[7].innerHTML + "' "+ "name='switch" +
                                                                 $(tableRow).find('td')[7].innerHTML + "'" + " >\
                                                           </p>";
                }
                if ($(tableRow).find('td')[5].innerHTML == "N") {
                    $(tableRow).find('td')[5].innerHTML = "<p  data-toggle='tooltip' data-placement='right' align='center'>\
                                                                <input id='changeIgnore' type='checkbox'  data-on-text='Yes' \
                                                                 data-off-text='No' data-indeterminate='false' data-text-label='Click To Toggle' \
                                                                 class='iP bsSwitch determine' data-id='"
                                                                 + $(tableRow).find('td')[7].innerHTML + "' " + "name='switch" +
                                                                 $(tableRow).find('td')[7].innerHTML + "'" + " >\
                                                           </p>";
                }

                if ($(tableRow).find('td')[4].innerHTML == "Y") {
                    $(tableRow).find('td')[4].innerHTML =  "<p data-toggle='tooltip' data-placement='right'  align='center'> \
                                                               <input  checked id='changePriority' type='checkbox'  data-on-text='Yes' \
                                                                       data-off-text='No' data-indeterminate='false' data-text-label='not Set' \
                                                                       class='iP bsSwitch determine' data-id='" + $(tableRow).find('td')[7].innerHTML + "' " +
                                                                       "name='switch" + $(tableRow).find('td')[7].innerHTML + "'" + " \>\
                                                           </p>";
                }
                if ($(tableRow).find('td')[4].innerHTML == "N") {
                    $(tableRow).find('td')[4].innerHTML =  "<p align='center' data-toggle='tooltip' data-placement='right' >\
                                                               <input  id='changePriority' type='checkbox'  data-on-text='Yes' \
                                                                       data-off-text='No' data-indeterminate='false' data-text-label='not Set' \
                                                                       class='iP bsSwitch determine' data-id='" + $(tableRow).find('td')[7].innerHTML + "' " +
                                                                       "name='switch" + $(tableRow).find('td')[7].innerHTML + "'" + " \>\
                                                           </p>";
                }

                return row;
            },
            "fnInitComplete": function (oSettings, json) {
                //alert('DataTables has finished its initialisation.');

                var oApiTable = $('#PropertyTable').DataTable();
                yadcf.init(oApiTable, [
                    // if a column is ever added just tag it onto the end
                    { column_number: 1, filter_type: "multi_select", select_type: 'chosen' },
                    { column_number: 2, filter_type: "multi_select", select_type: 'chosen' },
                    { column_number: 3, filter_type: "multi_select", select_type: 'chosen' },
                    { column_number: 4, filter_type: "multi_select", select_type: 'chosen' },
                    { column_number: 7, filter_type: "multi_select", select_type: 'chosen' },
                ]);
            }
        });`

why initialize in the fnInitComplete ?? because otherwise the filters fail to load at all.

**Comment by vedmack** [comment]
Hi,

A smaller sample could be better next time :)

Anyway I have added `.dataTables_scrollHead {
	overflow: visible !important;
}` to [yadcf css file](https://github.com/vedmack/yadcf/blob/7b88a12db2e51cce0712bde8c81ac85a948c3bb3/beta/jquery.dataTables.yadcf.css), it works for me, so grab and tell me how it does for you

**Comment by vedmack** [comment]
Because of the chosen behaviour it is incapable to "get along" with datatables scrolX (select2 works just fine), so I will remove the `.dataTables_scrollHead { overflow: visible !important; }` from yadcf so the scrolX will work with yadcf, but if you dont need the scrolX you can add the `.dataTables_scrollHead { overflow: visible !important; }` code to your own css file and the chosen will work with the scrolY for you

See related info:

https://github.com/vedmack/yadcf/issues/43#issuecomment-118832177
https://github.com/DataTables/DataTables/issues/593
