### ISSUE TITLE
Select box with selected option

### ISSUE THREAD

**Issue by oliobi** [vedmack/yadcf#208]
Hi vedmack,
for example, i got a table with col value (True, False) and i use your plugin to add a select filter to this col and it appear likes:

-Select value
-True
-False

Can this plugin add a selected in True or False option or just remove the "select value"  to make the 2nd option jump to default?
i try to use 
data: [{value: "True", label: "True", select: "selected"}]
but no luck :(
plz help!

**Comment by vedmack** [comment]
If you want to show your table `pre-filtered` you can use the following yadcf api function [exFilterColumn](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L223) , you can see it action in the [showcase](http://yadcf-showcase.appspot.com/multiple_tables.html) scroll to bottom of the page and inspect code snippets,

next time please use [stackoverflow (tag with yadcf)](http://stackoverflow.com/questions/tagged/yadcf) for asking question (github is for new features / bug reports only)
