### ISSUE TITLE
Ajax mData deep example filters not working

### ISSUE THREAD

**Issue by RRaylion** [vedmack/yadcf#210]
http://yadcf-showcase.appspot.com/ajax_mData_source.html

on this web page you demonstrate the ajax and filtering, however Browser and platform filters do not work.

I am on chrome if that makes a difference.

**Comment by vedmack** [comment]
Its a bug related to auto_complete filter type, this bug was fixed several days ago and available in the latest beta version [0.8.9.beta.1](https://github.com/vedmack/yadcf/blob/1537be73b59b166e4323c0a85bc768b524533e58/jquery.dataTables.yadcf.js)
