### ISSUE TITLE
Support for bootstrap datetime picker and date range

### ISSUE THREAD

**Issue by sradesign** [vedmack/yadcf#211]
Hi Daniel,
Please add the support of bootstrap https://github.com/Eonasdan/bootstrap-datetimepicker this one is amazing. I need only this to complete one of my projects.

Best Regards,
Ali.M

**Comment by vedmack** [comment]
Added in [0.8.9.beta.5](https://github.com/vedmack/yadcf/blob/60a02ea6f362dc2a24bf2707062721fed1aa095a/jquery.dataTables.yadcf.js) no official showcase sample yet, but you can take a look at my local sample. just do view source,

Also look at the code snippet


```
        $(document).ready(function () {
            var datepickerDefaults = {
                showTodayButton: true,
                showClear: true
            };
            $('#example').dataTable().yadcf([
                {
                    column_number: 4,
                    filter_type: "range_date",
                    datepicker_type: 'bootstrap-datetimepicker', 
                    date_format: 'YYYY-MM-DD', 
                    filter_plugin_options: datepickerDefaults
                }
            ])
        });
```
