### ISSUE TITLE
Jquery plugins memory leak

### ISSUE THREAD

**Issue by gauravjhs** [vedmack/yadcf#213]
When destroying datatables and yadcf instance, other plugins for number slider and select plugin are not destroyed which leads to memory leak.

**Comment by gauravjhs** [comment]
Hi Daniel. Any view on this? I can help on this if we can discuss how to go forward with this.

**Comment by vedmack** [comment]
Hi,

Sorry . lack of time recently, the solution should be very simple, inside the `removeFilters` function you should call a helper function that will iterate over all yadcf options and with a simple switch will call the destory function of the third party plugin (if used for that column). PR is welcome

**Comment by vedmack** [comment]
gonna release this enachcement soon

**Comment by vedmack** [comment]
fixed that one in [0.8.9.beta.19](https://github.com/vedmack/yadcf/blob/5513793369d923e82c99e7676c65afe56e544934/jquery.dataTables.yadcf.js), please confirm its working well

**Comment by gauravjhs** [comment]
This is great. Thanks a lot.
