### ISSUE TITLE
Custom function not work properly.

### ISSUE THREAD

**Issue by 6aKa** [vedmack/yadcf#215]
When enable yadcf extension with custom function, on load select is "blue" (inuse class enabled).
Than when select some value, I can't drop filter (selecting first value in list "Select value") filter still enabled. Only reload drop filter from field.

DataTables version 1.10.7
yadcf version 0.8.8

**Comment by vedmack** [comment]
Please provide a jsbin, use can use [this for start](http://jsbin.com/mexemavusu/edit?js,output)

**Comment by 6aKa** [comment]
Done. I provide full example, with colvis and fixedheader.
Use nightly fixedheader build because, in release bug with autocolumn width(not update header when changed column width).

**Comment by vedmack** [comment]
fixedheader are not supported by yadcf yet, there is an open issue for that already https://github.com/vedmack/yadcf/issues/157 , if its related to fixedheader only, then you can close this issue and "watch" the already open issue https://github.com/vedmack/yadcf/issues/157

**Comment by 6aKa** [comment]
If disable hixed header, bug still present.

**Comment by vedmack** [comment]
please provide a live example
