### ISSUE TITLE
Column Reorder and Column Filter not working properly together

### ISSUE THREAD

**Issue by mtrayn01** [vedmack/yadcf#218]
I’m seeing an issue with Column Reorder and Column Filter not working together properly. When I move a column to the left, and then try to column filter, it does not work.

I see this has been reported under issue #186, but is marked as fixed in beta21.

I have updated to 89beta4 and still see the problem.

A PM has been sent with connection details to my website to see the problem.

**Comment by vedmack** [comment]
fixed in [0.8.9.beta.8](https://github.com/vedmack/yadcf/blob/7aff7d945557c997e3936d2d85cf4a05f5d9017d/jquery.dataTables.yadcf.js)
