### ISSUE TITLE
Datatable Server Side Filter Defaults

### ISSUE THREAD

**Issue by lavere** [vedmack/yadcf#219]
Is it possible to set default filter values before the first ajax call to the server side? I only want it to run when localStorage is null. Once the user has interacted with the page it should use their settings.

Is this possible? I have tried setting the search values in datatables (doesn't set the filter values) and I have tried using exFilterColumn but then it fires on every page load. Can this not be set in the passed config?

**Comment by vedmack** [comment]
But isnt withouht the fitering on that every page load you table will be loaded with all the rows? I mean that your server return the rows based on the query you are getting from your client and each page load your client fires that query and server response back to it, so how you plan to make your server to return filtered rows only?

**Comment by lavere** [comment]
The idea was that the page would load (having no local storage values, so it would use the defaults), but on subsequent page loads the local storage would be used.

**Comment by vedmack** [comment]
Please describe the flow, from a to z, because I still don't get it how you want yadcf to be used in your scenario... You want your table to be loaded prefiltered without filtering it? so you are using stateSave? yadcf does support stateSave, see [sample page](http://yadcf-showcase.appspot.com/DOM_source.html) play with flters and hit F5...

**Comment by lavere** [comment]
I have an ajax driven table.

I would like to have particular filters set when the page first loads. For
example, I have a type menu that I would like to default search for
"Invoice".

Once the page loads and the user interacts with the table, I would like to
have those settings saved in localStorage so that if the user leaves the
page and comes back (in the same session) that the menus remain as they
were last.

If the user logs out and comes back later, the page should return to the
default settings.

I hope that makes sense.

**Comment by vedmack** [comment]
You can do the following

Make sure you use `stateSave: true` , see [docs here](https://datatables.net/reference/option/stateSave) (uses localStorage unde the hood)

Then also use [yadcf.exFilterColumn(...);](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L233) See it in action [on showcase](http://yadcf-showcase.appspot.com/server_side_source.html) 

And on logout you can call the datatables `table.state.clear();`

**Comment by lavere** [comment]
Wont that call the exFilterColumn every time the page is loaded and NOT use
the local storage?

**Comment by vedmack** [comment]
You can either set a flag into localStorage yourself (and clear it on logout) and use it to tell if calling the `exFilterColumn` is required , or find out if there is some datatables api to tell if stateSave is not empty
