### ISSUE TITLE
Better support for multiselect dropdown and angularjs in general

### ISSUE THREAD

**Issue by jkildedal** [vedmack/yadcf#222]
Hi

Are you planning to make an angularjs version of your plugin (maybe implement it in angular-datatables)? 

Have you considered using a multiselect dropdown list instead of using links beneath the dropdown? 
A plugin like this would be interesting:
http://isteven.github.io/angular-multi-select

Thanks in advance!

**Comment by vedmack** [comment]
Links below the dropdown? huh? I think you confused my yadcf plugin with someones else, here is [yadcf showcase](http://yadcf-showcase.appspot.com/) , you can integrate the selct filter with select2 or chosen or any other third plugin you want using the [initSelectPluginCustomTriggers](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L262) API

Regarding the AngularJS version, I'll think about it

**Comment by jkildedal** [comment]
Hi 

Sorry, confused you with another plugin
https://github.com/cyberhobo/ColumnFilterWidgets

Another thing I noticed: When filtering on one column, the Dropdown/autocomplete values do not update on other columns. Will that be implemented in the future?
This is done in the ColumnFilterWidgets plugin.

It would be great with an angular version through angular-datatables.

**Comment by vedmack** [comment]
You mean that you want something like that issue describes in it? https://github.com/vedmack/yadcf/issues/196 if so you can close this one and open a new one for angular stuff...

**Comment by peyus** [comment]
ok
