### ISSUE TITLE
Multi Table Example? 

### ISSUE THREAD

**Issue by nancle** [vedmack/yadcf#223]
Could someone post a working multiple table example zip file?

**Comment by vedmack** [comment]
You can grab it from the [yadcf-showcase repo'](https://github.com/vedmack/yadcf-showcase) , here is the [relevant html](https://github.com/vedmack/yadcf-showcase/blob/master/war/dom_multi_columns_tables_1.10.html) , here its in action in the [showcase](http://yadcf-showcase.appspot.com/dom_multi_columns_tables_1.10.html)
