### ISSUE TITLE
Allow for predefined filter elements

### ISSUE THREAD

**Issue by jchafik** [vedmack/yadcf#224]
For external filters, it would be nice to be able to

1. Specify a selector containing a predefined filter element.
2. Specify a function to obtain the selected filter value for a filter function.

This would allow for greater flexibility (looking through the other issues - it would allow the user to: define a time filter, radio button filter, placing filters in a popover, etc.) with a reduced need for Javascript manipulating the DOM (resulting in better performance).

**Comment by vedmack** [comment]
You can easily achive it by using the [exFilterColumn](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L233) , you can use it with any input type you wish...
