### ISSUE TITLE
On table reload, "Uncaught TypeError: Cannot read property 'yadcf_data_0' of null"

### ISSUE THREAD

**Issue by Xcellere** [vedmack/yadcf#227]
I updated to the latest stable release of YADCF, and the latest versions of DataTables and Editor. This error doesn't always occur when the table is reloaded, only some of the time.

![log](https://cloud.githubusercontent.com/assets/6492910/9342503/ea40e8f0-45b0-11e5-8622-afac8ac49c74.jpg)

**Comment by vedmack** [comment]
Not sure to which version your refering as latest stable, but try the [newst](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js) from repo, and if still happens provide a link to the page so I can check it there

**Comment by Xcellere** [comment]
You can view the issue here: https://www.dcturano.com/to-do_list/

**Comment by vedmack** [comment]
From my quick check it seems that there is a different error before the one you reported

see console log:

Object {action: "remove", data: Object}
With JSON:
Object {data: Array[0]}
With action:
datatables.include-footer.1668b7.js:formatted:53397 remove
Uncaught TypeError: Cannot read property '0' of undefined
rowID=row_3147


Then after doing page refresh indeed your reported issue appear, its very easy to fix that error on yadcf side- (null check for the json coming back on table loading, **BUT** I never seen a scenario in which the json is coming back as null, so If you want I can add that null check on yadcf, but itd sure doesn't look healthy, IMO you should also find out why the json comes sometimes as null.

**Comment by Xcellere** [comment]
Could you point me in the direction to find out why it’s coming back as null? It doesn’t always do that, but it does sometimes when the page is reloaded.


Regards,
Eric

Software Design - dc|turano
www.dcturano.com<http://www.dcturano.com> | emt@dcturanoinc.com<mailto:emt@dcturanoinc.com> | (310) 956-0284



On Sep 3, 2015, at 1:09 AM, Daniel Reznick <notifications@github.com<mailto:notifications@github.com>> wrote:


From my quick check it seems that there is a different error before the one you reported

see console log:

Object {action: "remove", data: Object}
With JSON:
Object {data: Array[0]}
With action:
datatables.include-footer.1668b7.js:formatted:53397 remove
Uncaught TypeError: Cannot read property '0' of undefined
rowID=row_3147

Then after doing page refresh indeed your reported issue appear, its very easy to fix that error on yadcf side- (null check for the json coming back on table loading, BUT I never seen a scenario in which the json is coming back as null, so If you want I can add that null check on yadcf, but itd sure doesn't look healthy, IMO you should also find out why the json comes sometimes as null.

**Comment by vedmack** [comment]
I would go and check your server code and try to debug and find out why it doesn't return a proper data

**Comment by Xcellere** [comment]
I wanted to send another issue your way. When DataTables Responsive is used and hidden rows are shown, fields with using YADCF and select options show all the options instead of only the selected option. You corrected this in a beta, but it seems to be back:


[image1.PNG]


Regards,
Eric

Software Design - dc|turano
www.dcturano.com<http://www.dcturano.com> | emt@dcturanoinc.com<mailto:emt@dcturanoinc.com> | (310) 956-0284

On Sep 4, 2015, at 2:14 PM, Daniel Reznick <notifications@github.com<mailto:notifications@github.com>> wrote:


I would go and check your server code and try to debug and find out why it doesn't return a proper data

-

**Comment by vedmack** [comment]
@Xcellere , if you reproduce it on the showcase page (second table) http://yadcf-showcase.appspot.com/DOM_Ajax_Multiple_1.10.html please do an open a new issue, if you can tell in what version it did work and since what version it has stopped please mention it too,,,

**Comment by vedmack** [comment]
replaced *uncaught* message with console.log (just in case)

**Comment by mrcrbrown** [comment]
@vedmack the test for undefined won't be hit for me. I'm seeing the json parameter return as null instead of undefined. My scenario is that the datatable is populated after the it's painted. The initial json return is empty so that the datatable has no rows.

**Comment by vedmack** [comment]
Sending a PR changing `===` into `==` is shorter than the above post :) If not, I will commit it in the following days

**Comment by vedmack** [comment]
fixed in [0.8.9.beta.18](https://github.com/vedmack/yadcf/blob/dd61e6aee189cf933c0b80889cf5034ae8d46d55/jquery.dataTables.yadcf.js)
