### ISSUE TITLE
multi_select filters with select2 autocomplete filter in server side showcase

### ISSUE THREAD

**Issue by AlexPowen** [vedmack/yadcf#229]
Sorry, but I don't understand where can I make requests.

Can you include a multi_select filters with select2 autocomplete filter in your ***server side showcase***, please? 
This filter is present  inside your 'client' version only

![autocomplete seach](https://cloud.githubusercontent.com/assets/11960124/9500403/89861f96-4c25-11e5-9724-8debfd6b8f60.png)

In your server side example Global Filter doesn't work. If I type "Internet explorer" nothing happens

![global search](https://cloud.githubusercontent.com/assets/11960124/9500424/ad6f625a-4c25-11e5-9a6a-bac0f6949cdd.png)

**Comment by vedmack** [comment]
I fixed the global search (on the server side) regarding the `filter_type: "multi_select"` , first of all did you succesfully managed to make a filter_type: select to work with your server side setup?

**Comment by AlexPowen** [comment]
Unfortunately not, at the moment no one has a solution with the php . 
Daniel, Will you be able to share an offline showcase version of yadcf with your java version? It would be a valuable aid for me because on StackOverflow  there is no one who can give me a solution..
Thanks

**Comment by vedmack** [comment]
My [yadcf showcase is on github for several month now](https://github.com/vedmack/yadcf-showcase) and you can take a look at it, see [EntrysTableServerSideSource.java](https://github.com/vedmack/yadcf-showcase/blob/master/src/dr/yadcf/servlets/EntrysTableServerSideSource.java) for more info.
