### ISSUE TITLE
Range filtering

### ISSUE THREAD

**Issue by PaulDesigns** [vedmack/yadcf#230]
Hey,

I asked the question on http://datatables.net/forums/discussion/comment/80025 and you asked me to make it an issue here, when you have tie could you add this feature?.

Thanks
Paul

**Comment by vedmack** [comment]
Added, [see in action](https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/DOM_source_select2.html),
docs will be updated in a day or two
code used in this page 
`{column_number : 1, filter_type: "range_number_slider", range_data_type: 'range', range_data_type_delim: '-'}`

**Comment by PaulDesigns** [comment]
this still allows me to use this other search i have, on my page?, and thanks for this

**Comment by vedmack** [comment]
Yes, and also you can keep your original ui by placing the filter outside the table into some external div (use [filter_container_id](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L101) , like in the [showcae sample - third column](http://yadcf-showcase.appspot.com/DOM_source.html) , just make that div `display:none;` and add `onkeypress` event to your range inputs and in them call the [yadcf.exFilterColumn](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L256) for more info read docs / look at the showcase

**Comment by PaulDesigns** [comment]
Ok thanks, i tried this last night but no luck getting it working, i try again soon

**Comment by vedmack** [comment]
`range_data_type: 'range',
range_data_type_delim: '-'`

Allows to filter by range instead single value per column

<table id="test">
  <thead>
    <th>Name</th>
    <th>Surname</th>
    <th>Values</th>
  </thead>
  <tbody>
    <tr>
      <td>John</td>
      <td>Smith</td>
      <td>20-34</td>
    </tr>
    <tr>
      <td>David</td>
      <td>Louise</td>
      <td>15-89</td>
    </tr>
    <tr>
      <td>David2</td>
      <td>Louise2</td>
      <td>60-70</td>
    </tr>
  </tbody>
</table>

```
var tTable = $("table#test").DataTable({
  "bJQueryUI": true
});

yadcf.init(tTable, [{
  column_number: 2,
  filter_type: "range_number_slider",
  range_data_type: 'range',
  range_data_type_delim: '-'
}]);

```
