### ISSUE TITLE
exGetColumnFilterVal returns null for hidden column with colVis in Button-extension

### ISSUE THREAD

**Issue by the86freak** [vedmack/yadcf#231]
Hy Daniel,

I hope I just used your plugin wrong, if not, it's a bug.

http://jsbin.com/reweha/edit?html,js,console,output
### Steps to reproduce
1. filter one column
2. hide this column
3. filter another column
#### result

the entered filter value is not read out anymore but returns null
#### expected

the entered filter value of the hidden column should still be returned by exGetColumnFilterVal

Greetz, Malte

**Comment by vedmack** [comment]
Yep, exGetColumnFilterVal as it is now can get value of visible filter only. are you sure that you need a value of a filter that is now visible to the user?

**Comment by the86freak** [comment]
you mean *not? instead of now, or?

yeah, the point is, that I need the value, as people filter and then hide the column and save the state.
Furthermore, filters are still applied to the dataset, even when the column is hidde, which is fine. But then I need to display that these filters are applied, otherwise, users (sadly) confuse themself.

**Comment by vedmack** [comment]
Ok, then its a feaute, that I will try to implemet as soon as I have time

**Comment by the86freak** [comment]
thanks a lot! Also for providing such an add-on and for such a fast response!

1) If you give me a hint I can try to implement and make a PR if you want.
I would begin here:
https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L3665
?

2) Even more, I thought of an additional parameter for the method, but wouldn't add it, as returning a value is better than null. If someone else doesn't want to retrieve the value he/she can look if the column is hidden or not for themself.

**Comment by vedmack** [comment]
Its not a straight forward the process of retreiving values from filters as part of them are stored in datatables `settingsDt.aoPreSearchCols[column_position].sSearch` and part of them (range filters) are stored relying on yadcf and datatables hybrid solution `oTable.fnSettings().oLoadedState.yadcfState` , PR are surely more than welcomed :) (should be jslinted).
The way I see it, I will rewrite `exGetColumnFilterVal` to get its data from the `aoPreSearchCols` and `oLoadedState.yadcfState` instead from jquery selectors of the filters
