### ISSUE TITLE
Select2, after 'cancel' there are still 'search words' in form

### ISSUE THREAD

**Issue by gesior** [vedmack/yadcf#232]
http://yadcf-showcase.appspot.com/DOM_source_select2.html

After I add 'Some Data' filter 'search word' appears in form.

When I click 'cancel filter', it disables filter (display not filtered data), but in form stays 'search word'.

----
'Chosen' source works fine.
http://yadcf-showcase.appspot.com/DOM_source_chosen.html

**Comment by vedmack** [comment]
fixed in [0.8.9.beta.15](https://github.com/vedmack/yadcf/blob/45c85d24ae0ba7fcbc15404b15644c5387be4321/jquery.dataTables.yadcf.js)
