### ISSUE TITLE
Prevent column sort when hitting Enter in filter

### ISSUE THREAD

**Issue by gesior** [vedmack/yadcf#233]
When I type something in 'filter', it works fine.
When I click enter with 'focus' on filter element, it sort data by column in which is filter.

Can I disable it somehow? Any on/off option in config?

Many people that use old programs click 'enter' after they type text they want to search (not expect 'live' updates).

**Comment by vedmack** [comment]
You are right, haven't noticed it before... will disable pressing enter on filter since there is no point in them.

**Comment by gesior** [comment]
'Number range' from this example:

http://yadcf-showcase.appspot.com/DOM_source_chosen.html

I don't know, if it's a bug, but this filter is called:
**range_number_slider**

There is no slider, just 2 input fields for min/max value.

**Comment by vedmack** [comment]
@gesior , on that showcase ([see js source file](http://yadcf-showcase.appspot.com/resources/js/dom_source_chosen_example.js)] I'm using `filter_type: "range_number"` , the code snippet that is shown in the bottom is indeed wrong... will update the showcase next time a new beta will be released.

**Comment by vedmack** [comment]
fixed in [0.8.9.beta.20](https://github.com/vedmack/yadcf/blob/3c8b167be5a84d620ff4a61f4cb8e689b1909210/jquery.dataTables.yadcf.js)
