### ISSUE TITLE
Date range, wrong date format

### ISSUE THREAD

**Issue by gesior** [vedmack/yadcf#234]
http://yadcf-showcase.appspot.com/server_side_source.html

Scripts use by default wrong 'date picker' date format configuration ('DAY/MONTH/YEAR' - it's not standard!).

Is there any way to configure date format for 'date picker' of 'date range'?

PHP code [test date formats]:

    var_dump(strtotime('25/07/2015')); // DAY/MONTH/YEAR = 'false', not parsable
    var_dump(strtotime('07/25/2015')); // MONTH/DAY/YEAR = 1437796800, US date format
    var_dump(strtotime('25-07-2015')); // DAY-MONTH-YEAR = 1437796800, european date format

**Comment by vedmack** [comment]
You can use the [date_format <-- read docs](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L146) to set your date format.

Next time please use [stackoverflow for asking questions](http://stackoverflow.com/questions/tagged/yadcf)
