### ISSUE TITLE
cumulative_filtering - not giving expected results

### ISSUE THREAD

**Issue by liutaurasa** [vedmack/yadcf#238]
Hi,
I'm trying to use new feature - cumulative_filtering, which description is:
Change the default behaviour of the filters so its options will be populated from the filtered rows (remaining table data after filtering) only unlike the normal behaviour in which the options of the filters are from all the table data.
So I expect that if I have 2 filters of select type and choose an option in one filter, the other filter select options are limited to the values of column of displayed rows (data). That makes a lot of sense to me, as choosing values which are not displayed in the table will automatically make no rows displayed.
I've tried that, but doesn't seem to work.
I've added 'cumulative_filter': true to the yadcf definition, but don't see any changes in filtering behavior. On the contrary, the resetAllFilters functionality seems to be broken if I add 'cumulative_filter': true or 'cumulative_filter': false. To get resetAllFilters working again I have to remove 'cumulative_filter' from yadcf definition at all. 'ResetAllFilter was just fixed for select elements (now select elements are cleared, thanks a lot for that), but adding cumulative_filter option makes resetAllFilters not to reset filter state, but clears the select element (the oposite as it was before the fix). If I press resetAllFilters button, the filtering doesn't change, but select element is cleared. The only way to get back all the rows is to refresh page ( I have bStateSave: true), that brings select element with selected option and clear selected option. I'm using multi_select elements with select2 plugin, however with single select elements situation is not different.

Apreciate your comments
Liutauras

**Comment by vedmack** [comment]
For start make sure you used this feature as a global argument for yadcf, like in the [showcase example](http://yadcf-showcase.appspot.com/cumulative_filtering.html) (see code at the bottom). if you still have a problem please provide a link to a live sample jsbin/jsfiddle and describe the steps to reproduce and expect/actual results

**Comment by liutaurasa** [comment]
Ah, yes - my mistake, I've added cumulative_filter: true as yet another column filter definition. Sorry for bothering. Thanks a lot.
