### ISSUE TITLE
ajax populated fields + externally_triggered + server_side removing fields value

### ISSUE THREAD

**Issue by lyrad** [vedmack/yadcf#239]
Hi,
First thanks for your work. 0.9 seems to fix most of our issues with yadcf...

Ok after futher tests, here is the problem : 
When YADCF used with server side AND ajax loaded field (for select, multiselect & autocomplete), some options may be present into the filters, but not in the datatable result set.

When that happens, YADCF delete the selected option after the datatable request.

In some cases (using multiselect select2), that is just fine. In others (simple select) it is not (the user see the filter he just set disappear).

Tested :
 - Send back selected option to yadcf trougth "yadcf_data_X" => does not work (=> presence of option into the select is not the problem here).
 - Overwrite select2 select type with custom select type, to control refresh filter function => does not work (=> refreshing the filter is not responsible for this issue)

I'm still testing, but I think at the end, a filter option "do refresh with dataset?" could be useful to add to say to YADCF to not do anything with datatable data set, for this filter.

Here an exemple of ajax loaded single select2...
yadcf.init(tableWalletHistorique, [ {
        column_number: INDEX_EQUIPEMENT_LIEU_UO,
        filter_type: "select",
        select_type: "select2",
        filter_default_label: "Sélectionnez...",
        filter_container_id: "tableWalletHistorique_filtre_UO",
        select_type_options: { 
			language: "fr",
			templateResult: formatFilterBasic,
			ajax:  {
				url: "/referentiel/getequipementlieulignelist",
                                dataType: "json",
                                method: "post",
                                delay: 500,
                                processResults: function ( data ) {
                                        ...
                                }
                        }
      }
} ], { externally_triggered: true } );

    // Initialisation du boutton "Filtrer"
    $( "#tableWalletHistorique_filtre button[id=trigger]" ).button({
    	icons: { primary: "ui-icon-rafraichir" },
    	text: true
    }).click(function(event){
        // Stop la propagation de l'évènement, pour ne pas déclencher un rafraichissement de la page
        event.stopPropagation();
        event.preventDefault();
        // Lancement du filtrage
    	yadcf.exFilterExternallyTriggered( $('#tableWalletHistorique').DataTable() );
    });

Thanks!

**Comment by lyrad** [comment]
Correction : the issue occurs ONLY if no rows are return by the datatable request.

**Comment by lyrad** [comment]
Okay, I think I got it.
The fact is yadcf remove fileds options witch are not in datatable result set, after each ajax query.
That is a problem with my use of yadcf, because my fields are all externaly populated.

A solution could be to return in "yadcf_data_XX", the field value selected... except for multi select fields where this functionnality is wanted.
Fields will contain only one option, but will be ajax updtated on user click.

Sorry for opening this useless issue!

**Comment by vedmack** [comment]
Sorry, but its not clear from your issue what the real problem is, please provide step to reproduce with expected results and actual results with a minimal test case (jsbin/etc)

**Comment by lyrad** [comment]
Okay,
Before to try it on jsbin, I'll try the good old screenshot test case.
I take an externaly filtered yadcf (filter button) because the issue is more visible, but same thing happens on "automatic" filtering.

TEST CASE 1 :
1) http://www.hostingpics.net/viewer.php?id=681372811.png
Here a select is opened and ajax loaded.
Data sent back by ajax request are independant of datatable dataset (the reason is 
=> the "AME" option is and should exist in the select, but not in dataset targeted.

2) http://www.hostingpics.net/viewer.php?id=507193363.png
Here I select the "AME" option and I proceed filtering

3) http://www.hostingpics.net/viewer.php?id=750457852.png
Here is the final result. 0 items are returned with is normal since AME option is not in dataset targeted.
select filter was emptied by YADCF (because it didn't see "AME" in datatable result I guess).
So the whole filter is empty (just like there was no filtering) but the data displayed are filtered... witch isn't logical, from the user point of vue...

TEST CASE 2 (more vicious) :
In the test case 1, where had an item ID/N° => "50230175", Ligne => "L02" (first one in table).

1) http://www.hostingpics.net/viewer.php?id=281588843.png
Here I filtered on Ligne "L03", witch exclude item 50230175 from result.

2) http://www.hostingpics.net/viewer.php?id=474522353.png
Here I add an ID filter on 50230175 (witch is not in dataset since exclude by first filtering) and proceed.

3) http://www.hostingpics.net/viewer.php?id=508388433.png
Here is the result. Select filter "Ligne" has been emptied.
So if I believe the YADCF/Datatable strictly displays on this view, there is no item 50230175!
Of course I could remember I first filtered on "L03" witch could had exclude 50230175... but since the user is an idiot...
There is no reset filter buttons because of externaly filtered method. But it was automatic filtered, we would have the same result, and a click on reset button of the empty filter "Ligne" would have made appear the 50230175 item... user : Why clear an empty displayed filter change the result?!


The fact is, in some cases, this behaviour is desirable : With Multiselect select2 for exemple, I'm happy a second filtering "removes" mutiselect options with are not in resultset...
That's why I was talking about an filter configuration option to allow the developer to decide if the filter should be update or not, considering the data returned...

Hope this helped, if not I will provide a web exemple... 

Thanks!

**Comment by lyrad** [comment]
And there is more.

1) http://www.hostingpics.net/viewer.php?id=436243771.png
In green, you can see a select filter, ajax loaded with select2 (witch also provides optgroups) using a template allowing to have a different value/text for each option (<option value="1#12">Epuisement station/gare</option> => HTML equivalence for the exemple)
Here, select2 is in charge, nothing to do with YADCF business.
Filtering uses the option value (not label), on a user hidden column (displayed in green for the needs of the exemple).
Select label is displayed to the user (in red) : User feels he's filtering a label while he's filtering an id... machiavellian.

2) http://www.hostingpics.net/viewer.php?id=209658972.png
On selection, filter value/label is correct while YADCF is waiting for datatable dataset.

3) http://www.hostingpics.net/viewer.php?id=596761463.png
YADCF has replaced my label with the ID, witch is data it found in datatable result dataset.
The fact is, in this case, YADCF doesn't have data to "update" the field (has id but would need label, optgroup...).
So here again, an option to tell "Please YADCF, let me handle filter displaying througth plugin options and don't feel concerned by datatable data" may be usefull.

Note for this exemple, I didn't try to return option in "yadcf_data_X".

Thanks,

**Comment by lyrad** [comment]
As a hack, I commented lines 2256 and 2257 :
// $filter_selector.empty();
// $filter_selector.append(column_data);

I need to perform some test, but seems that it fix my issue. I guess that only "solve" something for my use of YADCF (with datatable in server side mode, and independantly ajax loaded filter)...

**Comment by lyrad** [comment]
Okay, time to conclude.
This could be concidered as an issue, or not...
I finally was able to solve the problem, that is, to use YACF with externaly ajax populated selects/multiselect.
The thing is to initialize the filter using the "data" option, giving it an array of every possible value that could be later returned by the ajax request witch will update the field.
In this way, you're sure ajax data you selected will be in the filter, when reloading the page (stateSave selection) or update the datatable.

So, a first dataset is needed for each filter (if data comme from a database, that meens a first request set). The ajax request should return only "options" witch are in the initial data array. Otherwise, issue decribed above could occur.

Great thing that 0.9 actually allows this usage of YACF, I ll try to provide an online usecase of it, before december, for posterity.

Again, thanks for work work!

**Comment by vedmack** [comment]
Hi,

I'm glad you solved that eventually, Indeed you can use the `data` property to populate the filters, but I must say that using the `yadcf_data_N#` is the yadcf way to work with server side setup of datatables.
Closing this issue
