### ISSUE TITLE
Clear a field in externaly triggered mode

### ISSUE THREAD

**Issue by lyrad** [vedmack/yadcf#240]
Me again for an other issue (an enhancement this time :)).
I noticed there are no "clear buttons" with externaly triggerred mode.
As far I understand YADCF, that is because clear button is yadcf.doFilter('clear'...) witch clear the display AND refresh/redraw the table.

Would it be possible to split "clear function" (diplaying functionality) and "refresh/redraw" function, allowing clear buttons to just... clear the filter displaying without update the table, in externaly triggered mode?

Thanks

**Comment by vedmack** [comment]
docs... showcase... :)

You should use the [yadcf.exResetAllFilters(oTable);](vedmack) function , see it in action on the [showcase](html)

**Comment by lyrad** [comment]
Sorry, I was talking about the own filtre reset button, witch are not displayed in externally filterred mode...
But yes, I can add them manually, just after each filter containers, and use exResetFilters to reset the field...

Adding manually buttons, pffffffff.
I guess I'm getting used to see YADCF doing everything for me ;)...

**Comment by vedmack** [comment]
I dindn't think that there are much sence in providing filter reset buttons when the filter is not triggered on change/keyup anyway but by using the external filter button.
Anyway you can comment out the following code in yadcf to keep the reset buttons when working with external triggered mode
```
			//no individual reset button for externally_triggered mode
			if (default_options.externally_triggered === true) {
				options_arg[i].filter_reset_button_text = false;
			}
```

**Comment by lyrad** [comment]
The problem is, since server is not providing a defaut option "please select..." (maybe it should, maybe not), the user can't cancel a select filter after he first selected something.
Also, I don't want yadcf to redraw the table, but just clear the field to his defaut value.

So, I was able to add my own button, and use the exResetAllFilters function to clear the filter.

To anyone having the same issue, exResetAllFilters has a 'noRedraw' parameter.
Exemple : yadcf.exResetAllFilters( tableWallet, true, [ parseInt( numcol ) ] );
=> will clear the filter without any table redrawing.
