### ISSUE TITLE
On refresh, the dropdown value goes back to default

### ISSUE THREAD

**Issue by Emwat** [vedmack/yadcf#241]
The table is loading the right values and getting properly updated via JSON from the server.

So you click a value on the dropdown filter, it loads properly.
You refresh the page.
The page keeps its data and its filter values, but the filter points back to the default 'select value'.  Pressing 'x' doesn't do anything, but functionality of the dropdown still works.

**Comment by vedmack** [comment]
Show me your datatables/yadcf config and point a link to reproduce the issue
