### ISSUE TITLE
Suppressing non-critical prompts from YADCF

### ISSUE THREAD

**Issue by jhyland87** [vedmack/yadcf#242]
I when I use the HTML5 data-* attributes for DataTables, but if I don't set the html5_data to true for YADCF, it alerts an error.

The problem is I don't really want YADCF to prompt, I mean a console.error is fine if it needs to, but prompting is a bad idea.. Is there a way to disable this without modifying the code in jquery.dataTables.yadcf.js? I mean I know I could edit that, but I try not to edit the 3rd party files for anything, to make updates easier..

I would think that if it alerts errors, there would be an option to suppress errors to display in the console only.

I would also think that instead of alerting the error, it would just do what DataTables does, and see that it has the html5 attributes, so just automatically search them as well

**Comment by vedmack** [comment]
fixed in [0.8.9.beta.26](https://github.com/vedmack/yadcf/blob/17b1c290a0fb78e767db44bd0440a4189fc8b9d1/jquery.dataTables.yadcf.js)
