### ISSUE TITLE
How to enable auto_complete as a filter for AJAX source 

### ISSUE THREAD

**Issue by rysss12** [vedmack/yadcf#243]
Nick,

I am trying to implement an auto_complete filter from an ajax source. I am using the newest version of yadcf and DataTables so I am having difficulty getting your past answers to work. Specifically, do I need to include enable_auto_complete anywhere?

I tried changing the filter_type from "text" to "auto_complete" but that didn't work. 
What else do I have to edit to enable auto_complete from an ajax source?

I can provide a js fiddle to show my syntax/files. Thanks for the continued help. 

Edit, Also, do I need to include a text_data_delimiter?

**Comment by vedmack** [comment]
You mean that you want to set a the source attribute of the auto complete plugin? Like in the following examples? [N#1](https://jqueryui.com/autocomplete/#remote) / [N#2](https://jqueryui.com/autocomplete/#remote-jsonp) ?

You know that you can populate your autocmplete filter by using the [data](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L48) of yadcf and if not it will get populated automatically by yadcf.

Please describe your scenario.

**Comment by rysss12** [comment]
I have a dataTable with yadcf filters. Tables are being drawn to an html page from mysql tables via an AJAX file. I want to have the auto-complete filter use the same data that the column has. Is there a simple edit if the auto-complete has the same values as the column if its filtering? 

Thanks for the explanation.

**Comment by vedmack** [comment]
It should work automatically,  please post your datatables and yadcf setup

**Comment by rysss12** [comment]
Those files are thousands of lines long, which sections are you interested in? Alternatively, i have posted a link to my source code if you don't mind looking at that. Your help is always appreciated. 

https://www.dropbox.com/sh/sl099mnccavco5i/AABko2JrED4xogtPFds153-Ya?dl=0

**Comment by vedmack** [comment]
In server side mode you must return additional data in your json for each yadcf column, that attribute should be called `yadcf_data_0` / `yadcf_data_1` / etc... look at the [showcase page - server side setup - read all the comments on that page](http://yadcf-showcase.appspot.com/server_side_source.html) you can see all the relevant stuff (server response) in developer tools of chrome in the network tab.

**Comment by rysss12** [comment]
The autocomplete filter on the link you provided for the server set up does not work.

**Comment by vedmack** [comment]
You are right , I messed it up in *0.8.9.beta.23* , will fix it in the following days, untill then you cna use *0.8.9.beta.22*
