### ISSUE TITLE
Exclude specific item from select dropdown

### ISSUE THREAD

**Issue by jshah4517** [vedmack/yadcf#244]
Is there a way to exclude a specific item from the select dropdown that is generated? My column is comma delimited HTML (e.g. [HTML LINK], [HTML LINK], [HTML LINK]). The text_data_delimiter option works well if the column data type is text, but I can't use it with HTML data, hence it is adding ", " as an option in the dropdown which I'd like to remove.

Thanks!

**Comment by vedmack** [comment]
please provide a minimal jsbin sample with your issue...

**Comment by jshah4517** [comment]
This was a quickly set up example.
http://jsbin.com/kusatavora/edit?html,output

If you check the dropdown it has the comma as an option, it would be nice to remove that.

**Comment by vedmack** [comment]
Your best bet it to change 
```
<td><a href="tag/2/edit">1</a>, <a href="tag/3/edit">one more</a>, <a href="tag/1/edit">Test</a></td>
```

into 

```
<td><span><a href="tag/2/edit">1</a></span>, <span><a href="tag/3/edit">one more</a></span>, <span><a href="tag/1/edit">Test</a></span></td>
```

wrap each `<a>` with `<span>`

and modify your yadcf init like this:

```
oTable.yadcf([
            {
                column_number : 0, 
                column_data_type: "html",
                html_data_type: "selector",
                html_data_selector: "a",
                filter_container_id: "filter_tag"
            }
        ]);
```

[See working sample](http://jsbin.com/gonihoziyo/edit?html,output)

read about [html_data_selector](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L85)

p.s future questions should be asked on [SO](http://stackoverflow.com/questions/tagged/yadcf)
