### ISSUE TITLE
Problem with ColReorder, Date Range, Server Side

### ISSUE THREAD

**Issue by dotpmrcunha** [vedmack/yadcf#246]
Hi, I have recently found a bug, when using your plugin in a server side table with ColReorder and a date range filter. 

For example:  table with [1, 2, 3, 4], the 4th is the date range. 
1) When initialized and then filter the date everything works fine.
2) Then I change to [1, 2, 4, 3] and try to filter again, this time the table filters the column 3 with date range filter.
3) Last I change back to [1, 2, 3, 4], everything seems to be messed up and the table tries to filter column 3 and 4 with the date range.

Meanwhile, I have forked your script and fixed for our needs, but you could check if there is more of that type. (https://github.com/dotpmrcunha/yadcf)

**Comment by vedmack** [comment]
I looked at the line of code that you modified and did the same in yadcf way let me know if there are more places that need a fix , grab [0.8.9.beta.22](https://github.com/vedmack/yadcf/blob/56034cd73aa95115e313cde7e4528c21387839b5/jquery.dataTables.yadcf.js)
