### ISSUE TITLE
Column Filtering

### ISSUE THREAD

**Issue by edimusxero** [vedmack/yadcf#247]
This is more of a question than a issue per say, but the issue I am running into has to do with column filtering.  Here is the scenario, I have a column with the 2 given choices. "Found" and "Not Found".  If I apply this to the column, 

`{column_number: 2, data: ['Found', 'Not Found'], filter_default_label: "Found/Not Found"},`

The sort is created as expected, however if I chose the option for "Found" it shows all the matches for "Not Found" as well.  I am assuming this is because the word "Found" is also present in "Not Found".  Is there a way around this?

**Comment by vedmack** [comment]
Hi,

Use `filter_match_mode: 'exact'` for that column , and read more about it in [the docs](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L160)

Please next time ask question on [stackoverflow (tag with yadcf)](http://stackoverflow.com/questions/tagged/yadcf)

**Comment by edimusxero** [comment]
Ok thank you. I couldn't find it in the docs,  guess I over looked it
