### ISSUE TITLE
serverside select2 value=>display

### ISSUE THREAD

**Issue by Jrizzi1** [vedmack/yadcf#248]
Maybe i missed something in the documentation, but is there a way to , rather than pass an array of values for a select2 (or any select) dropdown, to pass a value=>display key value array set that could make an option like

<option val="ON">Ontario</option>

**Comment by vedmack** [comment]
You can use the data attribute for that, see the  Yes/No column at the [showcase sample](http://yadcf-showcase.appspot.com/multiple_tables.html) (first table -> third column)

data attribute value looks like this

```
data: [{
            value: 'Yes',
            label: 'Yessss :)'
        }, {
            value: 'No',
            label: 'Noooo :('
        }],
```
