### ISSUE TITLE
Date Range Filter ServerSide

### ISSUE THREAD

**Issue by vkhattar** [vedmack/yadcf#249]
I am using a your plugin to support filtering in my DataTable, everything is working fine besides the date range filter. When I select the dates from the dropdown, first of all on selection the dropdown does not close ( That is a minor problem and I am not too concerned about that) but when I click outside to close the datepicker it does not fire an api request. Interestingly when I clear the filter, it fires the api request with  columns[5][search][value]:-yadcf_delim- which will of course be empty. 

Here is my date range filter: 
 {
        column_number: 5,
        filter_type: "range_date",
        date_format:  'mm/dd/yyyy',  // I tried several different formats. 
        filter_delay: "500"
 }
FYI: I am using Version:     0.8.9.beta.22 currently
Can you please provide a fix as I will have to change the entire logic of my code if the date range filtering does not work. Thanks.

**Comment by vedmack** [comment]
It should work just fine, see showcase as reference, I even set it to use the same date_format as yours... to figure out whats wrong you can try and use the same version of jquery ui datepicker as I use on showcase (grab from the showcase itself) you can provide  a link to you web app and I can take a look.

**Comment by Orca11** [comment]
I am currently using the 0.8.9.beta.21  and DateRange is working fine, except for min/max date selection after filter reset. The min/max date range of from date is kept as long as I dont click in the to date again.. I dont know yet whether it is a little yadcf bug or something else in my sourcecode and usage of it... at the moment I havent any time to investigate it .. I am taking care later of it... some weeks maybe....

I am using the standard jquery ui datepicker styled via template...

**Comment by vedmack** [comment]
Closing this issue because there is no test case to work with and it works for me/others.
@Orca11 if you have a test case/sample with your issue you can open a new issue with detailed scenario.
