### ISSUE TITLE
No load event. Can't add listeners

### ISSUE THREAD

**Issue by perich** [vedmack/yadcf#251]
I want to add listeners to certain columns/inputs. There is no 'loaded' event. jQuery page load event is too soon so the events have nothing to bind to.

something like this 

in init

    style_class: 'expand_on_focus'

listener:

```
 function expand_on_focus () {
  $('.expand_on_focus').on('focus', function () {
    console.log("focus");
  }).on('blur', function () {
    console.log('blur');
  })
}

// This doesn't work
$(document).ready(function() {
  expand_on_focus()
});
```

**Comment by vedmack** [comment]
yadcf is listening to the [datatables draw event](https://datatables.net/reference/event/draw) , so you could really listen to it too, or you can try the [init event too](https://datatables.net/reference/event/init) , let me know if there is still an issue related to the yadcf
