### ISSUE TITLE
Buttons, colVis, and range_number filters

### ISSUE THREAD

**Issue by nilsey** [vedmack/yadcf#252]
http://jsfiddle.net/nilsey/r8x7Lpu6/2

When one uses the Buttons datatables.net extension and yadcf, the colvis button and the range_number filters do not play well together. When the number column is hidden (last col in my  example) the other filters no longer work.

Does anyone know if this has been addressed?

**Comment by vedmack** [comment]
fixed in [0.8.9.beta.28](https://github.com/vedmack/yadcf/blob/26c51a6cb08e7657d2a86430276596f4e7b1da1a/jquery.dataTables.yadcf.js)
