### ISSUE TITLE
trigger column search onClick instead of keyUp

### ISSUE THREAD

**Issue by GMEHTA1981** [vedmack/yadcf#253]
Hello Daniel,

My requirement is to have the "search control" inside the "individual columns", but I would like to trigger them together on single external button click.
I have read about the external Filters, However when I implement it.. it needs the search controls outside the column. Errors out at mData.

I created a button
<asp:button id="btnExFilter" runat="server" CssClass="yadcf_ExtFilter" Text="Search"></asp:button>

Code is
        $(".yadcf_ExtFilter").click(function () {
            yadcf.exFilterExternallyTriggered(oTable);
        });

But it does not filter. It clears of the column filter data.

Please help.
Regards

**Comment by vedmack** [comment]
Please provide a jsbin with your issue, It impossible to tell what went wrong in your code, see [externally_triggered: true showcase page](http://yadcf-showcase.appspot.com/dom_source_externally_triggered.html) , and notice that the `externally_triggered: true` is defined per table and not per column

**Comment by GMEHTA1981** [comment]
I think this function exFilterExternallyTriggered expects the filters to be outside / external to the datagrid.

What I am looking for it Filters be a part of the columns grid. But, I want them to be trigger onClick of an external button (just like reset button). I do not want individual columns filters to trigger on keypress.

**Comment by vedmack** [comment]
Its doesn't matter where the filters are... make a simple jsbin and if it wont work let me know

**Comment by GMEHTA1981** [comment]
http://jsbin.com/qozaqahaqe/edit?html,js,console,output

**Comment by GMEHTA1981** [comment]
Here is a the setup on jsbin side.. please can you help me out

**Comment by vedmack** [comment]
The problem is that you asked to place a filter on `column_number: 5` while there is no such column, remove that from your yadcf init and all will work just fine, see [working jsbin ( added reset button too)](http://jsbin.com/qozaqahaqe/edit?html,js,console,output)
