### ISSUE TITLE
input type text width

### ISSUE THREAD

**Issue by carlinchisart** [vedmack/yadcf#254]
Hi all,

i have one question, is posible or change the width of input type text in the head? i have one column that the filter is input text but the width of that colum change when create a filter, so is posible work like a select filter? chosen for example is adjust to the width of the column.

Thanks,

**Comment by vedmack** [comment]
Hi,

Every yadcf filter / its wrapper have a class / id so you can set any style / width / etc to the filters, this is the only way possible to control the size of the filters.
