### ISSUE TITLE
How can i sort date column?

### ISSUE THREAD

**Issue by mrcherie** [vedmack/yadcf#256]
Hello,
I have some dates in my table like 22.11.2015, 22.12.2015, 22.01.2016 etc.
I can not sort my table by date.

Please help me.
Thanks

**Comment by vedmack** [comment]
Hi,

Thiis is a yadcf github repository and not datatables :)

You should ask your question on [datatables forum](https://datatables.net/forums/) or [stackoverflow](http://stackoverflow.com/questions/tagged/datatables) 

But before that you betetr google it [ - sort date column datatables](https://www.google.co.il/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=sort%20date%20column%20datatables)

**Comment by mrcherie** [comment]
I am using yadcf data table. Also i am wrong place for my problem?

**Comment by vedmack** [comment]
yadcf is responsible of filtering your table, you are asking me how to sort the table, the sorting of the table is being done by datatable.

if you have any yadcf filtering related question feel free to ask on [stackoverflow and tag it with yadcf](http://stackoverflow.com/questions/tagged/yadcf) . Please open an issue on github only to reort a bug or ask for a new feature.

**Comment by mrcherie** [comment]
aha. okay. thank you

**Comment by mrcherie** [comment]
i didn't find any way to sorting by date.
i am searching about 3 days but i didn't find more document about yadcf datatables.

can you help me?

**Comment by louking** [comment]
A search of "datatables sort date" yielded
https://www.datatables.net/plug-ins/sorting/

Is this not helpful?

But really this should be on datatables forum
https://www.datatables.net/forums/

**Comment by mrcherie** [comment]
**louking** thank you very much. i got it
