### ISSUE TITLE
with select2 4.0 when remove filter and use exact mode, no result

### ISSUE THREAD

**Issue by carra** [vedmack/yadcf#258]
Hi,
I use your fantastic plugin but, when I use  filter_match_mode "exact" and select2 (the 4.0 version)
and I remove the filter (with "x" of select 2 or button of yadcf plugin) the table is empty.

I modify the yadcfMatchFilter function and add the "selected_Vaue=="" "
<pre>
if (filter_match_mode === "contains"  || selected_value=="") {
				oTable.fnFilter(selected_value, column_number, false, true, true, case_insensitive);
			} else if (filter_match_mode === "exact") {
				selected_value = escapeRegExp(selected_value);				
				oTable.fnFilter("^" + selected_value + "$", column_number, true, false, true, case_insensitive);
</pre>
Because when it searchs "^$" the result is empty.
I don't know if my fix it's correct, but it works.

**Comment by vedmack** [comment]
please provide a jsbin that shows this issue, because I could reproduce it using select2 v4
