### ISSUE TITLE
exFilterColumn and exFilterExternallyTriggered working together

### ISSUE THREAD

**Issue by GMEHTA1981** [vedmack/yadcf#259]
Hello Daniel,

Project requires to have individual column filters within the grid firing thru single search button.
I use 'exFilterExternallyTriggered' works gr8 !

Now, the project needs certain asp.net control filters on top of the grid, for filtering records.

My code reads as 
 $(".yadcf_ExtFilter").click(function (e) {
            e.preventDefault();
            yadcf.exFilterExternallyTriggered(oTable);
});

This works perfectly.. it calls the webservice without reloading the webpage. Awesome !
But how do I implement exFilterColumn along with this.

I need onClick of 'Apply Filter' button it should take values of external filter controls and column filters
Please help.
I would highly recommend more details / clarity in documentation process. 

Thank You.

**Comment by vedmack** [comment]
Please explain how does `exFilterColumn` fit into your page? I mean, you are using the `exFilterExternallyTriggered` , a screenshot of your page might help, a jsbin is even better

**Comment by GMEHTA1981** [comment]
The filters under red marking are all asp.net filters
![image](https://cloud.githubusercontent.com/assets/5384690/11538583/93ca739a-98f0-11e5-8019-c20494761e19.png)

I need to attached them to the search button. So, customer can filter on column filters and external filters using one single button.

**Comment by GMEHTA1981** [comment]
Issue is updated.

**Comment by vedmack** [comment]
The only thing that I can suggest for your to do is to manually construct and trigger the `exFilterColumn` function upon user click on your search button, the `exFilterColumn` can trigger the filtering as if it was coming from the column filter that are used in your table. so upon clicking on the search button grab the values that were used in in your external filters and feed them into the `exFilterColumn` function.

As to your issue title , there is no problem at all to use the `exFilterColumn` along with the `externally_triggered: true` mode, you can try calling `yadcf.exFilterColumn(oTable, [[3, 'a_value']])` in the [showcase](http://yadcf-showcase.appspot.com/dom_source_externally_triggered.html) (from dev tools console and see that it works.
