### ISSUE TITLE
Error with autocomplete filter box

### ISSUE THREAD

**Issue by mrcherie** [vedmack/yadcf#260]
Hello,
I'm using yadcf datatable.
I have a autocomplete filter box. And this column have some links with html tags. When i try to write something on this box column content is come and html tags also shown.
Is this a bug?
Thanks

![autocoplete error](https://cloud.githubusercontent.com/assets/15889585/11443394/7ec510aa-9525-11e5-8ff2-41a873490dd1.png)

**Comment by vedmack** [comment]
Hi,

Thats not a bug, you should use the [html_data_selector](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L85) and also set the `column_data_type: "html"` , see similar [more complicated jsbin](http://jsbin.com/jokepehafe/edit?js,output). Play with the selector to see what fits you the most, I think it should be `html_data_selector: 'span'` , in case of trouble post a minimal jsbin smaple

**Comment by mrcherie** [comment]
I will try. Thank you. 

iPhone'umdan gönderildi

27 Kas 2015 tarihinde 17:22 saatinde, Daniel Reznick <notifications@github.com> şunları yazdı:
