### ISSUE TITLE
Exclude filter bug -- If exclude filter is selected for column1, it automatically performance exclude filter for other columns.

### ISSUE THREAD

**Issue by GMEHTA1981** [vedmack/yadcf#264]
This is a screenshot of the grid.
Steps:
1) I search a column with value 'JAX' -- works fine. It will filter records with JAX 
![346a9638-98ef-11e5-9ab8-751a2e09d9ba](https://cloud.githubusercontent.com/assets/5384690/11590581/43ac348c-9a5f-11e5-954d-d3fb1f5bef6e.png)

2) I add a search criteria, in another column.  Origin column search 'DTW' -- works fine. It will filter records with DTW (in origin) and JAX (in Station)
![image](https://cloud.githubusercontent.com/assets/5384690/11538370/c42477e4-98ef-11e5-871c-4cdd94aba00f.png)

3) Now I want to exclude records. 
I want to exlude all records with station 'JAX' and include records with origin 'DTW'
![image](https://cloud.githubusercontent.com/assets/5384690/11538402/f390a430-98ef-11e5-871a-3da2109cfdb3.png)

If you see the results in screenshot 3, it excluded all station with 'JAX' and also performed the exclude function to other criteria. 
So, now I have result that excludes 'JAX' in station and excludes 'DTW' in Origin column
![image](https://cloud.githubusercontent.com/assets/5384690/11538466/31d399be-98f0-11e5-9534-a1057543acc7.png)

**Comment by vedmack** [comment]
first image is broken - please edit your question with a proper link (edit it - no need to post more comments)

**Comment by GMEHTA1981** [comment]
Daniel.. first image is uploaded. Please provide a fix for this issue.. its causing business issue

**Comment by vedmack** [comment]
as usual im lack of free time... will take a look at it whenver I can, untill then, consider sending a PR with a fix, its an open source code you can allways modify / improve/ fix... nothing too complicated there...

**Comment by vedmack** [comment]
@GMEHTA1981 , can it be that you are using serverSide logic in your datatables, and that logic had some bugs in it? because it works just fine for me, see the [following example](https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/DOM_Ajax_Multiple_1.10.html).
Update me with your conclusions.

**Comment by GMEHTA1981** [comment]
I found the bug.
Inside the function exFilterColumn
inside case "date":
 if (filter_value !== undefined && filter_value.indexOf('_exclude_') !== -1) {
                            exclude = true;
                            filter_value = filter_value.replace('_exclude_', '');
                        }
                        else { exclude = false; } //NEEDED ELSE CONDITION.

**Comment by vedmack** [comment]
Thanks for pointing out to the bug, fixed it by setting it to false inside thte begining of the loop
Fixed in [0.8.9.beta.27](https://github.com/vedmack/yadcf/blob/74563ea75711c0b1654ac29ab89b5afa491b56dd/jquery.dataTables.yadcf.js) grab it and see how it works for you.
