### ISSUE TITLE
All Rows Hidden When multi_select_custom_func Cleared/Empty

### ISSUE THREAD

**Issue by ereilly** [vedmack/yadcf#266]
Hi Daniel,

[Here is a JS Fiddle example using the `multi_select_custom_func` filter .](http://jsfiddle.net/user1508773/wkwhmcb1/)

Issue: Click `Clear`.  Result : All rows are hidden (all rows should be displayed!)

Error at [Line 3862 of jquery.dataTables.yadcf.js](http://yadcf-showcase.appspot.com/resources/js/jquery.dataTables.yadcf.js): ```exGetColumnFilterVal error: no such filter_type: multi_select_custom_func```

Fix error but not overall issue by adding the following to the `switch` statement in `exGetColumnFilterVal()` (around line 3818):

```case multi_select_custom_func':```
```retVal = $('#yadcf-filter-' + table_selector_jq_friendly + '-' + column_number).val(); ```
```console.log("retVal: "+retVal);```
```if (retVal === null) { retVal = ''; } break;```

Either I'm giving `retVal` the wrong value or maybe this has something to do with a function like `exResetFilters()` or `clearStateSave`. Any ideas?

Thanks so much.

**Comment by vedmack** [comment]
Hi,

The solution lies in your code, inside your custom search function you must consider gettin `null` as `filterVal`, null will arrive whenever you hit the clear or erase the select input and in that case you should return true.

```
function myCustomFilterFunction(filterVal, columnVal) {
	if (filterVal === null) {
  	    return true;
    }
    .
    .
    .
```

[see working jsfiddle](http://jsfiddle.net/wkwhmcb1/137/)

**Comment by ereilly** [comment]
Brilliant!  Thanks!
