### ISSUE TITLE
Range Filter with Datatable Reorder

### ISSUE THREAD

**Issue by etlouie** [vedmack/yadcf#267]
Hi,

I've read "Adding support for ColReorder to remaining filter_types #138" but for me it doesn't work with any range filters. I am using version 0.8.9.beta.26. The Select and Text filters work without any issues only the ranges ones don't. It basically continues to put the filter information in the original  mDataProp, and bSearch parameters instead of the reorder parameters.

Also, using DataTable 1.10.10, jQuery v2.1.3, jQuery UI v1.11.4 and Bootstrap Bootstrap v3.3.4.

Let me know, if you need anything else. 

Edward

**Comment by etlouie** [comment]
Incase you didn't know, all filtering is server side.

**Comment by etlouie** [comment]
Hi,
I did some debugging of your code and discovered that you are not using the ColReorder. Don't know if the following is even correct, but it did allow the RangeNumberSlide to use the reorder parameters

function rangeNumberSliderChange(table_selector_jq_friendly, event, ui) {
          event = eventTargetFixUp(event);
          var oTable,
                 min_val,
                 max_val,
                 slider_inuse,
                 yadcfState,
                 column_number = $(event.target).attr('id').replace("yadcf-filter-", "").replace(table_selector_jq_friendly, "").replace("-slider-", ""),
                 columnObj,
                 keyUp;


        oTable = oTables[table_selector_jq_friendly];
// These three line below allow the to use the ColReorder #, instead of the original column_number
var settingsDt = getSettingsObjFromTable(oTable);
initColReorder2(settingsDt, table_selector_jq_friendly)
column_number = plugins[table_selector_jq_friendly].ColReorder[column_number];
        columnObj = getOptions(oTable.selector)[column_number];

        keyUp = function () {

                        $.fn.dataTableExt.iApiIndex = oTablesIndex[table_selector_jq_friendly];

**Comment by etlouie** [comment]
Correction, the code should be
var settingsDt = getSettingsObjFromTable(oTable);
initColReorder2(settingsDt, table_selector_jq_friendly)
if (plugins[table_selector_jq_friendly] !== undefined && (plugins[table_selector_jq_friendly] !== undefined && plugins[table_selector_jq_friendly].ColReorder !== undefined)) {
        column_number = plugins[table_selector_jq_friendly].ColReorder[column_number];
}
So that is ColReorder is not used, the range slider will still work

**Comment by vedmack** [comment]
Please provide a link to a jsbin/jsfiddle with the issue, otherwise I wont be able to reproduce/debug it

**Comment by etlouie** [comment]
I'll try and get this one in the next few days

**Comment by etlouie** [comment]
I started to strip out everything from my JSP file, but I've looked at jsbin/jsfiddle and don't know how to provide the information you need, since it requires server side access and a database connection. If I hardcode the data into the HTML, there is no issues. Any suggestions?

**Comment by vedmack** [comment]
create a jsbin with range filters with reorder ability and that it, something simple (2 rows are enough)
the simplier the better...

**Comment by etlouie** [comment]
If I create a simple HTML file with a few rows with reorder ability and a range filter, there is no issue. The issue only happens when we do a server side call because the parameter information is not stored in the correct mDataProp, and bSearch variables. 

If you look at the "hack" fix above to function rangeNumberSliderChange(), I hope you can see that the original "Column Orders" are used instead of the "Reordered Columns".

Thanks,
Edward

**Comment by vedmack** [comment]
will try to take a look at it this week...

**Comment by vedmack** [comment]
Without a link to a working test case I wont be able to help.
