### ISSUE TITLE
Date range filter not working

### ISSUE THREAD

**Issue by tshafer** [vedmack/yadcf#268]
Example of my use attached. It just wont filter.
http://jsfiddle.net/grLzcgbn/

**Comment by vedmack** [comment]
Just remove the `searching:!1,` and it will work see [sample](http://jsfiddle.net/grLzcgbn/1/) and read the following [stackoverflow question/answer](http://stackoverflow.com/a/34107178/617373) and the commets (follow the links for more gems)

**Comment by tshafer** [comment]
Perfect. Thanks!
