### ISSUE TITLE
div for yadcf-filter-wrapper-<userfilterid> does not provide class to add stying

### ISSUE THREAD

**Issue by louking** [vedmack/yadcf#269]
Somewhere between release 0.6.9 and 0.8.8, an extra div was added wrapping external filters. In 0.6.9 the outer div was of class `.yadcf-filter-wrapper` which is display: inline-block. There is now an outer div with id `#yadcf-filter-wrapper-<userfilterid>` that has no classes, which as a div defaults to display: block.

Because of this I believe the user has no way to display a series of filters on the same line, and no generic way to style the series of filters.

See http://stackoverflow.com/questions/34211731/format-change-when-upgade-from-yadcf-0-6-9-to-0-8-8 for running example.

I suggest adding some class to the outer wrapper. Not sure if it's appropriate for yadcf to style that class, or if that should be left to the user. Below you see the div  with id `yadcf-filter-wrapper-_rrwebapp_filtergender` has no classes assigned.

```
   <span id="_rrwebapp_filtergender">
      <div id="yadcf-filter-wrapper-_rrwebapp_filtergender">
         <div id="yadcf-filter-wrapper--_rrwebapp-table-standings-3" class="yadcf-filter-wrapper">
            <select id="yadcf-filter--_rrwebapp-table-standings-3" class="yadcf-filter" onchange="yadcf.doFilter(this, '-_rrwebapp-table-standings', 3, 'contains');" onmousedown="yadcf.stopPropagation(event);" onclick="yadcf.stopPropagation(event);"><option value="-1">Select value</option><option value="F">F</option><option value="M">M</option></select>
            <button type="button" id="yadcf-filter--_rrwebapp-table-standings-3-reset" onmousedown="yadcf.stopPropagation(event);" onclick="yadcf.stopPropagation(event);yadcf.doFilter('clear', '-_rrwebapp-table-standings', 3); return false;" class="yadcf-filter-reset-button">all</button>
         </div>
      </div>
   </span>
```

**Comment by louking** [comment]
I verified the need for this class on this div by putting

`#yadcf-filter-wrapper-_rrwebapp_filtergender { display: inline-block;}`

into my style.css file.

**Comment by louking** [comment]
I was able to work around this by adding a class to my filter span

```
   <span id="_rrwebapp_filtergender" class="_rrwebapp-filter">
      <div id="yadcf-filter-wrapper-_rrwebapp_filtergender">
         <div id="yadcf-filter-wrapper--_rrwebapp-table-standings-3" class="yadcf-filter-wrapper">
            <select id="yadcf-filter--_rrwebapp-table-standings-3" class="yadcf-filter" onchange="yadcf.doFilter(this, '-_rrwebapp-table-standings', 3, 'contains');" onmousedown="yadcf.stopPropagation(event);" onclick="yadcf.stopPropagation(event);"><option value="-1">Select value</option><option value="F">F</option><option value="M">M</option></select>
            <button type="button" id="yadcf-filter--_rrwebapp-table-standings-3-reset" onmousedown="yadcf.stopPropagation(event);" onclick="yadcf.stopPropagation(event);yadcf.doFilter('clear', '-_rrwebapp-table-standings', 3); return false;" class="yadcf-filter-reset-button">all</button>
         </div>
      </div>
   </span>
```

and  stying with

```
._rrwebapp-filter div {
  display: inline-block;
}
```

Still I think a class for the yadcf  `<div>` is appropriate, but up to you whether to implement that or just close this.

**Comment by vedmack** [comment]
Hi,

The since its your external container that you placing the yadcf filters at, the proper solution should be for you to set your containers with a `display: inline-block;` css rule and thats it.

You can add a class to your `_rrwebapp_filtergender` and `_rrwebapp_filterdivision` and set a rule for that class `display: inline-block;`

**Comment by louking** [comment]
Thanks, that worked -- I hadn't considered this. Sorry for the noise.

**Comment by BafS** [comment]
Hi,

This work if you don't use a framework. `style_class` is not possible for the button, is it possible to add an other field to use a custom class for the buttons ?

Thanks

**Comment by vedmack** [comment]
@BafS , read docs about [style_class](https://github.com/vedmack/yadcf/blob/70e5b09d51b9fc187b6e4ec8c148f7e12ad1266c/jquery.dataTables.yadcf.js#L253) , if you got a question please use stackoverflow (tag with yadcf)

**Comment by BafS** [comment]
It works well for the select but not the button, I think it's a bug.

Here a screenshot, the class is applied on the "select" only :

![image](https://cloud.githubusercontent.com/assets/588205/17273869/9808321e-56c6-11e6-9632-20771bca0015.png)

**Comment by vedmack** [comment]
@BafS , yadcf should give you enough tools to do what you want, in current case you can do [something like the following](http://jsbin.com/mucanusaqe/edit?html,css,output) to style your button

`.my_filter, .my_filter + input {
  background-color: lime;
}`

And its not a bug, its by design.

p.s all reset buttons got the same class that you can style as you want in your own css files...

**Comment by BafS** [comment]
Thank you for the information but then why `style_class` exists for the select and not the button ?
It's easy to customize yes, but if I want to use a framework (like bootstrap) I need to add a class to the select and also the button (of course, I can copy past the bootstrap code to `.my_filter, .my_filter + input` but that's not elegant).

**Comment by vedmack** [comment]
Then you should open a new issue for this possibility, or even better, send a PR (because it will take me a while to do it myself)  just take a look at the code on how I add the `style_class` to the filters and apply the same logic for the buttons

**Comment by BafS** [comment]
Yes, I will see if I can do that. Thanks.
