### ISSUE TITLE
Setting language url on datatables breaks functionality

### ISSUE THREAD

**Issue by jmoransalama** [vedmack/yadcf#270]
Whenever I try to translate the datatables strings using a json file the filters of yadcf are disabled.

When I load the page the filters show up, but when the page finishes loading they dissapear.

DataTables version: 1.10.10
yadcf version: 0.8.8

Current code (doesn't work):
```
$('#stock_table').dataTable( {
            "paginate": false,
            "dom": '<"#category">lfrt',
            "language": {
            	"url": "/includes/datatables/Spanish.json"
        	},
			"columnDefs": [
				{
					"targets": [ 1, 2, 3, 4 ],
					"searchable": false,
					"orderable": false,
					"className": "centrado"
				}
			]
        }).yadcf([
			{
				column_number: 0,
				filter_type: "auto_complete"
			},
			{
				column_number: 1,
				column_data_type: "html",
				html_data_type: "text",
				filter_default_label: "Seleccionar categoría"
			}
		]);
```

But deleting the language option on datatables makes it work:
```
$('#stock_table').dataTable( {
            "paginate": false,
            "dom": '<"#category">lfrt',
			"columnDefs": [
				{
					"targets": [ 1, 2, 3, 4 ],
					"searchable": false,
					"orderable": false,
					"className": "centrado"
				}
			]
        }).yadcf([
			{
				column_number: 0,
				filter_type: "auto_complete"
			},
			{
				column_number: 1,
				column_data_type: "html",
				html_data_type: "text",
				filter_default_label: "Seleccionar categoría"
			}
		]);
```

Sorry for my english.
Greetings from Spain!

**Comment by vedmack** [comment]
Please provide a link to a jsbin/jsfiddle with the language issue, otherwise I wont be able to reproduce/debug it

**Comment by jmoransalama** [comment]
https://jsfiddle.net/3fut3xhp/embedded/result/

**Comment by vedmack** [comment]
grab the [0.8.9.beta.29](https://github.com/vedmack/yadcf/blob/de66d422825d511e9f6a1fb18747f034d3e7fdd5/jquery.dataTables.yadcf.js) 
see [working sample](https://jsfiddle.net/3fut3xhp/2/)

as to the autocomplete filter you must include jquery ui autocomplete js/css in order for it to work
