### ISSUE TITLE
[NFR] Allow suppression of user-defined key codes to prevent filtering events 

### ISSUE THREAD

**Issue by temuri416** [vedmack/yadcf#272]
Hi,

I am looking at this YADCF example:

http://yadcf-showcase.appspot.com/server_side_source.html

1. Position cursor inside "Browser" column filter field
2. Press LEFT ARROW key

In Firebug you will notice an outgoing request to pull the data.

**Question**
How can I prevent submission of search context if arrow keys are pressed?

**Feature Request**
Give the implementer ability to define key codes that would not trigger search submission.

My StackOverflow question is here:

http://stackoverflow.com/questions/34440488/datatables-yadcf-do-not-search-on-arrow-key-presses

Thanks!

**Comment by vedmack** [comment]
Hi,

You can grab the [0.8.9.beta.33](https://github.com/vedmack/yadcf/blob/9ea72417dc805efa4ca667335c68c98839462f3f/jquery.dataTables.yadcf.js) in this version the text and auto complete filtes will ignore the arrow keys, if someone want more key to be igore he can send a PR with modified `keyCodes`

**Comment by temuri416** [comment]
Thanks, that worked!
