### ISSUE TITLE
Range Number Filter

### ISSUE THREAD

**Issue by JohnHanks** [vedmack/yadcf#273]
I have a sparse table.  The first 6 columns are static in my table.  Every instance of this table will have those first 6 columns and every row has data for those columns.  Those work fine.

The 7th to the Nth columns are sparse.  Not all rows in the table have data for every one of these columns.  Let's say I have a column called "Options".  In this column, some rows are blank (no value), some rows have numbers ranging 1 through 10.

Now, if I want to filter using the filter_type: "range_number", if I type 4 and 6 in the from and to fields, respectively, I see the filter effect occur.  What I am left with however are rows with cells containing 4 OR 5 OR 6 OR no value!  The last part there is my issue.  Why is a "blank value/blank cell" not getting filtered out?

Please advise.

If I need to provide a jfiddle or whatever link me your preferred place where I should make one

**Comment by vedmack** [comment]
This is the default behaviour of yadcf (not to filter out empty cells), I'll see what can be done.

**Comment by JohnHanks** [comment]
ahhh i see.  this enhancement would probably be nice as a boolean option one can set when init'ing the yadcf plugin.  whatever happens, i already am in love with this plugin.  you're awesome!  :smile:

**Comment by vedmack** [comment]
Thanks,
Since [0.8.9.beta.35](https://github.com/vedmack/yadcf/blob/1e23a16abf9f0419080e57905045a047e7eb43dc/jquery.dataTables.yadcf.js) yadcf ignores empty/sparse rows for range filters, thats the default and the only way a filter should handle empty values.
