### ISSUE TITLE
column filtering did not display all record

### ISSUE THREAD

**Issue by mrsibs** [vedmack/yadcf#274]
hi vedmack. your yadcf really save my coding time...currently im using yadcf 0.8.9 with datatable 1.10.7.
really impressing with the function provided.just now i want to use column filtering with server side and pagination. the problem is only record in the current page that is been displayed in the column, not all record. when i set server side to true it solve this problem. but im still want to use server side because of the performance wise(over 30k records).

thanks for your feedbacks.

**Comment by vedmack** [comment]
Hi,
When using DT with server side config you MUST provide yadcf with the values of each filter (think about it - you populate your DT with values of one page only, how do you expect yadcf to know what values exist in the other pages) so look at the showcase page - [Server side source example](http://yadcf-showcase.appspot.com/server_side_source.html) see code snippet at the bottom and inspect the dev tools and the network tab to see how I provide the needed data for yadcf filters (sending yadcf_data_0 / yadcf_data_1 / etc.. from server along with the DT data).

p.s please use github issue for reporting a bug/asking for a new feature only, questions should be asked on stackoverflow and [tag with yadcf](http://stackoverflow.com/questions/tagged/yadcf)
