### ISSUE TITLE
mRender + select

### ISSUE THREAD

**Issue by sameeralikhan** [vedmack/yadcf#275]
yadcf filter is not able to populate select options when data is formatted in mRender. In this example, change the date format filter type to select - it won't work.

https://jsfiddle.net/0ztkz9ey/51/

**Comment by vedmack** [comment]
You need to set the [column_data_type: 'rendered_html'](https://github.com/vedmack/yadcf/blob/7e74a7a61d9fe5aadb568ca3754a2424b8e4885f/jquery.dataTables.yadcf.js#L72)  for that column, but for that you must use the datatables 1.10. +
See [working jsfiddle](https://jsfiddle.net/0ztkz9ey/56/)
