### ISSUE TITLE
Select filter's values sorting not working when populated server-side

### ISSUE THREAD

**Issue by marianowadel** [vedmack/yadcf#278]
When a select is populated server-side, default sorting methods do not work properly or at all.

**Comment by vedmack** [comment]
In case you are populating your select with a pairs of value/label, then the sort wont work and you will have to provide the list of those pairs already sorted and set that filter to be `sort_as` property to `none` , [read more in the docs](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L137)


p.s question should be asked on stackoverflow, use github for issues/feature requests only

**Comment by marianowadel** [comment]
Thank you Daniel.
Congratulations for your work on this plugin.
Cheers
