### ISSUE TITLE
auto_complete doesn't work with AJAX mData

### ISSUE THREAD

**Issue by bambita** [vedmack/yadcf#282]
Hello,

filter_type: "auto_complete" is not working when AJAX mData is used.

Issue is reproduced on http://yadcf-showcase.appspot.com/ajax_mData_source.html
yadcf 0.8.9

Refer to column "Browser" or "Platform(s)".

Please advise.

**Comment by vedmack** [comment]
fixed, grab [0.9.0.beta.6](https://github.com/vedmack/yadcf/blob/fa76b48e2fb1e0dcd37fa93b589bc293edaca7bd/jquery.dataTables.yadcf.js), see it in action on [showcase](http://yadcf-showcase.appspot.com/ajax_mData_source.html)
