### ISSUE TITLE
Exporting PDF yadcf table 

### ISSUE THREAD

**Issue by rodrane** [vedmack/yadcf#284]
Hello,

I am trying to export pdf from a table that I've created with yadcf however the sub values of multiple select in header also exports to pdf.

```javascript
$(document).ready(function () {
    $('#yadcf').dataTable(
        {
            dom: 'Bfrtip',
            "iDisplayLength": 100,
            buttons: [
                {
                    extend: 'print',

                },
                'excel',
                {
                    extend: 'pdfHtml5',
                    orientation: 'landscape',
                    pageSize: 'LEGAL',
                    "bHeader": false //<-- THIS

                },
            ],

            "columnDefs": [
                {
                    "orderData": [1, 0], "targets": 0,},
                {header:"", className: "dt-head-center","target": "_all"  },
                {className: "dt-body-center" ,"targets": "_all"     },
            ],
        
        }
    ).yadcf([
        {column_number: 0},
        {column_number: 1},
        {column_number: 2},
        {column_number: 8},
    ]);
});
```
Here are some screenshots. 

![screen shot 2016-02-10 at 11 29 52](https://cloud.githubusercontent.com/assets/3604500/12943405/b782238e-cfe9-11e5-9b0f-18c3b007ae83.png)
![screen shot 2016-02-10 at 11 30 00](https://cloud.githubusercontent.com/assets/3604500/12943404/b763649e-cfe9-11e5-8d30-6a7e71f203f9.png)

thank you !

**Comment by bambita** [comment]
Hi, I have the same issue with export to excel. Filter values are part of header/column names...

Please help.

Thanks.

**Comment by vedmack** [comment]
The solution should be found in datatables / buttons configuration, you better ask on the forum / github of datatables, its not related to yadcf, take a look at [dt/buttons manual](https://datatables.net/reference/api/buttons.exportData()) , look at the _Format the header cells - adding the column index:_ at the bottom and please refer here to the solution when found

**Comment by bambita** [comment]
Thanks. Yes, you are right. I was able to exclude yadcf filters (html, **div**) from exported headers. Not sure if it is nice way but it works for me.

My working export button definition is

```javascript
{
	extend : 'excel',
	exportOptions : {
		columns : ':visible',
		format : {
			header : function (mDataProp, columnIdx) {
				var htmlText = '<span>' + mDataProp + '</span>';
				var jHtmlObject = jQuery(htmlText);
				jHtmlObject.find('div').remove();
				var newHtml = jHtmlObject.text();
				console.log('My header > ' + newHtml);
				return newHtml;
			}
		}
	}
}
```

**Comment by vedmack** [comment]
Cool, thanks for sharing

**Comment by vogel-st** [comment]
Great, thanks for sharing

**Comment by TauPan** [comment]
> Thanks. Yes, you are right. I was able to exclude yadcf filters (html, **div**) from exported headers. Not sure if it is nice way but it works for me.
> 
> My working export button definition is
> 
> ```js
> {
>     extend : 'excel',
>     exportOptions : {
>         columns : ':visible',
>         format : {
>             header : function (mDataProp, columnIdx) {
>                 var htmlText = '<span>' + mDataProp + '</span>';
>                 var jHtmlObject = jQuery(htmlText);
>                 jHtmlObject.find('div').remove();
>                 var newHtml = jHtmlObject.text();
>                 console.log('My header > ' + newHtml);
>                 return newHtml;
>             }
>         }
>     }
> }
> ```

Hm, somewhere I found this and have been using it for a while now and it still works with yadcf:
```js
  exportOptions : {
      columns : ':visible',
      header:
      (innerHtml, col_index, cell_node) => {
        return cell_node.childNodes[0].nodeValue;
      }
  }
```
