### ISSUE TITLE
Filter range_date does not return anything

### ISSUE THREAD

**Issue by sonukapoor** [vedmack/yadcf#285]
I am using the latest version to filter a date range. My data rows look like this:

```
<td>
<span>{{item.actionDTS | date: 'MM/dd/yyyy' }}</span>
</td>
```

The filter "from" and "to" works fine, but when I select the date it does not filter anything. My filter column is setup like this:

```
$("#tbl_Report").dataTable().yadcf([
                    {column_number: 0, filter_type: 'text'},
                    {
                        column_number: 1,
                        filter_type: 'range_date',
                        date_format: 'mm/dd/yyyy',
                        filter_container_id: "external_filter_container"
                    },
                  ....
                ]);
```

Any help is appreciated.

**Comment by sonukapoor** [comment]
I got it working after removing the span elements.

**Comment by vedmack** [comment]
You can keep the `span` but config yadcf to use `column_data_type: html` for that column, [see docs](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L72)

**Comment by sonukapoor** [comment]
Thank you. That worked beautiful.
