### ISSUE TITLE
Carry YADCF filter value from one page to another

### ISSUE THREAD

**Issue by GMEHTA1981** [vedmack/yadcf#288]
Hello,

We have multiple pages using similar columns. How do I carry forward user's search column filter value from one page to another. 

For example:
Page 1: has a grid with columns : User, DOB, Salary, Date of Joining etc
Page 2: has a grid with columns : User, Date, Enter Time, Exit Time

Now in the above case, using YDCF filter, I filter records for user "BOB" .. I would like the filter value top stay on the other page as well. so I dont need to re-filter. 

Is this possible ? 
YADCF recognizes columns by numbers not name. The order of column on another grid could be different. So, how do I make it work ?

**Comment by vedmack** [comment]
You should make use of the [exFilterColumn](https://github.com/vedmack/yadcf/blob/36dd5e2a7e2713cf9983ce475e71e73d6b47ef4c/jquery.dataTables.yadcf.js#L267) api function upon page load ,see it in action for the first table [at the showcase](http://yadcf-showcase.appspot.com/multiple_tables.html) whenever you use the filters on your first page/table you should store it in to local var and pass it to the other page and read/use on the other page load.

p.s

next time please ask question on stackoverflow and tag it with *yadcf*
