### ISSUE TITLE
Checkbox / Radio button filter

### ISSUE THREAD

**Issue by GMEHTA1981** [vedmack/yadcf#289]
Hello 

We have a requirement to provide checkbox / radio button as external filters. 
Please can you provide a showcase of how to incorporate this ?

As of now the plugin does not have this feature. I see this as part of enhancement...
I need it relatively urgently, please can you guide as to how I should modify ur plugin to create this filter and retain value.

**Comment by vedmack** [comment]
Its not related to yadcf, but here an example of column filtering [using datatables api only](http://jsbin.com/rugetomufi/edit?html,js,output) 

Here a sample using [yadcf and datatbles](http://jsbin.com/rixikoleqi/edit?html,js,output)

p.s

Next time please ask question on stackoverflow and tag them with yadcf
