### ISSUE TITLE
range_date not working with server_side data.

### ISSUE THREAD

**Issue by trf000** [vedmack/yadcf#290]
mysql data is from a Date field. returns 0 results, x does not clear query. when using the single Date filter, same thing except the X does clear the query. My date field is altered in my processing page like this:

`array( 'db' => 'DATE_FORMAT(date_ordered,"%m-%d-%Y")', 'dt' => 9, 'field' => 'date_ordered', 'as' => 'date_ordered')	`

However even when I just select the field normally, same thing happens.

**Comment by vedmack** [comment]
It works for me just fine, see [showcase sample](http://yadcf-showcase.appspot.com/server_side_source.html) , so I guess it something on your server side implementation that should be tuned up... , in case it helps you can look at my server side range  date [filtering implementation](https://github.com/vedmack/yadcf-showcase/blob/master/src/dr/yadcf/servlets/EntrysTableServerSideSource.java)

**Comment by trf000** [comment]
Maybe I am misunderstanding. I saw the Server side range date in the showcase, but saw no instructions on how to implement it. It doesn't come bundled with the download, so i'm not certain how to properly include the java file in either the javascript of the datatables or the php files.

**Comment by vedmack** [comment]
There is no need to include java in your php project and no midification in js are needed, yadcf will send using datatables api the dates that you selecting and inside your php code you should parse those dates and return only the relevant rows for the table, for example on the showcase the 4'th column using range_date, and picking up a date will send `columns[3][search][value]:04/13/2015-yadcf_delim-02/20/2016` to your server, parse those dates (yadcf uses the *-yadcf_delim-* delimiter), and return only the relevant rows back to client. You have to ,modify your php code (not a php user so I can't help on that

**Comment by trf000** [comment]
I think I understand. So the modification would take place in the ssp.php
page in datatables. I'll take a look. I think you'll have a lot of php
users looking at this. If I can provide you a good php solution, I will.

**Comment by vedmack** [comment]
You are correct, feel free to post your php code in the following thread https://github.com/vedmack/yadcf/issues/206 - its a thread in which php users can post their code for other users, you also can try looking at [github php/yadcf related code](https://github.com/search?l=php&p=26&q=yadcf&ref=searchresults&type=Code&utf8=%E2%9C%93)
