### ISSUE TITLE
data-search attribute not works for date

### ISSUE THREAD

**Issue by ver1000000** [vedmack/yadcf#291]
Hello.
I have a custom date column like:
`<td data-search="02/13/2016">
    <span data-timeupdate data-time="1455368890000" title="Saturday, February 13th 2016, 8:08:10 pm">16 days ago</span>
</td>`

I need to filter by data-search attribute. But it's search by inner html (span > data-time).

My settings is 
```
yadcf.init(machineTable, [
       {
            column_number: 8,
            filter_type: 'date',
            html5_data: 'data-search'
        }
  ]);
```

The page http://cybot.verstkalab.ru/machines/index.html ("Last available" column)

Please help((

**Comment by vedmack** [comment]
Closing this 1 since your example is not available... if you'll provide another one let me know
