### ISSUE TITLE
Numbers on range_filter_slider not variate with scrollX:true and Reset Buttons will not Work

### ISSUE THREAD

**Issue by hardythaker** [vedmack/yadcf#295]
If we use scrollX=true in DataTable then the numbers which comes on range_number_slider (start,end) will not increments/decrements as the slider moves. And also the filter_reset button besides the filter will not work of all filters. 
here is the [fiddel](https://jsfiddle.net/m52cqoom/10/)

[update] Its only occurring when we use the `footer` option in the yadcf constructor.On the header its working fine.
updated [fiddel](https://jsfiddle.net/7zzdy8go/)

**Comment by vedmack** [comment]
fixed in [0.9.0.beta.14](https://github.com/vedmack/yadcf/blob/b1e4bf6311b2f170cc7352bace89e83d958bf4a1/jquery.dataTables.yadcf.js) see [sample](https://jsfiddle.net/m52cqoom/17/)

oopsi - forgot about the [x] button - will fix it later

**Comment by vedmack** [comment]
properly fixed in [0.9.0.beta.16](https://github.com/vedmack/yadcf/blob/85c398ec19b757780259a59045282c266ce312a9/jquery.dataTables.yadcf.js) see [sample](https://jsfiddle.net/m52cqoom/20/)
