### ISSUE TITLE
Datatable yadcf datetimepicker issue

### ISSUE THREAD

**Issue by irfanjvd** [vedmack/yadcf#296]
As i open datetimepicker and select a date from picker  it gets close while i have to select time too so i want not to colse the picker on date select is it possible

**Comment by vedmack** [comment]
Fixed in [0.9.0.beta.13](https://github.com/vedmack/yadcf/blob/2dd5749f6c7b0a6456538edacbcb4f13e4cb81da/jquery.dataTables.yadcf.js)

**Comment by irfanjvd** [comment]
Great plugin Thanks vedmack :)
