### ISSUE TITLE
Position in second row thead

### ISSUE THREAD

**Issue by FelipeKoblinger** [vedmack/yadcf#297]
Hi!
I didn't find a way (without hard coding) to put filters in second row (tr) of thead.

There is a way to this in options?

Example:

``` html
<table>
  <thead>
    <tr>
      <th>Test</th>
    </tr>
    <tr>
      <!-- Filters  here !-->
      <th></th>
    </tr>
  </thead>

  <tbody></tbody>
  <tfoot></tfoot>

</table>
```

**Comment by vedmack** [comment]
provide a minimal sample on jsbin and I'll try to see what can be done

**Comment by FelipeKoblinger** [comment]
Sorry, vedmack. I made the jsbin and was working perfectly there.
I figured out that the option "orderCellsTop" as true in DataTable was messing the position.

Now everything is working!

Thanks for this great plugin.

**Comment by vedmack** [comment]
Another reason to provide a test case along with the Q` :)

**Comment by FelipeKoblinger** [comment]
Hi again, Vedmack.
I figured out the problem. I can't find a way to put first row as orderable and second row as filter inputs, without hard-coding.

In this example (https://jsbin.com/fahehihale/edit?html,js,output) the "orderCellsTop: true" is enabled and the first row of thead is orderable (can click to order asc or desc) along with filter inputs (second row is blank). If I set to false in orderCellsTop, everything shows perfectly, but, the orderable click is in second row instead of first row.

So I've just set this line code:

``` javascript
filter_selector_string = table_selector + ' ' + filters_position + ' tr:eq(' + $(unique_th[column_position]).parent().index() + ') th:eq(' + $(unique_th[column_position]).index() + ')';
```

to

``` javascript
filter_selector_string = table_selector + ' ' + filters_position + ' tr:eq(' + 1 + ') th:eq(' + $(unique_th[column_position]).index() + ')';
```

And now works first row orderable click and second row filters. I know this is horrible solution, but a quick one to me.

Thanks again.

**Comment by vedmack** [comment]
fixed in [0.9.0.beta.14](https://github.com/vedmack/yadcf/blob/b1e4bf6311b2f170cc7352bace89e83d958bf4a1/jquery.dataTables.yadcf.js) see [sample](https://jsbin.com/quxozekama/edit?html,js,output)

usage is via global property [filters_tr_index](https://github.com/vedmack/yadcf/blob/b1e4bf6311b2f170cc7352bace89e83d958bf4a1/jquery.dataTables.yadcf.js#L266)

**Comment by FelipeKoblinger** [comment]
Thanks, vedmack! :+1:

**Comment by vincentwhales** [comment]
I think this doesn't work if the data is loaded from ajax: 

 ```
 $.ajax({
    'url': 'index_view_data',
    'success': function(everything) {

      var table = $('#main-table').DataTable({
        columns: everything.headers,
        data: everything.data,

        paging: false,
        bAutoWidth: false,
      });

      $('.toggle-visibility').change(function () {
        var column = table.column( $(this).attr('data-column') );
        column.visible( ! column.visible() );
      });

      yadcf.init(table, everything.filters, { filters_tr_index: 0 });
    },
  });

```

I am getting this bug: 

jquery.dataTables.yadcf.js:712 Uncaught TypeError: t.chosen is not a function
    at b (jquery.dataTables.yadcf.js:712)
    at ee (jquery.dataTables.yadcf.js:2745)
    at ye (jquery.dataTables.yadcf.js:3478)
    at Object._e [as init] (jquery.dataTables.yadcf.js:3680)
    at Object.success (?sort=0&desc=1:483)
    at j (jquery.min.js?v=2.1.4:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?v=2.1.4:2)
    at x (jquery.min.js?v=2.1.4:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js?v=2.1.4:4)
