### ISSUE TITLE
Datetimepicker not working properly

### ISSUE THREAD

**Issue by marekpagel** [vedmack/yadcf#298]
> {
                    column_number: 0,
                    filter_type: "range_date",
                    datepicker_type: 'bootstrap-datetimepicker',
                    date_fotmat: 'dd/mm/yy HH:mm:ss',
                    filter_plugin_options: datetimepickerOptions
                }

Filter like this breaks, when using both lower and upper datetime bound.

Reason:
`function rangeDateKeyUP(table_selector_jq_friendly, date_format, event)`
is using `$.datepicker.parseDate` to parse the given date.

`$.datepicker.parseDate` can parse only year, month, day data but not hour, minute, second.
As a result, `min instanceof Date` and `max instanceof Date` are always false.

Exception from `$.datepicker.parseDate:` Unexpected literal at position 11

**Comment by vedmack** [comment]
Hi, please provide a jsbin / etc' link with this issue

**Comment by marekpagel** [comment]
I'm sorry but I have no time to create the sample.
I can also provide the information that `$.datepicker.parseDate` comes from 
project 'jqueryui' and the working alternative of the same function can be found in
'jqueryui-timepicker-addon' project, named `$.datepicker.parseDateTime`

**Comment by vedmack** [comment]
Ok.

Feel free to reopen this issue with a proper test case of your issue.
