### ISSUE TITLE
exFilterColumn and YADCF initialization together makes two AJAX requests.

### ISSUE THREAD

**Issue by GMEHTA1981** [vedmack/yadcf#299]
Hello Daniel, 

Assume this is my dataTable initialization, at the end of it.. I attached the YADCF plugin. 
This is one AJAX call. 

oTable = $('#entrys_table').dataTable({
        "iDisplayLength": 10,
        "bJQueryUI": true,
        "bProcessing": true,
        "sAjaxSource": 'entrys_table_source',
        "aoColumns": [{
            "sTitle": "Engine"
        }, {
            "sTitle": "Browser"
        }, {
            "sTitle": "Platform"
        }, {
            "sTitle": "Version",
            "sClass": "center"
        }, {
            "sTitle": "Grade",
            "sClass": "center",
            "fnRender": function (obj) {
                var sReturn = obj.aData[obj.iDataColumn];
                if (sReturn === "A") {
                    sReturn = "<b>A</b>";
                }
                return sReturn;
            }
        }]
    }).yadcf([{
        column_number: 0
    }, {
        column_number: 1,
        filter_type: "text"
    }, {
        column_number: 2,
        filter_type: "auto_complete"
    }, {
        column_number: 3,
        filter_type: "range_number_slider"
    }, {
        column_number: 4    }], 'footer');
}, { externally_triggered: true });

yadcf.exFilterColumn(oTable, {[2,'IE Browser'], [3,'100']});

But, I need to pass certain user preference search values to my external /internal column filters. Thus, as per your previous recommendation I use "exFilterColumn"... this creates a second AJAX call.

We are dealing with millions of records, this is causing a heavy load on the database.
Can you please suggest something ? Just like ResetAllFilters .. can exFilterColumn have one AJAX call.. ??

Thanks for your help.
Gayatri Mehta

**Comment by vedmack** [comment]
Hi,

exFilterColumn is sending one ajax only, you calling it a "second ajax call" because it comes after the initial call to server by datatables itself, I'd say that you should ask datatables author / google if about how to init datatables without making any call to server, and that way the first call will be sent by yadcf 

OR you can try writing some code on server to ignore the first ajax call coming from server (datatables call) and respond only to the call > 1 / second call and so on

**Comment by GMEHTA1981** [comment]
Is there a way, I could set default filter values during YADCF initialization ?

().datatables().yadcf([{
column_number: 1,
filter_type: "text",
**filtervalue: "XXXX"**
}]);

**Comment by GMEHTA1981** [comment]
I was thinking, if there was a way we can supply filters default initial value, in such a way that it can be picked up with your code

tmpStr = yadcfParseMatchFilter(tmpStr, getOptions(oTable.selector)[column_number].filter_match_mode);

Can it will be automatically replaced with user's search.. if applicable.
