### ISSUE TITLE
Set YADCF filter value on initial load without exFilterColumn

### ISSUE THREAD

**Issue by GMEHTA1981** [vedmack/yadcf#300]
How do I set default YADCF filter value, based on user preference without using exFilterColumn.
Issue with using exFilterColumn is that is caused double AJAX load.

For eg: In our system, user has a preference that his default filter be set to airport 'DTW'
I want a way to supply default filter value, when initializing YADCF column filters.

"column_number": 5,
filter_type: "text",
"column_name": "Airport"
**"Column_initialValue": "DTW"**

How should be able to do this ???

**Comment by vedmack** [comment]
Try using [searchCols](https://datatables.net/reference/option/searchCols) , without calling `exFilterColumn` and let me know how it works for you.

**Comment by GMEHTA1981** [comment]
As per your suggestion, I tried searchCols.

Two issues with it:
1) Main issue .. does not work for external filters.
2) does not account for hidden columns

So, I dont thing this is help out, since.. I need something whereby I can initialize filters whether external / internal to grid.

![image](https://cloud.githubusercontent.com/assets/5384690/14354364/016f16a8-fcab-11e5-8869-c6fe6f09f583.png)

**Comment by vedmack** [comment]
Sorry but that is the only available option, about the hidden columns you can ask datatables author on the forum ([you can here](http://datatables.net/forums/discussion/comment/91667)), as to the external filters - who created them? if you did then you should maintain their initial value too

**Comment by GMEHTA1981** [comment]
Well, 
I am using "filter_container_id" to place the filter outside the grid. 
The filters are still generated via YADCF

**Comment by vedmack** [comment]
you mean that searchCols loads the table pre filtered the external filters does not display the pre filtered value? Describe your issue and provide a link to jsbin / jsfiddle
