### ISSUE TITLE
yadcf - error on externaltrigger with multiselect 

### ISSUE THREAD

**Issue by gnouffre** [vedmack/yadcf#301]
i use yadcf with Extern container some "multi-select" and "externally_triggered" option. When i trigger the filter with my filter button if i got this error on console  : TypeError: selected_value.join is not a function  jquery.dataTables.yadcf.js:710:22

The reason is the variable filter_value can be equal space on multiselect and  the join fonction only work on an array. 

I fix the problem on function exFilterColumn, but i am not sure this is the finest solution 
  

case 'multi_select':
                    $('#yadcf-filter-' + table_selector_jq_friendly + '-' + column_number).val(filter_value);
           **         if (filter_value == '') {
                    tmpStr = '';
                    } else {**
                    tmpStr = yadcfMatchFilterString(table_arg, column_position, filter_value, optionsObj.filter_match_mode, true);
              **      }**
                    table_arg.fnSettings().aoPreSearchCols[column_position].sSearch = tmpStr;
                    if (optionsObj.select_type !== undefined) {
                        refreshSelectPlugin(optionsObj, $('#yadcf-filter-' + table_selector_jq_friendly + '-' + column_number), '-1');
                    }
                    break;

exemple here [http://jsfiddle.net/wbgkp5ta/](http://jsfiddle.net/wbgkp5ta/
)

pull request here 
#302

**Comment by vedmack** [comment]
fixed in [0.9.0.beta.15](https://github.com/vedmack/yadcf/blob/9a6d7a7b97982da2cc72b2dd9f79299fdf71a825/jquery.dataTables.yadcf.js)
