### ISSUE TITLE
select2 4.0+ Uncaught Error: No select2/compat/containerCss

### ISSUE THREAD

**Issue by Jrizzi1** [vedmack/yadcf#304]
using version 0.9.0.beta.6

when i include select2 version > 4.0 i get the following error
Uncaught Error: No select2/compat/containerCss

if i include select2 3.5.3, this issue does not occur, select2 works normally

**Comment by vedmack** [comment]
Please try the latest beta and provide a jsbin/etc' sample

**Comment by itonohito** [comment]
Same issue, tried with latest 0.9.0 beta21.

**Comment by vedmack** [comment]
Please provide a sample...

**Comment by Marionovello** [comment]
Was having this issue too, solution found with Select2
https://github.com/select2/select2/issues/3302#issuecomment-98030694

**Comment by vedmack** [comment]
@Marionovello , thanks for the input, I will check if the code snippet that responsible for that dependency is a must and to warn/"optionize" its usage

**Comment by vedmack** [comment]
took me time to figure out why I'm using the `adaptContainerCssClass` (which in turn requires *select2.full.js*), and the reason can be [found here](https://github.com/select2/select2/issues/2461) so that Select2 will not inherit all classes from original select that is generated by yadcf
