### ISSUE TITLE
Select plugin refresh not triggered for datatable.row.add

### ISSUE THREAD

**Issue by gauravjhs** [vedmack/yadcf#306]
Hi,

When I am adding rows to datatables, for filter_type multi_select, internal select box is updating the new values, but select plugin is not getting refreshed.

**Comment by vedmack** [comment]
please provide a link to test case jsbin / jsfiddle / etc'

**Comment by gauravjhs** [comment]
Hi Vedmack,

I am unable to create a jsbin/jsfiddle being a first time user of those services. 
Am not able to include your latest js file in their resource library. Can you help me out with this.

Or if you can create a sample fiddle for me to work on. Apologies for the inconvenience.

**Comment by vedmack** [comment]
Here are the latest versions on yadcf css/js
https://rawgit.com/vedmack/yadcf/7b37b3142059efc8e2d81c5f6d93d38d81a022bd/jquery.dataTables.yadcf.css
https://github.com/vedmack/yadcf/blob/9a6d7a7b97982da2cc72b2dd9f79299fdf71a825/jquery.dataTables.yadcf.js

**Comment by gauravjhs** [comment]
Hi Vedmack

Please look at http://jsbin.com/bayuru/edit?html,js,console,output

Created 2 select box filters. Basic select box is updated with no value. MultiSelect plugin box is not getting refreshed.

**Comment by vedmack** [comment]
Hi

There was an issue in your code - invalid use of the [exFilterColumn](https://github.com/vedmack/yadcf/blob/85c398ec19b757780259a59045282c266ce312a9/jquery.dataTables.yadcf.js#L281) <-- read docs,

See this [jsbin sample](http://jsbin.com/gefuweyopu/edit?html,js,output) , click on First Col / Second Col to see how the filters / table reacts...

As to the datatable.row.add, I don't see its use in the jsbin. You should extend that jsbin to reflect your issue...

**Comment by gauravjhs** [comment]
Hi,
I was using someone else code, that's why the exFilterColumn. I have removed it as I am not using that.

I have not used datatable.row.add in this example as of now.
Issue can be seen what I clear datatables with 
<code>dataTableObjRedraw.clear();
dataTableObjRedraw.draw();</code>
Multiselect plugin still reflects the old values but normal select box clears all previous values.
i.e. Multiselect is not able to refresh underlying values.

Hope I am clear this time.

**Comment by vedmack** [comment]
If you made a new test sample please provide its code

**Comment by gauravjhs** [comment]
I have removed exFilterColumn. Please check jsbin http://jsbin.com/bayuru/edit?html,js,console,output

**Comment by vedmack** [comment]
Sorry, but I really can't understand what are you trying to show in your jsbin sample?

You must provide a scenario with expected flow / and to explain whats the actual flow, the moment you will provide a jsbin sample with the expected  / actual flow I will be able to try and help you, untill then - I can't

**Comment by gauravjhs** [comment]
I have made a button to clear data in Datatables.

Case 1: Load Datatable with initial data and load filters.
Expected : Table generated with proper filter values.

Case 2: Clear data present is datatables
Expected : Data rows is removed and all values in filters are removed.
Actual : Column 1 filter still retains old values(Should have cleared these values). Column 2 filter clears old Values (as expected)

![yadcf](https://cloud.githubusercontent.com/assets/10832473/15171788/d4b2c5d6-176e-11e6-875e-19df8979319b.PNG)

Please see the jsbin http://jsbin.com/bayuru/edit?html,js,console,output with "Clear Datatables" button.

**Comment by gauravjhs** [comment]
Hi Vedmack,
Were you able to figure out the issue?

**Comment by vedmack** [comment]
Hi,
It looks more a multi select plugin issue than yadcf, it seems that when you init the multi select it does not clear its values, so the only possible solution I came with is to init it / destroy then init again

like this

```
yadcf.initSelectPluginCustomTriggers(
    function(selectBoxObj) {
      selectBoxObj.multiselect({});
      selectBoxObj.multiselect("destroy");
      selectBoxObj.multiselect({});
    },
    function(selectBoxObj) {
      selectBoxObj.multiselect('refresh');
    });
```

[See working sample](http://jsbin.com/zofifiqopu/edit?html,js,console,output)
