### ISSUE TITLE
Combine range number and range number slider

### ISSUE THREAD

**Issue by SarahCSharp** [vedmack/yadcf#307]
Is it possible to combine range number filter with range number slider input where if you use the slider the values of the range number input is changed dynamically.

something similar to google finance for example : https://www.google.com/finance#stockscreener

**Comment by vedmack** [comment]
Currently its impossible, might add it in the future / PR is welcomed too - it shouldn't be a difficult task just add 2 inputs to the slider with proper callbacks...

**Comment by SarahCSharp** [comment]
I'm quite a newbie at this so would you mind telling me how I could go about doing that?

**Comment by vedmack** [comment]
Despite the fact that it could be a nice addition to yadcf it wont be implemented (luck of interest from the community / no time)
