### ISSUE TITLE
Range number slider & select not refreshed after adding row 

### ISSUE THREAD

**Issue by gnouffre** [vedmack/yadcf#308]
I will try to make a jsfiddle exemple the scenario is
- External filter with range number slider.
First i have a datatable with only 1 value, my range slider put this value on min and max range slider.
If i trigger an external filter, with that range slider, all my data are filtered.

Next i populate my datatable with new value, the range slider dont bring those value.

I try to change using range number, and now yadcf working nice.

**Comment by gnouffre** [comment]
try adding range slider, but dont work?, but same effect on select  => value are well initialized on load table, but adding a row dont update filter value (not in this fiddle but on select2 filter, values are well updated)

http://jsbin.com/sodibi/3/edit?html,css,js,console,output

**Comment by vedmack** [comment]
No issues with select filter being updated, [see working jsbin](http://jsbin.com/jotarevoju/edit?html,css,js,output)

but there indeed an issue with the slider...

**Comment by vedmack** [comment]
fixed in [0.9.0.beta.17](https://github.com/vedmack/yadcf/blob/4c7b49fa418d0f91da5438248e9a4664170dd618/jquery.dataTables.yadcf.js),

[see sample](http://jsbin.com/tiwegufefu/edit?html,output)
