### ISSUE TITLE
Datetimepicker not working properly

### ISSUE THREAD

**Issue by marekpagel** [vedmack/yadcf#309]
> {
                    column_number: 0,
                    filter_type: "range_date",
                    datepicker_type: 'bootstrap-datetimepicker',
                    date_fotmat: 'dd/mm/yy HH:mm:ss',
                    filter_plugin_options: datetimepickerOptions
                }

Filter like this breaks, when using both lower and upper datetime bound.

Reason:
`function rangeDateKeyUP(table_selector_jq_friendly, date_format, event)`
is using `$.datepicker.parseDate` to parse the given date.

`$.datepicker.parseDate` can parse only year, month, day data but not hour, minute, second.
As a result, `min instanceof Date` and `max instanceof Date` are always false.

Exception from `$.datepicker.parseDate:` Unexpected literal at position 11

I created the jsfiddle you asked for [here](https://jsfiddle.net/y4zzak2y/)
You can't see the error message, as `rangeDateKeyUP` swallows the error message that is thrown by  `$.datepicker.parseDate`. You could use the debugger (commented out by default) to verify this.

For whatever reason this jsfiddle doesn't filter at all. I am not sure if it's something I've done wrong as in my real application I use server side filtering and it works. Also, this jsfiddle works with regular date_range filter.

(Another easier solution would be to remove `instanceof Date` check as a whole as it isn't used consistently anyway and the user is supposed to use ui-picker to avoid bad format.)

**Comment by vedmack** [comment]
In case that its still relevant I fixed that now, [see live sample](https://jsfiddle.net/y4zzak2y/5/)

It now requires to include momentjs library and to provide a `moment_date_format` property for the column, in your case it should look like this `moment_date_format: 'YYYY-MM-DD hh:mm:ss',`

Sorry for the delay but I can barely find some spare time lately and your issue wasn't that easy

**Comment by marekpagel** [comment]
Thank you! works like a charm.
