### ISSUE TITLE
loosing focus when using fixedHeader and no pagination after every char

### ISSUE THREAD

**Issue by jonnsn** [vedmack/yadcf#310]
When using a column filter in a datatable with fixed Header and without pagination setting a text filter is very hard as the input loses focus after every single char.
This seems to occur due to the fact, that the header gets changed every time in the dom.
https://jsfiddle.net/n2ybwhpv/

I currently have no idea how this could be fixed.... Maybe one could set focus manually after the header is updated but I guess that will lead to a delay between every char nobody wants to wait for. Maybe it should not be seen as an issue on yadcf side at all. I just wanted to document it here at least.

**Comment by vedmack** [comment]
> [As of v3, FixedHeader doesn't display a clone but rather the original element](https://github.com/DataTables/FixedHeader/issues/47#issuecomment-181425851)


So yadcf works with fixedheadrs out of the box, [see showcase (first table)](http://yadcf-showcase.appspot.com/DOM_Ajax_Multiple_1.10.html)

(you have to include fixed header js/css)

**Comment by jonnsn** [comment]
Well - yes, it works with fixedheaders in general, but as you can see in my fiddle the issue with the focus exists though. The showcase uses filter types like auto_complete, date and range slider. With these inputs the filter is applied as soon as a complete value is entered/selected, so the focus lost is no issue here. The second showcase example has a text-filter column, but has no fixedheaders set.

If the filter is **a plain text field** (as in my fiddle), every single char leads to lost focus while typing when fixedheader is enabled.

**Comment by vedmack** [comment]
You should include the fixed header js/css into your jsfiddle...

**Comment by jonnsn** [comment]
Thanks for your help on this!

You mean the datatables fixed header js/css?
Its included - see the urls:
cdn.datatables.net/t/dt/jqc-1.12.0,dt-1.10.11,**fh-3.1.1**/datatables.min.js
cdn.datatables.net/t/dt/jqc-1.12.0,dt-1.10.11,**fh-3.1.1**/datatables.min.css

In the js file the fixedHeader part is the last part.
I generated these links via the datatables dowanload page: https://datatables.net/download/index

Is there any other CSS/JS I should include? I am very sorry if I am overseeing something obvious.

**Comment by vedmack** [comment]
My bad, haven't noticed that you generated the js / css that way. I will see what can be done with the focus issue...

**Comment by jonnsn** [comment]
I am currenty trying to find a way to workaround this - is it correct that there is no way to disable the automatic search on keypress except the 'externally_triggered' option which applies to all filters?

**Comment by vedmack** [comment]
> is it correct that there is no way to disable the automatic search on keypress except the 'externally_triggered' option which applies to all filters?

Yes that is corrent,

Looks like its an issue in the datatables itself

**Comment by vedmack** [comment]
Apparently it was already fixed in the latest FixedHeader library, so just update it to the "3.1.2 release of FixedHeader" and it will work for you, [see sample](https://jsfiddle.net/n2ybwhpv/9/)
