### ISSUE TITLE
Need of event triggered when filter are added

### ISSUE THREAD

**Issue by aureltime** [vedmack/yadcf#312]
hello,

when i use datatables with autowidth option at true and a mecanism of responsive height linked to the "resize" event, the fact that i use yadcf provokes misalignement of header columns with data columns. If i resize my window, resize event is triggered and alignement is good again.

i would need one "filters just added" event to handle and if i link my resize triggering event, my problem would be solved.

I just speak about my own problem but the add of specific events is maybe more general and would be great help to be able to manage more things. Also after filtering has been done so for example, update footer that could be sum of values in different rows to only considerer what has been filtered

thanks for your work !

**Comment by vedmack** [comment]
yadcf reacts to datatables events, draw / xhr  / etc, try listening to them and see how it works for you, if it wont work - let me know and I will add this your requested feature to yadcf

**Comment by aureltime** [comment]
yes i listen to them but they i didn't find ways they tell me when the filters are added in my table for example.

For the second thing that i wrote, about the footer update, it is not necessary to have an event for that but i think it could still be usefull for other usecases. If you just want to make operations on the filtered rows, use the [selector-modifier option](https://datatables.net/reference/type/selector-modifier)

It would be great to have them :)
