### ISSUE TITLE
Data not loaded into chosen multi-select as of 0.8.9

### ISSUE THREAD

**Issue by cpell** [vedmack/yadcf#313]
I updated yadcf from 0.8.8 to 0.8.9 (have also tried most recent commit) and noticed a new issue with the chosen multi-select options. It seems that the data is no longer making it's way into the chosen plugin.

I will investigate this further and post back if I find anything.

https://jsfiddle.net/kkf2czcc/

**Comment by nikita030493** [comment]
I faced exactly same problem when installed 0.8.9. However it only seems to aprear if using "scrollX: true" or "scrollY: ##vh" properties of jQuery Datatables. I tried to downgrade to 0.8.8 and it worked, BUT then header became unscrollable and wouldn't colapse.

**Comment by nikita030493** [comment]
Try to get rid of  **filter_type: 'multi_select'** I think it is multi select by default so you don't have to specify it anymore.

**Comment by cpell** [comment]
@nikita030493 tried doing that in my JS fiddle and it becomes a single select, still with no options to select from

**Comment by vedmack** [comment]
@cpell , for your second column (`1`) you must specify `column_data_type: 'rendered_html',` (read docs for more info) for your first column - I'm not sure how you populate the 1/2/3 values into that column, but if you will try to use the global datatables filter you will notice that its also can't see those 1/2/3 values for that column - for example try to type the `3` value into datatables global filter and you wont get the row with `3` in the table, the moment you will figure out how to populate it properly I hope that yadcf will be able to populate those values into the filter.
