### ISSUE TITLE
Values with quotation marks filtered incorrectly by filter_type select

### ISSUE THREAD

**Issue by int-ua** [vedmack/yadcf#317]
Any value that contains quotation marks will be used only partially when selected in the filter, ending on the first quotation mark.

**Comment by quazerro** [comment]
this bug has been found in yadcf.js 0.8.9 (jquery.dataTables.js 1.10.11, jQuery v2.2.3)

**Comment by vedmack** [comment]
Please provide a jsbin / jsfiddle test case.

**Comment by quazerro** [comment]
here it is:
https://jsfiddle.net/gz0b2438/

**Comment by int-ua** [comment]
Hack-ish workaround is to simply add `.replace(/"/g, '&quot;')` to the value while inserting it into an option attribute `value`. AFAIU forming selects with jQuery (`.attr()`) is safer.

**Comment by vedmack** [comment]
fixed in [0.9.0.beta.19](https://github.com/vedmack/yadcf/blob/e71367f656f6bbd50440843ada88dea8123fb01b/jquery.dataTables.yadcf.js)
[see working sample](https://jsfiddle.net/gz0b2438/7/)
