### ISSUE TITLE
filter_default_label for filter_type range_date

### ISSUE THREAD

**Issue by benblub** [vedmack/yadcf#319]
If i set filter_default_label on the filter_type range_date like "Custom Label" only the first character is displayed in the "from" input -> C, the u goes in the second input and rest is invisible

**Comment by vedmack** [comment]
Show your yadcf code

**Comment by benblub** [comment]
`if (  $.fn.DataTable.isDataTable( '#tableVeranstaltungen' ) ) {
        yadcf.init(tableVeranstaltungen, [ {
            column_number: 1,
            filter_type: "range_date",
            style_class: 'asdfasdfasdfasdf',
            date_format:  'dd.mm.yy',
            filter_default_label: 'von'
        }, {
            column_number: 3,
            filter_type: "select",
            style_class: 'form-control'
        }
        , {
            column_number: 4,
            filter_type: "select",
            style_class: 'asdfasdfasdfasdf',
          }
        ]);
    }`

**Comment by slimiles** [comment]
This example above is in our project (@benblub).
Is there a way to get the **style_class** working for **range_date**? And how can I define a custom class for the reset buttons?

Thanks for your help!

**Comment by vedmack** [comment]
Read docs for the [filter_default_label](https://github.com/vedmack/yadcf/blob/430cdddf85defa6b728782e937f0524b6d09bc41/jquery.dataTables.yadcf.js#L120)

> Required:			false
> 				Type:				String / Array of string in case of range_number filter (first entry is for the first input and the second entry is for the second input
> 				Default value:		Select value
> 				Description:		The label that will appear in the select menu filter when no value is selected from the filter
> 

Usage example for range filters:

```
filter_type: "range_date",
filter_default_label: ["My From", "My Two"]
```

> style_class - allows adding additional class/classes to filter - available for the following filters: select / multi_select / text / custom_func / multi_select_custom_func

if you want style_class to work with other filters open an issue or even better send a PR (its really easy to add for other filters)

IMO there no need for "custom class for the reset buttons" just override the current class definition
