### ISSUE TITLE
For the custom_func instead of sending rowValues, you should just send me row

### ISSUE THREAD

**Issue by Serjster** [vedmack/yadcf#320]
I have custom data attributed on my columns to help me filter... but since you're sending the column values, which is more or less useless to me, you should just give me the **row** HTML element so I can use jquery to get at those data attributes

**Comment by vedmack** [comment]
Provide a jsbin/jsfiddle sample

**Comment by Serjster** [comment]
Like this? https://jsfiddle.net/n9dkofnx/

**Comment by vedmack** [comment]
No, a sample showing your scenario/issue something that I can work with...
