### ISSUE TITLE
multi_select not working "TypeError: $selectObject.chosen is not a function"

### ISSUE THREAD

**Issue by qlassalle** [vedmack/yadcf#322]
First of all, thank you for your wonderful plug-in, it helped me a lot to do what I want combined with DataTables !
However, since yesterday, I'm trying to use a multi_select for a column of my table. This column contains actors and I want to be able to select many actors. I tried to apply the following properties to my column 
`
		        column_number: 4,
		        filter_default_label: "Tous",
		        style_class: "yadcf-proprietaire-filter",
		        filter_reset_button_text: false,
			filter_type: "multi_select",
			select_type: 'chosen'`

but I'm not getting the same result as shown in the first column here http://yadcf-showcase.appspot.com/DOM_source_chosen.html

My result when I apply those properties looks like 
![multi_select not working](https://cloud.githubusercontent.com/assets/9036994/15959972/c59ab9f4-2efd-11e6-8744-50a28404647f.PNG)

Thanks for your help

**Comment by vedmack** [comment]
Hi

Make sure to include the chosen js/css in your html page (include them before the yadcf js)

**Comment by mourareaupro** [comment]
I have the exact same problem, i used the downloaded package v9.0.3, i was running the exemple.html and i just changed the column 0 with multi select and i get the same error.  hope you can help me 
![capture](https://user-images.githubusercontent.com/25173073/53080019-06ac4e00-34f8-11e9-8ca3-d639ce9a582d.PNG)

**Comment by vedmack** [comment]
@mourareaupro , looks like you trying to use the chosen plugin for your multi select, make sure to include the chosen js/css in your html page (include them before the yadcf js)

**Comment by mourareaupro** [comment]
@vedmack thanks a lot for your fast reply. i just missed to load the others js dependencies. as chosen library. thanks again for your help and this amazing package

**Comment by Ynjxsjmh** [comment]
Encountered into the same problem when using `multi_select` parameters.

Solved by including [chosen.jquery.min.js](http://yadcf-showcase.appspot.com/resources/js/chosen.jquery.min.js) found on http://yadcf-showcase.appspot.com/DOM_source_chosen.html before `jquery.dataTables.yadcf.js`.
