### ISSUE TITLE
Multi select problem in yadcf datatables

### ISSUE THREAD

**Issue by RazaTG3** [vedmack/yadcf#323]
I'm using yadcf-0.8.9 plugin with JQuery datatable 1.10.10. I'm facing problem with multi-select of yadcf. when I select anything in the multi-select filter then no any record show in the table below.

@section Scripts
{
<link href="~/css/jquery.dataTables.yadcf.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.yadcf.js"></script>

    <script type="text/javascript">
        var siteRoot = "@Url.Content("/")";
        var oTable;
        $(document).ready(function () {
            'use strict';
            oTable = $('#example').dataTable({
                "bStateSave": true
            }).yadcf([{
                column_number: 0,
                filter_type: "multi_select",
                select_type: 'chosen'
            }]);
        });
    </script>
}

![capturemultiselecttest](https://cloud.githubusercontent.com/assets/19878637/15990025/5bc9629a-30a2-11e6-85ac-aaa73f38096f.JPG)

**Comment by vedmack** [comment]
Provide a test case jsbin/jsfiddle or link to your site

**Comment by RazaTG3** [comment]
![capture1](https://cloud.githubusercontent.com/assets/19878637/15990350/add96b5a-30a9-11e6-8403-b35e2960f6bf.JPG)
![capture2](https://cloud.githubusercontent.com/assets/19878637/15990351/adda2f40-30a9-11e6-8903-08278af8ab29.JPG)
![capture3](https://cloud.githubusercontent.com/assets/19878637/15990352/ade150cc-30a9-11e6-949a-640fd0e5682d.JPG)
![capture4](https://cloud.githubusercontent.com/assets/19878637/15990353/ade5ea10-30a9-11e6-9f3b-cb00337ca14f.JPG)

and when I clear the multi-select filter then all records appear again.

**Comment by RazaTG3** [comment]
I need its solution. Kindly help me out.

**Comment by RazaTG3** [comment]
I just want working multi select column filter in my JQuery datatables.

**Comment by vedmack** [comment]
Provide a test case jsbin/jsfiddle or link to your site, because as you can see in the showcase multi select with  chosen works fine - [see first column in showcase](http://yadcf-showcase.appspot.com/DOM_source_chosen.html)
