### ISSUE TITLE
yadcf doesn't show empty element in default select

### ISSUE THREAD

**Issue by ashl1** [vedmack/yadcf#324]
If I use yadcf on column with empty values ```value===''``` with default type (select) it will not add the empty option to select., so I cannot select the empty value to filter.

**Comment by vedmack** [comment]
Please provide a jsbin or jsfiddle sample

**Comment by ashl1** [comment]
Yep, of course.
https://jsfiddle.net/qrmkt90s/1/

**Comment by vedmack** [comment]
By design yadcf omits empty strings from the filter, but since yadcf is very configurable you can achieve your goal with the following setup

```
yadcf.init(table, [
  {
    column_number: 0,
    data: [' '],
    append_data_to_table_data: 'before',
    filter_match_mode: 'exact'
  }

])
```

[See live sample](https://jsfiddle.net/qrmkt90s/2/)

More info can be found in the yadcf js file (docs)
