### ISSUE TITLE
Chosen doesn't work with datatables scrollx or scrolly.

### ISSUE THREAD

**Issue by nikita030493** [vedmack/yadcf#326]
Vedmac, first of all thanks for your work! Great plugin!

I use yadcf 0.8.9.
Chosen select list doesn't work properly when used with Datatables scrollx or scrolly options enabled. 
Here is an example:

https://jsfiddle.net/p9qo1kj9/17/

Is there a quick fix or would it actually require to modify yadcf?

**Comment by vedmack** [comment]
Hi,
You are welcome, unfortunately because of the way that chosen is being rendered its impossible (unless you will find a way) to use it with scrollX option, but you can use the select2 plugin instead (which is compatible with scrollX)
