### ISSUE TITLE
Adding 'tfoot' Prevents Cumulative_Filtering from Working

### ISSUE THREAD

**Issue by jackerman09** [vedmack/yadcf#327]
I would like to use cumulative_filtering and to have the filters display in the footer, not the header. Both of these features are working on their own, but when I include both options together the cumulative_filtering does not work (the tfoot option is still working). How can I use these two options together? Thanks!

```
yadcf.init(table, [
	{ column_number: 1, filter_reset_button_text: false, select_type: 'select2'	},
	{ column_number: 2, filter_reset_button_text: false, select_type: 'select2'	},
	{ column_number: 3, filter_reset_button_text: false, select_type: 'select2'	},
	{ column_number: 4, filter_reset_button_text: false, select_type: 'select2'	},
	{ column_number: 6, filter_reset_button_text: false, select_type: 'select2' },
	{ column_number: 7, filter_reset_button_text: false, select_type: 'select2'	},
	{ column_number: 8, filter_reset_button_text: false, select_type: 'select2', column_data_type: "html", html_data_type: "text" }
	],
	'footer',
	{ cumulative_filtering: true }
)
```

**Comment by vedmack** [comment]
Hi,

The docs are a bit unclear (will update them soon about this feature),
Anyway since you want to specify the filters location and use the cumulative you should use it in the following way

    yadcf.init(table, [
        { column_number: 1, filter_reset_button_text: false, select_type: 'select2' },
        { column_number: 2, filter_reset_button_text: false, select_type: 'select2' },
        { column_number: 3, filter_reset_button_text: false, select_type: 'select2' },
        { column_number: 4, filter_reset_button_text: false, select_type: 'select2' },
        { column_number: 6, filter_reset_button_text: false, select_type: 'select2' },
        { column_number: 7, filter_reset_button_text: false, select_type: 'select2' },
        { column_number: 8, filter_reset_button_text: false, select_type: 'select2', column_data_type: "html", html_data_type: "text" }
        ],
        {
            filters_position: 'footer',
            cumulative_filtering: true 
        }
    )

Its either the third argument as a string (for position) or third argument for an object with `filters_position` key and 'footer' as a value.

[Same on SO](http://stackoverflow.com/questions/38151942/adding-tfoot-prevents-cumulative-filtering-from-working)
