### ISSUE TITLE
delay to search search until 3 characters(maybe not an issue)

### ISSUE THREAD

**Issue by ismailyilmaz** [vedmack/yadcf#329]
hi folks, i want to delay to search search until 3 characters been typed or enter is clicked! there are many sampes without yadcf, and those work well, but same methods doesnt work with yadcf.. please help me how to do it.. thanks in advance.

**Comment by ismailyilmaz** [comment]
hey, something strange i recognized, this code works in chorem debug mode, but without debug mod it doesnt work, woaw so strange:) 

```
$('#yadcf-filter--datatables-1')
                    .unbind('keypress keyup')
                    .bind('keypress keyup', function (event) {
                        debugger;
                        if ($(this).val().length < 3 && event.keyCode !== 13)
                            return;
                        dataTable.fnfilter($(this).val());
                    });
```

**Comment by vedmack** [comment]
Take a look on how the textKeyUpMultiTables function is implemented and modify it to do the filtering only after X amount of chars entered
