### ISSUE TITLE
Re-initialization of datatable is breaking 

### ISSUE THREAD

**Issue by Gstji** [vedmack/yadcf#332]
If we re-initialize a datatable on a page using ajax ,then it is raising parsing exception on yadcf js.

**Comment by vedmack** [comment]
Hi,
You don't really expect me to be able to provide a fix based on your issue description... Please provide a complete test case with link... if not possible, provide as much info / error from console as possible (don't flood with code, just the relevant)

**Comment by jaswinder97** [comment]
I'll provide you a test case link for this.

**Comment by valamelkor** [comment]
I have the same issue. 
The case is that: 
I have datatable with DOM data loaded and initialized with ajax. 
On first pass it is ok, but on the second one (the same div loads from ajax and the same yadcf.init(...) code is executing) it shows me 'cannot call oSavedState of undefined' on 0.8.9 and 'cannot call sTableId of undefined' on current master. 

I will try to provide example
