### ISSUE TITLE
How to bind one multi_select depends on another multi_select's selected value. (Not an issue)

### ISSUE THREAD

**Issue by ismailyilmaz** [vedmack/yadcf#335]
I would like to bind **multi_select** with the id _external_filter_model_ depends on selected value of **multi_select** with the id _external_filter_brand_. Is there any method provided by your awesome framework? If no, can i do some jquery stuff? Thanks in advance.
```
[{
    column_number: 3,
    filter_type: "multi_select",
    filter_container_id: 'external_filter_brand',
    select_type: 'select2',
    select_type_options: {
        width: '120px'
    },
    filter_default_label: "All"
}, {
    column_number: 4,
    filter_type: "multi_select",
    filter_container_id: 'external_filter_model',
    select_type: 'select2',
    select_type_options: {
        width: '120px'
    },
    filter_default_label: "All"
}]
```

**Comment by ismailyilmaz** [comment]
I found a way to populate ddlModels and its works. But after init of datatable complated ddlModels becomes empty, i tried many callbacks of your framework and also datatables own callbacks but i couldnt succeeded, i think i need a callback method of your framework like datatable's initComplate. Is there and callback method ensures your framework totally finished its init? Most probably after your framework totally finished its init after each ajax call, i would be able to use  **yadcf.exGetColumnFilterVal(dataTable, 4)**. because it returns empty array, even for example 3 items selected.

```
function bindModelDropdownList() {
    var
        selectedBrandIds = yadcf.exGetColumnFilterVal(dataTable, 4), // 4 = external_filter_brand,
        ddlModels = $("table td#external_filter_model select"),
        postData = {
            brandIds: selectedBrandIds
        };

    $.ajax({
        cache: false,
        type: "POST",
        dataType: 'json',
        async: false,
        url: "@(Url.Action("
        GetSelectListOfModelsByBrandId ", "Model "))",
        data: postData,
        success: function(data) {
            ddlModels.html('');
            $.each(data, function(id, option) {
                ddlModels.append($('<option></option>').val(option.Value).html(option.Text));
            });
        },
        error: function(xhr, ajaxOptions, thrownError) {
            alert('Failed to retrieve models.');
        }
    });
}
```

```
$("table td#external_filter_brand select").change(function() {
    bindModelDropdownList();
});
```

**Comment by vedmack** [comment]
Hi,

Please use this repository issues only for reporting a bug or asking for a feature, for general questions use stackoverflow.com and tag your question also with yadcf. As for events of yadcf, you can watch/subscribe to the https://github.com/vedmack/yadcf/issues/312 issue and you will be updated on when its available (can't tell exactly when).

As to your current question, you might want to go over the yadcf docs (inside the js file) and read about the `data_as_is` and the `append_data_to_table_data` , also know that you can populate the yadcf filters along with the datatables data, just place the relevant array of values into the `yadcf_data_XXX` (read more in docs/showcase)
