### ISSUE TITLE
yadcf does not works with jQuery 3

### ISSUE THREAD

**Issue by BafS** [vedmack/yadcf#336]
Hi,

Thank you for yadcf.
I use jQuery 3 and unfortunately yadcf seems to not be compatible with the third version. Will it be supported soon ?

Thanks in advance.

**Comment by vedmack** [comment]
Hi,

Please provide a jsbin/etc sampke so I could see whats wrong and fix it

**Comment by BafS** [comment]
- Working with jquery 1 : http://jsbin.com/xerocuhova/edit?html,output
 - Not working, with jquery 3: http://jsbin.com/leqacesifi/edit?html,output

**Comment by vedmack** [comment]
It was fixed by @ckoeber , [grab 0.9.0.beta.25 ](https://raw.githubusercontent.com/vedmack/yadcf/a58be6b48d88c7bcba6902f8ffe9663729a66dd0/jquery.dataTables.yadcf.js)
