### ISSUE TITLE
multi_select with filter_match_mode "regex" escapes regex metacharacters

### ISSUE THREAD

**Issue by scintill** [vedmack/yadcf#338]
In [`doFilterMultiSelect`](https://github.com/vedmack/yadcf/blob/7839bfbf2be5d93624660acbf28d90489091062d/jquery.dataTables.yadcf.js#L928-L939), I think the "regex" type should not escape regex special characters, under the assumption that the developer has already escaped them if needed. There is no apparent difference between "contains" and "regex" in this context, and I expect escaping/not-escaping should be the difference.

If it helps, the context is that I'm trying to build a multiselect regexp filter with a simple list of OR'd strings, but the `|` character is being escaped, which causes my filter to find nothing because there are no literal `|`'s in my data.

**Comment by vedmack** [comment]
Please provide a simple test case

**Comment by scintill** [comment]
I made a test at https://jsfiddle.net/q4wL1arL/2/ The single-select on top works how I would expect. But on the multiselect on bottom with the same configuration, the regexes with `|` don't select anything, and I think it's because the character is escaped by yadcf.

Thanks for your work on this project and for looking into this issue. I have a patch for this, according to my understanding of the issue and how yadcf is supposed to work, on a private branch that I can publish if you want.

**Comment by vedmack** [comment]
If you already patched it, feel free to send a PR.

**Comment by scintill** [comment]
I opened PR #339. https://jsfiddle.net/9r0LLnhx/1/ uses my changed version and works like I expect.
