### ISSUE TITLE
yadcf select2 external filter option ordering not as sent through ajax response

### ISSUE THREAD

**Issue by louking** [vedmack/yadcf#340]
Please see http://www.scoretility.com/resultschart?club=fsrcrt . 

Take a look at the response to the ajax retrieve of `_resultschart` when the page is rendered. `yadcf_data_1` is in alphabetic order, but the first option for the Name external filter is from the middle of the list.  

In my application, the options are passed from python into javascript through a flask jinja2 template (this detail shouldn't matter) -- the python for datatable options and yadcf options below as `dt_options` and `yadcf_options` respectively. `getcol('runnerid')` resolves to column 1.

            dt_options = {
                'dom': '<"dt-chart-table dt-chart-tabledisplay dt-hide"<"H"lBpr>t<"F"i>>',
                'columns': [
                    { 'data': 'date',           'name': 'date',             'label': 'Date',        'className': 'dt-body-center dt-chart-nowrap'},
                    { 'data': 'runnerid',       'name': 'runnerid',         'label': 'Runner ID',   'visible': False },
                    { 'data': 'name',           'name': 'name',             'label': 'Name',        'visible': False },
                    { 'data': 'series',         'name': 'series',           'label': 'Series',      'className': 'dt-chart-nowrap' }, 
                    { 'data': 'race',           'name': 'race',             'label': 'Race',        'className': 'dt-chart-nowrap'},
                    { 'data': 'miles',          'name': 'miles',            'label': 'Miles',       'className': 'dt-body-center' },
                    { 'data': 'age',            'name': 'age',              'label': 'Age',         'className': 'dt-body-center' },
                    { 'data': 'time',           'name': 'time',             'label': 'Time',        'className': 'dt-body-center' },
                    { 'data': 'pace',           'name': 'pace',             'label': 'Pace',        'className': 'dt-body-center' },
                    { 'data': 'agtime',         'name': 'agtime',           'label': 'AG Time',     'className': 'dt-body-center' },
                    { 'data': 'agpercent',      'name': 'agpercent',        'label': 'AG %age',     'className': 'dt-body-center' },
                ],
                'language' : {
                    'emptyTable': 'no results found for current selection',
                    'zeroRecords': 'no results found for current selection',
                },
                'ordering': True,
                'serverSide': True,
                'order': [0,'asc'],
                'paging': False,
            }

            filterdelay = 500
            yadcf_options = [
                {
                    'column_number':getcol('runnerid'),
                    'filter_container_id':"_rrwebapp_filtername",
                    'filter_type':"select",
                    'select_type': 'select2',
                    'filter_reset_button_text': 'clear',
                },{
                    'column_number':getcol('date'),
                    'filter_container_id':"_rrwebapp_filterdate",
                    'filter_type':'range_date',
                    'date_format':'yyyy-mm-dd',
                    'filter_delay': filterdelay,
                    'filter_reset_button_text': 'all',
                },{
                    'column_number':getcol('miles'),
                    'filter_container_id':"_rrwebapp_filterdistance",
                    'filter_type': 'range_number',
                    'filter_delay': filterdelay,
                    'filter_reset_button_text': 'all',
                },{
                    'column_number':getcol('agpercent'),
                    'filter_container_id':"_rrwebapp_filteragpercent",
                    'filter_type': 'range_number',
                    'filter_delay': filterdelay,
                    'filter_reset_button_text': 'all',
                },{
                    'column_number':getcol('series'),
                    'filter_container_id':"_rrwebapp_filterseries",
                    'filter_reset_button_text': 'all',
                }
            ]

**Comment by vedmack** [comment]
Hi,
Try setting sort_as to 'none'

**Comment by louking** [comment]
That takes care of it, thanks. Sorry I opened issue instead of stackoverflow question -- really thought this was a bug.

**Comment by vedmack** [comment]
no problem, even as a old user of yadcf you should read the docs from time to time :)
yadcf got tons of options and configurations :)

**Comment by louking** [comment]
wonderful package, yes very configurable. really allows me to concentrate on the core of my application. thanks again for producing and supporting this
