### ISSUE TITLE
[Bug] exFilterColumn not working when cells contain brackets

### ISSUE THREAD

**Issue by xirevinian** [vedmack/yadcf#342]
[Using 0.9.0.beta.13 version]

Hello,

First of all thank you for creating such useful tool. I noticed a possible bug using yadcf. It occurs when the  value of given column contains round brackets, i.e. "Verification (In progress)". I've encountered it for following column setup:
`filter_type : "multi_select", filter_match_mode : "exact"`

In such case, when I call external filtering using
`yadcf.exFilterColumn(oTable, [[0, ["Verification (In progress)"]]]);`
regex returns no records as the brackets aren't escaped. It will work after escaping brackets:
`yadcf.exFilterColumn(oTable, [[0, ["Verification \\(In progress\\)"]]]);`

BR,
X.

**Comment by vedmack** [comment]
Hi,
Please provide a link to a test case jsbin/ jsfiddle/ etc

**Comment by xirevinian** [comment]
Hello,

Here you are:

https://jsfiddle.net/beLeux4k/6/

X.

**Comment by vedmack** [comment]
fixed in [0.9.0.beta.26](https://raw.githubusercontent.com/vedmack/yadcf/239f7b7974f024f5a10fb740737f3d667fcf2986/jquery.dataTables.yadcf.js)
