### ISSUE TITLE
fixedHeader setting issue

### ISSUE THREAD

**Issue by wujitouch** [vedmack/yadcf#343]
If the DataTable option fixedHeader is true, the column headers lose focus after every keystroke. I'm guessing this is because the header is destroyed and recreated, but I'm not sure. It works fine if fixedHeader is false. I worked around this by changing the plugin so it only searches when you press "Enter" but it would be nice if live filtering still worked.

**Comment by vedmack** [comment]
Hi

> [As of v3, FixedHeader doesn't display a clone but rather the original element](https://github.com/DataTables/FixedHeader/issues/47#issuecomment-181425851)


So yadcf works with fixedheadrs out of the box, [see showcase (first table)](http://yadcf-showcase.appspot.com/DOM_Ajax_Multiple_1.10.html)


(you have to include fixed header js/css)

related issues
https://github.com/vedmack/yadcf/issues/157
https://github.com/vedmack/yadcf/issues/310

**Comment by wujitouch** [comment]
My bad. I should have done a better job of searching for this issue
