### ISSUE TITLE
Accent neutralise plugin compatibility

### ISSUE THREAD

**Issue by gsanox** [vedmack/yadcf#345]
Hi, first of all thanks for your work, this plugin is amazing!!

The data I load in my aplication is in spanish and the accents are an issue when filtering per column, there is a plugin, accent neutralise that solves this with global search/filtering, this is handy especially when there are gramatical errors in the data, you have to replace characters in the search input as well by applying this:
`$('#myInput').keyup( function () {
        table
          .search(
            jQuery.fn.DataTable.ext.type.search.string( this.value )
          )
          .draw()
      } );`

When I try to add similar code to the yadcf input selector in the column like this:
`$('#yadcf-filter--clients-1').keyup( function () {
        table
          .search(
            jQuery.fn.DataTable.ext.type.search.string( this.value )
          )
          .draw()
      } );`

It doesn't work correctly, because it modifies the global search/filter from datatables and lead to strange behavior.

I would like to know if it is possible to add compatibility for accent neutralise plugin or if there is a way to work around to achieve its functionability.

Thanks in advance

**Comment by vedmack** [comment]
Please provide a test page with relevant data(use your preferred js playground site) and provide a string that I can test with, also provide expected result and actual one.

**Comment by gsanox** [comment]
Hi again vedmack and thanks for your answer, 

The plugin accent neutralise and yadcf together works well, I realize that when I setup the fiddle to show you what the problem was, but for my surprise alltogether work just fine in the playground, so I have to debug my application to find where the problem must be.

I apologize for any inconvinience, I may have caused.

Sincerly

**Comment by vedmack** [comment]
No problem, feel free to post your playground link so other users may use it as a reference.

**Comment by gsanox** [comment]
Playground link: [https://jsfiddle.net/gsanox/j080nybh/](https://jsfiddle.net/gsanox/j080nybh/)
Notes, as you can see in the tests there's a problem searching with accents in the yadcf inputs, so when typing in those inputs we must ignore accents.
