### ISSUE TITLE
Problem with pagination and stateSave

### ISSUE THREAD

**Issue by DiloWagner** [vedmack/yadcf#347]
You can verify at line 3423. I changed the function 
```javascript
   oTable.fnDraw(false);
```
to

```javascript
   oTable.draw(true);
```

I am refresh the page and the pagination keeps.

https://jsfiddle.net/dilowagner/tLuyfghv/

Thank you

**Comment by vedmack** [comment]
Hi,

It works for me with the latest yadcf version, note that I removed your code that modify footer (so the filter will be placed propely) 
https://jsfiddle.net/tLuyfghv/8/

scenario: 
type "t" 
paginate to second page
refresh
result -> show page N#2

**Comment by DiloWagner** [comment]
Ok vedmack,

Thank you for reply!

**Comment by DiloWagner** [comment]
You have prediction to provide this version?
I am using the "bower" to solve the dependence of my libraries

He's generated the error:

bower yadcf#0.9.0                    ENORESTARGET No tag found that was able to satisfy 0.9.0
Additional error details:
Available versions in https://github.com/vedmack/yadcf.git: 0.8.9, 0.8.8, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.0, 0.7.4, 0.7.2, 0.7.0, 0.6.9, 0.6.7, 0.6.4, 0.6.3, 0.6.0, 0.5.8, 0.5.6, 0.5.0, 0.4.7, 0.4.6, 0.4.2, 0.4.0, 0.3.8, 0.3.5, 0.3.3, 0.3.1, 0.3.0

**Comment by vedmack** [comment]
probably in in less than a week.

**Comment by vedmack** [comment]
0.9.0 is out
