### ISSUE TITLE
Bootstrap Datetimepicker Issue when using serverside processing

### ISSUE THREAD

**Issue by dabeedj** [vedmack/yadcf#349]
Hello
Great plugin so far!
The only issue I've got for now is the additional filter fields insertion into datetimepicker
To be more specific - let me show you in steps:
1 On datatable init I open datetimepicker

![image](https://cloud.githubusercontent.com/assets/13512646/18329678/5c9e0c48-755d-11e6-8669-8887116eff90.png)

2 On any 'onchange' event datatables sends ajax request and redraw itself with according data. Now yadcf adds additional fields to datetimepicker as it contains th tags as well as datatable's header/footer. For example you can just hit DEL key, or you may type anything and then backspace, or use arrow key, so onchange event fires.

![image](https://cloud.githubusercontent.com/assets/13512646/18329788/f523e23a-755d-11e6-99e0-f10449e7a451.png)

![image](https://cloud.githubusercontent.com/assets/13512646/18329928/89602a1c-755e-11e6-853a-a782c1b4ff9f.png)

Hope you can help

Thank you for you great work!

Volodymyr

**Comment by dabeedj** [comment]
And here comes my temporary solution. I've just added a direct descendant combinator '>' to your code (Version: 0.9.0.beta.24)

I'm not sure if this destroy something else, but my filters seem to work ok now

![image](https://cloud.githubusercontent.com/assets/13512646/18330429/2ca6dc82-7561-11e6-89cb-4d42ba141993.png)

**Comment by vedmack** [comment]
Please provide a test page in your preferred js playground so I can debug it

**Comment by alecaceaes** [comment]
on 0.9.4.beta.28

![image](https://user-images.githubusercontent.com/16571466/67072958-9eae2480-f1b8-11e9-9842-9838a7da5b33.png)
