### ISSUE TITLE
yadcf fails silently with jquery 3.1.0

### ISSUE THREAD

**Issue by marekpagel** [vedmack/yadcf#350]
When using jQuery 3.1.0, no filterboxes are injected and no error is shown.

When using jQuery 2.2.4, the 'Timestamp' fitlerbox is visible : https://jsfiddle.net/y4zzak2y/

The same code with jQuery 3.1.0: https://jsfiddle.net/y4zzak2y/7/

Other types of filters also fail.

**Comment by vedmack** [comment]
Try with latest yadcf it support jquery 3
