### ISSUE TITLE
Multiple Columns filter using Or instead of And

### ISSUE THREAD

**Issue by cemery-jpe** [vedmack/yadcf#352]
It appears that when you use the initMultipleColumns, the filter performs an AND operation wher it only includes records that have that value in both columns. Is it possible to have it filter using an OR operation where the value is in either column?

The reason I ask is I have a table that has 6 columns that represent Approval Levels that contain the names of a person who can approve at that level. What I want to do is have a single select or multi_select that would allow a person find records which they are an approver at any level. Hopefully, I'm making sense.

BTW, this is a great plugin and you have done an awesome job. 

Thanks!

**Comment by vedmack** [comment]
Hi,

yadcf uses the datatables api and I'm not aware of OR filtering with the dt api, I can think of a way to achieve it, I remeber other users doing it in the following way: use the [multi_select_custom_func](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L31) , and apply your own filtering logic to check for presence in several columns, and as to the position of the filter outside the table you can use the filter_container_id or filter_container_selector (all described in the docs)
