### ISSUE TITLE
Bootstrap Multiselect click issue

### ISSUE THREAD

**Issue by valuco** [vedmack/yadcf#353]
When i use yadcf in combination with the bootstrap multiselect the stopPropagation() is not working.
Every time that the bootstrap dropdown (ul-element) opens after i click the dropdown button the datatable column sorting is triggered.
When i use the default multiselect of chosen select then there a no problems.
I checked the code generated for the select element, but this had the onclick and onmousedown events like on the normal select elements without bootstrap multiselect.

**Comment by vedmack** [comment]
please provide a test page with your preferred js playground site

**Comment by valuco** [comment]
https://jsfiddle.net/3hyzorps/6/ 

When clicking on the select in the first column the ASC/DESC is triggered.

**Comment by vedmack** [comment]
Hi,

There is a special way to apply third party select plugins to yadcf, [see the following jsbin](http://jsfiddle.net/vg6oLvxo/127/) to understand how its done, but for some unknown reason the multi select plugin not being opened on - I can't understand why, I [created another jsbin](http://jsfiddle.net/vg6oLvxo/129/) in which I apply the the multiselect manually (without using the yadcf way) and it seems to work fine, If you will find the reason it does not open when called from yadcf - let me know

**Comment by vedmack** [comment]
Found the reason, need to comment the following in the yadcf code
```

 else if (selectType === 'custom_select') {
            selectElementCustomInitFunc($selectObject);
            //$selectObject.next().attr("onclick", "yadcf.stopPropagation(event);").attr("onmousedown", "yadcf.stopPropagation(event);");
        }
```

but without it muti  select will trigger the sorting of the th, you should contact multiselect author and ask him on how you should solve this,
using the following code does not help either
```

	$filterSelector.multiselect({ onDropdownShow: function(event) {
                yadcf.stopPropagation(event);
            }});
```
