### ISSUE TITLE
Select2 filter search field values disappear when search returns no results. 

### ISSUE THREAD

**Issue by rambor919** [vedmack/yadcf#354]
I have already opened a StackOverflow question for this query, so I will just post a link to the question instead. If you'd prefer, please let me know and I can detail the issue here instead.

http://stackoverflow.com/questions/39374749/select2-filter-values-disappear-when-search-returns-no-results

**Comment by vedmack** [comment]
Hi,

In your SO question you referred to showcase page with autocomplete not being populated with the right data - I have fixed that but I don't think it helps you much, so please provide a link to a test page that reproduces your issue so I can debug/fix it

http://yadcf-showcase.appspot.com/cumulative_filtering.html
