### ISSUE TITLE
yadcf with Angular 2 and chosen not updating table

### ISSUE THREAD

**Issue by chrissena** [vedmack/yadcf#355]
When I try to use yadcf with multiselect on a datatable within an Angular 2 app it works fine. I can change the filter by selecting other options.

However when I apply chosen or select2 and change the filter by selecting another option a request is not sent.

It looks as if something is stopping the change event from firing when a new option is chosen. This means the doFilterMultiSelect(arg, table_selector_jq_friendly, column_number, filter_match_mode) function is not called and the updated filter is not applied.

I have created a plunker with both an angular and non-angular version to demonstrate the issue.

http://plnkr.co/edit/xA3FyZerodIxRxDRJvGt?p=preview

I would be very grateful for any help with this. Or a workaround to get this working.

**Comment by vedmack** [comment]
Hi,

Did you found the reason / solved this?
