### ISSUE TITLE
Filter type multi_select_custom_func causing fail when Datable refreshed

### ISSUE THREAD

**Issue by alieralex** [vedmack/yadcf#359]
I have a column with a custom_func and it appears to be causing the following problem to occur:
In the refresh after i make a server call I get a console message :

jquery.js:3855 Uncaught TypeError: obj.Table is not a function

UPDATE:( this fails for both custom_func and multi.. - also I found that the selector in the oInstance of the settingsDt is not present the second time through. I am using destroy: true on datatable init. I also found that the filterval is not present).

If I change the column filter to just multi_select everything works fine:

It looks like somehow the settingsDt is getting used before completely filled in? Not really sure:

    function generateTableSelectorJQFriendly2(obj) {
        var tmpStr;
        if (obj.oInstance !== undefined && obj.oInstance.selector !== undefined) {
            tmpStr = obj.oInstance.selector;
        } else if (obj.selector !== undefined) {
            tmpStr = obj.selector;
        } else {
	    console.log('getting table selector');
	    console.dir(obj.Table());
            tmpStr = obj.Table().node().id;
        }
        tmpStr = replaceAll(tmpStr, ".", "-");
        tmpStr = replaceAll(tmpStr, ' ', '');
        return tmpStr.replace(":", "-").replace("(", "").replace(")", "").replace("#", "-");
    }

Here is the stack trace.
generateTableSelectorJQFriendly2 @ yadcf:674
(anonymous function) @ yadcf:1219
_fnFilterCustom @ jquery.dataTables.js:4311
_fnFilterComplete @ jquery.dataTables.js:4279
_fnReDraw @ jquery.dataTables.js:3517
_fnInitialise @ jquery.dataTables.js:4708
(anonymous function) @ jquery.dataTables.js:1339
each @ jquery.js:368
each @ jquery.js:157
DataTable @ jquery.dataTables.js:869
$.fn.DataTable @ jquery.dataTables.js:15105
(anonymous function) @ VM909487:424
mightThrow @ jquery.js:3570
process @ jquery.js:3638
setTimeout (async)jQuery.readyException @ jquery.js:3854
(anonymous function) @ jquery.js:3874
mightThrow @ jquery.js:3570
process @ jquery.js:3638
setTimeout (async)(anonymous function) @ jquery.js:3676
fire @ jquery.js:3305
fireWith @ jquery.js:3435
fire @ jquery.js:3443
fire @ jquery.js:3305
fireWith @ jquery.js:3435
process @ jquery.js:3658
setTimeout (async)(anonymous function) @ jquery.js:3676
fire @ jquery.js:3305
add @ jquery.js:3364
(anonymous function) @ jquery.js:3696
Deferred @ jquery.js:3780
then @ jquery.js:3681
jQuery.fn.ready @ jquery.js:3868
(anonymous function) @ VM909487:30
_evaluateScript @ 3_3_3.Finalorg.ajax4jsf.javascript.AjaxScript?rel=1476574686000:81
(anonymous function) @ 3_3_3.Finalorg.ajax4jsf.javascript.AjaxScript?rel=1476574686000:82
setTimeout (async)evalScripts @ 3_3_3.Finalorg.ajax4jsf.javascript.AjaxScript?rel=1476574686000:82
updatePagePart @ 3_3_3.Finalorg.ajax4jsf.javascript.AjaxScript?rel=1476574686000:93
A4J.AJAX.processResponseAfterUpdateHeadElements @ 3_3_3.Finalorg.ajax4jsf.javascript.AjaxScript?rel=1476574686000:131
callback @ 3_3_3.Finalorg.ajax4jsf.javascript.AjaxScript?rel=1476574686000:136
appendNewHeadElements @ 3_3_3.Finalorg.ajax4jsf.javascript.AjaxScript?rel=1476574686000:95
A4J.AJAX.processResponse @ 3_3_3.Finalorg.ajax4jsf.javascript.AjaxScript?rel=1476574686000:136
_request.onreadystatechange @ 3_3_3.Finalorg.ajax4jsf.javascript.AjaxScript?rel=1476574686000:64

And here is my yadcf init:

yadcf.init(openSubmissionsTableVar, [{
        // The indicator column      (COL 6)
        column_number : 6,
        //filter_type: "multi_select",

        filter_type: "multi_select_custom_func",
        custom_func: filterIndicatorUsingAND,
        //select_type: 'chosen',
        //select_type: 'select2',
        //select_type_options: {
            //width: '150px',
            //minimumResultsForSearch: -1 // remove search box
        //},
        column_data_type: "html",
        html_data_type: "text",
        filter_default_label: "All",  
        //filter_default_label: "Select tag",
        filter_reset_button_text: false
    }, {
        // the group name column     (COL 7)
        column_number: 7,
        //filter_type: "multi_select",
        filter_type: "auto_complete",
        column_data_type: "text"
    }, {
        //the policy effective date  (COL 8)
        column_number: 8,
        filter_type: "multi_select",
        filter_default_label: "All",
        filter_reset_button_text: false
    }, {
        // the carrier               (COL 9)
        column_number: 9,
        filter_type: "multi_select",
        //filter_type: "multi_select_custom_func",
        //custom_func: filterCarrier,
        
        //select_type: 'chosen',
        column_data_type: 'text',

        filter_default_label: "All",
        filter_reset_button_text: false,

        exclude: true
    }, {
    // Submission status            (COL 10)
        column_number: 10,
        filter_type: "multi_select",
        filter_default_label: "All",
        filter_reset_button_text: false
        //select_type: 'chosen'
    }, {
        // the coverage type .       (COL 14)
        column_number: 13,
        filter_type: "multi_select",
        filter_default_label: "All",
        filter_reset_button_text: false
        //select_type: 'chosen'
    }, {
        // the Case Advocate.       (COL 15)
        column_number: 14,
        filter_type: "multi_select",
        filter_default_label: "All",
        filter_reset_button_text: false
        //select_type: 'chosen'
    }]

**Comment by vedmack** [comment]
What does `destroy: true` in init do? does yadcf works if you remove that line from your code?

**Comment by alieralex** [comment]
Hi Daniel,

It doesn't seem to have an effect if I comment it out or leave it on. When
I put a breakpoint on Yadcf init in my code though, it doesn't seem to get
called on the rerender. but the afnFiltering function does get called.Only
without the Datatable being fully initialized.  I notice rangeDate and
RangeSlider are the only other filter types that use this. I might try
those and see if they fail too. I am thinking maybe explicitly calling it:

myTable.on( 'init.dt', function () {
        yadcf.init(myTable, [{...}]);});


I will try that and let you know...

Alex Osborne
President
Conexus Inc,
510-592-4578

**Comment by vedmack** [comment]
I would not recommend calling yadcf init that way, can you provide a link to a test case?

**Comment by alieralex** [comment]
That will be hard as this application is embedded in Salesforce. I can't
really duplicate that ajax behavior. I could do a gotomeeting and walk you
through what I have found. Can you suggest a way I could create a test
case? I have never done a jsfiddle or the other ways that people seem to
provide test cases.



Another bug I found is in exGetColumnFilterVal line 4099 in your 0.9.0
release. You had left out the " case 'multi_select_custom_func':"  so
multifunc wasn't working. This fixed it.

Also found that having ampersands embedded in data for autocomplete columns
was causing the filtering not to work. If I made this a text column instead
of autocomplete it did the right thing with ampersands. as a quick
workaround I went into the doFilterAutocomplete and changed the code as
follows:

    function doFilterAutocomplete(arg, table_selector_jq_friendly,
column_number, filter_match_mode) {
        $.fn.dataTableExt.iApiIndex =
oTablesIndex[table_selector_jq_friendly];
        var oTable = oTables[table_selector_jq_friendly],
            column_number_filter,
            settingsDt = getSettingsObjFromTable(oTable);

        column_number_filter = calcColumnNumberFilter(settingsDt,
column_number, table_selector_jq_friendly);

        if (arg === "clear") {
            if (exGetColumnFilterVal(oTable, column_number) === '') {
                return;
            }
            $("#yadcf-filter-" + table_selector_jq_friendly + "-" +
column_number).val("").focus();
            $("#yadcf-filter-" + table_selector_jq_friendly + "-" +
column_number).removeClass("inuse");
            $(document).removeData("#yadcf-filter-" +
table_selector_jq_friendly + "-" + column_number + "_val");
            oTable.fnFilter("", column_number_filter);
            resetIApiIndex();
            return;
        }

        $("#yadcf-filter-" + table_selector_jq_friendly + "-" +
column_number).addClass("inuse");
// FIXME: Workaround for filter matching problem ALEX OSBORNE 10-05-16
var newArgValue = arg.value.replace("&amp", "&");
newArgValue = newArgValue.replace("&;", "&");
arg.value = newArgValue;

        $(document).data("#yadcf-filter-" + table_selector_jq_friendly +
"-" + column_number + "_val", arg.value);

        yadcfMatchFilter(oTable, arg.value, filter_match_mode,
column_number_filter);

        resetIApiIndex();
    }

Sorry for throwing all this extra stuff at you.


Thanks,


Alex Osborne
President
Conexus Inc,
510-592-4578

**Comment by vedmack** [comment]
Here is a very basic jsfiddle setup that using the latest yadcf : https://jsfiddle.net/6c660hat/11/ you can update it with your relevant code that reproduces the issue/s, dont forget to hit the *Update* button so a new fiddle will be created(updated url will be generated)m then post it here with description of "expected" / "actual" behavior
