### ISSUE TITLE
YADCF failing silently - jQuery 3.1.1 / YADCF 0.9.0 / Datatables 1.10.12

### ISSUE THREAD

**Issue by JoeMellon** [vedmack/yadcf#360]
I have no idea or cannot find out why as nothing is logged, the filters just don't get appended to the table silently, yet debugging the initialization everything seems to be in order.

Any clue as to how I can find out what causing this?

Thanks!

**Comment by vedmack** [comment]
Nope, sorry

Here is a very basic jsfiddle setup that using the latest yadcf : jsfiddle.net/6c660hat/11 you can update it with your relevant code that reproduces the issue/s, dont forget to hit the Update button so a new fiddle will be created(updated url will be generated) then post

**Comment by JoeMellon** [comment]
Thanks for the reply, cannot reproduce it using the basic fiddle. I use a custom generation of the column definitions in classes which then get passed into the initialization of the table in typescript. All worked fine until I updated everything to the latest version...maybe I'll have to revert back if I can't catch the errors.

**Comment by vedmack** [comment]
Then try a previous version of yadcf, in addition take a look at the dev tools console for possible errors, without a test case I cant do much

**Comment by JoeMellon** [comment]
http://jsfiddle.net/6c660hat/54/ - managed to get it to fail using all the latest scripts. Although this is failing on Datatable call. Strange...running from my project the datatable initializes fine but no YADCF.

**Comment by vedmack** [comment]
fixed your fiddle, removed older jquery and moved your to the top in resources, continue form here http://jsfiddle.net/6c660hat/55/

**Comment by JoeMellon** [comment]
Thanks for the responses - ok [http://jsfiddle.net/6c660hat/57/] - is this because I'm using the old api?

**Comment by vedmack** [comment]
Yep, I forgot that the jquery 3 support was added for newer yadcf api (.init)

anyway fixed that now in the [0.9.1.beta.6](https://github.com/vedmack/yadcf/blob/ce235345907115ab3760f48eee285e22b0829028/jquery.dataTables.yadcf.js) version, here a [jsfiddle](http://jsfiddle.net/6c660hat/64/)

**Comment by JoeMellon** [comment]
That's great, thanks for providing such a good plugin.
