### ISSUE TITLE
filter_container function?

### ISSUE THREAD

**Issue by jeffblake** [vedmack/yadcf#361]
If I'm rendering multiple data tables of the same kind on the same page, using `filter_container_id` breaks the tables, obviously, and `filter_container_selector` cannot query relative to the current table. It would be good to have a way to target the exact table. Perhaps `filter_container_class` should be implemented instead, and the code to find the element uses jquery's `.closest().finds(...)`

**Comment by vedmack** [comment]
`filter_container_id ` and `filter_container_selector ` are meant to be used outside the table and anyway you should have unique [ids](https://developer.mozilla.org/en/docs/Web/HTML/Global_attributes/id) in your page, as to the `filter_container_selector ` you can modify this [jsfiddle](http://jsfiddle.net/6c660hat/64/) to show your issue.
