### ISSUE TITLE
ColumnDefs render not working with yadcf

### ISSUE THREAD

**Issue by sebbalex** [vedmack/yadcf#364]
Hello,
I'm facing a strange behavior with the plugin:
I have a rendered column with a classic fullname concatenation:
`function ( data, type, full ) { return full.user.firstname + " " + full.user.lastname; }`

according to this [post](https://stackoverflow.com/questions/35872079/yadcf-not-searching-the-value-with-render-colums) I should be able to use the filter by setting the column_data_type: 'rendered_html' property.

This is my setup: 
`        {
            column_number: 4,
            column_data_type: 'rendered_html',
            filter_default_label: 'Seleziona'
        }`

this is the error I get:
jquery.dataTables.yadcf.js:2286 Uncaught TypeError: Cannot read property '4' of null(…)

This is data[j] to that moment: 
0 :Object_aData:
Object _aFilterData :null

NB: I'm using it with cakephp3 framework and [Ypnos' plugin](https://github.com/ypnos-web/cakephp-datatables/)
plugin version: latest (0.9.1)

Thanks

**Comment by vedmack** [comment]
Hi,
Please provide your datatables/yadcf setup code, if it wont be enough you will have to modify the following [test page](https://jsfiddle.net/6c660hat/77/) to reproduce your error

**Comment by sebbalex** [comment]
Hello,
I figured out which is the root cause of my problem!
It is just the [serverSide](https://datatables.net/examples/data_sources/server_side.html) option in datatable that breaks everything.

**Comment by vedmack** [comment]
serverSide does not break stuff, its just that you must implement the filtering logic on your server side

**Comment by sebbalex** [comment]
I got all the filters working (with serverSide on) without using the column rendered, all requests are perfectly managed by the server! Problem appears only when I enable the rendered_html option.

**Comment by vedmack** [comment]
rendered_html and many other options (all that related to filtering behaviour or the client side) are irrelevant when serverside is used

**Comment by sebbalex** [comment]
Understand, is there a way to get things working with serverSider and a merged field on datatable?
Should I modify something on my server side?

**Comment by vedmack** [comment]
your server should be aware of your client side, also - I think that since your data comes from server and filtered on your server side, then the manipulation of the presented data should be done on your server side

**Comment by sebbalex** [comment]
I tried to jsfiddle my [setup](https://jsfiddle.net/sebbalex/hp857z5p/2/)
As you can see in third filter you can only select the lastname, which is the column specified on datatable columnDefs is there a way to specify to yadcf to handle both field together?
Or I just have to use a custom field that doesn't exist on database and handle it in server side?
Thanks

**Comment by vedmack** [comment]
When using `"serverSide": true,` you are doing all the filtering logic on server side only, so the use of the `columnDefs ` is irrelevant to yadcf or to client side filtering, when `"serverSide": true,` is used the entire filtering logic is being done by you on your server side

**Comment by sebbalex** [comment]
Ok, all clear, thanks for support and patience.

**Comment by vedmack** [comment]
example of such server side (jave) filtering can be seen in the [yadcf showcase source code on github](https://github.com/vedmack/yadcf-showcase/blob/master/src/dr/yadcf/servlets/EntrysTableServerSideSource.java)
