### ISSUE TITLE
pass arguments to jquery-ui datepicker

### ISSUE THREAD

**Issue by h0dges** [vedmack/yadcf#365]
I would like to be able to set, from within my script, various datepicker options as documented here: https://jqueryui.com/datepicker/

The most useful options would be 'button bar' and 'month & year menus':

` $( "#datepicker" ).datepicker({
      showButtonPanel: true,
      changeMonth: true,
      changeYear: true
    });`

**Comment by vedmack** [comment]
Just use the [filter_plugin_options](https://github.com/vedmack/yadcf/blob/d5dba790602738a234d4629596b1005c1d9fab56/src/jquery.dataTables.yadcf.js#L222) it works also for jquery-ui datepicker (need to update docs)

**Comment by h0dges** [comment]
```
yadcf.init(table, [{column_number : 2,
                            filter_type: "range_date",
                            date_format:  'dd/mm/yyyy',
                            datepicker_type: 'jquery-ui',
                            filter_container_id: 'dateFilter',
                            filter_plugin_options: '{changeMonth: true, changeYear: true}'}]);
```

The above has no effect (i.e. no select boxes for month/year). Is the syntax correct?

**Comment by vedmack** [comment]
then please provide a working jsfiddle / jsbin sample, [use this as a starting point](https://jsfiddle.net/6c660hat/78/)

**Comment by h0dges** [comment]
https://jsfiddle.net/h0dges/7wyjynj5/

**Comment by vedmack** [comment]
You gave the property a string (docs says object) that why it didn't work , see this sample https://jsfiddle.net/7wyjynj5/1/
