### ISSUE TITLE
DOM_Ajax_Multiple_1.10

### ISSUE THREAD

**Issue by ajjujaiswal** [vedmack/yadcf#367]
Hi,

I am using DOM_Ajax_Multiple_1.10. I don't want to Search, Show entries, pagination and entry count below. How to remove it. Please suggest asap
![datatable](https://cloud.githubusercontent.com/assets/6695880/20511938/45370cc8-b0a2-11e6-8381-c7cb421d6b80.JPG)

**Comment by vedmack** [comment]
You should ask your Q in the [datatables forum](https://datatables.net/forums/)

This repo/issues are related to yadcf plugin only (for bug/new features request only)
