### ISSUE TITLE
Would it be possible to have typings of yadcf?

### ISSUE THREAD

**Issue by aloisdg** [vedmack/yadcf#368]
Hello,

We are looking to use yadcf, in a TypeScript project. It would be handy to have typings.
Does anyone made some? It would be a nice feature to have.

see :

- https://github.com/DefinitelyTyped/DefinitelyTyped

Cheers,

**Comment by vedmack** [comment]
Hi,

Its possible, feel free to guide me on how (a short good tutorial) or even better a PR will be welcomed

**Comment by aloisdg** [comment]
I may look into it, but we use it without. If they give the budget I will create the typings. Fo now, I dont know. :)

**Comment by DaveyJake** [comment]
Here's a preliminary Typed definition of `YADCF`: https://gist.github.com/DaveyJake/a7009c82ed3f4fbd278b814d62009631
