### ISSUE TITLE
The processing message/loading indicator not appearing while doing filtering

### ISSUE THREAD

**Issue by saravan23** [vedmack/yadcf#370]
I've more than 120,000 records in the datatables. Whenever i apply filters the processing message was not showing up. However, this is appearing when i apply sorting.

Any pointers would be highly appreciated on this.

**Comment by vedmack** [comment]
Hi,

Its not related to the yadcf plugin, I suggest you try playing with the [language](https://datatables.net/reference/option/language) especially the 'processing' key, see how it can be used [here](https://datatables.net/examples/basic_init/language.html)
