### ISSUE TITLE
(multi_)select with chosen has no options with serverside data

### ISSUE THREAD

**Issue by tdamsma** [vedmack/yadcf#374]
Somehow the search options are not passed to the chosen widget when using server side rendering, and passing the options via `yadcf_data_n`

**Comment by vedmack** [comment]
fixed in [0.9.2.beta.3](https://github.com/vedmack/yadcf/blob/a30566e68c7330c0b3e414d170e9c9182d4c02ed/src/jquery.dataTables.yadcf.js)

**Comment by tdamsma** [comment]
great, i'll switch to the unreleased version then.
