### ISSUE TITLE
After refresh its goes to first page if filter is applied on any column

### ISSUE THREAD

**Issue by jatinhs** [vedmack/yadcf#378]
Thanks for the great extension.

I have 1000 of records and i am showing using the Datatable(latest version) and using YADCF(latest version) for filtering. 
I am using the server side processing, so it will call Ajax request each time and display data.
State save is also **ON**.
On each page i am displaying 50 records.

**My Problem:** (assume there are 20 pages - on each page its displaying 50 records)
Steps: 
1) Applied filter on one column. Its working fine and give me 200 records that match with filter.
2) I navigate to 3rd page.
3) Now i refresh page. When the page load, its gives me the filtered data but its navigate to page 1 instead of page 3 (before refresh i was on page 3)

Can you help how to remain on same page with filtered data even i refresh the page.

Thank You.

**Comment by vedmack** [comment]
do the following test: 
1)use the global filter of the table (upper right) 
2)navigate to 3rd page
3) refresh

if it navigate to page 1 then you are "not telling to your datatables" something important (to which page it should go) and its not related to yadcf
