### ISSUE TITLE
YADCF + Server Side yadcf_data output .. howto 

### ISSUE THREAD

**Issue by bledarshehu** [vedmack/yadcf#379]
Hey there to all

I literally have searched Every Single Page that mentions the argument, but cant seem to figure this one out 
I am using datatables with yadcf , ajax source, server_side.php and ssp.class.php

Now i want to populate the select filters with All the data, not just the current page,
I read and saw the showcase that the only mention is a JQuery (java) part to populate the yadcf_data_n 
But cant find one single example to do the same using the server_side.php and ssp.class.php to retrieve the data.

I (and from what i saw around a lot of other people) would be really great full to have a piratical example on how to archive this

Thanks in advance for your time

**Comment by vedmack** [comment]
Hi,
Try looking into the following thread or search github for php code related to yadcf and let me know if you found something useful.

**Comment by bledarshehu** [comment]
Hey there 

I looked at those topics, even before, and i tried all kind of search combinations through google till the last found result but nothing,

@vedmack I know your time is really limited but if you point me in the right directions i will post back a working example for others in the future since a this point you are my only hope at actually archiving this

**Comment by vedmack** [comment]
Hi,

Here is some code that I hoe will help you a bit

There is a little modification to the demo `server_processing.php` script. Instead of using:

	echo json_encode(
		SSP::simple( $_GET, $sql_details, $table, $primaryKey, $columns )
	);

What could be done is:

	$data = SSP::simple( $_GET, $sql_details, $table, $primaryKey, $columns );

	// Get values
	$stmt = $db->prepare( 'SELECT first_name FROM datatables_demo' );
	$stmt->execute();
	$data['yadcf_data_0'] = $stmt->fetchAll();

	echo json_encode( $data );

That will add a `yadcf_data_0` property to the JSON returned by the server and will contain the information from the SELECT statement (which can be easily modified to suit the formatted needs of YADCF and also the query that the users need).

Additional queries could likewise be added as required.

**Comment by bledarshehu** [comment]
Thanks for the perfect solution 

I posted my reply at my stackex.. question for anyone else in need 

http://stackoverflow.com/questions/41507443/yadcf-datatables-server-side-populate-select-with-php

**Comment by vedmack** [comment]
Great
