### ISSUE TITLE
Server side processing with chosen multiselect wouldn't filter

### ISSUE THREAD

**Issue by tjackadams** [vedmack/yadcf#381]
I am using yadcf version 0.9.2.beta.3 with the chosen multiselect plugin.

Essentially if i provided the filter data from the server, the multiselect would populate fine, however when i actually selected a filter option, it would not trigger the column filter in the datatable.

this is the error produced in the console.

`jquery.dataTables.yadcf.js:2487 Uncaught TypeError: Cannot read property 'length' of null
    at appendFilters (jquery.dataTables.yadcf.js:2487)
    at HTMLTableElement.<anonymous> (jquery.dataTables.yadcf.js:3539)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:3)
    at HTMLTableElement.<anonymous> (jquery.min.js:3)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at n.fn.init.trigger (jquery.min.js:3)
    at u (datatables.min.js:127)`

i have managed to resolve this issue by adding a null check on line 2485 as follows

`                    if (typeof (data) !== 'undefined') {
                        if (data !== null) {
                            for (ii = 0; ii < data.length; ii++) {
                                column_data.push(data[ii]);
                            }
                        }                      
                    }`

Now all the filtering works as expected.

**Comment by vedmack** [comment]
can you replicate this? you can use this [test page](http://live.datatables.net/dotoduju/4/edit)

**Comment by tjackadams** [comment]
@vedmack i'm just trying to replicate this now in the jsbin. Are you aware of anyway to provide a custom server_processing script to the jsbin?

I need to provide the filter data from the server side and i can't see a way to do this from the jsbin.

also just to clarify, when i manually provided the filter data as below, it would work fine.

``` 
 yadcf.init(table, [
            {
                column_number : 0,
              data: [{value: 'Ashton', label: 'Ashton'}],
              filter_container_id: 'ResourceFilter',
              filter_default_label: 'Select Resource',
                filter_type: "multi_select",
              filter_reset_button_text: false,
                select_type: 'chosen'
            }
 
  ]);
```

it was only when 'yadcf_data_x' was provided in the response that the issue occurred. Also just to clarify, providing the server side filtering has been working fine for the other types such as text/date, its only been on the multi-select/chosen combination that this happened.

**Comment by vedmack** [comment]
I have tested serverSide with multi select chosen and it all works fine for me, try using latest beta (0.9.2.beta.6)
