### ISSUE TITLE
cumulative_filtering and html_data_type:"rendered_html" seems not work

### ISSUE THREAD

**Issue by gmeriaux** [vedmack/yadcf#382]
Hello,
first of all, thank you for your work, it is a very good feature for datatable.

I am experiencing a problem to use "select" filter type with rendered cell. Finally, I notice it come from the option cumulative_filtering. yadcf don't succeeded to populate my select with options from my rendered cell. 

When I go in source code, I find the source of the problem : 
In the function parseTableColumn, for column_data_type === "rendered_html", you are using _aFilterData but this data aren't generated in the function getFilteredRows ( you generate only _aData). Have you got a simple solution to patch this part of source code?

Other small comment, in the function dot2obj, sometimes, nested object can be undefined. To avoid crash, I think you should replace
`for (i = 0; i < dot_refs.length; i++) {
				tmpObj = tmpObj[dot_refs[i]];
			}`
by
`for (i = 0; i < dot_refs.length; i++) {
				tmpObj = tmpObj && tmpObj[dot_refs[i]];
			}`

**Comment by vedmack** [comment]
Hi,
Thanks for the feedback, please provide a jsfiddle to show the described above issue so I can fix them

**Comment by gmeriaux** [comment]
Here is an example : [http://jsfiddle.net/wb7d6mac/](http://jsfiddle.net/wb7d6mac/).
If you don't remove {cumulative_filtering: true} at the end of js, you should get the error : 

> Uncaught TypeError: Cannot read property '2' of undefined
>     at parseTableColumn (jquery.dataTables.yadcf.js:2286)

**Comment by maig81** [comment]
Hi, 
I have the same issue regarding cumulative filtering and rendered_html. Is there a fix?
Thanks

**Comment by vedmack** [comment]
added `column_data_render' , see [usage in jsfiddle test page](http://jsfiddle.net/vedmack/o3c9r2f5/17/)

IMO is a reasonable solution, open to suggestion to make it even better...

provide yadcf with a function that will help it to know what is "text" that is present in the cell, for example (relevant for the jsfiddle test page above

    {
      column_number: 2,
      column_data_type: "rendered_html",
      column_data_render: function (data) {return data.sim.name || ('id ' + data.sim.id)}
    },

**Comment by vedmack** [comment]
@maig81 yep you are right 😁
