### ISSUE TITLE
Select2 Multi-select - Error  Cannot read property 'query' of null

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#384]
I'm having an issue 
To reproduce:  http://jsfiddle.net/lenamtl/epagqe6s/7/
open Chrome dev tool 
Let say I select one value **Value 1** when I clear using the Select2 tag X to clear the selected item 
I'm having this error message:
```
select2.full.min.js:2 Uncaught TypeError: Cannot read property 'query' of null
    at e.<anonymous> (select2.full.min.js:2)
    at e.d.invoke (select2.full.min.js:1)
    at e.d.trigger (select2.full.min.js:1)
    at e.trigger (select2.full.min.js:2)
    at e.open (select2.full.min.js:2)
    at e.toggleDropdown (select2.full.min.js:2)
    at d.<anonymous> (select2.full.min.js:2)
    at d.invoke (select2.full.min.js:1)
    at d.trigger (select2.full.min.js:1)
    at HTMLSpanElement.<anonymous> (select2.full.min.js:1)
```

PS I also have this error when not using empty value
```
data: [''],
append_data_to_table_data: 'before',
filter_match_mode: 'exact',
```
This is also happening when clearing all selected data using clear all X of Select2

This is also happening on the demo page 
http://yadcf-showcase.appspot.com/DOM_source_select2.html

**Comment by vedmack** [comment]
You (and showcase) are using old yadcf, please use the latest version from repository/src folder, [see working jsfiddle](http://jsfiddle.net/epagqe6s/9/)

**Comment by lenamtl** [comment]
ok thanks

**Comment by lephleg** [comment]
@vedmack 
I'm using Select2 v4.0.3 full build with the latest version on the yadcf and I'm getting this error on clear. 
Could you please confirm?

**Comment by vedmack** [comment]
@lephleg please try with the latest yadcf beta ([0.9.2.beta.6](https://raw.githubusercontent.com/vedmack/yadcf/6558c50be09cf9582a7493d913dde4ad4e9ef01a/src/jquery.dataTables.yadcf.js))

**Comment by lephleg** [comment]
@vedmack I can confirm that your beta version solves the issue! Thanks for the instant reply!
Will it be stable soon in the near future? I'll need to push this update to production.

**Comment by vedmack** [comment]
current beta is very stable (its more stable than the 0.9.1 final)
