### ISSUE TITLE
Extenal filter problems when columns is not displayed

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#386]
Hi,

I have 1 table that show different columns based on configuration and user role.
I'm using PHP to hide columns and filters.
The data is from the DOM.

I have 2 problems with filters:

1- If the page is not showing a filter to some users
I'm having this container error :
ERROR: Filter container could not be found, columnObj.filter_container_selector: #external_2 

2- If the column number does not exist, let say I have a filter on column 11 and I show only 6 columns in some cases
I'm having this error : 
jquery.dataTables.yadcf.js:2421 Uncaught TypeError: Cannot read property 'mData' of undefined

I have tried to show different table VAR, but if the table var is not displayed it will be not found and I will also get an error.... so I don't know what to do...

Any solution is welcome

**Comment by vedmack** [comment]
Hi

Its a question and it should be asked on [stackoveflow](http://stackoverflow.com/questions/tagged/yadcf)

**Comment by vedmack** [comment]
You should write your code so you want try to init yadcf for columns that are not actually exist (check it with jquery for example) or make sure you don't point yadcf to container that does not exist
