### ISSUE TITLE
Multiple external_filter_container is creating duplicates

### ISSUE THREAD

**Issue by FANMixco** [vedmack/yadcf#387]
Hi, thanks for this great plugin! However, I found this strange issue if I add another external filter, it starts creating multiple clones without stop:

```
$(document).ready(function(){
  $('#example').dataTable().yadcf([
		{column_number : 0},
	    {column_number : 1,  filter_type: "range_number_slider", filter_container_id: "external_filter_container"},
	    {column_number : 2, data: ["Yes", "No"], filter_default_label: "Select Yes/No"},
	    {column_number : 3, text_data_delimiter: ",", filter_type: "auto_complete"},
	    {column_number : 4, column_data_type: "html", html_data_type: "text", filter_default_label: "Select tag", filter_container_id: "external_filter_container"}]);
});
```

You can see the example of what is happening here:
[http://pasteboard.co/wfyxfiCVQ.png](http://pasteboard.co/wfyxfiCVQ.png)

Here is the jsfiddle example:
[https://jsfiddle.net/tmke0xa7/](https://jsfiddle.net/tmke0xa7/)

Thanks again!

**Comment by vedmack** [comment]
Hi,

You have to provide separate external filter container for each external filter (while you used the same container for several filters)

[see working jsfiddle](https://jsfiddle.net/vedmack/tmke0xa7/2/)

p.s

Next time please post question on stackoverflow
