### ISSUE TITLE
Select2 multiple select in fixedColumns not showing options

### ISSUE THREAD

**Issue by apfz** [vedmack/yadcf#388]
When I load select2 in a column that is fixed (through fixedColumns) the input box is shown but no options. The underlying select2 however (below the fixedColumns) does have the options and behaves as expected.

The corresponding select-element of the select2 widget in the fixed column does however have all the options. 

Is this a bug?

**Comment by vedmack** [comment]
At the moment there is no support with fixed columns because of luck of an API to integrate with (yadcf does support fixedHeaders)
