### ISSUE TITLE
Select filter not showing all the results

### ISSUE THREAD

**Issue by thalesmiguel** [vedmack/yadcf#393]
Hello.
First of all, this is a awesome plugin!

I have this datatables with a lot of data and, when I try to filter it with a select filter, not all data is shown:
![1](https://cloud.githubusercontent.com/assets/1305223/23922300/959256dc-08e0-11e7-86f6-ac5f224c3dc3.png)

It only shows values that are currently being shown on the datatables:
![2](https://cloud.githubusercontent.com/assets/1305223/23922306/983dde6a-08e0-11e7-8d11-574148a60ad5.png)

Is that the default behavior?
Is there a way to show all the values so I can filter this datatables correctly?

Thanks in advance.

**Comment by vedmack** [comment]
You probably using server side setup but not providing the needed data to yadcf filters (from the server) you should do some googling/read docs/read on the server side page on showcase, in cade additional​ question will rise - use stackoverflow to ask a q'
