### ISSUE TITLE
Chosen + rendered_html not  working

### ISSUE THREAD

**Issue by BCaldas** [vedmack/yadcf#394]
I have this code to render my column:

```
columns: [

            {
                data: null,
                render: function(data) {
                    return colunaCodigo(data.idOrdemServico,data.codigo, data.pdf, data.dwg)
                }},
            {
```

and that's my function colunaCodigo: 

```
function colunaCodigo(idOs,cod,pdf){

    var codigo = '<a href="'+SERVICEORDER_URL+'/'+idOs+'" class="col-codigo">' + cod + '</a>';
    var arquivoPdf = '';

    if (!pdf) {
        arquivoPdf =  '<br>' + '<div class="btn-vert"><a id="anexarPdf" class="anexar" title="Anexar PDF" href="#" data-id='+idOs+'>' +
            '<i class="fa fa-file-pdf-o fa-2x"><sup><i class="fa fa-plus"></i></sup></i></a></div>';
    } else {
        arquivoPdf = '<div class="btn-vert"><a title="Visualizar PDF" href="'+pdf+'" target="_blank" data-id='+idOs+'>' +
            '<i class="fa fa-file-pdf-o fa-2x"></i></a>' +

            '<a title="Atualizar PDF" id="anexarPdf" class="btn-hori anexar" href="#" data-id='+idOs+'>' +
            '<i class="fa fa-refresh"></i>'+
            '</span></a></div>';
    }

    return codigo + arquivoPdf;
}
```

now my yadcf: 

```
yadcf.init(table, [
        {
            column_number: 0,
            select_type: 'chosen',
            column_data_type: 'rendered_html'
        }
```

It's just not working. But works fine with default select. Somebody can help me?

**Comment by louking** [comment]
are the arguments to colunaCodigo from render in correct order? Seems like pdf is 3rd parameter in the function definition but 2nd when you're calling it

**Comment by BCaldas** [comment]
return colunaCodigo(data.idOrdemServico, data.codigo, data.pdf, data.dwg)

see? is the 3rd when i call too. Ignore the "data.dwg" parameter, was wrong, still not working.

**Comment by BCaldas** [comment]
How i said, with default select, it works fine, but i need the chosen multi select

**Comment by louking** [comment]
Ha, sorry I misread. I think the spacing fooled my eyes. Carry on.

**Comment by vedmack** [comment]
Please provide a simple jsfiddle sample page

**Comment by BCaldas** [comment]
Well, i could paste my cod in jssfiddle, but the table just cant' populate (via ajax). here a pic with the default select working and chosen not. Follow:

https://jsfiddle.net/L64v7teq/2/

![default](https://cloud.githubusercontent.com/assets/8901028/24181299/e224256c-0e98-11e7-8e40-93e40dad8913.png)

![default](https://cloud.githubusercontent.com/assets/8901028/24181356/48972826-0e99-11e7-95d3-084fa31fc50c.png)

**Comment by vedmack** [comment]
you will have to provide a working jsfiddle page, no need with over complicated example , one column rendered html and chosen will be fine
