### ISSUE TITLE
Using with DateRangePicker for ranges

### ISSUE THREAD

**Issue by Sherman2k2** [vedmack/yadcf#395]
Any thought on adding bootstrap-daterangepicker as an option to replace the "to" and "from" fields?

Would provide a single field to select ranges or pre-defined selections instead of having the "to" and "from" fields.

**Comment by vedmack** [comment]
For "pre-defined selections" you can use the `filter_type: 'custom_func'`, see sample in [showcase ](http://yadcf-showcase.appspot.com/DOM_source.html)
