### ISSUE TITLE
Keep filter after refresh

### ISSUE THREAD

**Issue by Nassim91** [vedmack/yadcf#396]
Hi,

Do you know if it's possible to keep the filters after a refresh. Like this topic : 

http://stackoverflow.com/questions/37030451/jquery-datatable-retain-filter-parameter-after-refresh

**Comment by vedmack** [comment]
Hi,

Use `stateSave: true` , read more in the [dt docs](https://datatables.net/reference/option/stateSave)m yadcf supports this out of the box
