### ISSUE TITLE
How to set default value 

### ISSUE THREAD

**Issue by Nassim91** [vedmack/yadcf#397]
Hi, 

Sorry but i didn't find how to set 2 defaults values in the same column for multi-select type. 

Thank you

**Comment by vedmack** [comment]
You can use [yadcf.exFilterColumn(oTable, [[0, ['Some Data 1','Some Data 2']]]); // for pre filtering multi select filter you should use array with values (or an array with single value)](https://github.com/vedmack/yadcf/blob/6558c50be09cf9582a7493d913dde4ad4e9ef01a/src/jquery.dataTables.yadcf.js#L323) , read more in the docs.

next time please use stackoverflow for asking questions (github for bugs/features request only)

**Comment by Nassim91** [comment]
I'm Sorry,
 do you have a specific stackoverflow ?

**Comment by vedmack** [comment]
post you question on [http://stackoverflow.com/questions/tagged/yadcf](http://stackoverflow.com/questions/tagged/yadcf) and tag it with yadcf and since i'm subscribed to yadcf tag I will be notified about new questions
