### ISSUE TITLE
multi_select with select2 type is visible but filtering not working

### ISSUE THREAD

**Issue by siick** [vedmack/yadcf#398]
Hello and first thanks for your work!
Your plugin is exactly what i need for my datatables but i've got some problem to make it work.
I've got my multiple select filter present with all values (and also the basic select) but when i select a value, i've got no row returned... My datatables is empty. When i delete the filter, i've got my table back with all data. It seems i can't get filters work in a proper way.
Data are coming from a BDD not by ajax request, just by a simple php request. Searching from the Datatables search is OK, just filtering with your select is not.

I've got no error in console when i used basic select and when i use multi-select without select2 i've got no error too .
But when i use multi-select and select2 i've got : 
`select2.js:241 Uncaught TypeError: Cannot read property '0' of null`

I give you my JS code in case and if you need it i can make an example html page of my problem.
`<script type="text/javascript">
	$(document).ready(function() {
    // Met la recherche dans chaque colonne en bas
    $('#table_projet tfoot th').each( function () {
        var title = $(this).text();
        $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
    } );
 	
    // Ajout des boutons pour PDF Excel et la sélection multiple des lignes du tableau
    // avec prise en compte de la sélection pour l'export
    var table = $('#table_projet').DataTable({
	    "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "Tout"]],
	    dom: 'lBfrtip',
	   	select: 'multi',
	    responsive: true,
	    altEditor: true,      
	    fixedHeader: true,
	    buttons: [
		    {
		      	extend: 'colvis',
		      	text: 'Colonnes à afficher'
			},
		    'selectAll',
	        'selectNone',
	    	{
	    		extend: 'copy',
	    		text: 'Copier',
	    		exportOptions: {
	    			modifier: {
	    				selected: true
	    			}
	    		}
	    	},
	    	{
	    		extend: 'excel',
	    		exportOptions: {
	    			modifier: {
	    				selected: true
	    			}
	    		}
	    	},
	    	{
	    		extend: 'pdf',
	    		exportOptions: {
	    			modifier: {
	    				selected: true
	    			}
	    		}
	    	},
	    	{
                text: 'Ajouter',
                action: function ( e, dt, node, config ) {
                    document.location.href='creer_projet.php';
                }
            },
	    	{
		      	extend: 'selected',
		      	text: 'Supprimer',
		      	name: 'delete'      // NE PAS CHANGER LE NOM !!!!!!
		   	},
	    ],
	    language: {
	        buttons: {
	            selectAll: "Tout sélectionner",
	            selectNone: "Tout désélectionner"
	        }
	    },
	    "columnDefs": [
            {
                "targets": [ 0 ],
                "visible": false,
                "searchable": false
            }
        ]
	});

	yadcf.init(table, [{
		column_number: 0
	}, {
		column_number: 1
	}, {
		column_number: 2
	}, {
		column_number: 3
	}, {
		column_number: 4
	}, {
		column_number: 5,
		filter_type: "multi_select",
		select_type: 'select2'
	}, {
		column_number: 6,
		filter_type: "multi_select",
		select_type: 'select2'
	}, {
		column_number: 7
	},{
		column_number: 8
	}, {
		column_number: 9
	}, {
		column_number: 10
	}, {
		column_number: 11,
		filter_type: "multi_select",
		select_type: 'select2'
	}, {
		column_number: 12,
		filter_type: "multi_select",
		select_type: 'select2'
	}, {
		column_number: 13,
		filter_type: "multi_select",
		select_type: 'select2'
	}, {
		column_number: 14
	}])
 
    // Pour la recherche
    table.columns().every( function () {
        var that = this;
 
        $( 'input', this.footer() ).on( 'keyup change', function () {
            if ( that.search() !== this.value ) {
                that
                    .search( this.value )
                    .draw();
            }
        } );
    } );
} );
</script>`
I have surely missed something but i can't find it by myself....
Thanks in advance for your future answer.

**Comment by vedmack** [comment]
please post questions on stackoverflow  (tagged with yadcf) http://stackoverflow.com/questions/tagged/yadcf , as to this specific Q' you must simplify your use case, narrow your table to 1 or two columns, also know that you must read on your server side `columns[0][search][value]` / `columns[1][search][value]` . etc... and you must perform serach based on those values and return the relevant rows back to client
