### ISSUE TITLE
Need minDate, maxDate support please

### ISSUE THREAD

**Issue by momon** [vedmack/yadcf#399]
I have noticed that when using the range_date filter I can't specify a minData and a maxDate for the form fields.   In my case scenario it would ideally do it automatically based on the dates available in the table but that isn't the case.

I have temporarily enforced them by using:

```
$("#yadcf-filter--setstable-from-date-0").datepicker( "option", { minDate: "01/01/2017", maxDate: "31/01/2017"} );
$("#yadcf-filter--setstable-to-date-0").datepicker( "option", { minDate: "01/01/2017", maxDate: "31/01/2017"} );
```

This works on page load but as soon as the filter is cleared there appears to be a "reset" function that dismisses my hardcoded values.

So I'm not sure if my use scenario here is too custom but could probably be resolved by allowing to input custom minDate and maxDate on the jquery datepicker or alternatively automatically assume minDate and maxDate based on the dates in the table (which makes total sense to me).

**Comment by vedmack** [comment]
You should use [filter_plugin_options](https://github.com/vedmack/yadcf/blob/6558c50be09cf9582a7493d913dde4ad4e9ef01a/src/jquery.dataTables.yadcf.js#L222) (read docs) you can feed it with any options you like and it will be passed "as is" to your third party plugin, for example `filter_plugin_options: {minDate: '...', maxDate: '...'}` .

Next time please ask questions on stackoverflow and tag with yadcf

**Comment by momon** [comment]
Thank you and I apologize for not seeing that before.  However, after testing it, it appears to have the same bug as my own implementation (which I've since removed).  After setting the entries the first time and clearing them out (reset), the start date defaults back to "today's" date which based on my settings shouldn't even be an option.

So to put it into a visual, the first time I click on the date fields, it show's my date limits fine.  After resetting it, if I go back to select a start date again, the start date field defaults to today's date which is outside of my minDate and maxDate range.  So I feel there is still some sort of bug with the reset operation.

**Comment by vedmack** [comment]
Ok, please provide a minimal test case (jsfiddle / etc)  so i can reproduce
and fix it

**Comment by momon** [comment]
Sure thing, here is the example:

https://jsfiddle.net/6n7bn2tx/

You can see when you try to select the date the first time, the range is limited (as it should) but as soon as you click the "reset" button it seems to dismiss the range and defaults the picker to "today's" date.

Please note I didn't give the example much attention other than making sure it had a date range to play with.

**Comment by vedmack** [comment]
@momon , take a look at the [following jsfiddle page](https://jsfiddle.net/vedmack/6n7bn2tx/8/) it uses the newest yadcf beta (in resources), see if solves your issue and let me know

**Comment by momon** [comment]
@vedmack that example does seem to be behaving as expected so looks like it's been fixed in the beta already.

Thanks!

**Comment by vedmack** [comment]
@momon please [use the yadcf beta 0.9.2.beta.8](https://github.com/vedmack/yadcf/blob/83901377a249df01714fc01bd10bddccc5062161/src/jquery.dataTables.yadcf.js) in case of any issue let me know
