### ISSUE TITLE
Filter type select set options key value pair

### ISSUE THREAD

**Issue by irfanjvd** [vedmack/yadcf#400]
Hi,

Is there any way in yadcf that i can set select filter options in key value pair

Thanks

**Comment by vedmack** [comment]
Question should be asked on stackoverflow and tagged with yadcf - http://stackoverflow.com/questions/tagged/yadcf , that way more people
will be able to help you and your questions will be easier to find for others

Use github for bug reports or new features request only

In case of bug always post a code sample that resembles your issue or event better provide a link to your page
