### ISSUE TITLE
Init on dynamically created table

### ISSUE THREAD

**Issue by dspanic** [vedmack/yadcf#401]
In version 0.9.0 instance.selector in init stays empty and filter does not init on dynamically added table.

Reason is this line:
if (instance.selector === undefined) {
            instance.selector = tableSelector;
        }
because in this case instance.selector is not undefined but empty which skips setting tableSelector to instance.selector thus not initializing the filter.

**Comment by vedmack** [comment]
If you are using the `init` function then grab the latest beta version because it was fixed there
