### ISSUE TITLE
server side working but only detect current page

### ISSUE THREAD

**Issue by Pawlarius** [vedmack/yadcf#402]
I am using Rails and gem ajax-datatables-rails for this.
Filtering work fine, but there is some bug(?), at first, it will show all options.( in this case only 2 options)
![screen shot 2017-04-26 at 9 19 46 pm](https://cloud.githubusercontent.com/assets/27823957/25439290/3fbe5690-2ac6-11e7-9373-610276e0a86a.png)

After i  choose filtering, and click again, it only show my options.
![screen shot 2017-04-26 at 9 19 54 pm](https://cloud.githubusercontent.com/assets/27823957/25439353/6d9f35b6-2ac6-11e7-8660-ca40977e64fa.png)

Only after i choose "Select Value" again then it will show all options again.. how to fix this?

**Comment by Pawlarius** [comment]
okay my mistake, after adding some data, i found out it only show 2 options because it only check current datatable's page. somehow it cant detect all data from the datatables ajax..

**Comment by Pawlarius** [comment]
![screen shot 2017-04-26 at 10 15 22 pm](https://cloud.githubusercontent.com/assets/27823957/25441952/e19653b2-2acd-11e7-8ca0-145ee18ecf1e.png)
here's my datatable & yadcf init, i checked http://yadcf-showcase.appspot.com/DOM_Ajax_Multiple_1.10.html too..

pls help @vedmack

**Comment by vedmack** [comment]
Its not a bug but rather a question, In addition to your returned data from server you must return additional data for yadcf filters , yadcf_data_0 / yadcf_data_1 / yadcf_data_2 / ... read in docs (yadcf js file) and see showcase server side sample page, in addition [see this Q/A on SO](http://stackoverflow.com/questions/41507443/yadcf-datatables-server-side-populate-select-with-php)
