### ISSUE TITLE
AutoComplete - yadcf

### ISSUE THREAD

**Issue by kvickery** [vedmack/yadcf#403]
In the older examples of the AutoComplete filter, as soon as you typed in a letter the filtering was applied reducing the numbers of rows shown.  For example, if I typed the letter "x", only rows with that column containing the letter "x" would be displayed.

{ column_number : 1, filter_type: "auto_complete" },

In the newer examples, the AutoComplete filter does not do this.  I want the original functionality for my web page - how do I achieve this?  Is there an option I need to pass to the AutoComplete plugin via the filter_plugin_options parameter?  Or is there a different filter I should be using? 

yadcf - http://stackoverflow.com/questions/tagged/yadcf

**Comment by vedmack** [comment]
[Asking on SO is good enough :)](http://stackoverflow.com/questions/43645022/yadcf-autocomplete-not-working-as-in-original-examples)
