### ISSUE TITLE
Filter does not work when columns hidden per Buttons API

### ISSUE THREAD

**Issue by hrrhrst** [vedmack/yadcf#406]
It seems the PugIn is not capable of applying filters when some columns are hidden via Button API.
It seems to appear more often when you hide columns and then reorder some other columns.

jquery.dataTables.yadcf.js:654 Uncaught TypeError: Cannot read property 'length' of undefined
    at escapeRegExpInArray (jquery.dataTables.yadcf.js:654)
    at yadcfMatchFilterString (jquery.dataTables.yadcf.js:775)
    at exFilterColumn (jquery.dataTables.yadcf.js:3998)
    at Object.exFilterExternallyTriggered (jquery.dataTables.yadcf.js:4367)
    at executeFilter (dataTables.js:612)

**Comment by vedmack** [comment]
Please provide a link to a jsbin/jsfiddle with a test case

**Comment by hrrhrst** [comment]
Would a link to a demo-system also be okay? Would be much easier for me right.

**Comment by vedmack** [comment]
yes, but I might ask to link to a yadcf in my dropbox so I will be able to debug it

**Comment by hrrhrst** [comment]
that souldn't be a problem. i will send you a link and login via email soon.

**Comment by vedmack** [comment]
fixed in [0.9.2.beta.12](https://github.com/vedmack/yadcf/blob/63e161ef2d3b441eeba960399ae3b365234c4f78/src/jquery.dataTables.yadcf.js)
