### ISSUE TITLE
Filters on server-side processing 

### ISSUE THREAD

**Issue by ihatecodinglikeking** [vedmack/yadcf#407]
Hi There, 

I am trying to implement http://yadcf-showcase.appspot.com/server_side_source.html on my datatables 
Do you have any example that explain server side changes in PHP 

I have seen this https://stackoverflow.com/questions/41507443/yadcf-datatables-server-side-populate-select-with-php but  I am using https://github.com/IgnitedDatatables/Ignited-Datatables 

So can you explain what are the changes should be... 

I am getting filters from DOM but I want from them server side

**Comment by vedmack** [comment]
Hi,

Sorry but I dont have any examples, you can use github search to find php projects that uses yadcf and try to learn from them, im 99% sure that there are many users that are using yadcf with php with Ignited-Datatables , please in case you will find some relevant info post it back here in this thread.

you can also post a question on stackoverflow and tag it with yadcf / php / Ignited-Datatables
