### ISSUE TITLE
Add name to inputs

### ISSUE THREAD

**Issue by hrrhrst** [vedmack/yadcf#408]
We are currently implementing jQuery Validation for Filterinputs. This lib requires giving a name on the input which you want to validate. This is currently not possible. Perhaps you could implement that in a future version. 

Validation for Filterinputs is neccessary, because you can end up in serious rendering issues with datatables if you don't.

**Comment by vedmack** [comment]
Hi,
Since its a very easy task to do (just go over the code and add a `name` attribute next to the `id` attribute a PR will be welcomed and will merge it...
