### ISSUE TITLE
Using jquery-ui with: changeMonth: true,       changeYear: true,

### ISSUE THREAD

**Issue by vladilin** [vedmack/yadcf#410]
Hello,

I can't seem to get it to work. Please help me out here:

In my old form I had this: 
```
$( "#datepicker1" ).datepicker({
      changeMonth: true,
      changeYear: true,
```

with yadcf this code doesn't work:

```
.yadcf([
					{column_number: 0, filter_type: "range_date", 
                    datepicker_type: 'jquery-ui', 
                    changeMonth: true,
      changeYear: true,
     filter_container_id: "external_filter_container"}
```

What am I doing wrong?

Thank you in advacne.
Vlad

**Comment by vedmack** [comment]
Question should be asked on stackoverflow and tagged with yadcf - http://stackoverflow.com/questions/tagged/yadcf
