### ISSUE TITLE
Add some css class helper on date range

### ISSUE THREAD

**Issue by n-rodriguez** [vedmack/yadcf#413]
Hi!

It seems that between version 0.8.9 and 0.9.1 the range date filters have lost the `yadcf-filter-range-start` and `yadcf-filter-range-end` css class :

```diff
-               $(filter_selector_string).append("<input onkeydown=\"yadcf.preventDefaultForEnter(event);\" placeholder=\"" + filter_default_label[0] + "\" id=\"" + fromId + "\" class=\"yadcf-filter-range-date yadcf-filter-range yadcf-filter-range-start\" " + filterActionStr + "></input>");
-               $(filter_selector_string).append("<span class=\"yadcf-filter-range-date-seperator\" >" + "</span>");
-               $(filter_selector_string).append("<input onkeydown=\"yadcf.preventDefaultForEnter(event);\" placeholder=\"" + filter_default_label[1] + "\" id=\"" + toId + "\" class=\"yadcf-filter-range-date yadcf-filter-range yadcf-filter-range-end\" " + filterActionStr + "></input>");
+               $(filter_selector_string).append("<input onkeydown=\"yadcf.preventDefaultForEnter(event);\" placeholder=\"" + filter_default_label[0] + "\" id=\"" + fromId + "\" class=\"yadcf-filter-range-date yadcf-filter-range\" " + filterActionStr + "></input>");
+               $(filter_selector_string).append("<span class=\"yadcf-filter-range-date-seperator\" >" + "</span>");                               
+               $(filter_selector_string).append("<input onkeydown=\"yadcf.preventDefaultForEnter(event);\" placeholder=\"" + filter_default_label[1] + "\" id=\"" + toId + "\" class=\"yadcf-filter-range-date yadcf-filter-range\" " + filterActionStr + "></input>");
```
it breaks the custom css that depends on it :

```css
.yadcf-filter-range-start {
  border-right: 1px solid #e5e6e7;
  border-left: none;
}

.yadcf-filter-range-end {
  border-left: 1px solid #e5e6e7;
  border-right: none;
}
```
Thank you!

**Comment by vedmack** [comment]
@n-rodriguez hi, can you point me on github the that version in which you saw this classes? https://github.com/vedmack/yadcf/releases or the one of my commits?

**Comment by n-rodriguez** [comment]
Well obviously it was not in 0.8.9 : https://github.com/vedmack/yadcf/blob/0.8.9/jquery.dataTables.yadcf.js.
Do you think it's possible to add this classes?

**Comment by n-rodriguez** [comment]
> @n-rodriguez hi, can you point me on github the that version in which you saw this classes? https://github.com/vedmack/yadcf/releases or the one of my commits?

Sorry, I may have added them to fix some css bugs.

Do you think it's possible to add this classes?

**Comment by vedmack** [comment]
Yes, please tell me exactly where they should be added, or even better send a PR with the relevant modifications, just fork the repo and modify the yadcf js file under the src folder src/jquery.dataTables.yadcf.js and send PR (it will be much faster)

**Comment by n-rodriguez** [comment]
> Yes, please tell me exactly where they should be added, or even better send a PR with the relevant modifications, just fork the repo and modify the yadcf js file under the src folder src/jquery.dataTables.yadcf.js and send PR (it will be much faster)

Ok! Thanks!
