### ISSUE TITLE
update 0.9.2 on NPM

### ISSUE THREAD

**Issue by darron1217** [vedmack/yadcf#415]
Hello I'm using this plugin on Angular4

On version 0.9.1 the code below
https://github.com/vedmack/yadcf/blob/0fef198b9bb8193ef517ca690ac5f322cc9f0ad8/src/jquery.dataTables.yadcf.js#L3732

appears like
https://github.com/vedmack/yadcf/blob/4efab911d2b92d3febfffb0578f0c8f6157f2fb4/jquery.dataTables.yadcf.js#L3649

and this made yadcf cannot find table which is initialised without selector
ex) `$(element).DataTable()`

So... please release current code with tag 0.9.2 and upload on NPM

Anyway thanks for making this beautiful plugin :)

**Comment by vedmack** [comment]
done...

**Comment by darron1217** [comment]
@vedmack 
Thanks for the fix :)

**Comment by vedmack** [comment]
@darron1217 I thought that tagging repo' will trigger npm version update but it looks like was wrong? because the [npm site](https://www.npmjs.com/package/yadcf/) shows 0.9.1 , can you remind me what else do I need to do in order to tell npm about my update?

**Comment by darron1217** [comment]
@vedmack Did you execute `npm publish` on your project folder?

**Comment by vedmack** [comment]
@darron1217 now I did, thanks
