### ISSUE TITLE
FixedHeader and yadcf still not working nicely together

### ISSUE THREAD

**Issue by alanburke** [vedmack/yadcf#417]
So I've read the previous issues
eg
https://github.com/vedmack/yadcf/issues/310#issuecomment-230260617

But I think there is some issues outstanding. 
To be clear - the fixedHeader works, and the yadcf filters work, as long as the user hasn't scrolled down the table, such that the 'fixedHeader' is active .
Once that happens, the filtering doesn't work.

To replicate, take the example url
http://yadcf-showcase.appspot.com/DOM_Ajax_Multiple_1.10.html
scroll such that fixedHeader is 'in action'
Try to use the Number Range filter
The filtering seems to happen, but the 'Range Slider' isn't updated

also
scroll such that fixedHeader is 'in action'
Try to use the Date Popup filter
Select a date 
The filtering works, but user is 'jumped' to the top of the page. 

The 'Select' filter works fine.

My issue is with a 'textbox' filter, where I experience some odd issues.
Once typing starts, focus is lost. 
The filter doesn't appear to work. 
The link referred to in the issue above https://jsfiddle.net/n2ybwhpv/9/ 
has the same issues 
Again, the 'fixedHeader' must be active by scrolling down, before experiencing the issue.

Thanks for a great plugin - outstanding work!

**Comment by alanburke** [comment]
to add
tested with Firefox and Chrome latest, on mac

**Comment by vedmack** [comment]
I fixed the filter_type: 'text' for the fixed header , [see working jsfiddle](https://jsfiddle.net/vedmack/n2ybwhpv/12/) and let me know

**Comment by alanburke** [comment]
Functionality working now - excellent work!

**Comment by vedmack** [comment]
fixed for `filter_type: 'text'` only, other filters will be fixed on demand (due to lack of time)

**Comment by iamandiradu** [comment]
Hey, @vedmack! Any chance of fixing it for custom functions? Thank you!
