### ISSUE TITLE
exFilterColumn not loading from localstorage

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#419]
Hi, I'm having this case 
I'm saving the localstorage value for the tables.

I have a filter by default using exFilterColumn
It save the value correctly
The problem I'm having is
If the user reset the filter 
when reloading the page the exFilterColumn default value is back again not the value from the localstorage

So is there a way to use a default value and if the user use another filter or reset it it will take new value from localstorage without forcing the default value it on every page load?

```
yadcf.exFilterColumn(table18, [
	[2, "Active"]
]);
```

There is a solution oSearch which is work the way I need but it is for all columns not for a specific column https://legacy.datatables.net/ref#oSearch
`"oSearch": {"sSearch": "Active"},`

Anyone have a solution for this?

**Comment by vedmack** [comment]
(Your) solution could be found here https://datatables.net/forums/discussion/45868/problem-using-yadcf-exresetallfilters-in-my-ajax-response

**Comment by lenamtl** [comment]
This is not the same problem.
Could you reopen this...

**Comment by vedmack** [comment]
You have to find a way to maintain / get the values that the datatables storing in the local storage by your self, its not something that is related to yadcf, see this [localStorage for state saving](https://datatables.net/blog/2012-01-16) and try to get to the point where you can tell what are the values that where used by the datatables filters, then you will be able to use those values if needed, 

## p.s.

**Isnt state saving is what you want? because yadcf support statesaving out of the box**

**Comment by lenamtl** [comment]
I don't think you understand the problem I'm having, let me recap...

If we compare exFilterColumn default value with Datatables default values for the search
these are not working the same way

The problem occur **only** when using exFilterColumn

```
yadcf.exFilterColumn(table18, [
	[2, "Active"]
]);
```

When the value is changed by the user the new value is saved in Datatables localstorage, 
if the page reload, the yadcf.exFilterColumn value will be applied, not the one from localstorage ...

What I understand is yadcf.exFilterColumn is applied on every page load and not taking account localstorage for the filter/search when loading the page...

So this is not having the same logical as the Datatables search default value..
because if we use oSearch or other Datatables default value this will apply the default value first time, 
once the user change it, on next page load this will take the value from localstorage not the default value (I don't have anything to code for this, this is the way it's working).
So this is allow to have a default value on first load and not forcing the user to always use this default value....

I'd like that Yadcf default value work the same way as Datatables default value.
Everything else is working fine with localstorage and Yadcf...

Hope it is more clear ...

**Comment by lenamtl** [comment]
Can we please re-open this, because there is a real problem from Yadcf  as it's not having the same logical of Datatables with stateSave (localstorage).

I also found the same bug related here https://github.com/vedmack/yadcf/issues/219

YADCF
I have set a filter value by default using exFilterColumn
It save the value correctly into LocalStorage.
If the user select a new value (same column of  exFilterColumn) the default value is override.
Localstorage save the new value.
Now if we reload the page
Now the problem is, it is not Loading the value from LocalStorage...
So on page load  exFilterColumn will pick up again the default value set in the Yadcf script instead of loading the value from localstorage.

*PS I'm using `externally_triggered: true`

Datatables act differently
If I set a default value using oSearch fro example , and the user change the search value the new value will be saved and load from localstorage.  So on page load the data is taken from localstorage not from 
oSearch default value

If I reset the table the oSearch default value will be selected.

https://legacy.datatables.net/ref#oSearch
`"oSearch": {"sSearch": "Active"},`

Note: all other Yadcf values are saved and load from localstorage correctly.
The problem occurred only when setting exFilterColumn default value.

**Comment by lenamtl** [comment]
Hi,

Any clue how to fixed this ?
Do you understand the problem?

**Comment by vedmack** [comment]
Hi,

By design whenever `exFilterColumn` is called with a certain value it will filter based on that value, in case that you want `exFilterColumn` to reflect the value stored in localStorage you must read it from localStorage and feed it into `exFilterColumn`, so if it the case its not an issue with yadcf.

**Comment by lenamtl** [comment]
But Datatables act differently and for that reason I cannot use this feature.

If I set a default value using oSearch for example , and the user change the search value, 
the new value will be saved and load from localstorage. 
So on page load the data is taken from localstorage not from oSearch default value.

I think this should work the same as it's break the localstorage logical...

Otherwise it's forcing a default value on each page reload..

**Comment by vedmack** [comment]
Ok :),  I will extend this function to obey localStorage if there is such
value... Will probably add param to function signature.

**Comment by lenamtl** [comment]
Can we reopen this one to work on this case?

**Comment by lenamtl** [comment]
Hi,

is this fixed?

**Comment by vedmack** [comment]
nope, unfortunately, I don't have the time to fix this one
