### ISSUE TITLE
column_data_type html doesn't fallback to text

### ISSUE THREAD

**Issue by JeroenvO** [vedmack/yadcf#422]
When `column_data_type` is set to `'html'`, and (some) cells do not contain sub-html-elements, the contents is discarded. This is due to the `$(..)` on line https://github.com/vedmack/yadcf/blob/master/src/jquery.dataTables.yadcf.js#L2288. The `$(..)` returns an empty string when a plain text input is given.

Suggested fix: change line https://github.com/KolibriSolutions/yadcf/blob/master/src/jquery.dataTables.yadcf.js#L2332, to take the originall cell content instead of `col_inner_elements`

**Comment by vedmack** [comment]
please provide a jsfiddle test page so I check / test it

**Comment by JeroenvO** [comment]
Ok, i think it is quite obvious, but anyway:

- No problems using jquery 1.x: https://jsfiddle.net/jeroenvo/Lfez4tm6
- Jquery 3.x doesn't show the text-only element in dropdown: https://jsfiddle.net/jeroenvo/bzc853hc

**Comment by vedmack** [comment]
fixed, here is a [working jsfildde](https://jsfiddle.net/vedmack/bzc853hc/8/)

**Comment by JeroenvO** [comment]
Thanks a lot!
