### ISSUE TITLE
Pagination state is not being saved when using yadcf with language option

### ISSUE THREAD

**Issue by sunde41** [vedmack/yadcf#423]
I appreciate your awesome works.

I am working on DT 1.10.16 with yadcf
and everything works great other than using language option..

stateSave: true,
language: {
           url: '/static/datatables/datatable-korean.json',
 },

If i remove url, pagination state is being saved... otherwise it does not work

Thanks

**Comment by vedmack** [comment]
please provide a jsfiddle test page
