### ISSUE TITLE
Parsing html-lists in table-cells for use in filter

### ISSUE THREAD

**Issue by JeroenvO** [vedmack/yadcf#424]
Hi again,
I have some tables which have html-lists inside a cell like:
`<td><ul><li>item1</li><li>item2</li></ul></td>`
I would like the individual list items to appear in the filters, such that the filter shows 'item1' and 'item2' as distinct values. It should then be possible to filter cells that have any of the selected list-items inside the list in the cell.

I already made have a working example on https://github.com/KolibriSolutions/yadcf/blob/master/src/jquery.dataTables.yadcf.js#L2314 by adding a new `html_data_type` named 'multi_selector'. When i have time i will make a jsfiddle to demonstrate.
<img width="99" alt="yadcf-list" src="https://user-images.githubusercontent.com/5551571/33634402-ecc95f52-da0b-11e7-89dc-f96f072329c0.png">

Do you like this idea? If yes, i'll work it out and send you an pull request.
Thanks for yadcf anyway!

**Comment by vedmack** [comment]
Hi
I tweaked yadcf a bit to add this ability, see [working jsfiddle](https://jsfiddle.net/vedmack/bzc853hc/11/)

**Comment by JeroenvO** [comment]
Thanks for the nice fix, I did some more extensive testing and found a little bug in your code, after processing a row with multiple html-matches, the `col_inner_data_helper` gets populated (correctly), but it is not reset after processing the row. In the next table-row the check on line https://github.com/vedmack/yadcf/blob/master/src/jquery.dataTables.yadcf.js#L2315 fails if the row doesn't have multiple elements.

Possible fix: set `col_inner_data_helper=null` between line 2327 and 2328
