### ISSUE TITLE
Filter fails when using data-* 

### ISSUE THREAD

**Issue by JeroenvO** [vedmack/yadcf#425]
When using any `data-` attribute on the `td`, yadcf wants the `html5_data` attribute. The console says: "Warning: Looks like you have forgot to define the html5_data attribute for the 0 column"

Because DataTables only filters on `data-search` or `data-filter`, this check should be limited to these two data- attributes. Using an other data- attribute doesn't work because datatables does not support it (As you point out correctly in the documentation in the sourcefile 👍 )

If now a data-sort (or any other data-) is used, it is not possible to use any yadcf filter. See https://jsfiddle.net/jeroenvo/w7rnuhLn/3/

Probably related to https://github.com/vedmack/yadcf/issues/158

I think the check on https://github.com/vedmack/yadcf/blob/master/src/jquery.dataTables.yadcf.js#L1179 needs to be rewritten, to not check if it is an object, but to check if it contains a valid `data-` attribute like `data-filter` or `data-search`

Thanks for the awesome filter plugin and keep up the good work!

**Comment by vedmack** [comment]
fixed in[ 0.9.3.beta.3](https://github.com/vedmack/yadcf/blob/81a80abbbba04acf15ac80daee104c11108a304c/src/jquery.dataTables.yadcf.js) ,see working jsffiddle https://jsfiddle.net/vedmack/w7rnuhLn/5/
