### ISSUE TITLE
Tags filtering

### ISSUE THREAD

**Issue by iamandiradu** [vedmack/yadcf#427]
I've had some problems using Yadcf with multiple tags and 'exact' filtering. My JSON file looked something like this

```
 {
	"id": 1,
	"name": "Roy",
	"city": "Sibiu",
	"country": "RO",
	"tags": "black,yellow,active",
	"state": "random-state",
	"comission": 3,
	"date": "12/10/2017"
}
```

and using 'contains' filtering would return 'active' and 'inactive' when iltering for 'active'. I tried using 'exact', but it would not work because it's argument would be the whole tags string. If anyone is having a hard time filtering multiple tags, try a custom function like the one below. Cheers! 

```
function custom_tags (filterVal, columnVal) {
    	if(columnVal === '') {
    		return true;
    	}
    	var tag = columnVal.split(',');
    	if(tag.indexOf(filterVal) !== -1) {
    		return true;
    	}

    	return false;
    }
	yadcf.init(tableh, [
	    {
	    	column_number : 4,
	        column_data_type: "text",
	        html_data_type: "text",
	        text_data_delimiter: ",",
	        filter_type: 'custom_func',
	        custom_func: custom_tags,
	        filter_reset_button_text: "&#128473"
	    }
       ]);
```

**Comment by vedmack** [comment]
yep, that is one of the reasons the I developed the `custom_func`. and there also the `multi_select_custom_func `

**Comment by iamandiradu** [comment]
Thanks*
