### ISSUE TITLE
Feature requested - a way to display if a filter is applied

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#428]
Hi, 

All my Yadcf filters are in a collapsable box.
When the box is collapsed we don't see if there are filters set.
So I'm looking for a way to display / notify on the page if any filters is applied by Yadcf.

The only way I see is to get info from localstorage but this is complicated to parse...

Any other way to do it?

Thanks

**Comment by JeroenvO** [comment]
Maybe look at the `column.search()` property of the datatable.
https://datatables.net/examples/api/multi_filter.html
Since yadcf calls internally to the datatables api to do a column search.

**Comment by lenamtl** [comment]
I forgot to mention that I'm also using **externally_triggered**

I have not found any way to get if a Yadcf filter / Datatables column search is applied or not...

So basically I want to display is there any filters applied Y or not N not only on page load but also when it changing Y to N or N to Y

**Comment by vedmack** [comment]
Try using the [exGetColumnFilterVal](https://github.com/vedmack/yadcf/blob/master/src/jquery.dataTables.yadcf.js#L325) method, also - in case you storing filters values in local storage you can always apply them using the [exFilterColumn ](https://github.com/vedmack/yadcf/blob/master/src/jquery.dataTables.yadcf.js#L317)method


exGetColumnFilterVal:
>  Description:        Allows to retrieve  column current filtered value (support ALL filter types!!!)
                Arguments:          table_arg: (variable of the datatable),
                                    column number:  column number from which we want the value
                Usage example:      yadcf.exGetColumnFilterVal(oTable,1);
                Return value:       String (for simple filter) / Object (for range filter) with from and to properties / Array of strings for multi_select filter


exFilterColumn:
              

>   Description:        Allows to trigger filter/s externally/programmatically (support ALL filter types!!!) , perfect for showing table with pre filtered columns
>                 Arguments:          table_arg: (variable of the datatable),
>                                     array of pairs: column number String/Object with from and to, filter_value (the actual string value that we want to filter by)
>                 Usage example:      yadcf.exFilterColumn(oTable, [[0, 'Some Data 2']]); //pre filter one column
>                                     yadcf.exFilterColumn(oTable, [[0, 'Some Data 1'], [1, {from: 111, to: 1110}], [2, {from: "", to: "11/25/2014"}]]); //pre filter several columns
>                                     yadcf.exFilterColumn(oTable, [[0, ['Some Data 1','Some Data 2']]]); // for pre filtering multi select filter you should use array with values (or an array with single value)
>

**Comment by lenamtl** [comment]
Thanks this is working fine using exGetColumnFilterVal
```

table24.on('search.dt', function() {
		
                // check datatables search
                 if (table24.search(this.value) != "") {
			$('#myfilter1').addClass('alert alert-warning').html('There is a search item');
			} else {  
			$("#myfilter1").removeClass('alert alert-warning').html('There is no search item');
			}
                // check yadcf filters 
		if (yadcf.exGetColumnFilterVal(table24, 2) != "") {
			$('#myfilter2').addClass('alert alert-warning').html('There is filter applied');
			} else {  
			$("#myfilter2").removeClass('alert alert-warning').html('There is no filter applied');
			}

});
```

The only problem I got is a random issue
when using Select2 + Multiselect and using the main clear X of the select2 field
So when clearing the field it's deleting only one items and we can see a visible glitch
Maybe  != "" cannot be use with Select2

I cannot find the trigger to reproduce it but this occurred once and a while....
No error into the console
