### ISSUE TITLE
Date range filter with ColReorder populates wrong column for AJAX searches

### ISSUE THREAD

**Issue by gavbaa** [vedmack/yadcf#429]
When using ColReorder and an AJAX endpoint, the date range filter pushes the search term into the wrong field.  I've put together a simple example: http://23.239.11.111/yadcf_test/index.html that is about as stripped as I could get it.  The server component does not return "right" data, it's just there to mirror the "draw" field so it doesn't fail.

What's happening: in the AJAX call, the columns[n][search][value] entry is right for the text field searches.  But for the date range search, it goes in it's "natural" spot, not in its reordered spot.

You can see from the attached image that even though the date field is "platform2", the date search went into the "engine" search field.
![image](https://user-images.githubusercontent.com/189923/34464169-b33dcaa2-ee42-11e7-8425-23d81d150592.png)

For reference, I've also attached the data.php in case you want to recreate the example locally.

[data.php.txt](https://github.com/vedmack/yadcf/files/1595460/data.php.txt)

Note: This appears to be a very similar issue to #267 , but I'm providing an example and the fix listed there doesn't work for me.

**Comment by gavbaa** [comment]
As an aside, after doing the date selection in the 1st column, you'll notice that the 3rd column's filter field has the focus, not the 1st column like you might expect.  I assume these are related behavior/bugs.

**Comment by vedmack** [comment]
fixed, look at the the updated showcase page (see new js code) and if you want you can see the new server side java code in the showcase source code https://github.com/vedmack/yadcf-showcase
