### ISSUE TITLE
Bootstrap Datetimepicker of Eonasdan v4 - Adding Custom Icons in Datetimepicker

### ISSUE THREAD

**Issue by benjieperez** [vedmack/yadcf#431]
Hi vedmack, i've add some changes for this date time picker plugin. It seems that this plugin relies on the default icons of bootstrap, here are the codes that might help in future researchers that want to use this plugin.

Cheers,
Benjie

Please include this code at line 1707
...........................................................
var datepickerOption = {
                    time: "fa fa-clock-o",
                    previous: 'fa fa-chevron-left',
                    next: 'fa fa-chevron-right'
                };
                datepickerObj.icons = datepickerOption;

**Comment by vedmack** [comment]
You can use the `filter_plugin_options` for that,
