### ISSUE TITLE
Using data-* attributes as parameters

### ISSUE THREAD

**Issue by mcmimik** [vedmack/yadcf#432]
First of all, thanks a lot for a powerful plugin!
I want to suggest one feature.

There is a table that is generated from a query where necessary data (columns) are set manually. In this way I don't know the order and the number of the columns, because it depends of the query. So when I need to filter one specific column, I should give the column an ID, then write the script to define the index of the column with this ID and use it on _yadcf.init_ for _column_number_ parameter. Or, I should write a lot of backend and frontend things to do it with data-attributes (indexes, loops, etc.).

It would be great if setting the parameters through the data attributes worked out of the box. Then I could just give the desired parameters to the th via data-*, for example:

`<th data-filter-type="range_number" data-html5-data="data-filter"></th>`

**Comment by vedmack** [comment]
sounds like a nice feature, not sure about when / if I will have the time for it, in the meanwhile you can send a PR for it, it shouldn't be a big deal to implement it
