### ISSUE TITLE
Is it possible to give each option a separate data soruce? And refresh?

### ISSUE THREAD

**Issue by work0407506** [vedmack/yadcf#437]
HI~ Daniel 

Sorry my English is not good~!

First of all, thanks to this plugin, I feel he is very powerful

But the example data soruce I see is the same as DataTable Ajax,
I hope to make different data for individual options Soruce
So I made the following things:

Client
<pre>
yadcf.init(oTable, [
     {
          column_number: 0,
          filter_container_id: 'account',
          filter_type: 'select',
          data: (function () {
          $.post('/users/filter', {}, function (data, status) {
                    return data;
               });
          })(),
     }
], { externally_triggered: true });
</pre>

Server
<pre>
exports.filter = function (req, res, next) {
     return res.json(["KHTML", "Webkit", "Trident", "Misc", "Other browsers", "Tasman", "Presto", "Gecko"]);
};
</pre>

This will indeed get the data to the server and return
But he did not show it correctly ,How can I do a similar thing?

I also want to ask how to refresh a single project
Let the project independently with the server to obtain the latest information
`yadcf.exResetFilters` Does not seem to perform the function inside the data again

I'm sorry I'm still a novice
But again thank you for this great plug-in

**Comment by vedmack** [comment]
github issues are to be used for bug reports and new features request only, question should be asked on stackoverflow

when using the `externally_triggered: true` try using the `exFilterExternallyTriggered` to reload data, if it wont work just try to redraw the table using datatables api, something like oTable.redraw (or something similar)

As to the way you try to fetch data from server (using that $post) this is not the way, you should return `yadcf_data_0` from you server along with the data of the table itself in order for yadcf to be able to read it, take a look at the server example page http://yadcf-showcase.appspot.com/server_side_source.html

further question should be asked on stackoverflow and tagged with `yadcf`

**Comment by work0407506** [comment]
Ok
I will try again, if there is a problem will be posted on stackoverflow
Thanks again for this plugin
