### ISSUE TITLE
Add configuration to modify the standrad labels

### ISSUE THREAD

**Issue by EmadMokhtar** [vedmack/yadcf#438]
If the user will use another language than English, please give the option to modify `placeholderLang` to pass the translated version of labels.

**Comment by vedmack** [comment]
You should read about the filter_default_label / omit_default_label

in addition there is an undocumented option to init all labels at once with the `language` option

yadcf.init(oTable, [{
  column_number: 0
}, {
  column_number: 3
}], {
  language = {
    'select': 'Select value',
    'select_multi': 'Select values',
    'filter': 'Type to filter',
    'range': ['From', 'To'],
    'date': 'Select a date'
  }
});

p.s

next time please ask question on stackoverflow only

**Comment by EmadMokhtar** [comment]
@vedmack I added the request here because I thought it is a missing feature, I can make a PR to update the docs with this hidden feature ;)

**Comment by vedmack** [comment]
@EmadMokhtar feel free to send the PR . just make sure it in the same format and stuff... (there is a special section for global properties in the docs)
