### ISSUE TITLE
filtering date column not happening

### ISSUE THREAD

**Issue by umamaheswarcs** [vedmack/yadcf#441]
Previously, On selection of date on date picker the search filter triggers and shows the matches(rows) but looks like now it is not happening.

RCA - The selected date on date picker is not initialized before below call happens and thereby not filtering the column values.
oTable.fnFilter(date, column_number_filter) Ln: 1462

**Comment by vedmack** [comment]
Hi please show your yadcf init code / provide test page

**Comment by umamaheswarcs** [comment]
Created Test page for 441 and 442 issues jsfiddle.net/umamaheswarcs/UvjnT/2975

**Comment by lenamtl** [comment]
Hi,
You are trying to use uxsolutions https://github.com/uxsolutions/bootstrap-datepicker
The new beta version is almost supporting this plugin, @vedmack still working on it
I have the same problem it's not filtering...
See my post : https://github.com/vedmack/yadcf/issues/435

**Comment by vedmack** [comment]
Hi

[0.9.3.beta.9](https://raw.githubusercontent.com/vedmack/yadcf/4f1f9456d1cead3a2680841270f76dc73b80d8ad/src/jquery.dataTables.yadcf.js) supposed to fix this issue
