### ISSUE TITLE
Filtering not working when Datatable option "searchable": false 

### ISSUE THREAD

**Issue by Mollekemiel** [vedmack/yadcf#443]
I'm not sure if it is actualy a bug, 
but the (default) filtering is not working when i set the Datatable option "searchable" to false for that column.  When i remove the option everything is fine.

in the example : column nr 3, same behaviour with column nr  4.
(Column nr 2 -range_number_slider- seems to work correct)

Test file:

<!DOCTYPE html>
<html>
<head>
<LINK href="DataTables-1.10.11/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
<LINK href="yadcf-0.9.2/jquery.dataTables.yadcf.css" rel="stylesheet" type="text/css">
<LINK href="jquery-ui-1.11.4.custom/jquery-ui.min.css" rel="stylesheet" type="text/css">

<SCRIPT SRC=jquery-1.11.3.min.js TYPE=text/javascript></SCRIPT>
<SCRIPT SRC=DataTables-1.10.11/js/jquery.dataTables.min.js TYPE=text/javascript></SCRIPT>
<SCRIPT SRC=yadcf-0.9.2/jquery.dataTables.yadcf.js TYPE=text/javascript></SCRIPT>
<SCRIPT SRC=jquery-ui-1.11.4.custom/jquery-ui.min.js TYPE=text/javascript></SCRIPT>

    <script>
	

function modif(a){

 alert("Modify "+a);
}		

function del(a){

 alert("Delete "+a);
}		

	
	$(document).ready( function () {
	// alert("press format data");

	    var oTable = $('#ResTbl').DataTable({
	"columnDefs": [
		     
            {
                "targets": [ 3 ],
                "searchable": false
            } 
			,
            {
                "targets": [ 6 ],
              
			  "orderable": false ,
				"searchable": false
            },
            {
                "targets": [ 5 ],
                
			  "orderable": false,
                "searchable": false
            },
			]
	
	});
	 yadcf.init(oTable, [{
					        column_number: 0 , filter_default_label: "..." , exclude: true
					    }, {
					        column_number: 2,
					        filter_type: "range_number_slider"
					    } ,
						
						{
					        column_number: 1,
					        filter_type: "auto_complete",
					        text_data_delimiter: ","
					    },
						{
					        column_number: 3 , filter_default_label: "..." 
					    } , 
						{
					        column_number: 4 , filter_default_label: "..." 
					    }
						]);

} );

</script>

</head>
<body>

<table id="ResTbl" class="compact">
    <thead>
        <tr>
            <th>Column 1</th>
            <th>Column 2</th>
            <th>Column 3</th>
			<th>mob</th>
			<th>controle</th>
			<th></th>
			<th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Row 1 Data 1</td>
            <td>Row 1 Data 2</td>
            <td>1</td>
			<td align=center>X</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('1')"> Modify</a></td>
			<td><a href="javascript:del('1')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 2 Data 1</td>
            <td>Row 2 Data 2</td>
            <td>2</td>
			<td align=center>X</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('2')"> Modify</a></td>
			<td><a href="javascript:del('2')"> Delete</a></td>

        </tr>
        <tr>
            <td>Row 3 Data 1</td>
            <td>Row 3 Data 2</td>
            <td>500</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('3')"> Modify</a></td>
			<td><a href="javascript:del('3')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 4 Data 1</td>
            <td>Row 4 Data 2</td>
            <td>4</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('4')"> Modify</a></td>
			<td><a href="javascript:del('4')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 5 Data 1</td>
            <td>Row 5 Data 2</td>
            <td>5</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('5')"> Modify</a></td>
			<td><a href="javascript:del('5')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 6 Data 1</td>
            <td>Row 6 Data 2</td>
            <td>6</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('6')"> Modify</a></td>
			<td><a href="javascript:del('6')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 7 Data 1</td>
            <td>Row 7 Data 2</td>
            <td>7</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('7')"> Modify</a></td>
			<td><a href="javascript:del('7')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 8 Data 1</td>
            <td>Row 8 Data 2</td>
            <td>700</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('8')"> Modify</a></td>
			<td><a href="javascript:del('8')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 9 Data 1</td>
            <td>Row 9 Data 2</td>
            <td>9</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('9')"> Modify</a></td>
			<td><a href="javascript:del('9')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 10 Data 1</td>
            <td>Row 10 Data 2</td>
            <td>10</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('10')"> Modify</a></td>
			<td><a href="javascript:del('10')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 11 Data 1</td>
            <td>Row 11 Data 2</td>
            <td>300</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('11')"> Modify</a></td>
			<td><a href="javascript:del('11')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 12 Data 1</td>
            <td>Row 12 Data 2</td>
            <td>12</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('12')"> Modify</a></td>
			<td><a href="javascript:del('12')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 13 Data 1</td>
            <td>Row 13 Data 2</td>
            <td>13</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('13')"> Modify</a></td>
			<td><a href="javascript:del('13')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 14 Data 1</td>
            <td>Row 14 Data 2</td>
            <td>14</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('14')"> Modify</a></td>
			<td><a href="javascript:del('14')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 15 Data 1</td>
            <td>Row 15 Data 2</td>
            <td>15</td>
			<td align=center>Train</td>
			<td align=center></td>
			<td><a href="javascript:modif('15')"> Modify</a></td>
			<td><a href="javascript:del('15')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 16 Data 1</td>
            <td>Row 16 Data 2</td>
            <td>1156</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('16')"> Modify</a></td>
			<td><a href="javascript:del('16')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 17 Data 1</td>
            <td>Row 17 Data 2</td>
            <td>17</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('17')"> Modify</a></td>
			<td><a href="javascript:del('17')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 18 Data 1</td>
            <td>Row 18 Data 2</td>
            <td>1500</td>
			<td align=center>Train</td>
			<td align=center></td>
			<td><a href="javascript:modif('18')"> Modify</a></td>
			<td><a href="javascript:del('18')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 19 Data 1</td>
            <td>Row 19 Data 2</td>
            <td>19</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('19')"> Modify</a></td>
			<td><a href="javascript:del('19')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 20 Data 1</td>
            <td>Row 20 Data 2</td>
            <td>20</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('20')"> Modify</a></td>
			<td><a href="javascript:del('20')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 21 Data 1</td>
            <td>Row 21 Data 2</td>
            <td>21</td>
			<td align=center>Bus</td>
			<td align=center></td>
			<td><a href="javascript:modif('21')"> Modify</a></td>
			<td><a href="javascript:del('21')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 22 Data 1</td>
            <td>Row 22 Data 2</td>
            <td>22</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('22')"> Modify</a></td>
			<td><a href="javascript:del('22')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 23 Data 1</td>
            <td>Row 23 Data 2</td>
            <td>23</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('23')"> Modify</a></td>
			<td><a href="javascript:del('23')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 24 Data 1</td>
            <td>Row 24 Data 2</td>
            <td>24</td>
			<td align=center>Bus</td>
			<td align=center></td>
			<td><a href="javascript:modif('24')"> Modify</a></td>
			<td><a href="javascript:del('24')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 25 Data 1</td>
            <td>Row 25 Data 2</td>
            <td>25</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('25')"> Modify</a></td>
			<td><a href="javascript:del('25')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 26 Data 1</td>
            <td>Row 26 Data 2</td>
            <td>26</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('26')"> Modify</a></td>
			<td><a href="javascript:del('26')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 27 Data 1</td>
            <td>Row 27 Data 2</td>
            <td>27</td>
			<td align=center>Train</td>
			<td align=center></td>
			<td><a href="javascript:modif('27')"> Modify</a></td>
			<td><a href="javascript:del('27')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 28 Data 1</td>
            <td>Row 28 Data 2</td>
            <td>28</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('28')"> Modify</a></td>
			<td><a href="javascript:del('28')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 29 Data 1</td>
            <td>Row 29 Data 2</td>
            <td>29</td>
			<td align=center>Bus</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('29')"> Modify</a></td>
			<td><a href="javascript:del('29')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 30 Data 1</td>
            <td>Row 30 Data 2</td>
            <td>30</td>
			<td align=center>Bus</td>
			<td align=center></td>
			<td><a href="javascript:modif('30')"> Modify</a></td>
			<td><a href="javascript:del('30')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 31 Data 1</td>
            <td>Row 31 Data 2</td>
            <td>31</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('31')"> Modify</a></td>
			<td><a href="javascript:del('31')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 32 Data 1</td>
            <td>Row 32 Data 2</td>
            <td>32</td>
			<td align=center>Train</td>
			<td align=center>X</td>
			<td><a href="javascript:modif('32')"> Modify</a></td>
			<td><a href="javascript:del('32')"> Delete</a></td>
        </tr>
        <tr>
            <td>Row 33 Data 1</td>
            <td>Row 33 Data 2</td>
            <td>33</td>
			<td align=center>Train</td>
			<td align=center></td>
			<td><a href="javascript:modif('33')"> Modify</a></td>
			<td><a href="javascript:del('33')"> Delete</a></td>
        </tr>

		
    </tbody>
</table>

</body>
</html>

**Comment by vedmack** [comment]
Hi,

This is by design (datatables design) when you set `"searchable": false` for a specific column / entire table you literally disabling the filtering for that column/table which results in inability for yadcf to function.
