### ISSUE TITLE
issue with multi_select_custom_func with 2 tables

### ISSUE THREAD

**Issue by mocraimer** [vedmack/yadcf#444]
after debugging this for a lil while i think i found the bug:
in jquery.dataTables.yadcf.js:2617
we do the following:
  $filter_selector = $(filter_selector_string).find(".yadcf-filter");

when there are 2 tables only the first one initialized will be returned

e.g lets say there are is table1 and table2 and table 1 was initiated first
it wlll initiate correctly and filter correctly but then when initiating table 2 at the same line 
$filter_selector will find table1's selector and not table2 as needed

**Comment by mocraimer** [comment]
was using the same id as filter_container_id in filters setting this works fine with multi_select filter type but fails otherwise, adding another filter_container_id fixes the issue

**Comment by vedmack** [comment]
glad it was resolved for your, in general you should use unique ids for your elements in HTML

**Comment by mocraimer** [comment]
the element was unique but i was using the same element for both tables which caused the issue
using the same element with multi_select type did not cause this issue

**Comment by vedmack** [comment]
ohh , got it now, you are welcome to send a PR to fix it or a test page that reproduces the issue

**Comment by mocraimer** [comment]
i will when i get a chance, thanks for the plugin and your support of it!
