### ISSUE TITLE
Eonasdan Bootstrap Date range bugs with localstorage

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#445]
I'm debugging uxsolutions datepicker see https://github.com/vedmack/yadcf/issues/435 

So I decided to tests Eonasdan Date Range to see if the act the same and found some identical bugs.

What I have found out is because some empty / null results are not saved the same way this is causing issues. It's seems that when it is saved this way **"from":"","to":""** after the next result that will be saved in localstorage will be wrong.

Tests are performed in this order I have done each tests twice and you will see at the end I have different results...

Yadcf main reset button
1) "yadcfState":{"-allmytasks-list":[null,null,null,null,null,null]}}
2) same result

FROM date selected
1) "yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":"14/03/2018","to":""}]}}
2) same result

TO date selected **BUG**
1)"yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":"14/03/2018","to":""}]}} 
2) same result

Yadcf main reset button
1)"yadcfState":{"-allmytasks-list":[null,null,null,null,null,null]}}
2) same result

FROM date selected
1)"yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":"21/03/2018","to":""}]}
2) same result

FROM clear using Datepicker clear btn ( this is an option `showClear: true,` )
1)"yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":"","to":""}]}}
2) same result

Select TO date **BUG**
1)"yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":"","to":""}]}}
2) same result

Select FROM date 
1)"yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":"15/03/2018","to":"22/03/2018"}]}}
2) same result

Yadcf main reset button **BUG**
1)"yadcfState":{"-allmytasks-list":[null,null,null,null,null,null]}}
and I see date selected in calendar view
2) same result

Select FROM and TO dates **BUG**
1)"yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":"16/03/2018","to":""}]}}
2) same result

Delete TO manually 
1)"yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":"16/03/2018","to":""}]}}
2) same result

Delete FROM manually 
1)"yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":"","to":""}]}}
2) Different result
"yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":null,"to":null}]}}

Select From date
1) "yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":"15/03/2018","to":""}]}}
2) same result

Delete From date Manually **BUG** ( There was no TO date selected and date format is wrong)
1) "yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":null,"to":"2018-03-21T04:00:00.000Z"}]}}
2) Different result
"yadcfState":{"-allmytasks-list":[null,null,null,null,null,{"from":"","to":""}]}}

**Comment by vedmack** [comment]
HI

unless there are some unique bug in *Eonasdan Bootstrap* integration with yadcf this issue is redundant

thanks
