### ISSUE TITLE
exResetAllFilters doing many Ajax requests

### ISSUE THREAD

**Issue by n-rodriguez** [vedmack/yadcf#448]
When calling `yadcf.exResetAllFilters(dt)` many ajax requests are sent in the same time. 
From what I see you  have 1 request per filter. If you disable redraw you gain 1 request but still have many requests.

**Comment by vedmack** [comment]
what if you set `true` as the second argument for this function ?

> 
> * exResetAllFilters
>                 Description:        Allows to reset all filters externally/programmatically (support ALL filter types!!!) , perfect for adding a "reset all" button to your page!
>                 Arguments:          table_arg: (variable of the datatable)
>                                     noRedraw:   (boolean) , use it if you don't want your table to be reloaded after the filter reset,
>                                                 for example if you planning to call exFilterColumn function right after the exResetAllFilters (to avoid two AJAX requests)
>                 Usage example:      yadcf.exResetAllFilters(oTable);

**Comment by n-rodriguez** [comment]
> If you disable redraw you gain 1 request but still have many requests.

**Comment by vedmack** [comment]
please provide a scenario / simple test page

**Comment by n-rodriguez** [comment]
i'm still working on it.

**Comment by kgiil** [comment]
I have the exact same issue, using latest build. 
It happens with when you have filter_type='multi-select' and select_type='select2'.

Calling exResetAllFilters works just fine, but sends a number of repeated Ajax request, as many as visible columns. If noRedraw=true there are one less Ajax request than number of visible columns.

**Comment by n-rodriguez** [comment]
>  It happens with when you have filter_type='multi-select' and select_type='select2'.

this is my config too.

It's nice to know I'm not alone :)

**Comment by n-rodriguez** [comment]
Hi! Can you please reopen this issue?

**Comment by vedmack** [comment]
Please post a link to a test page

**Comment by n-rodriguez** [comment]
@kgiil do you still have the issue?
