### ISSUE TITLE
yadcf - destroy/re-create

### ISSUE THREAD

**Issue by jduncalf** [vedmack/yadcf#449]
Am using latest version 0.9.2 in a scenario where I create the DataTable and then initialize yadcf:

   myTable = $('#mytable').DataTable({...});
   yadcf.init(myTable, yadcfStruct, 'footer');

The user is able to select a different (server-side) table as the source so I then destroy the DataTable:

   myTable.destroy();

And re-create with a new server-side AJAX API returned column definition set. However I can't destroy or re-create the yadcf association. I receive the following error when I recreate the DataTable with a differing number of columns than the original so obviously yadcf is still using the first set of column definitions:

   "Uncaught TypeError: Cannot read property 'mData' of undefined"

How can I dis-associate yadcf from my DataTable (myTable) so that I can re-associate later when i've created a new DataTable?

Many Thanks.

**Comment by jduncalf** [comment]
Hi, have implemented a fix/workaround. Exposed a reset() function to which sets options['#mytable'] = null and sets plugins['-mytable'] = {}

Seems to work fine with these additions.

**Comment by vedmack** [comment]
Hi,

So you can add it to the `removeFilters` function and send a PR

**Comment by vedmack** [comment]
Please provide a jsfiddle test case and I see what can be done

**Comment by konuch** [comment]
@vedmack Hello, I've run into a same issue, so I've created the above mentioned pull request myself.

**Comment by jduncalf** [comment]
Cool, I forgot all about it, it was a while ago. Just checked my local fix/workaround, I added the following to removeFilters():

    var settingsDt = getSettingsObjFromTable(oTable);
    options[table_selector] = null;
    plugins[generateTableSelectorJQFriendly2(settingsDt)] = undefined;
