### ISSUE TITLE
Select2 stay opened when clicking on another field

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#450]
Select2 stay opened when clicking on another field
See the Jsfiddle
http://jsfiddle.net/lenamtl/1s8ngatd/3/

click on any of 2 dropdown  
then click on a second dropdown directly
both dropdown stay opened 
the fist one should close when clicking on the second one

**Comment by vedmack** [comment]
fixed in 0.9.3.beta.15

**Comment by lenamtl** [comment]
Thanks
