### ISSUE TITLE
Javascript error in closeOpenDatePickersIfAny() method

### ISSUE THREAD

**Issue by umamaheswarcs** [vedmack/yadcf#451]
I have checked the new yadcf 0.9.3 beta.14 and found that the square brackets(bold) in function parameters mentioned in below code throws javascript error(message: Expected Identifier).

Object.entries(getAllOptions()).some(function (**[**tableSelector, tableOptions**]**) {
                Object.entries(tableOptions).some(function (**[**key, value**]**) {

I removed square brackets and the error has gone. After i ran the application and on click of the input field in column filter throws entries method is not found.

Please help if i missed anything

**Comment by vedmack** [comment]
what browser do you use?

**Comment by vedmack** [comment]
way to old browser, but I have fixed it anyway
