### ISSUE TITLE
Filtering is not happening for range_number

### ISSUE THREAD

**Issue by umamaheswarcs** [vedmack/yadcf#453]
Hi,

I'm trying to use range_number in my data table. It seems like it's not working.
Below is test page created.

JSFiddle - http://jsfiddle.net/UvjnT/3289/

Please suggest me if I'm missing anything

**Comment by vedmack** [comment]
remove the `searching: false,` , it disables the searching ability in your table

in case of further question related to datatables you their forum / stackoverflow
