### ISSUE TITLE
new div is created every time date selected (date-range)  + selection (inuse class) not removed when using clear button

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#457]
I'd like to know if this is normal and the reason why these div are created.

I'm using date range  **uxsolutions**/bootstrap-datepicker
and **external filters**
occurred in several browser

Every time I select a date
a new div is created, this is visible through the console 

To reproduce select a from or to date and check in console
`<div id="yadcf-filter-wrapper--13_4"></div>`

see console results
![2018-04-04_11-39-25](https://user-images.githubusercontent.com/2241324/38318744-17039f4e-37fe-11e8-8190-1eb4bb5c9a48.png)

this seems similar to this https://github.com/vedmack/yadcf/issues/68

**Comment by vedmack** [comment]
thanks, its a bug, please provide a simple test case so I will be able to fix it sooner

**Comment by lenamtl** [comment]
Hi, do you know when this is going to be fixed?

**Comment by lenamtl** [comment]
Do you know what create this and how to fix it?

**Comment by vedmack** [comment]
Haven't got the time to check it, you are free to debug / fix / pinpoint
the error line, my guess is that somewhere the selector is wrong and its
not aware of the fact that the div already there and creates it again

**Comment by lenamtl** [comment]
I think this bug should be fix as it may bring other issues probably the random issue I got with loclastorage.

As You already fix the problem for range see #68
I thought it will not be long for you to fix this one too, 

I would really appreciate...

**Comment by vedmack** [comment]
@lenamtl ,  please provide a simple test case page

**Comment by lenamtl** [comment]
Hi, 
I'm not able to create a jsfiddle...
I have tried a few time but I cannot link **Yadcf beta file** as it is **not** in CDN
I have tried to link the raw version from Github with no luck.

Anyway you should be able to reproduce easily 
I'm using externally_triggered: true
date range **uxsolutions**/bootstrap-datepicker

I have 4 filters that are select2 and only one with date range

On page load an extra div the one of the date_range (is duplicated) appear just before the **ending span** 
(check image I provided previous message)
`<div id="yadcf-filter-wrapper--13_4"></div>`

*If I select a date in calendar it is creating one extra div
**If i enter the date manually it is creating one extra div for each digit or each keyboard key I hit

**Comment by lenamtl** [comment]
Thanks for the info.

Here is the JSfiddle 
https://jsfiddle.net/lenamtl/124aussb/21/

**Comment by vedmack** [comment]
fixed

**Comment by lenamtl** [comment]
Thanks a lot

**Comment by lenamtl** [comment]
?

**Comment by vedmack** [comment]
@lenamtl  hhhhhh.... No freaking idea how that was sent from my account...I mean I do have a clue, but still...
