### ISSUE TITLE
Problem with bStateSave

### ISSUE THREAD

**Issue by WGlenat** [vedmack/yadcf#462]
Hello,

I am using version 0.9.2 of yadcf and version 1.10.16 of datatables

When I put "bStateSave": true and hide a column: table.column (1) .visible (0);
the filter in the last column takes the filter from another column.

Can you see where the problem is coming from?

Thanks

**Comment by vedmack** [comment]
Hi

try the latest beta https://github.com/vedmack/yadcf/tree/master/src and if still wont work provide a test page with the issue

**Comment by WGlenat** [comment]
it works !
thank you

**Comment by vedmack** [comment]
you are welcome, always try the latest beta and always bet on yadcf 😄
