### ISSUE TITLE
Beta builds on npm

### ISSUE THREAD

**Issue by TaylorRayHoward** [vedmack/yadcf#464]
Would it be possible for you to push the 9.3.beta.X builds to npm?  You've got some good changes in 9.3 and I'd like to have them through npm if possible.

**Comment by vedmack** [comment]
Yeah I will try to do it in the next days

**Comment by vedmack** [comment]
Hi

9.3 final is out and it on npm, regarding the beta on npm, I know that I can use `npm publish --tag beta` but how can I apply that to the js file that sits in `src` folder only?
