### ISSUE TITLE
yadc 0.9.3.beta with Safari 

### ISSUE THREAD

**Issue by WGlenat** [vedmack/yadcf#466]
Hello,

When I use yadc 0.9.3.beta with Safari I have the following error message in the console
jquery.dataTables.yadcf.js:489SyntaxError: Use of reserved word 'let' in strict mode

**Comment by vedmack** [comment]
Hi

You can upgrade your safari / change the several let keywords into var or wait till I will start to transpile yadcf with webpack / babel into es5 compatable (any help on that will be appreciated)

**Comment by WGlenat** [comment]
thanks i change let and const into var
