### ISSUE TITLE
v0.9.3 contains ES6 code

### ISSUE THREAD

**Issue by jakub300** [vedmack/yadcf#467]
Hey, we have noticed our build breaking with newest version. After investigating we discovered that yadcf contains ES6 code (specifically const and let keywords). This breaks declared browser support and builds when ES6 code in dependencies is not expected.

https://github.com/vedmack/yadcf/blob/552d1e5906eb84af13c767826eda3303083229dc/jquery.dataTables.yadcf.js#L489-L491
https://github.com/vedmack/yadcf/blob/552d1e5906eb84af13c767826eda3303083229dc/jquery.dataTables.yadcf.js#L2433
https://github.com/vedmack/yadcf/blob/552d1e5906eb84af13c767826eda3303083229dc/jquery.dataTables.yadcf.js#L4175

**Comment by ielcoro** [comment]
Same here, using systemjs-builder that uses uglify-js (not uglify-es that supports ES6), and the build breaks when using production settings (minify: true)

**Comment by vedmack** [comment]
use /dist version 

or

*npm install yadcf@beta*
