### ISSUE TITLE
Display-problems with range-filters in tables with scrollX

### ISSUE THREAD

**Issue by mbaas2** [vedmack/yadcf#468]
My [sample page](http://mbaas.de/t47/TamStat.html) shows how the header with filters has an offset to the data in tbody. As soon as I change a filter or make a column visible, the display gets correct. Only the initial draw is incorrect.
Using release 0.9.3,  552d1e5 .

**Comment by vedmack** [comment]
please provide a test page on jsfiddle / etc so it will be easier for debug / seeing your code/html, you might get a faster/better reply on datatables forum because it looks like something related to table drawing
