### ISSUE TITLE
filter_delay not working on range_date

### ISSUE THREAD

**Issue by darron1217** [vedmack/yadcf#470]
filter_delay not working on range_date

It seems expected, but is there any plan to support it?

**Comment by vedmack** [comment]
it is supported and should work, please provide a test page

**Comment by darron1217** [comment]
http://jsfiddle.net/chcLmmps/79/

Here's example

Whenever I select first date(start date) it immediately searches value

**Comment by vedmack** [comment]
you are right, delay applied only when manipulating date from manually (keyboard)

**Comment by vedmack** [comment]
@darron1217  please try *0.9.4.beta.2* (not yet in github) from at the http://jsfiddle.net/chcLmmps/83/ test page (its in the resources of the test page)

**Comment by darron1217** [comment]
Yes, I checked it working :)
Thanks @vedmack

**Comment by vedmack** [comment]
0.9.4.beta.2 released
