### ISSUE TITLE
yadcf does not use DT render: filter / orthogonal data? 

### ISSUE THREAD

**Issue by bkarlson** [vedmack/yadcf#471]
In a table with large values I use render filter to set display and filter values like this:
original value: 123456
filter value: 123
display value: 123K

As you see, numbers are displayed as __123K__, so in range filters we type `123` to get values 123,000+ instead of typing `123000`.

When I set up a DT [custom range filter function](https://www.datatables.net/examples/plug-ins/range_filtering.html) everything works as expected. 

Yadcf range filter however, still uses original data, i.e. 123 stil filters values 123+, not 123000+.

Am I missing some option or yadcf ignores orthogonal data? 

Cheers. 

p.s. this is the rendering function that returns 123 and 123K for filtering and display values.

```js
$.fn.dataTable.render.kilo = function () {
  return function(data, type, row){
   var value = (data / 1000);
   if (type === 'display') {
     if (data < 10000)  {return $.fn.dataTable.render.number( ',', '.',1, '', 'K' ).display(value)}
      else  {
        return $.fn.dataTable.render.number( ',', '.',0, '', 'K' ).display(value)} 
      }
      else if (type === 'filter') {
        return value;} 

      return data;
      }
    };
```

**Comment by vedmack** [comment]
please provide a minimal test page jsfiddle / etc and I will see what can be done
