### ISSUE TITLE
Filtered event callback

### ISSUE THREAD

**Issue by kerbooo** [vedmack/yadcf#472]
Hi, firstly thank you for your great plugin. It is amazing.

I would like to hide reset button if yadcf is not active then show when it is active. Is there any event callback for this? I did not find. If any way, please tell me how?

**Comment by vedmack** [comment]
Thanks
There is no such event, you can bind to datatables filter event and draw event, or you can bind to filters inputs 'onchange' / 'keyup' / etc events and do your logic based on value in the inputs
