### ISSUE TITLE
exFilterColumn value type

### ISSUE THREAD

**Issue by ehdwns980416** [vedmack/yadcf#476]
exFilterColumn value with number is not working.

```typescript
yadcf.exFilterColumn(oTable,[
    /* not work with number type */
    [3, [2004, 1986]]
    /* work well with string type */
    /* [3, ['2004', '1986']]  */
]);
```

Here's test page
 [JSfiddle](http://jsfiddle.net/JunKim/1mjwatxz)

**Comment by vedmack** [comment]
You are right, that because all multi select filter values are treated as string, use strings , if it a value that passed from somewhere else convert it to string like this: '' + someNum
```
yadcf.exFilterColumn(oTable,[
     [3, [ '' + 2004, '' + 1986]]   
]);
```

**Comment by ehdwns980416** [comment]
Thank you for your reply.
I'll go ahead with it.
