### ISSUE TITLE
When will you release 0.9.4?

### ISSUE THREAD

**Issue by darron1217** [vedmack/yadcf#479]
I'm waiting for the release...

I need the date picker's style_class option :)

**Comment by vedmack** [comment]
If you mean on npm then I'll see how its possible to release beta version on it

**Comment by vedmack** [comment]
@darron1217  you mean that you want an updated version on npm ?

**Comment by darron1217** [comment]
Yes, that's right

**Comment by vedmack** [comment]
Ok, I need to check how can I add beta versions to npm

**Comment by darron1217** [comment]
Thanks for your kindness :)

**Comment by konuch** [comment]
Hello, I would also like to ask for a next release, so we can use the beta features in our project, without the need to reference our own fork of this greate lib.
Here's a link to npm tagging features https://docs.npmjs.com/getting-started/using-tags

**Comment by vedmack** [comment]
Hi

Sorry for such a delay, here you go

Use `npm install yadcf@beta` for the latest beta version (es5)

-------------------
For my own possible future reference

Update in package.json "version": "0.9.4-beta.5"
Drop latest beta in yadcf (backup the latest before that)
Run npm install yadcf@beta
