### ISSUE TITLE
filter_type: "range_number" not working

### ISSUE THREAD

**Issue by psangelov** [vedmack/yadcf#480]
Hello,
I have some issues with the plugin. I have a column that contains amounts. The numbers contain the symbol $ in the cell. I'm trying to configure a range_number or even better a range_number_slider but without any success. I tried several ways to handle the amount. I tried to set ignore_char so that the $ won't be a problem and I also tried html5_data: 'data-search' and added the data-search attr to all cells that but in both cases the no data is filtered. Any idea of what could be wrong?

**Comment by vedmack** [comment]
please provide a test page jsfiddle / jsbin / etc
