### ISSUE TITLE
Autocomplete is not reading filter_plugin_options

### ISSUE THREAD

**Issue by lfsupport** [vedmack/yadcf#482]
Hi 
I am using the auto_complete feature in yadcf plugin. I want to set the minLength for it, but on using filter_plugin_option ,the property does not seem to reflect on the page.

Please take a look at my code in the given link.

https://jsfiddle.net/lfsupport/bkpLtn0e/

(The code is working on my local, (yadcf is not getting called)but I don't understand how to make it work on jsfiddle. Maybe some url issues.  I tried but no avail. Sorry about that)

**Comment by vedmack** [comment]
fixed in 0.9.4.beta.3

**Comment by lfsupport** [comment]
Hi Vedmack,

Thanks a lot the filter_plugin_options is working fine. But now I have encountered 2 problems
1)filter_match_mode: "startsWith" is not working. I checked with filter type as text, the match mode works but not with auto_complete. It does not work even if remove filter_plugin_options.
2) yadcf 0.9.4 beta version is not working with iPad 2 model mc982hn/a. So just to see whether even previous versions had this issue I tried 0.9.3 again it did not work on this iPad model while 0.9.2 works fine. But only on this device the code does not work, It works fine on iPhone, iPad (5th generation).

**Comment by vedmack** [comment]
@lfsupport 
about the `1)filter_match_mode: "startsWith"` pleasse provide a test page (because it does work for me even on your test page provided here in the thread
as to the `iPad issue` its related to js es5 issuem I started to use es6, I will start providing backward compatibility generated file so it will be solved soon keep an eye on this https://github.com/vedmack/yadcf/issues/467

**Comment by lfsupport** [comment]
Hi 

The beta 0.9.4 is working perfectly on all devices. Thanks a lot.

As for the issue I am sending you the link. When you just type 'a' in the autocomplete box that is column1 corresponding to States all the entries that have 'a' anywhere is presented in the drop down, rather than the ones that just start with 'a'.

https://jsfiddle.net/ywc018L3/33/

Just to show the difference I have made column 2 as text, there when I type 'a' it filters data perfectly and shows only cities starting with letter 'a'. 

Please check
