### ISSUE TITLE
Number Range Slider Not working

### ISSUE THREAD

**Issue by DaviehS** [vedmack/yadcf#483]
the range slider is not working at all
i added all the css and js of jqueryui and still nothing

Thanks for the help

and also is there a way to set the range by my self ? without scaning the data?

http://david123456.vangus.site/examples/server_side/simple.html

David

**Comment by vedmack** [comment]
getting 503 , you can set range data by using the `filter_plugin_options` , set `min` / `max` 

please provide a test page jsfiddle / etc so it will be possible to check your issue
