### ISSUE TITLE
Make Yadcf filters resizable when you use datatables column resizing

### ISSUE THREAD

**Issue by AlexPowen** [vedmack/yadcf#484]
In datatable you can use Column resizing to make a flexible width lengh
https://www.gyrocode.com/articles/jquery-datatables-column-reordering-and-resizing/

In Yadcf this can't be done, the size of the Yadcf filters can not be lengthened or shortened if you use this plugin.
Is there a way to fix this lack?
![resizable yadcf](https://user-images.githubusercontent.com/3471861/43836058-6377bdf0-9b14-11e8-8e59-fdc4fa7ee396.png)

**Comment by vedmack** [comment]
please provide a test page with minimal setup and I will take a look

**Comment by AlexPowen** [comment]
I test on this table
https://datatable.vn.cisinlive.com/index.php

**Comment by AlexPowen** [comment]
Did you get an idea of ​​the problem?

**Comment by vedmack** [comment]
please provide a test page (jsfiddle) with minimal setup and I will take a look

**Comment by AlexPowen** [comment]
I don't use jsfiddle, but you can see that is not possible to dinamically resize when I resize column, I test here https://datatable.vn.cisinlive.com/index.php

**Comment by vedmack** [comment]
you can play with filters css, for example set width to auto / using min / max width etc... what do you expect to happen to filters upon resize? I tried your sample page and it looks ok to me

**Comment by AlexPowen** [comment]
I expect that the text inside the rows is distributed evenly in the columns adapting to the available space, without going to show up in 2 lines, however, often there is so much empty space available and the text breaks and wrap. 
Instead, the filter, keeping its width locked, is as if it were blocking this.

![empty bad space](https://user-images.githubusercontent.com/11960124/43927542-33a6335c-9c2e-11e8-9d64-c1065ea33e45.png)

**Comment by vedmack** [comment]
You can try and play with the third party plugins (in your case chosen) I suggest you to try the [filter_plugin_options](https://github.com/vedmack/yadcf/blob/552d1e5906eb84af13c767826eda3303083229dc/jquery.dataTables.yadcf.js#L222) try setting `{ width: '100%' }`  , [read here for more](https://stackoverflow.com/questions/16960690/chosen-harvesthq-resize-width-dynamically) , thats the best I can do
