### ISSUE TITLE
Select problem

### ISSUE THREAD

**Issue by ehdwns980416** [vedmack/yadcf#485]
I set select option like this:
`pending, active, inactive`

And when I select `active` value `inactive` came out 😭 
What should I do?

Here's test page
 [JSfiddle](http://jsfiddle.net/chcLmmps/92/)

**Comment by vedmack** [comment]
Its not a problem, you should use [filter_match_mode: 'exact'](https://github.com/vedmack/yadcf/blob/552d1e5906eb84af13c767826eda3303083229dc/jquery.dataTables.yadcf.js#L187)

[see it working](http://jsfiddle.net/vedmack/zdmLfvg5/)

p.s 
next time please use stackoverflow for questions / read docs

**Comment by ehdwns980416** [comment]
OMG..
@vedmack What should I do, when I want to see all items..
I used `value=''` attribute in select option.
But after I use `filter_match_mode: 'exact'` I can't see all items. 😢

**Comment by vedmack** [comment]
@ehdwns980416 just hit the [x] button to reset the filter
