### ISSUE TITLE
filter_match_mode get ignored with Select2

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#487]
Hi,

I'm using Select2 single and multiple.

If I want to change the **Select2 search** to start with only
What I mean by that is when entering Mart in the select2 search 
it will display only Mart in the **select2 list**
Walmart Inc
Mart Inc

Is this a settings from Datatables, Yadcf or Select2?

Thanks

**Comment by vedmack** [comment]
Hi please ask on StackOverflow

**Comment by lenamtl** [comment]
Hi,

This is a possible bug
It seems that **filter_match_mode** get ignored with Select2 (single and multiple)

See this jsfiddle
https://jsfiddle.net/lenamtl/7a4q5ksb/1/

I have not set anything for the select2 (single) = and it does not search contain but only start with
For the second select2 (multiple) `select filter_match_mode: "startsWith",` and it does search by contain not by start with ...

Let me know how can I fix that, thanks

**Comment by lenamtl** [comment]
Any news on this?

**Comment by vedmack** [comment]
[Here a jsfiddle test page](https://jsfiddle.net/vedmack/sqaoh8uf/7/) that shows possible usages of this feature along with select2 input, in general I think it better be used with text input, in my opinion when using with select input you better add some custom options to the select input, like this:

    data : ["PR", "DEV"],
    append_data_to_table_data: true,
    filter_match_mode: "startsWith",
