### ISSUE TITLE
Accent insensitive option

### ISSUE THREAD

**Issue by pmietlicki** [vedmack/yadcf#488]
Hi, first of all thanks for your work, this plugin is amazing!!

The data I load in my aplication is in french and the accents are an issue when filtering per column, there is a plugin, accent neutralise that solves this with global search/filtering, this is handy especially when there are gramatical errors in the data, you have to replace characters in the search input as well by applying this:
$('#myInput').keyup( function () { table .search( jQuery.fn.DataTable.ext.type.search.string( this.value ) ) .draw() } );

I don't know how to change yadcf behavior to "normalize" strings inside a search, for example with multi_select option.

I would like to know if it is possible to add compatibility for accent neutralise plugin or if there is a way to work around to achieve its functionability. Maybe being able to change the string before filtering with something like "str.normalize('NFD').replace(/[\u0300-\u036f]/g, "")"

Thanks in advance

**Comment by lenamtl** [comment]
One temporary solution is to use Select2 dropdown as it have the search built-in, the list is populate from the data found in column.

I'm having the same problem with Datatables search, several solutions exists but most will fin with accent or no accent but not both.
I have found this solution that cover both, not I have not implemented yet, as i'm still looking for solutions,  I guess this could be applied to Yadcf too.

**Comment by pmietlicki** [comment]
Hi,
Accent neutralize is working well for the global search inside datatables but it does not affect yadcf plugin. Your fiddle does a lot like what accent neutralize plugin is doing, it works well with the builtin datatables search but I don't know how to make it work with yadcf.

That's why I'm looking for a way to change the data before launching a search inside yadcf.

I've tried with select2 but no luck.

Thanks for your help.

**Comment by pmietlicki** [comment]
Hi,

That one : [](https://jsfiddle.net/mqecjf48/)

I think this part is making yadcf not working correctly :
`searchType.html = function ( data ) {
    return ! data ?
        '' :
        typeof data === 'string' ?
            removeAccents( data.replace( /<.*?>/g, '' ) ) :
            data;
};`

**Comment by lenamtl** [comment]
Hi, 
if you inspect the code you have this error 
$selectObject.chosen is not a function

**Comment by vedmack** [comment]
@pmietlicki , I was about to start trying to find a solution for your issue, but it seems to work out of the box just fine, please [see this jsfiddle ](https://jsfiddle.net/vedmack/05dtpk1s/1/)

IN addition you can use custom function filtering and inside your custom func you can apply the accent insensitive function on both the searched item and the item in the row and retun true when they match / contains /etc...

**Comment by lenamtl** [comment]
I'm not sure what you are trying to do 
but for any dropdown (select2 or chosen if you have Bloc Op**e**ratoire and Bloc Op**é**ratoire this will generate 2 entries into the list.

**Comment by lenamtl** [comment]
If you have Bloc Opératoire and Bloc Operatoire this will generate 2 entries in the dropdown 
(Select2 or Chosen)

If you search (using the select search) Bloc Opératoire 
with Select2 it will find both Bloc Opératoire and Bloc Operatoire 
with Chosen it will find one and will not find Bloc Operatoire

Overall Select2 have more option and is more flexible as it also have a “built-in” matcher and a custom matcher and have stripDiacritics()
Chosen does not have this.

**Comment by pmietlicki** [comment]
@vedmack, I opened your jsfidlle and I wrote down in the search input : "Bloc Operatoire" and it does not return anything. So no, the search is not case insensitive.

My need is to be able to find anything with or without accent inside the search input.

Do you have an example of custom function filtering to make it case insensitive ?

Thanks for your help.

Best regards,
Pascal

**Comment by vedmack** [comment]
@pmietlicki, [Here is a quick example of custom filtering](https://jsfiddle.net/vedmack/05dtpk1s/11/), 

You can read more about in yadcf js docs,




	$(document).ready(function() {

	   var oTable;
		 oTable = $('#example').DataTable({
	   });

	   yadcf.init(oTable,
			  [{
				column_number: 0,
				filter_type: 'custom_func',
			custom_func: myCustomFilterFunction
			  }]);  
	  
	});


	function removeAccents ( data ) {
		return data
			.replace( /έ/g, 'ε' )
			.replace( /[ύϋΰ]/g, 'υ' )
			.replace( /ό/g, 'ο' )
			.replace( /ώ/g, 'ω' )
			.replace( /ά/g, 'α' )
			.replace( /[ίϊΐ]/g, 'ι' )
			.replace( /ή/g, 'η' )
			.replace( /\n/g, ' ' )
			.replace( /á/g, 'a' )
			.replace( /é/g, 'e' )
			.replace( /í/g, 'i' )
			.replace( /ó/g, 'o' )
			.replace( /ú/g, 'u' )
			.replace( /ê/g, 'e' )
			.replace( /î/g, 'i' )
			.replace( /ô/g, 'o' )
			.replace( /è/g, 'e' )
			.replace( /ï/g, 'i' )
			.replace( /ü/g, 'u' )
			.replace( /ã/g, 'a' )
			.replace( /õ/g, 'o' )
			.replace( /ç/g, 'c' )
			.replace( /ì/g, 'i' );
	}
	 
	 
	function myCustomFilterFunction(filterVal, columnVal) {
	   return removeAccents(filterVal) === removeAccents(columnVal);
	}

**Comment by lenamtl** [comment]
Here a more complete list 
this is for the default datatables search box https://jsfiddle.net/lenamtl/6t3mnwjz/
you can reuse it for Yadcf

The idea is to remove the accent when hitting the search box from the data + from the world that is in the search box so this way you will see both

**Comment by lenamtl** [comment]
Hi check this one https://github.com/DataTables/Plugins/issues/401

I have not tried yet, but look simpler...

**Comment by pmietlicki** [comment]
Hello,

Yes I have already tried that, it worked but I think it was in conflict with the bootstrap search inside my page.

Thanks for your answers though.

Have a nice day,

**Comment by vedmack** [comment]
Since [custom filtering does work here](https://github.com/vedmack/yadcf/issues/488#issuecomment-427264289) I will close this issue
