### ISSUE TITLE
FEATURE REQUEST - Text filters with dynamic regex switch

### ISSUE THREAD

**Issue by konuch** [vedmack/yadcf#489]
Hello, it would be useful to have a custom checkbox next to the textbox filters which will toggle regex filtering for a given column on/off, if it's defined in the filter settings for a given column.

When this checkbox is checked, given column filter starts treating its input as a regex.

**Comment by lenamtl** [comment]
This may be a good idea to have this also for Select2 and other input.

**Comment by konuch** [comment]
Thank you!
