### ISSUE TITLE
Exact match does not work with multiple items in cell

### ISSUE THREAD

**Issue by JeroenvO** [vedmack/yadcf#491]
Exact match does not work with multiple items in a cell
When selecting 'ab', 'aab' should not be visible.

https://jsfiddle.net/jeroenvo/bzc853hc/66/

**Comment by vedmack** [comment]
Can you please elaborate more on what do you expect to happen? its a bit of a complex structure that you have in the jsfiddle you are using the `html_data_selector: 'li',   column_data_type: 'html',` so you will get each value as a separate option, therefor exact filtering on that separate value wont match with the origin row

**Comment by JeroenvO** [comment]
That explains, thanks. 
What i would like to achieve is that the filter value has an exact match with the text inside the html, in any of the 'li' items in a cell.
It indeed is a complex structure, so i totally understand if you don't want to support it.

**Comment by JeroenvO** [comment]
Okay, thanks for the help!
