### ISSUE TITLE
Missing state saved value is restored to select filter as null and inuse

### ISSUE THREAD

**Issue by konuch** [vedmack/yadcf#493]
In our project, we have several tables which depend on each other.
For example, entries from TableA are used in a select filter in TableB.
We've just started using DT state saving. It works perfectly for the filters, but in case we have a saved filter value in TableB, then we remove this entry from TableA and move back to TableB, the filter tries to preselect this stored value in the dropdown, but it's selected as null and also set as `inuse`.

Expected behaviour: In case the option to be preselected does not exist in the select dropdown, do not try to preselect it.

**Comment by vedmack** [comment]
simple jsfiddle test page will speed up the fix for this issue

**Comment by konuch** [comment]
Hey, here's a jsfiddle, where you can simulate the behaviour:
http://jsfiddle.net/you54cr1/16/

Just uncomnent the line 13, which will simulate a non existing select option being stored in datatables state.

I also made a PR with a proposed solution. #494
Here's a fiddle whith the fix: http://jsfiddle.net/fxvjueqL/3/
