### ISSUE TITLE
cannot filter on empty cells

### ISSUE THREAD

**Issue by louking** [vedmack/yadcf#50]
I have a column were some cells have values and some cells are empty.  The filter select shows all the values and the empty selection.  However, when I try to filter on the empty selection, all the rows are shown.

I would have expected this to work similar to excel when you are using data filtering, and select only (blanks)

Let me know if you need a jsbin for this.  (I wonder if this is underlying datatables problem)

**Comment by jasekz** [comment]
My issue was that if any columns BEFORE the filter were empty, i.e - text filter on col 3, but col 2 (no filter) had empty values - I would get no results.  The solution that worked for me was to add a non-breaking space (nbsp;) to all data cells.
