### ISSUE TITLE
Regex state save restored incorrectly when exclude = true

### ISSUE THREAD

**Issue by konuch** [vedmack/yadcf#501]
With the recent addition of regex_checkbox buttons to each column we can now have both regex and exclude checkboxes available. During state saving restoration though, the filter keeps only the first 6 characters of the saved regex, if exclude checkbox is available for the column filter.

Following regex value `^([^0-9]*)*$` is then restored as this: `^([^0`, keeping only the first 6 characters.

**Comment by vedmack** [comment]
fixed by you
