### ISSUE TITLE
Include current src changes in the npm install

### ISSUE THREAD

**Issue by konuch** [vedmack/yadcf#503]
Hello Daniel, 

we are looking for a way, we could get the latest changes of the ./src/* via npm install. Currently, even if a pull request is accepted for the file in ./src/ folder, we can't get the changes via npm, until they are also copied to root file or to ./dist/ folder as beta. 
We can target your plugin directly via github url path in the package.json, so we can get to the up-to-date master branch, but it still only downloads the release or beta file.
This is probably due to the following package.json part:
```
  "files": [
    "jquery.dataTables.yadcf.js",
    "jquery.dataTables.yadcf.css"
  ],
```
Could we please somehow add also the latest src file to the package,json, so we can work with the latest changes in our project?

Thanks,
Rado

**Comment by vedmack** [comment]
Hi

Use npm install yadcf@beta for the latest beta version (es5), it should include beta 0.9.4-beta.8

Daniel

**Comment by konuch** [comment]
Thanks for the hint,

setting "yadcf": "beta" in package.json did the trick. :)

Rado
