### ISSUE TITLE
Chosen Multiselect - Sort by added, not by Name

### ISSUE THREAD

**Issue by wattzor** [vedmack/yadcf#505]
Hello! Is it posible to have the chosen multiselect to sort by the value im adding, insteed as it its right now by A-z 

Thansk!

**Comment by vedmack** [comment]
Yes, use the[ `sort_as` property](https://github.com/vedmack/yadcf/blob/630ee39247140e8d351e0ac5523ee0faf7a1cff6/jquery.dataTables.yadcf.js#L143)

next time please ask questions on stackoverflow
