### ISSUE TITLE
By default, display table empty?

### ISSUE THREAD

**Issue by martinmurciego** [vedmack/yadcf#506]
Greetings, I want to ask you about a behavior that they asked me exclusively to achieve with the DataTables that I do not find how to achieve it.
In my scenario, I retrieve data from a server (node ​​js) that returns data in json format and I have it paged from the DataTables configuration.
But I was asked that the default listing does not show any rows unless a filter is written that has matching results. How I do this?

I'm not sure, but is it possible that the datatables have already downloaded all the records before showing them?

**Comment by vedmack** [comment]
Hi,

Note that question should be asked on stackoverflow (tagged with yadcf)

It is possible, all you need to do is send empty data to datatables and send the yadcf filter data `yadcf_data_0` /  `yadcf_data_1` / etc... with columns distinct values
