### ISSUE TITLE
By default, display table empty

### ISSUE THREAD

**Issue by martinmurciego** [vedmack/yadcf#507]
Greetings, I want to ask you about a behavior that they asked me exclusively to achieve with the DataTables that I do not find how to achieve it.
In my scenario, I retrieve data from a server (node ​​js) that returns data in json format and I have it paged from the DataTables configuration.
But I was asked that the default listing does not show any rows unless a filter is written that has matching results. How I do this?

I'm not sure, but is it possible that the datatables have already downloaded all the records before showing them?

Could it be that a filter should be created for empty / null / white that does not return records? Of course, the default filter applies to all columns. Is there any way to apply it to all?

My Config tiene:
bLengthChange: true,
lengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "Todas"]],
pagingType: "first_last_numbers",
pageLength: 5,
data: dataSet,
ajax: "/reservas/json/",
sAjaxDataProp: "datos.reservas",

**Comment by vedmack** [comment]
I think you can achieve it only by using `serverSide: true` , because in this mode you can feed the filters from your server unrelated to the datatables data while in you current setup filters are being fed from the data that your datatables are being fed, you can go and ask @
