### ISSUE TITLE
oScroll has been deprecated

### ISSUE THREAD

**Issue by charlesnoble** [vedmack/yadcf#508]
Great work Daniel, super awesome script.

Using:
Datatables 1.10.3
yadcf 0.9.3

When I turned on "responsive: true" for Datatables, an error started emerging here:

```
if (settingsDt.oScroll.sX !== '' || settingsDt.oScroll.sY !== '') {
```

From what I can understand on the DataTables docs, the oScroll setting is no more.

**Comment by vedmack** [comment]
Thanks, please provide a simple test page(jsfiddle) with responsive set to true so I will debug and see which object is there now...
