### ISSUE TITLE
Problem with Yadcf Plugin when used with Data Table Excel Export @ Server Side Processing

### ISSUE THREAD

**Issue by sarangshaikh2011** [vedmack/yadcf#509]
Hello sir, I am using Yadcf plugin in server side processing. It is working excellent. But when I integrate Export button of jquery data table it is working good upto I dont apply any filter on table using yadcf. As soon as I apply filter on column the export button disabled.

Can you please help with it. Thankyou

**Comment by vedmack** [comment]
Please provide a test page showing your issue
