### ISSUE TITLE
request for feature - input delay 

### ISSUE THREAD

**Issue by keithpjolley** [vedmack/yadcf#51]
hi vedmack,
i'm was wondering if you could incorporate something similar to: http://lab.narf.pl/jquery-typing/ into yadcf. maybe it's easy enough for me to add the previous into my script myself but it seems the most logical way of incorporating this feature would be to have a variable for each column which specifies the timeout. Default could be "0" to continue to have same behaviour as now.
thanks,
keith

**Comment by ismailyilmaz** [comment]
hi folks, i want to delay to search search until 3 characters been typed or enter is clicked! there are many sampes without yadcf, and those work well, but same methods doesnt work with yadcf.. please help me how to do it.. thanks in advance.
