### ISSUE TITLE
Feature request: Support more than column_number, like columnDefs.targets

### ISSUE THREAD

**Issue by VictorioBerra** [vedmack/yadcf#513]
Just like [`columnDefs.targets`](https://datatables.net/reference/option/columnDefs.targets) it would be nice to support a class name.

I have a set of default `<th>` columns across a few of my tables, some define them in different orders. Because of this, I use the `string` target type so my defs are matched up to the column name and everything just works.

Being forced to provide a 0-based index to `column_number` throws a wrench in my setup. I now have to iterate the `<th>` columns and store my YADCF definitions in such a way that they can be retrieved by a name, and then I must assign numbers. This is some pretty unfortunate boilerplate.

Please support a `target` options that can take a string.

**Comment by vedmack** [comment]
Please provide a minimal code sample to explain what do you exactly mean / which to work that way...

**Comment by VictorioBerra** [comment]
## Desired Feature:

```html
<table>
    <tr>
        <th class="Description">Description</th>
        <th class="Name">Name</th>
    </tr>
</table>
```

```javascript
  var myTable = $('#example').DataTable();
  
  yadcf.init(myTable, [
    { targets : '.Name' }
]);
});
```

Notice how to init a `yadcf` column I can now use `targets: '.classname'`.

Imagine now, that I can re-use the `yadcf.init` all around my code base and the order of my columns no longer matter.

**Comment by vedmack** [comment]
Please post a minimal working example (jsfiddle / etc)

**Comment by VictorioBerra** [comment]
@vedmack 

http://jsfiddle.net/Lord_Zero/7zx8htof/40/

Both tables share the same `columnDefs`, and the same yadcf options. But the HTML tables define the columns in different orders. This is currently not possible with yadcf because the library forces us to provide the column index instead of letting us provide any `[column-selector](https://datatables.net/reference/type/column-selector)` we want.

**Comment by vedmack** [comment]
Try [0.9.4.beta.10](https://github.com/vedmack/yadcf/blob/b2d9b1e9096a1909ed95dca41f9ac8a6181ea0e4/src/jquery.dataTables.yadcf.js), see it in [action here](http://jsfiddle.net/vedmack/whqyctap/)

Usage is as follows (notice its not camel case since from the start I used `_` separated:

`column_selector: '.Description',`

**Comment by VictorioBerra** [comment]
@vedmack Great job on this! I appreciate it. I am also thankful that [you pass the `column_selector` option directly to `.column()`](https://github.com/vedmack/yadcf/commit/b2d9b1e9096a1909ed95dca41f9ac8a6181ea0e4#diff-c5f14c47326ce9906489498bd5fbe212R687) thereby making it more flexible for us.

When do you expect to do a release?

**Comment by vedmack** [comment]
@VictorioBerra, you are welcome...  if you referring the npm module update - then I will update the beta on npm the day after tomorrow

**Comment by VictorioBerra** [comment]
Checking in, any word on the NPM package?

**Comment by vedmack** [comment]
Heya...
npm install yadcf@beta
