### ISSUE TITLE
Use form-control class on filter of type range_number breaks the display

### ISSUE THREAD

**Issue by MaximBG** [vedmack/yadcf#515]
In version 0.9.1 I used range_number filter together with form-control class.
After upgrade to 0.9.4 I found that this combination breaks the display.
```
filter_type: "range_number",
style_class: "form-control"
```
Removing style_class: "form-control" fixes the issue,

**Comment by vedmack** [comment]
please provide a test page showing your problem and even better show screen shot of the problematic phenomena

**Comment by MaximBG** [comment]
I found, that in 0.9.1 it probably was a bug - the class, that was specified in _style_class_ when using _filter_type: "range_number"_ was ignored. Looks like in 0.9.4 the mentioned bug was fixed which caused undesirable effects in display. So please ignore this issue.
