### ISSUE TITLE
YADCF not working with ajax based tables

### ISSUE THREAD

**Issue by dwichelo** [vedmack/yadcf#516]
First of all, thank you for this library. Its filtering functions work perfectly fine in combination with dom sources tables.

However, my ajax tables refuse to work.

After my tables have been succesfully made YADCF is initialised.
Line 3809 in the source code (version 0.9.3) is hit twice, where the first time the fnSettings() method is found. Immediately after this code is hit again and now the fnSettings() method is not available, throwing the error below:

![afbeelding](https://user-images.githubusercontent.com/7196191/49011515-f72a9c80-f176-11e8-8165-5fe4d933efc1.png)

I've not been able to reproduce this behaviour in a jsfiddle. 

What I don't quite get is why this API call is made in the first place. According to [this piece of datatable documentation](https://datatables.net/upgrade/1.10-convert) fnSettings is an old API call, which is now replaced by settings().

If I were to remove the lines which break YADCF and replace them with new API methods, the console no longer spawns any errors, but the filtering doesn't always function either.

**Comment by vedmack** [comment]
Hi
Try to use this jsfiddle http://jsfiddle.net/vedmack/whqyctap/ to reproduce your issue and post the updated link, if not then provide a lint to other test page, otherwise I can't help, in addition - use the latest yadcf beta (src version) in your test page

**Comment by dwichelo** [comment]
I was unable to reproduce my problem in the fiddle you provided, so I decided to look further.

Apparently, the datatable API returned 'table' as the instance selector, which would target all my tables on the page and initialize YADCF on each and every one of those, failing in the process.

The following is a screenshot of YADCF source code:
![afbeelding](https://user-images.githubusercontent.com/7196191/49160143-5975cf80-f326-11e8-80b9-19e3ac0e7fbe.png)


Removing line 4037 and 4039 seems to fix the issue. Nevertheless, it is still curious why the API returned this incomplete selector.

**Comment by vedmack** [comment]
Please post your job code to init table and yadcf filters

**Comment by dwichelo** [comment]
No can do. The code is not mine to share unfortunately.
