### ISSUE TITLE
please provide me full working code of cumulative filter, the code which has been given at showcase is not working properly

### ISSUE THREAD

**Issue by jagtappravin** [vedmack/yadcf#517]
i searched for cumulative filter  example, but i doesn't get any working code.

**Comment by vedmack** [comment]
Question should be asked on stackoverflow and tagged with yadcf - http://stackoverflow.com/questions/tagged/yadcf , that way more people
will be able to help you and your questions will be easier to find for others

Use github for bug reports or new features request only

In case of bug always post a code sample that resembles your issue or event better provide a link to your page
