### ISSUE TITLE
Selectize bug (initSelectPluginCustomTriggers 'select_type': 'custom_select' )

### ISSUE THREAD

**Issue by joneidejohnsen** [vedmack/yadcf#522]
I'm still experiencing the problem with Selectize as a custom_select, as described here: [https://stackoverflow.com/questions/35830152/yadcf-custom-select-selectize-bizarre-behavior?rq=1](https://stackoverflow.com/questions/35830152/yadcf-custom-select-selectize-bizarre-behavior?rq=1)

Has anyone managed to find a solution for this?

**Comment by vedmack** [comment]
please post an updated jsfiddle sample test with the latest yadcf beta

**Comment by joneidejohnsen** [comment]
See [https://jsfiddle.net/joneidejohnsen/xpvt214o/981183/](https://jsfiddle.net/joneidejohnsen/xpvt214o/981183/).

I'm also experiencing the same problem using bootstrap-select (https://github.com/snapappointments/bootstrap-select/) as a custom selector.

**Comment by joneidejohnsen** [comment]
I would appreciate if you can confirm that this is actually I bug, or if it is due to a misconfiguration from my side.

**Comment by vedmack** [comment]
fixed in 0.9.4.beta.11 (npm beta module not updated yet)

**Comment by vedmack** [comment]
@joneidejohnsen see working jsfiddle, I also fixed your selectize init functions so take a look

http://jsfiddle.net/vedmack/a6jobz9p/12/

`

     $(document).ready(function() {
        table = $('#example').DataTable();
    
 
  	yadcf.initSelectPluginCustomTriggers(
      function($filterSelector) {
        $filterSelector.selectize({});
      },
      function($filterSelector) {
        $filterSelector.selectize()[0].selectize.destroy();
        $filterSelector.selectize({});
      },
      function($filterSelector) {
        $filterSelector.destroy()
    	}
    );
    yadcf.init(table, [
    	{
      	'column_number': 2,
  			'filter_type': "multi_select",
  			'select_type': 'custom_select'
    	}
    ]);
     
    
});`

**Comment by joneidejohnsen** [comment]
Thank you for the quick fix!
