### ISSUE TITLE
range_date filter with bootstrap-datetimepicker date format issue (moment_date_format)

### ISSUE THREAD

**Issue by Vatvat99** [vedmack/yadcf#524]
I'm unable to make the range_date filter of yadcf to work. I'm using it with datatables.net.

I'm using this date format for the original data passed to datatable : YYYY-MM-DDTHH:mm.
And I'm using this format to display the date in the datetime-picker : DD/MM/YYYY.

I have looked inside the yadcf plugin to see what it does, and it seems to get the row date from the original value passed to datatable (which in my case is in this format : 'YYYY-MM-DDTHH:mm') and read it with the format provided in moment_date_format. Then it compares this date with the ones in the range filter, those dates are in this format : 'DD/MM/YYYY', but yadcf still reads it with the format provided in moment_date_format.

Here is the jsfiddle which demonstrate the problem : http://jsfiddle.net/vatvat99/go5mxw0d/32/

Thanks for your help.

**Comment by vedmack** [comment]
fixed in 0.9.4.beta.11 (npm beta module not updated yet)
