### ISSUE TITLE
select2 and select filters in one table bug

### ISSUE THREAD

**Issue by ecsos** [vedmack/yadcf#525]
If you have a select filter and a select2 filter, and you filter by the select, and then filter by the select2, javascript errors ensue.. the problem is that the code expects all select2, or none.

All the select2 selects have an additional class of select2-hidden-accessible, so in the code if you replace all of the css selectors for select.yadcf-filter in the "if select2 sections" with select.yadcf-filter.select2-hidden-accessible , then the problem goes away.  This doesn't seem ideal though and I think you might know a better way. 

Thank you. For now I'm going to just use select2 everywhere on this table.

**Comment by vedmack** [comment]
Hi,
pleases provide  a jsfiddle test page showing the issue
