### ISSUE TITLE
Support custom delimiter for range filters

### ISSUE THREAD

**Issue by misanek** [vedmack/yadcf#527]
Currently if we have range filter, like range_number, it adds `-yadcf_delim-` string as delimiter to value, which is sent to REST.

It would be useful, if we had some global setting for custom range delimiter, eg.: ` custom_range_delimiter: '-my-custom-delimiter' `

**Comment by vedmack** [comment]
fixed in Merge pull request[ #528 ](https://github.com/vedmack/yadcf/pull/528)

looks ok, but know that you better set it once as a global parameter for yadcf instead of per column, I will probably rename it name (will update in this thread later on)

thanks

**Comment by konuch** [comment]
Hey, is there currently a global parameter for this feature?
