### ISSUE TITLE
Headers width don't align with table columns width

### ISSUE THREAD

**Issue by Wouter8** [vedmack/yadcf#529]
When filtering my table on smaller screens (iPad for example) the table doesn't align properly with the headers. See: https://imgur.com/a/Q9OsAvG

When executing a redraw on the table via the console it renders it correctly again: https://imgur.com/a/o0OSMDg

I can't find an event which I can execute the redraw on. How can I solve this issue? I am using Scroller and Responsive plugins.

**Comment by vedmack** [comment]
please provide a jsfiddle test page

**Comment by Wouter8** [comment]
Can't get the jsfiddle to work at all. Responsiveness just doesn't seem to do anything there.

**Comment by vedmack** [comment]
Then please provide any other link so I can take a look at it

**Comment by Wouter8** [comment]
The problem is not because of this plugin. Since I'm fetching data with ajax constantly I have to recalculate the width of columns when the data is loaded. I added this to DataTables' ajax "complete" option.

```
table.columns.adjust().responsive.recalc();
```
