### ISSUE TITLE
DataTable Editor Conflicts 

### ISSUE THREAD

**Issue by Sheepy69** [vedmack/yadcf#533]
Hello, i try this example from this link : https://jsfiddle.net/fojp91zx/25/ . It works but the difference is that i am using DataTable editor and when i whrote the link for the editor js and css . It conflict with your plugin. My data is loading from ajax with a php script using Editor Class to generate the json.
So my question is :  Your plugin is compatible with DataTable Editor ? Or just with basics features of DataTable ?

**Comment by Sheepy69** [comment]
wrote*

**Comment by vedmack** [comment]
@Sheepy69 , Haven't tested my self but it should work, provide a link to a page that shows that conflict.
