### ISSUE TITLE
initMultipleTables trows a TypeError: "tablesArray[i] is undefined"

### ISSUE THREAD

**Issue by slaap123** [vedmack/yadcf#534]
yadcf.initMultipleTables(tables, [
                    {
                        filter_container_id: 'multi-table-filter',
                        filter_default_label: 'Filter all tables!',
                        column_data_type: "rendered_html",
                        html_data_type: "text",
                    }]);

gives a an error on the line 4296
"setOptions(tablesSelectors + '_' + column_number_str, dummyArr, tablesArray[i].table);"
the i in this line comes from a for loop that is clossed on line 4293 

changing the line to "setOptions(tablesSelectors + '_' + column_number_str, dummyArr);" as it was in version 9.3 fixes the issue. 
but if you want to keep the specifix table in the set option  seround the line i a new for loop

**Comment by vedmack** [comment]
@slaap123 please provide a link to  test case

**Comment by slaap123** [comment]
Here you go,
[https://jsfiddle.net/z3nt6j9m/](url)

**Comment by vedmack** [comment]
fixed in 0.9.4.beta.14
