### ISSUE TITLE
Change DatePicker langage on yadcf

### ISSUE THREAD

**Issue by mohamed-jebri** [vedmack/yadcf#536]
this is my question : 
https://stackoverflow.com/questions/54233373/change-datepicker-langage-on-yadcf

we're facing an issue with the datepicker for filter_type date/range_date.

I would like to change the langage of datepicker from english default to french

**Comment by vedmack** [comment]
You can find the relevant information on [datepicker website](https://api.jqueryui.com/datepicker/) , read the *Localization* section

> Localization
Datepicker provides support for localizing its content to cater for different languages and date formats. Each localization is contained within its own file with the language code appended to the name, e.g., jquery.ui.datepicker-fr.js for French. The desired localization file should be included after the main datepicker code. Each localization file adds its options to the set of available localizations and automatically applies them as defaults for all instances. Localization files can be found at https://github.com/jquery/jquery-ui/tree/master/ui/i18n.

The $.datepicker.regional attribute holds an array of localizations, indexed by language code, with "" referring to the default (English). Each entry is an object with the following attributes: closeText, prevText, nextText, currentText, monthNames, monthNamesShort, dayNames, dayNamesShort, dayNamesMin, weekHeader, dateFormat, firstDay, isRTL, showMonthAfterYear, and yearSuffix.

You can restore the default localizations with:

$.datepicker.setDefaults( $.datepicker.regional[ "" ] );
And can then override an individual datepicker for a specific locale:

$( selector ).datepicker( $.datepicker.regional[ "fr" ] );

**Comment by mohamed-jebri** [comment]
Thanks 👍 
I found this solution for my problem 
` $.datepicker.regional['fr'] = {clearText: 'Effacer', clearStatus: '',
                    closeText: 'Fermer', closeStatus: 'Fermer sans modifier',
                    prevText: '<Préc', prevStatus: 'Voir le mois précédent',
                    nextText: 'Suiv>', nextStatus: 'Voir le mois suivant',
                    currentText: 'Courant', currentStatus: 'Voir le mois courant',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin',
                        'Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
                    monthNamesShort: ['Jan','Fév','Mar','Avr','Mai','Jun',
                        'Jul','Aoû','Sep','Oct','Nov','Déc'],
                    monthStatus: 'Voir un autre mois', yearStatus: 'Voir un autre année',
                    weekHeader: 'Sm', weekStatus: '',
                    dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
                    dayNamesShort: ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'],
                    dayNamesMin: ['Di','Lu','Ma','Me','Je','Ve','Sa'],
                    dayStatus: 'Utiliser DD comme premier jour de la semaine', dateStatus: 'Choisir le DD, MM d',
                    dateFormat: 'dd/mm/yy', firstDay: 0,
                    initStatus: 'Choisir la date', isRTL: false};
                $.datepicker.setDefaults($.datepicker.regional['fr']);`
