### ISSUE TITLE
Individual Search Columns in the footer with ScrollX not searching properly

### ISSUE THREAD

**Issue by krishnapandya26** [vedmack/yadcf#540]
When the filters are placed in the footer in combination with the ScrollX, the reset button does not work and the filter type "range_date" does not filter the data.
Provided the following jsfiddle, https://jsfiddle.net/jxhp4Lgu/2/

Also, I want to add fixedColumns in the datatables,but the filter for the fixedColumns does not filter the data correctly.Provided the following jsfiddle,https://jsfiddle.net/y17rtfej/ for the fixedColumns

Can you please also let me know what is the correct way to add footer to the table?

**Comment by vedmack** [comment]
The issues related to `footer` will be fixed, as to the fixed column:

> At the moment there is no support with fixed columns because of luck of an API to integrate with (yadcf does support fixedHeaders)

https://github.com/vedmack/yadcf/issues/388#issuecomment-280902916

**Comment by krishnapandya26** [comment]
Thank you for the reply. I will wait for the bug to be fixed.

**Comment by vedmack** [comment]
fixed in [0.9.4.beta.14  ](https://github.com/vedmack/yadcf/commit/232d4a3d5c91c1be4c6a76394eb1db3addc24d3d)
see [working test page](http://jsfiddle.net/vedmack/m0rz9b15/)

**Comment by krishnapandya26** [comment]
Thank you for the quick fix. 
In my application I have used datatables at many places and I donot use "scrollX" for all the tables.
So, I have some tables with "scrollX" and some without "scrollX". The fix doesnot work for type "range_date" for tables without "scrollX".

**Comment by vedmack** [comment]
it worked before? again, always provide a jsfiddle test page so I can see the issue

**Comment by krishnapandya26** [comment]
Yes it worked before for tables without "scrollX".

These are the jsfiddle for - 
1. Without "scrollX" and older version* - http://jsfiddle.net/2w61x9kh/1/ - works perfectly
2. With "scrollX" and older version - http://jsfiddle.net/2w61x9kh/2/ - didnot work with "range_date" and reset button
3. Without "scrollX" and version 0.9.4.beta.14 - http://jsfiddle.net/5jhpobyz/1/ - issue with "range_date"
4. With "scrollX" and version 0.9.4.beta.14 - http://jsfiddle.net/5jhpobyz/ - works perfectly

*older version I used in my application was - version 0.9.4.beta.10

**Comment by vedmack** [comment]
@krishnapandya26 fixed in 0.9.4.beta.15

**Comment by Namoshek** [comment]
This issue seems to also apply to basic select filters (select2/chosen not tested). With `scrollX`, using select filters in the table footer doesn't work. Am I doing something wrong or is it possible your fix doesn't apply to select filters?
