### ISSUE TITLE
Multiple Tables does not support range_number

### ISSUE THREAD

**Issue by zatix16** [vedmack/yadcf#541]
Hi,

I'm sorry if this has been raised before. I tried using data range and multi-tables together and is getting error of "Filters Multiple Tables does not support range_number". Is this not supported?
Thanks in advance.

**Comment by vedmack** [comment]
Hi
Yup, multiple tables support only text / select / multi select filter types, I will mark this issue as enhancement but since multiple tables never was popular in yadcf I can't promise it will be implemented any time soon.

p.s

PR for this feature is more than welcome.

Daniel

**Comment by zatix16** [comment]
Hi Daniel,

Thanks for your reply, I use multi table as a tweak for main table that
require a rowspan and will be stripped off to a single html line when being
exported to excel. Not sure if there is a workaround for yadcf and rowspan.
Thanks again.

**Comment by vedmack** [comment]
@zatix16 you can provide a minmal jsfiddle test page with that rowspan example and I'll see whats going on

**Comment by zatix16** [comment]
Hi Vedmack,

Here is my fiddle https://jsfiddle.net/zatix16/ybhzquck/
I created a nested table to show my table as rowspan since I cannot use rowspan in yadcf.
My table is displaying from mysql query which one person will have 2 statements and then 2 statements will have another two levels and ratings. In my example I used datatable as I cannot find a direct link to yadcf js and css. The export button will make the nested table shows on one column in a line. 

What I did with multitables is creating another table that shows my result repeatedly without a rowspan, then use PDF export to export the data without the rowspan. Appreciate your advices.

**Comment by vedmack** [comment]
@zatix16 your test page does not include any js code nor js files

**Comment by vedmack** [comment]
Hi, since adding new filters to multiple table is not going to happen any time soon and if enabling range_number or range_date (I think you confused between them) is relevant for you use case please modify your jsfiddle with a relevant setup (notice column number you use (first column is *0*) and post update jsfiddle test page which I will try to see if possible to fix

**Comment by zatix16** [comment]
Hi Vedmac,

It is actually column number 5 for the submitted date. Sorry, my mistake.
Here is the correct one https://jsfiddle.net/zatix16/ybhzquck/19/

**Comment by vedmack** [comment]
@zatix16  Not sure that I understood your issue, you want to filter a single table that got row spans? is so, please post a jsfiddle with that single table and with relevant yadcf code

use this as resources in jsfiddle

[yadcf js](https://raw.githack.com/vedmack/yadcf/b53c4b1233de220b0841e34beea667eb8a07e5c3/src/jquery.dataTables.yadcf.js)

[yadcf css](https://raw.githack.com/vedmack/yadcf/master/jquery.dataTables.yadcf.css)

**Comment by zatix16** [comment]
Hi Vedmack,

I have included my code in here for single table with rowspan and filter
https://jsfiddle.net/zatix16/ybhzquck/20/
It works if I removed the rowspan.

Thanks in advance.

**Comment by vedmack** [comment]
@zatix16 I don't see it working without yadcf, 
first you must make sure that the `$('#example').dataTable();` works, right now its throwing *Uncaught TypeError: Cannot set property '_DT_CellIndex' of undefined*
please make sure your code works regardless of yadcf first

**Comment by zatix16** [comment]
Sorry for being a pain, please refer below for the two links one which is
working and the one that is not working.

Working code without rowspan on the table:
https://jsfiddle.net/zatix16/ybhzquck/24/
Not working code with rowspan on the table:
https://jsfiddle.net/zatix16/ybhzquck/26/

Thanks
