### ISSUE TITLE
CSS missing in last 0.9.4 release

### ISSUE THREAD

**Issue by carlosvega** [vedmack/yadcf#549]
Good morning, 

I just noticed that from the last 0.9.4 beta to the 0.9.4 release, the CSS files disappeared.

https://cdnjs.com/libraries/yadcf/0.9.4

https://cdnjs.com/libraries/yadcf/0.9.4-beta.13

Is this a mistake or is it intentional? The github repository still have these files.

**Comment by vedmack** [comment]
Hi

Looks like I accidentally released 0.9.4 (instead of 0.9.4.beta.5 some time ago),  0.9.4 is still in beta phase... and the one in https://cdnjs.com/libraries/yadcf/0.9.4 is actually 0.9.4.beta.5,

Thanks for noticing, b.t.w In case I wont be able to remove 0.9.4 from npm I will release 0.9.5
