### ISSUE TITLE
If tables have same ids, yadcf breaks

### ISSUE THREAD

**Issue by misanek** [vedmack/yadcf#550]
If we have one table and we destroy it and then we init new table with same id, but with different columns, filtering breaks.
jsFiddle: http://jsfiddle.net/1jkufqta/4/ 
click on reinit and than type value in range filter, filtering won't work and  in console there is an error.

So far i tried to add `$.fn.dataTableExt.afnFiltering = []` to removeFilters function, but it is not working either.

**Comment by vedmack** [comment]
Hi

Till I do the commit you can add this code
```

if ($.fn.dataTableExt.afnFiltering.length > 0) {
    $.fn.dataTableExt.afnFiltering.splice(0, $.fn.dataTableExt.afnFiltering.length);
}
```

Inside the `function removeFilters(oTable) {` function before the `destroyThirdPartyPlugins(oTable);` line

**Comment by misanek** [comment]
updated according to comment, PR #551 
Thanks for quick fix

**Comment by vedmack** [comment]
tx for the PR

**Comment by misanek** [comment]
@vedmack  could you please publish new beta ? thanks

**Comment by vedmack** [comment]
@misanek done
