### ISSUE TITLE
Using orthogonal data and text_data_delimiter with columns.data function

### ISSUE THREAD

**Issue by tanyona** [vedmack/yadcf#553]
This is related to #552 .

It is also possible to use a function when defining orthogonal data. An example is on the following jsfiddle https://jsfiddle.net/4jre6fsa/1/. The filtering works correctly using the datatables search box, but an error is raised in the console when `yadcf.init` is used.

Not sure if the latest fix works correctly with this but perhaps this can be tested.

**Comment by vedmack** [comment]
Added in 0.9.4.beta.22

see it working https://jsfiddle.net/vedmack/c2hyzsne/

Note this code:` column_data_type: 'rendered_html'`
