### ISSUE TITLE
startsWith being ignored when exclude option set

### ISSUE THREAD

**Issue by flippery-fish** [vedmack/yadcf#557]
When startsWith is used in conjunction with the exclude option, startsWith is ignored

Simple example at http://jsfiddle.net/flippery_fish/pezx26wq/19/ 

If you filter on 48 with startsWith and exclude selected it should only exclude 481000, but it also excludes 100048 and 104800

I believe the regex might be "^((?!" + selected value + ").)" instead of "^( + selected_value + ").)*$"

**Comment by vedmack** [comment]
fixed in 0.9.4.beta.20
