### ISSUE TITLE
Using Multiselect and exclude don't work together

### ISSUE THREAD

**Issue by pricejt** [vedmack/yadcf#559]
If my code uses multiselect and exclude the exclude box is removed. 
 {
                column_number: 7,
                filter_type: "multi_select",
                select_type: "select2",
                text_data_delimiter: ",",
                exclude: true
            },

See the comments box, that it no longer has an exclude checkbox. 

![image](https://user-images.githubusercontent.com/2791439/54694239-4c136980-4afe-11e9-9156-72fb03c2d1d4.png)

Is this how it should work? It would be nice to exclude multiple items to narrow down results.

**Comment by vedmack** [comment]
Hi,

Its "Currently available for the text filter" , but it can be added to multi select filter type, it shouldn't be a big deal, consider sending a PR or wait for it

**Comment by vedmack** [comment]
most of the "logic" is to replace `stringForSearch` in `oTable.fnFilter(stringForSearch, column_number_filter, true, false, true);` with `"^((?!" + stringForSearch + ").)*$"` inside the  `doFilterMultiSelect`, just need to add the regex checkbox (like in text filter) and adding a check if its checked while generating the `stringForSearch` in the `doFilterMultiSelect` function
