### ISSUE TITLE
multi_select_custom_func not considered in exGetColumnFilterVal

### ISSUE THREAD

**Issue by carlosvega** [vedmack/yadcf#562]
multi_select_custom_func is not considered in exGetColumnFilterVal rising an error:

`exGetColumnFilterVal error: no such filter_type: multi_select_custom_func`
 
https://github.com/vedmack/yadcf/blob/master/src/jquery.dataTables.yadcf.js#L4669

JSBin: http://live.datatables.net/yuqumamo/1/edit

If you download this[ HTML+JS file](https://pastebin.com/raw/c49UHSEJ) and run it in the browser you'll see the following error:

`exGetColumnFilterVal error: no such filter_type: multi_select_custom_func`

**Comment by vedmack** [comment]
Hi. please provide a jsfiddle test page so I can debug / etc

**Comment by carlosvega** [comment]
I just updated the issue.

**Comment by vedmack** [comment]
fixed in 0.9.4.beta.24
