### ISSUE TITLE
Number filter not filtering by zero value 

### ISSUE THREAD

**Issue by misanek** [vedmack/yadcf#563]
commit 795460cfad7466beb69a2115b24fae45f6fbdbdb intorduced bug when using data json with 0 values.

dot2obj function return `"" `instead of` 0`  from object with property `id: 0`

jsfiidle before commit: http://jsfiddle.net/vh64xbtr/1/

jsfiddle with commit :  http://jsfiddle.net/z1oe3ucg/

**Comment by vedmack** [comment]
fixed by @misanek https://github.com/vedmack/yadcf/pull/568
