### ISSUE TITLE
Excel Like cumulative_filtering [feature request]

### ISSUE THREAD

**Issue by klukiyan** [vedmack/yadcf#565]
Currently `cumulative_filtering` is correctly limiting the select list of other columns, while it doesn't correctly limit the current column `self`. 
Not only it prevents multiselect with `cumultative_filtering:true` but also becomes very confusing to excel users.

Can this feature be upgraded in a way that cumulative_filtering is applied to rest of columns but not to `self`.
Thank you

**Comment by tynort** [comment]
I had the same problem with it. This happens when you use ajax.
I solved this to add condition in 
'if (!columnObj.select_type_options || !columnObj.select_type_options.ajax) {'

`if ((!columnObj.select_type_options || !columnObj.select_type_options.ajax) && $filter_selector[0].selectedIndex<0) `

**Comment by klukiyan** [comment]
@tynort ,

Besides cumulative filtering, I couldn't make it work with JS object isntead of DOM, which prevented me from using `deferRender`. So I just wrote my own function that supports "excel like" cumulative filtering with deferRender and bootstrap-select for beautiful multiple selects.

**Comment by vedmack** [comment]
@klukiyan can you elaborate / give an example to your original comment? because in the showcase it does allow selecting from the same column http://yadcf-showcase.appspot.com/cumulative_filtering.html

**Comment by klukiyan** [comment]
@vedmack interesting. Some ~5 months ago when I started using yadcf, I guess there was another example, or something was different. On this particular example it seems to work well.
Maybe it's because of `select2` and `multi-select`. I was using single select without `select2` extension and with `cumulative_filtering` on each column was impacting not only other columns, but also self. So to select something from a column, users had to firstly click the [x] to deselect current selection in the column

**Comment by vedmack** [comment]
@klukiyan That showcase page wasn't touch for much more than ~5 months, in case that you have a specific example which does not work please post it here
