### ISSUE TITLE
More guidance for contributing?

### ISSUE THREAD

**Issue by louking** [vedmack/yadcf#576]
Suggest you enhance contributing.md. 

E.g., I am assuming the newest files are in the src directory, but it isn't clear. And I notice that there is no css file there. But the js file does seem to be later than that within the top directory and dist directory. And I'm guessing the dist directory is created automatically somehow, but that isn't clear how either.

Anyway, some guidance would be helpful to anyone who wants to contribute to help move this wonderful and very useful package along.

**Comment by vedmack** [comment]
https://github.com/vedmack/yadcf/wiki

let me know if missed something

**Comment by louking** [comment]
Thanks. I suggest referencing the wiki from contributing.md, and
referencing contributing.md from readme.md. Maybe others would think to go
to wiki, but I looked at contributing.md to see suggested practices.

Should we assume ok to do PR from master, or should it always be from
branch? I'm not that familiar with doing from master but I have seen this
requested in other repo contributing documents, so I guess it's possible.
