### ISSUE TITLE
Different value and display text for select filter element

### ISSUE THREAD

**Issue by kerbooo** [vedmack/yadcf#581]
```
    ...
    <td data-filter="text-for-filter">Display Text</td>
    ...
```

Hello, my datatable td's html codes as above and my yadcf filter settings as below

```
    ...
    yadcf.init(Datatable,
                                [{
                                    column_number: 0,
                                    style_class: "custom-select",
                                   html5_data: "data-filter"
                                },
    ...
```

After rendered html, result as below

```
    ...
    <option value="bla-bla">bla-bla</option>
    ...
```

I would like to get result as below. is it possible?

```
    ...
    <option value="text-for-filter">Display Text</option>
    ...
```

**Comment by vedmack** [comment]
please provide a test page (jsfiddle)

**Comment by kerbooo** [comment]
Hello again,

I have created an example into jsfiddle [https://jsfiddle.net/umtd07sj/1/](https://jsfiddle.net/umtd07sj/1/) 

I would like to show select element as below

```
<select id="yadcf-filter--TableTypes-0" class="yadcf-filter " onchange="yadcf.doFilter(this, '-TableTypes', 0, 'contains');" onkeydown="yadcf.preventDefaultForEnter(event);" onmousedown="yadcf.stopPropagation(event);" onclick="yadcf.stopPropagation(event);">
	<option value="-1">Select Types</option>
	<option value="types-car">Cars</option>
	<option value="types-fruits">Fruits</option>
</select>
```

**Comment by vedmack** [comment]
added in 0.9.4.beta.28  , see it working https://jsfiddle.net/vedmack/kq8avshw/

**Comment by tanyona** [comment]
I see this will require use of html data attributes. Would it be possible for it to work with the datatables [data ](https://datatables.net/reference/option/columns.data) option e.g. when using an ajax data source e.g.

```
columns: {
	"data": {
			_: "phone",
			filter: "phone_filter",
			display: "phone_display"
		}
	}
```

**Comment by vedmack** [comment]
@tanyona please open a new issue with jsfiddle test page and I will see what can be done
