### ISSUE TITLE
Empty yadcf settings array

### ISSUE THREAD

**Issue by ayyadalaa** [vedmack/yadcf#582]
I'd like to have the ability to give empty settings array object to the plugin so yacdf is not active even though it's applied to the datatable, like this:

```
var myDataTable= $('table').dataTable({
					}).yadcf( [ ]);
```

Because I'm providing dynamic options array based on a set of conditions and there's a case where no yadcf filter should appear at all. I'm currently tricking it by providing out of bound col number:

```
yadcfColumnsOptions = [{
  column_number: 500
}
```

But this causes a js error in the plugin.

Thanks,

**Comment by vedmack** [comment]
@ayyadalaa when no need on yadcf on your page why can't you skip yadcf init code at all?

**Comment by ayyadalaa** [comment]
Like this:
yadcf.init(myDataTable, yadcfColumnsOptions);

?

**Comment by vedmack** [comment]
I meant that you can call yadcf init only when its needed
if (ydcfFiltersNeeded) {
    yadcf.init(myDataTable, yadcfColumnsOptions);
}

**Comment by ayyadalaa** [comment]
Got it, thanks for your reply. I think this issue can be cancelled as invalid.

**Comment by ayyadalaa** [comment]
Worked well, just a note for whoever reading this thread:
Make sure to instantiate your datatable with capital D (as stated on yacdf site) like this:

```
var myDataTable= $('table').**D**ataTable({
//your datatable options
}).;
```
Thanks again!
