### ISSUE TITLE
yadcf mdbootstrap compatibility

### ISSUE THREAD

**Issue by user199226** [vedmack/yadcf#584]
Apparently, yadcf does not integrate well with material design bootstrap.

when using the "mdb-select" style class for a "multi_select" filter, i get very strange behaviors. The options for the dropdown never populate, and the checkboxes dont work.

I'm trying to achieve the "standard multiselect" style as shown in the example on this page ---->
https://mdbootstrap.com/docs/jquery/forms/multiselect/

yadcf.init(table, [
                            {
                                column_number: 1,
                                filter_type: "multi_select",
                                filter_reset_button_text: false,
                                style_class: "mdb-select",
                            }];

$('.mdb-select').materialSelect();

**Comment by vedmack** [comment]
@user199226 please read about initSelectPluginCustomTriggers first and play with it... then in case of issue post a link to a test case
