### ISSUE TITLE
Date filter does not work with the latest versions of JQuery-UI starting at v 1.11.1

### ISSUE THREAD

**Issue by cdeschervois** [vedmack/yadcf#585]
I have been using the date filtering for a while and I noticed it stopped working after updating to the last JQuery-UI stable version.  When a date is selected it always show an empty table. Here is a jsfiddle: 

https://jsfiddle.net/cdeschervois/y8agd6rz/9/

**Comment by vedmack** [comment]
please provide also a link to a working version with an older JQuery-UI plugin

**Comment by cdeschervois** [comment]
Hi, 
No problem, here is the same code and it is working with the older JQuery-UI  1.10.4: https://jsfiddle.net/cdeschervois/b6pq4ncw/1/

**Comment by vedmack** [comment]
Only thing I see that the `$.datepicker.parseDate` of the new jquery ui does not work (while the one in the older version does)

can you please pinpoint in which version exactly it stopped working and then I will look again at the change log of jquery ui and might find out the source of the problem

**Comment by cdeschervois** [comment]
it works up until 1.11.0, it looks like the issue was introduced with 1.11.1

https://jsfiddle.net/cdeschervois/pznakdcv/1/

**Comment by vedmack** [comment]
@cdeschervois sorry for the delay but it looks like an issue of jquery
Older jquery datepicker could accept `$.datepicker.parseDate("dd/mm/yy", "25/06/19 10:47 AM")` while the new one does not like the `19`, so It looks that you can change it into `2019` (four digit year) 
or try and figure out what in `Fixed: reject dates with two year digits when expecting 'yy' ` https://jqueryui.com/changelog/1.11.1/ affected/how this change in behavior

again you can change your *2 digits* year into *four digits*

**Comment by cdeschervois** [comment]
Ah good job spotting,  thanks! Using 4 digit for years made the problem go away, which is ok for me.
