### ISSUE TITLE
Minification failed. Strict-mode does not allow assignment to undefined variables: yadcfState

### ISSUE THREAD

**Issue by delianenchev** [vedmack/yadcf#586]
I'm getting this error when trying to minify yadcf in Visual Studio 2019 (ASP.Net Core project):

> Strict-mode does not allow assignment to undefined variables: yadcfState

Bindings:
yadcf@0.9.4.beta.28
jquery.dataTables.yadcf.js

**Comment by vedmack** [comment]
Hi

Not sure how can I help you and it might be even VS studio issue (google Minification failed. Strict-mode does not allow assignment to undefined variables:) 

but in case you need a minified yadcf you can grab it from [cdnjs ](https://cdnjs.com/libraries/yadcf/0.9.4-beta.28)
