### ISSUE TITLE
Display of values for slider-filters problematic

### ISSUE THREAD

**Issue by mbaas2** [vedmack/yadcf#593]
When the values used in the slider-filters gets large, they aren't fully shown...and may overlap with others columns.

Fiddle: https://jsfiddle.net/mbaas/g9vts4u5/6/

Unfortunately my CSS-Skills are not good enough to provide suggestions or even PR :(

**Comment by vedmack** [comment]
It looks like you havent include yadcf css file, see it with the css

https://jsfiddle.net/vedmack/01dpyxea/
