### ISSUE TITLE
jQuery.DataTables serverside processing + Bootstrap datetimepicker + yadcf

### ISSUE THREAD

**Issue by alecaceaes** [vedmack/yadcf#598]
The yadcf when using with datetimepicker from [eonasdan](https://github.com/Eonasdan/bootstrap-datetimepicker) when pressing anything will render the yadcf filter to the tables of the date picker.

I am using serverside processing, and it seems like its rerendering the table and the filters when pressing anything when the boostrap picker is open.

![asd](https://user-images.githubusercontent.com/16571466/67013897-74ac2200-f126-11e9-8e93-8f477d235b94.png)

**Comment by alecaceaes** [comment]
fixed by editing the code 

![image](https://user-images.githubusercontent.com/16571466/67073134-f6e52680-f1b8-11e9-91f2-7a41a754299d.png)

**Comment by vedmack** [comment]
You can send a PR with your fix then

**Comment by alecaceaes** [comment]
done creating PR, thanks for the library. really helped me on my projects.

**Comment by vedmack** [comment]
Also please post a test page / html / js code with your issue, maybe your problem can be solved without yadcf modifications
