### ISSUE TITLE
Filter not working on dynamic input in Firefox but in Chrome

### ISSUE THREAD

**Issue by alex-seitz** [vedmack/yadcf#602]
Hello,
I have a table with an editable cell that I update using the infalidate().draw() method. The filters get updated in both browsers but the filtering itself only works in Chrome. In Firefox I only get an empty table.

I have attached an example file where this is the case.
Here is a jFiddle: https://jsfiddle.net/alexseitz/sx9fgdw0/

This jFiddle shows that the data is present in the datatable and as I said, in Chrome the filtering works just fine.:
https://jsfiddle.net/afs68Lg7/

Additionally, is it possible to also select empty cells. The only example I found was to add the empty fields manually to the filter, which I then can't update with the dynamic content of the editable fields

Thank you in advance

Alex

**Comment by vedmack** [comment]
@alex-seitz , Hi in both test pages the filtered column is empty

**Comment by alex-seitz** [comment]
Hi,
you enter the Values in the contentEditable Fields, when. Afterwards the values are updated in the DataTable and can be selected in the Filter. However, the filtering itself only works in Chrome, in Firefox the result is always an empty table

**Comment by vedmack** [comment]
Its because of the <br> that for some reason are being added to the inputs,

I fixed it in 0.9.4.beta.31, you should add `ignore_char: '<br>'` to you filter

See working jsfiddle https://jsfiddle.net/su08z3f2/1/ (js file currently on my dropbox - lin in jsfiddle)

as to "empty cells." - please elaborate more about the scenario

**Comment by alex-seitz** [comment]
Thank you. It works great.
With the empty fields, I mean that I want to show only the rows where I did not add anything to the editable fields, so only the ones I left blank.
It is somewhat possible by adding the following two lines to the filter:
```
data: [ {value:'^$', label:'Empty' }],
filter_match_mode: 'regex'
```
but then the values I add to the cells no longer show up.

Best,
Alex

**Comment by vedmack** [comment]
I think you looking for `append_data_to_table_data` property, read more in the yadcf js file (docs)

**Comment by vedmack** [comment]
@alex-seitz  if it won't help you feel free to open a new issue with test page / scenario / expected / actual...

**Comment by alex-seitz** [comment]
@vedmack It works great, thank you for your help
