### ISSUE TITLE
Date range with jquery-ui datepicker disables "future" dates even after they have been cleared

### ISSUE THREAD

**Issue by snex** [vedmack/yadcf#603]
Page showing issue: https://poker.xens.org/hand_histories

When you use the date range filter on the above page, select a date in the past for the "To" date (e.g. August 1 2019). The "From" date correctly disallows selecting a date before this date. However, even after the filter is cleared out, the "From" date is being constrained by the previously chosen date.

**Comment by vedmack** [comment]
@snex Hi, please try this [yadcf version](https://www.dropbox.com/s/wtvywxpinqy54jn/jquery.dataTables.yadcf.js?dl=0)

if it won't work then provide me with a test page I can check myself

**Comment by snex** [comment]
The problem still persists, however now it seems to be preventing any date after the 1st of the month of the original chosen date (e.g, you selected Nov 17, then cleared the filters, it now disables Nov 1st and beyond). Unfortunately I am unable to push this to a live production site, but you should be able to reproduce the issue by following the steps provided.

**Comment by vedmack** [comment]
@snex try setting up a jsfillde page with minimal code that reproduces the issue and when it up post it here...
or just edit / debug yadcf code, 
bottom of the method `function rangeClear` , inside the `else if (columnObj.datepicker_type === 'jquery-ui') {` clause , you can modify it and see what works for you the best

**Comment by snex** [comment]
https://jsfiddle.net/x1k0f5s4/

Set the "To" date to 2019-09-01.

Notice the table data are correctly both filtered out.

Clear the filter.

The records correctly come back.

Click the "From" field.

Dates after 2019-09-01 are disabled.

**Comment by vedmack** [comment]
@snex try the following jsfiddle https://jsfiddle.net/t36emc8q/3/

It uses 0.9.4.beta.33 (u can grab it from the test page)

**Comment by snex** [comment]
This appears to fix it. Do you know when an official release will happen? I am using yarn/webpacker so having hacked files sitting around is probably not a good idea overall. Thanks.

**Comment by vedmack** [comment]
I   guess in a day or two a new beta will be out (it will be available on
npm)
