### ISSUE TITLE
Using different option value and text for select filter when using columns.data.filter property

### ISSUE THREAD

**Issue by tanyona** [vedmack/yadcf#604]
This is related to #581 

Would it be possible when using a select filter, to have the select value and the option text be different when using the columns.data property of datatables. Currently, the option text used is from the filter property.

An example jfiddle - https://jsfiddle.net/78xhybqn/1/

Datatables documentation on columns.data - https://datatables.net/reference/option/columns.data

**Comment by vedmack** [comment]
Yes, see the following example on how to

[working test page](https://jsfiddle.net/vedmack/zacy01L3/8/)

```
var data = [{
    "nameFilter": "one",
    "name": "1"
  },
  {
    "nameFilter": "two",
    "name": "2"
  },
  {
    "nameFilter": "one, two, three",
    "name": "1, 2, 3"
  }
];

var columns = [{
  "data": {
    _: "name",
    filter: "nameFilter",
    display: "nameFilter"
  }
}];

var table = $('#tb');
var dtable = table.DataTable({
  data: data,
  columns: columns
});

yadcf.init(dtable, [{
  column_number: 0,
  text_data_delimiter: ", "
}]);
```

**Comment by tanyona** [comment]
I would like the datatables search box to use 1, 2 or 3 as a filter. The idea is that the select displays one, two and three as options, but the search is on 1, 2, 3.
