### ISSUE TITLE
Add custom classes at yadcf-filter-wrapper-inner level

### ISSUE THREAD

**Issue by dwasyl** [vedmack/yadcf#607]
Currently, users can use `style_class` to add css classes to the `input` object, however, it is not possible to add any custom classes to the wrapper divs. This especially applies to multi-widget filters (such as the date range picker). These objects have both a standard `wrapper` and an `yadcf-filter-wrapper-inner` object.  Styling multi-widget filters often takes additional steps such that adding additional classes at the wrapper level is necessary.

Could there be an option to add custom css classes to either the `yadcf-filter-wrapper-inner` level or one of the more generic wrapper levels? (as then the option would apply to all filter types).

**Comment by vedmack** [comment]
@dwasyl why not style the existing classes such as `yadcf-filter-wrapper-inner`? the `style_class` support was added because of some third-party libraries that needed their own class to be present on inputs
