### ISSUE TITLE
Configure globally

### ISSUE THREAD

**Issue by bytestream** [vedmack/yadcf#610]
It would be good if we could set global defaults for the configuration, particularly for `language`

`$.fn.yadcf.defaults = {}`

I think it would just be a simple case of adding `$.extend({}, $.fn.yadcf.defaults, params)` here https://github.com/vedmack/yadcf/blob/master/dist/jquery.dataTables.yadcf.js#L4642

**Comment by vedmack** [comment]
Do you mean like this?

```
* Global Parameters (per table rather than per column)
*
* Usage example yadcf.init(oTable,[{column_number : 0}, {column_number: 3}],{cumulative_filtering: true});
```

The third argument is being applied to all columns

**Comment by bytestream** [comment]
No, I mean global for every table. https://github.com/vedmack/yadcf/pull/287 requires you to set `lang` on every table you want to change the language? I just want to set a languages definition once and it apply to every yadcf instance.

**Comment by bytestream** [comment]
@vedmack will you accept a PR for this? and when is the next release expected?

I need a single place to set languages rather than
```js
// template1.html
oTable.yadcf([/* unique column definition */], {
  language = {'select': 'Select value'}
});
// template2.html
oTable.yadcf([/* unique column defintion */], {
  language = {'select': 'Select value'}
});
```

**Comment by vedmack** [comment]
Sure, a PR is always welcomed

**Comment by bytestream** [comment]
Sent https://github.com/vedmack/yadcf/pull/617

**Comment by vedmack** [comment]
thanks! I will try to merge it when I'll find some spare time

**Comment by bytestream** [comment]
@vedmack sorry to ping but any chance of seeing this merged and released?
