### ISSUE TITLE
Pre Selecting  an escaped value

### ISSUE THREAD

**Issue by adrianmihalko** [vedmack/yadcf#612]
I am opening here a bug report, following my question on [Stackoverflow](https://stackoverflow.com/questions/59596440/yadcf-initial-select-latest-value/59601181?noredirect=1#comment105961344_59601181).

The problem is, that it's currently not possible to populate select input at init:

![67rfcw4e0m37](https://user-images.githubusercontent.com/733361/73140893-348e0100-407e-11ea-9289-22c2e36204ee.png)

it's empty, but filtering works correctly.

As found by Datatables developer on [their forum ](https://datatables.net/forums/discussion/59851/possible-bug-in-the-draw-function), maybe there is a race condition which is causing the YADCF plugin to clear the input value.

![crgutxl7f456](https://user-images.githubusercontent.com/733361/73140925-8a62a900-407e-11ea-9d66-c53589054c42.gif)

As you can see it shows up for a sec, then it's become hidden.

I tried multiple solution, but none seem to be work:

```
$('#mytable').on( 'init.dt', function () {
     yadcf.exFilterColumn(oTable, [[4, '3/2020']], true);
  } );

```

```
 yadcf.initOnDtXhrComplete(function() { 
   yadcf.exFilterColumn(oTable, [[4, $("#yadcf-filter--mytable-4 option:eq(1)").val()]], true);
  });
```

Test site:

[init.d](https://bow.thingiverse.ml)
[yadcf.initOnDtXhrComplete](https://bow.thingiverse.ml/index2.html)

**Comment by vedmack** [comment]
@adrianmihalko please try the 0.9.4.beta.39 https://www.dropbox.com/s/g2ctbdq6zfuziy4/jquery.dataTables.yadcf.js?dl=0

update it on your site so I can see how it works for you

**Comment by adrianmihalko** [comment]
@vedmack Hi Daniel, looks good:

https://bow.thingiverse.ml

thanks for your time 👍

**Comment by vedmack** [comment]
@adrianmihalko cool, can u please provide a test page for a scenario in which you try to pre-select a value that does not exist in the select, for example, 6/2020 (I want to see the flow...)?

**Comment by adrianmihalko** [comment]
@vedmack sure: https://bow.thingiverse.ml/index2.html

**Comment by vedmack** [comment]
@adrianmihalko you can get the final 0.9.4.beta.40 js version with the fix
