### ISSUE TITLE
autocomplete is not a function

### ISSUE THREAD

**Issue by jnaklaas** [vedmack/yadcf#626]
I'm having an issue with the `auto_complete` filter type.

When changing the filter type to `text`, it all works as expected. When using `auto_complete` filtering does not work on any of the columns. 

Console shows:
```
TypeError: $(...).autocomplete is not a function
```

My js code:
```js
let propertiesTable = $('.properties-table').DataTable({
    columnDefs: [
       { type: 'natural', targets: 0 }
     ],
     language: {
          url: dataTablesI18nUrl
      }
  });
  // yadcf DataTable filter init
  yadcf.init(propertiesTable, [{
    column_number: 0,
    filter_type: 'text',
    filter_default_label: (sales_object.language === 'nl') ? 'Typ om te filteren' : 'Type to filter',
  }, {
    column_number: 1,
    // select_type: 'chosen',
    select_type_options: {
        search_contains: true
    },
    filter_default_label: (sales_object.language === 'nl') ? 'Selecteer type' : 'Select type',
  }, {
    column_number: 2,
    // select_type: 'chosen',
    select_type_options: {
        search_contains: true
    },
    filter_default_label: (sales_object.language === 'nl') ? 'Selecteer aantal' : 'Select number',
  }, {
    column_number: 6,
    filter_type: 'auto_complete',
  }]);
```

PS I commented out `select_type: 'chosen',` because it too throws an error when used, but works flawlessly when omitted.

**Comment by vedmack** [comment]
Hi

You should add js/css of any third party jquery plugin in order to use them.

See [TypeError: $(…).autocomplete is not a function](https://stackoverflow.com/questions/16300586/typeerror-autocomplete-is-not-a-function)

**Comment by jnaklaas** [comment]
Thanks, apparently the jquery ui that I was using did not include the entire library.

**Comment by Ynjxsjmh** [comment]
Encountered into the same problem, as is stated in README

> autocomplete input - make use of the jQuery UI Autocomplete widget (with some enhancements)

Solved by including `jquery-ui.js` before `jquery.dataTables.yadcf.js`.
