### ISSUE TITLE
Tag 0.9.4

### ISSUE THREAD

**Issue by bytestream** [vedmack/yadcf#631]
Please can we tag 0.9.4 🤞 

I'm currently locked on 0.9.2 because 0.9.3 is broken if used without intervention in older browsers due to https://github.com/vedmack/yadcf/issues/467

I'm also waiting for stable release of https://github.com/vedmack/yadcf/pull/617

**Comment by vedmack** [comment]
@bytestream,  0.9.4 should be tagged in two weeks from now
if you want to use the latest beta (which will eventually become the 0.9.4) then I'd appreciate if you can help me with the following error message that I get when I try to publish the beta to npm

I call `$ npm publish --tag beta`

and getting the following error log

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish',
1 verbose cli   '--tag',
1 verbose cli   'beta'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose npm-session fc44066cbafb8575
5 verbose publish [ '.' ]
6 info lifecycle yadcf@0.9.4-beta.41~prepublish: yadcf@0.9.4-beta.41
7 info lifecycle yadcf@0.9.4-beta.41~prepare: yadcf@0.9.4-beta.41
8 info lifecycle yadcf@0.9.4-beta.41~prepublishOnly: yadcf@0.9.4-beta.41
9 info lifecycle yadcf@0.9.4-beta.41~prepack: yadcf@0.9.4-beta.41
10 info lifecycle yadcf@0.9.4-beta.41~postpack: yadcf@0.9.4-beta.41
11 notice
12 notice package: yadcf@0.9.4-beta.41
13 notice === Tarball Contents ===
14 notice 2.5kB   jquery.dataTables.yadcf.css
14 notice 255.9kB jquery.dataTables.yadcf.js
14 notice 924B    package.json
15 notice === Tarball Details ===
16 notice name:          yadcf
16 notice version:       0.9.4-beta.41
16 notice package size:  39.6 kB
16 notice unpacked size: 259.3 kB
16 notice shasum:        6b668b6e44041eb4e605704a719557f9f4bbfb94
16 notice integrity:     sha512-Sr3GOBk0MUYmg[...]JCXJymN2AB8aA==
16 notice total files:   3
17 notice
18 http fetch PUT 404 https://registry.npmjs.org/yadcf 955ms
19 verbose stack Error: 404 Not Found - PUT https://registry.npmjs.org/yadcf - Not found
19 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15
19 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
20 verbose statusCode 404
21 verbose pkgid yadcf@0.9.4-beta.41
22 verbose cwd C:\Users\daniel\Dropbox\github\yadcf\dist
23 verbose Windows_NT 10.0.18363
24 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish" "--tag" "beta"
25 verbose node v12.16.3
26 verbose npm  v6.14.4
27 error code E404
28 error 404 Not Found - PUT https://registry.npmjs.org/yadcf - Not found
29 error 404
30 error 404 'yadcf@0.9.4-beta.41' is not in the npm registry.
31 error 404 You should bug the author to publish it (or use the name yourself!)
32 error 404 Note that you can also install from a
33 error 404 tarball, folder, http url, or git url.
34 verbose exit [ 1, true ]

**Comment by bytestream** [comment]
I think you need to be logged in as `yadcf` user

https://stackoverflow.com/questions/31205590/error-publishing-a-new-version-of-a-package-in-npm

**Comment by vedmack** [comment]
I will update this beta again in a few days
then hopefully will release the 0.9.4

**Comment by bytestream** [comment]
Did you have any luck @vedmack

**Comment by vedmack** [comment]
trying to add a big PR with multiple code security fixes by @m417z https://github.com/vedmack/yadcf/pull/634 after that will release a new beta and then 0.9.4

**Comment by bytestream** [comment]
Any update on this @vedmack or is the recommendation to just use `npm i yadcf@beta`? I'll close if so.

**Comment by bytestream** [comment]
You may have issues publishing `0.9.4` to NPM given it already exists:
* https://www.npmjs.com/package/yadcf/v/0.9.4
* https://registry.npmjs.org/yadcf/-/yadcf-0.9.4.tgz

**Comment by vedmack** [comment]
@bytestream any chance you know how to delete the 0.9.4 tag? I tried npm dist-tag rm yadcf 0.9.4 but it says 

> npm ERR! 0.9.4 is not a dist-tag on yadcf

**Comment by bytestream** [comment]
Unfortunately you can't delete existing versions from NPM after 72 hours:

> Regardless of how long ago a package was published, you can unpublish a package that:
> * no other packages in the npm Public Registry depend on
> * had less than 300 downloads over the last week
> * has a single owner/maintainer

https://www.npmjs.com/policies/unpublish

You could try and contact NPM support.

**Comment by bytestream** [comment]
@vedmack maybe just publish 0.9.5 to bypass the issue of 0.9.4 already existing? I've been using the beta series for 3 years and have no issues.

**Comment by vedmack** [comment]
Hi,
I have published it as [0.9.5](https://github.com/vedmack/yadcf/commit/4e4372190a1d50d8bd4bc3a1368041ab6977f9bc)
