### ISSUE TITLE
yadcf.exResetAllFilters() no longer resets columns using select

### ISSUE THREAD

**Issue by Eddie-Fantastic** [vedmack/yadcf#639]
Just updated from beta 25 to beta 44 and my button which runs yadcf.exResetAllFilters(table) will reset all columns except those that use a select style filter. The column reset buttons still work on them though. 
Reverted back to 25 and is working again.

**Comment by vedmack** [comment]
can you please provide a jsfillde test page?

**Comment by Eddie-Fantastic** [comment]
Sure, my first so if I made a mistake let me know...

https://jsfiddle.net/61m4b3wk/5/

Individual filter reset buttons work. "Reset all column filters" button resets text searches but not select boxes. If I change to yadcf 0.9.4.beta.25 then all columns get reset as they should.

**Comment by vedmack** [comment]
see it live here https://jsfiddle.net/vedmack/yp8w2khg/
