### ISSUE TITLE
use of yadcf option filters_tr_index and datatables option columnDefs

### ISSUE THREAD

**Issue by aureltime** [vedmack/yadcf#640]
on jsfiddle https://jsfiddle.net/aureltime/5zh7u4rs/8/, the red right border shows up on column header : OK as expected

on other jsfiddle https://jsfiddle.net/aureltime/5zh7u4rs/10/, with 2 rows in the header, the red right border is not displayed on the 2 headers rows but just one.

by the way, the plugin is great ! thanks for your time

**Comment by vedmack** [comment]
it's not related to yadcf (you can omit yadcf code and that red border issue will remain)
but...
you can solve it in tow different ways,
1) add class to the `th` element like this `<th class="red">Yes / No</th>`
2) use css 

```
thead tr th:nth-child(3) {
	border-right : 5px solid red;
}
```

**Comment by aureltime** [comment]
thanks for your answer, i will ask on datatable forum
