### ISSUE TITLE
daterangepicker with singleDatePicker: true option

### ISSUE THREAD

**Issue by sparh** [vedmack/yadcf#641]
Hello,
on v0.9.4.beta.45 line 1662.
I have edite the line to this
``if($.trim(min.substring(0, min.indexOf('-'))) != '') min = $.trim(min.substring(0, min.indexOf('-')));

This allow me to use the singleDatePicker: true of daterangepicker plugin otherwise it does not work when singleDatePicker: true

Regards

**Comment by vedmack** [comment]
if you want it to enter the yadcf source then please provide a jsfiddle test page showing your test case/solution
