### ISSUE TITLE
[question] about array and space

### ISSUE THREAD

**Issue by lenamtl** [vedmack/yadcf#647]
Hi,

My table use this array data format 
```
[
  ["First Item", 196476, "88%", 172980, 23496, 167005, 5976, -272, 1],
  ["Second Item", 196480, "89%", 172980, 23496, 167005, 5976, -272, 1],
]
```
The problem I'm getting is because of the space between the colon and the value.
What setting should I use to get it filtered?
I would like to see some array example on your demo too.

Thanks

**Comment by vedmack** [comment]
Hi,
Please provide a minimal test case on jsfiddle

**Comment by lenamtl** [comment]
I will find the time to do it.
I forgot to mention tat I'm using Select2 (multi-select) and display data to the table using 
```
var dataSet =[
  ["First Item", 196476, "88%", 172980, 23496, 167005, 5976, -272, 1],
  ["Second Item", 196480, "89%", 172980, 23496, 167005, 5976, -272, 1],
]
```

The space between the colon and the value seem to prevent the data to get filled in Select2 dropdown.
I have a lot of items to display at leat 200.
I was thinking removing the space frome the array but I was wondering in there was specific Yadcf settings for the arrays.

**Comment by lenamtl** [comment]
Sorry the problem was related to something else.
