### ISSUE TITLE
Problem with ColReorder and exResetAllFilters function

### ISSUE THREAD

**Issue by gmeriaux** [vedmack/yadcf#650]
Hi,
By using the plugin yadcf combine with colReorder, I find a bug with the function exResetAllFilters whose don't reset correctly all filters.
I patched my file locally by adding the same code that in exFilterColumn with the support of column_position variable to replace column_number in 'aoPreSearchCols' and 'clearStateSave'

column_number = optionsObj.column_number;
					column_position = column_number;
					if (plugins[table_selector_jq_friendly] !== undefined && plugins[table_selector_jq_friendly] !== undefined && plugins[table_selector_jq_friendly].ColReorder !== undefined) {
						column_position = plugins[table_selector_jq_friendly].ColReorder[column_number];
					}

**Comment by vedmack** [comment]
Hi

In case its still relevant, you will need to provide a jsfiddle (or similar) test page so I can see it in action...
