### ISSUE TITLE
Unresponsive range_date after opening modal

### ISSUE THREAD

**Issue by Reddaxi** [vedmack/yadcf#652]
I've got a response from a server API along containing this: 
https://i.imgur.com/A9kBUWS.png

It is displayed like this in my table:
https://i.imgur.com/I539MRg.png

And out filter option looks like this:
https://i.imgur.com/hLcmOKi.png

However, once opened, the datepicker becomes unresponsive.
When we click a date on either the "to" or "from" field, the picker doesnt close, and it doesnt update the table either.

I've tried changing server output to dd-MM-yyyy, MM-dd-yyyy and a javascript datetime string. :(
I've tried the suggestions in this stackoverflow  thread: https://stackoverflow.com/questions/53630812/yadcf-range-date-filter-doesnt-work-with-specific-date-format
I've tried reading through the documents in an attempt to fix this myself, but to no avail.

I'm running version 0.8.8 of yadcf, v1.11.3 jquery and 2.10.6 moment.js.
Upgrading yadcg and jquery to the newest versions didn't help me either. 

I'm experiencing the same issue with the date filter. :(

How do i debug this further?
And/or what is the solution?

**Comment by vedmack** [comment]
If still relevant, please provide a working jsfiddle test page
