### ISSUE TITLE
How to edit no results hints?

### ISSUE THREAD

**Issue by chanben2005** [vedmack/yadcf#657]
Hi
How to edit the No matches found hints?
![image](https://user-images.githubusercontent.com/34121011/129588390-3bc2598c-3a6b-4117-a89e-ea21164d3332.png)
Any help would be appreciated.

**Comment by vedmack** [comment]
Please provide a jsfiddle test page with your example

**Comment by chanben2005** [comment]
![image](https://user-images.githubusercontent.com/34121011/129702143-49bdfdba-5cc0-4152-ab90-289da0612a7a.png)

http://live.datatables.net/yiliqepi/2/edit

for example, I want to modify the No results found to No results.

Thank you!

**Comment by vedmack** [comment]
Take a look at this http://live.datatables.net/yiliqepi/3/edit

Complete code:


```
// DataTable
$(document).ready(function(){
  let myOptions = {"language": {
       "noResults": function(){
           return "Hi there... Please be kind and use some other key word";
       }
  }}
  $('#item').dataTable().yadcf([
    {column_number : 0,filter_type: "multi_select", select_type: 'select2', select_type_options: myOptions},
	    {column_number : 1,  filter_type: "range_number_slider", filter_container_id: "external_filter_container"},
	    {column_number : 2, data: ["Yes", "No"], filter_default_label: "Select Yes/No"},
	    {column_number : 3, text_data_delimiter: ",", filter_type: "auto_complete"},
	    {column_number : 4, column_data_type: "html", html_data_type: "text", filter_default_label: "Select tag"}]);
});

```

**Comment by chanben2005** [comment]
Thank you for your guidance.
Where can find yadcf docs?
Is this website?
https://yadcf-showcase.appspot.com/

**Comment by chanben2005** [comment]
Thank you for your guidance.

**Comment by vedmack** [comment]
@chanben2005 all docs are inside the yadcf js file (non minified version)
