### ISSUE TITLE
Filtering the filters

### ISSUE THREAD

**Issue by nehaharidasneo** [vedmack/yadcf#659]
I have a request to add a feature that can filter the filters as we search in the table. 
For instance when we use this page DOM_source_select2.html and search for Some Data 2 then the Tags filter shows all the tags. Instead, I request it should only load the related data for the search.

so like in excel when we apply a filter in one column the filters of other column are also filtered something similar to that.
Let me know if we can take this in the main js file.

**Comment by vedmack** [comment]
take a look at the cumulative_filtering option? http://yadcf-showcase.appspot.com/cumulative_filtering.html ?
