### ISSUE TITLE
yadcf/datatables/svelte issue

### ISSUE THREAD

**Issue by ZMilosevich** [vedmack/yadcf#660]
Hi guys! I successfully added datatables component but I have an issue with yadcf. I got,
'jquery.dataTables.yadcf.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Api')'. Not sure what I am doing wrong but I'll appreciate any advice or hint hot to fix related issue.

Thank you in advance,

`<script>
  import jQuery from "jquery";
  import { onMount, tick } from "svelte";
  import { load } from "../js/data.js";
  import "https://code.jquery.com/jquery-3.6.0.slim.min.js";
  import "https://cdnjs.cloudflare.com/ajax/libs/yadcf/0.9.4/jquery.dataTables.yadcf.min.js";

  let el; // table element
  let testTable; // table object (API)

  onMount(() => {
    testTable = jQuery(el).DataTable({
      columns: [
        {
          data: 0,
          title: "Name",
        },
        {
          data: 1,
          title: "Position",
        },
        {
          data: 2,
          title: "Office",
        },
        {
          data: 3,
          title: "Start Date",
        },
        {
          data: 4,
          title: "Salary",
        },
      ],
      dom: "rtip",
    });

    load().then((rows) => {
      testTable.rows.add(rows).draw();
      yadcf.init(testTable, [
        {
          column_number: 0,
          filter_type: "text",
          filter_reset_button_text: false,
        },
        {
          column_number: 1,
          filter_type: "text",
          filter_reset_button_text: false,
        },
        {
          column_number: 2,
          filter_type: "text",
          filter_reset_button_text: false,
        },
        {
          column_number: 3,
          filter_type: "text",
          filter_reset_button_text: false,
        },
        {
          column_number: 4,
          filter_type: "range_number",
          filter_reset_button_text: false,
        },
      ]);
    });
  });
</script>`

**Comment by vedmack** [comment]
You better ask in on https://stackoverflow.com/ , but before that, try running you code outside the `load().then((rows)` make sure that the jquery/yadcf resource were really loaded
