### ISSUE TITLE
Search only by year

### ISSUE THREAD

**Issue by Alexisback** [vedmack/yadcf#665]
Hello everyone
I would like to filter the results of the field "Date" looking for only by year
The field has this format
2022-10-19

`{column_number : 3, 
		html_data_type: "text", 
		text_data_delimiter: "-", 
		filter_default_label: "Date"
		},`

[https://www.upload.ee/image/14598086/sshot-1.png](url)

**Comment by vedmack** [comment]
sorry, can't really tell what you trying to achieve nor understand your setup, please provide a test page.
