### ISSUE TITLE
Different result since 0.9.4.b46 when using a text_data_delimiter and a dt-render function

### ISSUE THREAD

**Issue by berndy2001** [vedmack/yadcf#682]
0.9.4.b45: https://jsbin.com/buguqej/1/edit?html,output
0.9.4.b46: https://jsbin.com/nobiqiw/1/edit?html,output

filter for Vertragsart = "xxx", b45 brings two results (correct), b46 only one (wrong)

**Comment by vedmack** [comment]
Nice catch!
I have fixed it in 0.9.4.b47 see jsbin https://jsbin.com/wenivakeyo/edit?html,output
It is also fixed in yadcf 2.0.1.beta.8 https://github.com/vedmack/yadcf/blob/master/2.0/jquery.dataTables.yadcf-2.0.js

**Comment by berndy2001** [comment]
Thank you very much. At first I thought it was due to my incompetence ;)
