### ISSUE TITLE
yadcf.exFilterExternallyTriggered

### ISSUE THREAD

**Issue by 13ran** [vedmack/yadcf#683]
I can't figure out what I am doing wrong. I am calling `yadcf.exFilterExternallyTriggered(dtcustomers);` it makes the request but it does not contain the search text from the input. 
Html:
`<input type="text" id="name" name="name" placeholder="" class="form-control">`

Javascript:

```
dtcustomers = $('#customers').DataTable({
      rowId: 'rowId',
      responsive: {
         details: true
      },
      serverSide: true,
      ajax: {
        url: 'api?get=CustomersTable',
        type: "POST",
        timeout: 10000,
      },
      "order": 
      [
         [ 0, "desc" ]
      ],
      columns: 
      [
         { data: 'VehicleCustomerId' },
         { data: 'VehicleDocumentId' },
         { data: 'DriversLicense' },
         { data: 'GstNumber' },
         { data: 'FirstName' },
         { data: 'LastName' },
         { data: 'CompanyName' },
         { data: 'Phone' },
         { data: 'Fax' },
         { data: 'Street' },
         { data: 'Province' },
         { data: 'PostalCode' },
         { data: 'Email' },
         { data: 'Notes' },
         { data: 'Name' },
         { data: 'City' }
      ]
});

yadcf.init(dtcustomers, 
   [
      {
         column_number: 6,
         filter_container_id: 'name',
         filter_match_mode: 'contains',
         filter_type: "text",
         externally_triggered: true
      }
   ],{   externally_triggered: true});
```

**Comment by 13ran** [comment]
So I was able to get it working with the code below. But it causes a double ajax call the first being without the search query and the second with

```
$('#SubmitFormButton').on('click', function() {
   var filters = [
      [6, $('#url').val()]
   ];
   yadcf.exResetAllFilters(dtcustomers,true);
   yadcf.exFilterColumn(dtcustomers, filters);
   yadcf.exFilterExternallyTriggered(dtcustomers);
});
```

**Comment by vedmack** [comment]
@13ran all you have to call from inside that button is `exFilterExternallyTriggered` see the showcase page and look into the source code of the filter button https://yadcf-showcase.appspot.com/dom_source_externally_triggered.html

**Comment by 13ran** [comment]
Yes I see now it generates the input for me. I misunderstood what the externally triggered meant. I wanted it to use my own input.

**Comment by vedmack** [comment]
then u can use filter_container_id: "external_filter_container" like in this showcase page https://yadcf-showcase.appspot.com/DOM_source.html

u can go over the showcase examples and see what fits u the best
