### ISSUE TITLE
Cumulative Filter is hiding filter options when selected one rather than disabling them

### ISSUE THREAD

**Issue by Yshdhiman** [vedmack/yadcf#686]
Hey,
i'm trying to use cumulative filter mode, when I select one of the 10 options, the filtering happens with no issue, but the 9 other options go away, and I need to "deselect the option" to find the complete list again.
can the other option just become disable rather than disappearing..??

**Comment by vedmack** [comment]
please share a test page showing your issue

**Comment by Yshdhiman** [comment]
![image](https://github.com/user-attachments/assets/5d8ff3ba-8e67-4fd8-8084-335d53fc8898)
![image](https://github.com/user-attachments/assets/2c4ba0b7-f3a6-4405-94aa-dbc2eb5b56ae)

as you can see i had multiple options in the filter, but when i select any they just disappeared not only for this but for other filter as well.

To sort this issues i had to create a custom function with custom functionalities. We have limited data so the approach i used is working fine.
i.e any selected filter shoundn't affect the previous one but only the unselected one and if i move to the previous filter then it will reset the next selected filters from that filter.
i would have send you a video of it but options are not showing in screen recording. 
i hope you got my point.

![image](https://github.com/user-attachments/assets/4167e521-213c-454d-9c8e-cf91a7a1001a)
![image](https://github.com/user-attachments/assets/15128c16-faae-488d-99c4-2eb9bfafb756)
![image](https://github.com/user-attachments/assets/d03dc977-9fae-44df-9da1-9ac34baa91cd)
![image](https://github.com/user-attachments/assets/62791d04-3287-4c73-ab9e-b5bcfe448898)

**Comment by vedmack** [comment]
I think you missed the purpose of the cumulative filtering, I have updated the showcase with such example see it here: https://yadcf.web.app/

In addition, you can read its purpose in the docs:

> * cumulative_filtering
                Required:           false
                Type:               boolean
                Default value:      false
                Description:        Change the default behavior of the filters so its options will be populated from the filtered rows (remaining
                                    table data after filtering) only, unlike the normal behavior in which the options of the filters are from all the table data
