### ISSUE TITLE
exFilterColumn for Sever Side configuration

### ISSUE THREAD

**Issue by mbenci** [vedmack/yadcf#69]
could you verify if the exFilterColumn works also in server side configuration and eventually correct the problem.
In my tests I was not able to make it works correctly neither using DataTable (D) nor dataTable (d)

Thanks,
Marco B

**Comment by manjulacredr** [comment]
Hi I am trying range_number_slider in yadcf tables 
I am trying it server side but it doesnt work :(

**Comment by vedmack** [comment]
@manjulacredr  , you should inspect the [showcase server side sample page](http://yadcf-showcase.appspot.com/server_side_source.html) there is a `range_number_slider`, so all the needed info can be found there, showcase [source code is also open sourced on github](https://github.com/vedmack/yadcf-showcase/blob/master/src/dr/yadcf/servlets/EntrysTableServerSideSource.java) , for additional questions please [use stackoverflow](http://stackoverflow.com/questions/tagged/yadcf)
