### ISSUE TITLE
One filter that checks against multiple columns

### ISSUE THREAD

**Issue by bkloef** [vedmack/yadcf#79]
It appears easy to create a filter that operates on a single column. I would like to see an option to create a global filter (working along with the global search field) that can affect multiple (specified) columns. This request arises from my DT forum support request at http://datatables.net/forums/discussion/23194/filter-rows-based-on-data-existing-in-a-particular-column

I'm new to DataTables, but despite searching for days I have not yet found an example anywhere of how to accomplish this.

Thanks for your consideration,
Brian

**Comment by vedmack** [comment]
Added (at last) , works for datatables 10.0+ , read docs over here: https://github.com/vedmack/yadcf/blob/master/lab/jquery.dataTables.yadcf.js#L255 no showacse example yet...
