### ISSUE TITLE
No initialization

### ISSUE THREAD

**Issue by rebendajirijr** [vedmack/yadcf#96]
Cannot initialize plugin like this way:

``` javascript
$('.table').each(function() {
    var table = $(this).DataTable();
    yadcf.init(table, [
        ... // column definition
    ]);
});
```

init function expects some defined selector, which obviously is unknown (if I dump [instance.selector](https://github.com/vedmack/yadcf/blob/master/jquery.dataTables.yadcf.js#L2067) it's an empty string so no initialization occurs.

**Comment by Pyreweb** [comment]
Hey, just a little simple solution, for reference;
It add an ID where there isn't one, so the selector is happy.
```
$('.table').each(function() {
	var selector = $(this).attr('id'),
		table;
	
	if (typeof (selector) === 'undefined') {
		selector = String.fromCharCode(65 + Math.floor(Math.random() * 26))  + Date.now();
		$(this).attr('id', selector);
	}
	table = $('#' + selector).DataTable(
     ....
```
(the random string on selector came from http://stackoverflow.com/a/6860962)

**Comment by taarimalta** [comment]
$(document.getElementById('example')).DataTable() did not work. Had to do $('#example').DataTable()

**Comment by McNetic** [comment]
That's not an enhancement, but a serious bug. Took me about 3-4 hours to figure this out. I have a jquery object, I assume I can apply jquery methods on it. Datatable works just fine, but yadcf fails silently, without any indication of the error.
Most of the times, it's obvious where the jquery object comes from, so (if you know you can only work on "selected" objects), you can find the error, but that's not always the case. You should really drop any reference to the selector property....

**Comment by vedmack** [comment]
Well apparently this issue was fixed long time ago :) just checked it and it works just fine, here a working jsfiddle... http://jsfiddle.net/vedmack/05dtpk1s/20/
